/**
 * app-supercharge-silver — Loom-native content bundle.
 *
 * GENERATED by scripts/csa-loom/import-supercharge-notebooks.mjs — do not edit by
 * hand; edit the converted notebooks under
 * examples/supercharge-fabric/notebooks/silver/ and re-run the script.
 *
 * Source: https://github.com/fgarofalo56/Suppercharge_Microsoft_Fabric (notebooks/silver).
 * Converted to run on Azure-native backends (Synapse Spark / Databricks + ADLS Gen2
 * + ADX) with zero hard Microsoft Fabric dependency — installs via notebookProvisioner,
 * executes via /api/items/notebook/[id]/execute-spark (AML Serverless Spark or Synapse
 * Livy). See docs/fiab/parity/supercharge-notebooks.md.
 */
import type { AppBundle, NotebookContent } from './types';
import type { NotebookCell } from '@/lib/types/notebook-cell';
import cellData from './_generated-cells/app-supercharge-silver.cells.json';

const CELLS = cellData as unknown as Record<string, NotebookCell[]>;

const bundle: AppBundle = {
  appId: "app-supercharge-silver",
  intro: `Silver (cleanse / conform) Spark notebooks from **Supercharge Microsoft Fabric**, converted to Loom-native (Synapse Spark / Databricks over ADLS Gen2 Delta).`,
  sourceDocs: ['examples/supercharge-fabric/notebooks/silver'],
  items: [
    {
      itemType: 'notebook',
      displayName: "01 — Silver Slot Cleansed",
      description: "Silver Layer: Slot Machine Data Cleansing",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_01_SILVER_SLOT_CLEANSED"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "02 — Silver Player Master",
      description: "Silver Layer: Player Master with SCD Type 2",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_02_SILVER_PLAYER_MASTER"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "03 — Silver Table Enriched",
      description: "Silver Layer: Table Games Enriched",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_03_SILVER_TABLE_ENRICHED"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "04 — Silver Financial Reconciled",
      description: "Silver Layer: Financial Reconciled",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_04_SILVER_FINANCIAL_RECONCILED"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "05 — Silver Security Enriched",
      description: "Silver Layer: Security Events Enriched",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_05_SILVER_SECURITY_ENRICHED"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "06 — Silver Compliance Validated",
      description: "Silver Layer: Compliance Validated",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_06_SILVER_COMPLIANCE_VALIDATED"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "07 — Silver Tribal Health",
      description: "Silver Layer: Tribal Healthcare Data Cleansing & Standardization",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_07_SILVER_TRIBAL_HEALTH"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "08 — Silver Dot Faa",
      description: "Silver Layer: DOT/FAA Data Quality & Enrichment",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_08_SILVER_DOT_FAA"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "09 — Silver Video Analytics",
      description: "Silver Layer: Video Analytics Cleansing & Enrichment",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_09_SILVER_VIDEO_ANALYTICS"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "10 — Silver People Movement",
      description: "Silver Layer: People Movement Data Cleansing & Enrichment",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_10_SILVER_PEOPLE_MOVEMENT"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "11 — Silver Geolocation",
      description: "Silver Layer: Geolocation Data Cleansing & Enrichment",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_11_SILVER_GEOLOCATION"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "12 — Silver Usda",
      description: "Silver Layer: USDA Crop Production & Food Safety",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_12_SILVER_USDA"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "13 — Silver Sba",
      description: "Silver Layer: SBA Loan Data Cleansing & Standardization",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_13_SILVER_SBA"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "14 — Silver Noaa",
      description: "Silver Layer: NOAA Weather & Climate Data Cleansing & Standardization",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_14_SILVER_NOAA"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "15 — Silver Epa",
      description: "Silver Layer: EPA Environmental Data Cleansing & Standardization",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_15_SILVER_EPA"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "16 — Silver Doi",
      description: "Silver Layer: DOI (Department of Interior) Data Cleansing & Standardization",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_16_SILVER_DOI"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "18 — Silver Doj",
      description: "Silver Layer: DOJ Data Cleansing & Standardization",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_18_SILVER_DOJ"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "40 — Late Arriving Backfill",
      description: "Silver Layer: Late-Arriving Data with Watermarked Idempotent Backfill",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_40_LATE_ARRIVING_BACKFILL"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "41 — Gdpr Cascading Delete",
      description: "GDPR Cascading Delete — DSAR Erasure Execution",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_41_GDPR_CASCADING_DELETE"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "50 — Healthcare Cleansed",
      description: "Silver Layer: Healthcare Encounter Cleansing",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_50_HEALTHCARE_CLEANSED"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "51 — Financial Enriched",
      description: "Silver Layer: Financial Transaction Enrichment",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_51_FINANCIAL_ENRICHED"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "52 — Insurance Validated",
      description: "Silver Layer: Insurance Claims Validated",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_52_INSURANCE_VALIDATED"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "53 — Retail Cleansed",
      description: "Silver Layer: Retail Sales Cleansed",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_53_RETAIL_CLEANSED"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "54 — Manufacturing Aggregated",
      description: "Silver Layer: Manufacturing Machine Health",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_54_MANUFACTURING_AGGREGATED"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "55 — Energy Validated",
      description: "Silver Layer: Energy Meter Readings - Validated & Enriched",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_55_ENERGY_VALIDATED"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "56 — Telecom Enriched",
      description: "Silver Layer: Telecom CDR Enrichment",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_56_TELECOM_ENRICHED"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "57 — Pharma Validated",
      description: "Silver Layer: Pharma Clinical Trial Validated Data",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_57_PHARMA_VALIDATED"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "58 — Media Sessions",
      description: "Silver Layer: Media Session Construction",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_SILVER_58_MEDIA_SESSIONS"] } as NotebookContent,
    },
  ],
};

export default bundle;
