/**
 * app-supercharge-utils — Loom-native content bundle.
 *
 * GENERATED by scripts/csa-loom/import-supercharge-notebooks.mjs — do not edit by
 * hand; edit the converted notebooks under
 * examples/supercharge-fabric/notebooks/utils/ and re-run the script.
 *
 * Source: https://github.com/fgarofalo56/Suppercharge_Microsoft_Fabric (notebooks/utils).
 * Converted to run on Azure-native backends (Synapse Spark / Databricks + ADLS Gen2
 * + ADX) with zero hard Microsoft Fabric dependency — installs via notebookProvisioner,
 * executes via /api/items/notebook/[id]/execute-spark (AML Serverless Spark or Synapse
 * Livy). See docs/fiab/parity/supercharge-notebooks.md.
 */
import type { AppBundle, NotebookContent } from './types';
import type { NotebookCell } from '@/lib/types/notebook-cell';
import cellData from './_generated-cells/app-supercharge-utils.cells.json';

const CELLS = cellData as unknown as Record<string, NotebookCell[]>;

const bundle: AppBundle = {
  appId: "app-supercharge-utils",
  intro: `Shared pipeline utilities from **Supercharge Microsoft Fabric** (Bronze helpers, lineage, pipeline-execution logging) — Azure-native Spark, attachable to any medallion notebook via %run.`,
  sourceDocs: ['examples/supercharge-fabric/notebooks/utils'],
  items: [
    {
      itemType: 'notebook',
      displayName: "Bronze Utils",
      description: "Bronze Layer Utilities",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_UTILS_BRONZE_UTILS"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "Lineage Utils",
      description: "Notebook Utilities: Data Lineage & Pipeline Helpers",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_UTILS_LINEAGE_UTILS"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "Pipeline Execution Log Setup",
      description: "Pipeline Execution Log Setup",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_UTILS_PIPELINE_EXECUTION_LOG_SETUP"] } as NotebookContent,
    },
  ],
};

export default bundle;
