/**
 * app-supercharge-guide — Loom-native content bundle.
 *
 * GENERATED by scripts/csa-loom/import-supercharge-notebooks.mjs — do not edit by
 * hand; edit the converted notebooks under
 * examples/supercharge-fabric/notebooks/hitchhikers-guide/ and re-run the script.
 *
 * Source: https://github.com/fgarofalo56/Suppercharge_Microsoft_Fabric (notebooks/hitchhikers-guide).
 * Converted to run on Azure-native backends (Synapse Spark / Databricks + ADLS Gen2
 * + ADX) with zero hard Microsoft Fabric dependency — installs via notebookProvisioner,
 * executes via /api/items/notebook/[id]/execute-spark (AML Serverless Spark or Synapse
 * Livy). See docs/fiab/parity/supercharge-notebooks.md.
 */
import type { AppBundle, NotebookContent } from './types';
import type { NotebookCell } from '@/lib/types/notebook-cell';
import cellData from './_generated-cells/app-supercharge-guide.cells.json';

const CELLS = cellData as unknown as Record<string, NotebookCell[]>;

const bundle: AppBundle = {
  appId: "app-supercharge-guide",
  intro: `The Hitchhiker's Guide notebooks from **Supercharge Microsoft Fabric** (connectivity, lakehouse/warehouse ops, security & identity, admin & governance, automation, troubleshooting) — Fabric control-plane recipes rewritten to their Azure-native equivalents (Synapse, ADLS RBAC/ACL, ARM, Azure Analysis Services).`,
  sourceDocs: ['examples/supercharge-fabric/notebooks/hitchhikers-guide'],
  items: [
    {
      itemType: 'notebook',
      displayName: "00 — Guide Index",
      description: "Pre-flight: which Fabric runtime am I on?",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_HITCHHIKERS_GUIDE_00_GUIDE_INDEX"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "01 — Guide Connectivity",
      description: "A — ADLS Gen2",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_HITCHHIKERS_GUIDE_01_GUIDE_CONNECTIVITY"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "02 — Guide Lakehouse Warehouse Ops",
      description: "A — Lakehouse CRUD",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_HITCHHIKERS_GUIDE_02_GUIDE_LAKEHOUSE_WAREHOUSE_OPS"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "03 — Guide Security Identity",
      description: "A — OneLake security role (RLS GA, CLS Preview)",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_HITCHHIKERS_GUIDE_03_GUIDE_SECURITY_IDENTITY"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "04 — Guide Admin Governance",
      description: "A — Boilerplate",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_HITCHHIKERS_GUIDE_04_GUIDE_ADMIN_GOVERNANCE"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "05 — Guide Automation Utilities",
      description: "A — Namespace conventions",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_HITCHHIKERS_GUIDE_05_GUIDE_AUTOMATION_UTILITIES"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "06 — Guide Troubleshooting",
      description: "| Symptom | Likely cause | Fix / reference |",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_HITCHHIKERS_GUIDE_06_GUIDE_TROUBLESHOOTING"] } as NotebookContent,
    },
  ],
};

export default bundle;
