/**
 * app-supercharge-bronze — Loom-native content bundle.
 *
 * GENERATED by scripts/csa-loom/import-supercharge-notebooks.mjs — do not edit by
 * hand; edit the converted notebooks under
 * examples/supercharge-fabric/notebooks/bronze/ and re-run the script.
 *
 * Source: https://github.com/fgarofalo56/Suppercharge_Microsoft_Fabric (notebooks/bronze).
 * Converted to run on Azure-native backends (Synapse Spark / Databricks + ADLS Gen2
 * + ADX) with zero hard Microsoft Fabric dependency — installs via notebookProvisioner,
 * executes via /api/items/notebook/[id]/execute-spark (AML Serverless Spark or Synapse
 * Livy). See docs/fiab/parity/supercharge-notebooks.md.
 */
import type { AppBundle, NotebookContent } from './types';
import type { NotebookCell } from '@/lib/types/notebook-cell';
import cellData from './_generated-cells/app-supercharge-bronze.cells.json';

const CELLS = cellData as unknown as Record<string, NotebookCell[]>;

const bundle: AppBundle = {
  appId: "app-supercharge-bronze",
  intro: `Bronze (raw ingestion) Spark notebooks from **Supercharge Microsoft Fabric**, converted to run Azure-native on Synapse Spark / Databricks landing into ADLS Gen2 Delta — no Microsoft Fabric required.`,
  sourceDocs: ['examples/supercharge-fabric/notebooks/bronze'],
  items: [
    {
      itemType: 'notebook',
      displayName: "01 — Bronze Slot Telemetry",
      description: "Bronze Layer: Slot Machine Telemetry",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_01_BRONZE_SLOT_TELEMETRY"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "02 — Bronze Player Profile",
      description: "Bronze Layer: Player Profile Ingestion",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_02_BRONZE_PLAYER_PROFILE"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "03 — Bronze Financial Txn",
      description: "Bronze Layer: Financial Transaction Ingestion",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_03_BRONZE_FINANCIAL_TXN"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "04 — Bronze Compliance",
      description: "Bronze Layer: Compliance Filings Ingestion",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_04_BRONZE_COMPLIANCE"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "05 — Bronze Table Games",
      description: "Bronze Layer: Table Games Ingestion",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_05_BRONZE_TABLE_GAMES"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "06 — Bronze Security Events",
      description: "Bronze Layer: Security Events Ingestion",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_06_BRONZE_SECURITY_EVENTS"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "07 — Bronze Tribal Health",
      description: "Bronze Layer: Tribal Healthcare Data Ingestion",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_07_BRONZE_TRIBAL_HEALTH"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "08 — Bronze Dot Faa",
      description: "Bronze Layer: DOT/FAA Transportation Data Ingestion",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_08_BRONZE_DOT_FAA"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "09 — Bronze Video Analytics",
      description: "Bronze Layer: Video Security Analytics Ingestion",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_09_BRONZE_VIDEO_ANALYTICS"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "10 — Bronze People Movement",
      description: "Bronze Layer: People Movement Data Ingestion",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_10_BRONZE_PEOPLE_MOVEMENT"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "11 — Bronze Geolocation",
      description: "Bronze Layer: Geolocation Data Ingestion",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_11_BRONZE_GEOLOCATION"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "12 — Bronze Usda",
      description: "Bronze Layer: USDA Data Ingestion",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_12_BRONZE_USDA"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "13 — Bronze Sba",
      description: "Bronze Layer: SBA Data Ingestion",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_13_BRONZE_SBA"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "14 — Bronze Noaa",
      description: "Bronze Layer: NOAA Data Ingestion",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_14_BRONZE_NOAA"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "15 — Bronze Epa",
      description: "Bronze Layer: EPA Data Ingestion",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_15_BRONZE_EPA"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "16 — Bronze Doi",
      description: "Bronze Layer: DOI Data Ingestion",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_16_BRONZE_DOI"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "17 — Bronze Shortcut Transformations",
      description: "Shortcut Transformations - Auto Delta Conversion",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_17_BRONZE_SHORTCUT_TRANSFORMATIONS"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "18 — Bronze Doj",
      description: "Bronze Layer: DOJ Data Ingestion",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_18_BRONZE_DOJ"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "19 — Variable Library Demo",
      description: "Variable Library Demo — Parameterized Pipeline Ingestion",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_19_VARIABLE_LIBRARY_DEMO"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "50 — Healthcare Admissions",
      description: "Bronze Layer: Healthcare Admissions Ingestion",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_50_HEALTHCARE_ADMISSIONS"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "51 — Financial Transactions",
      description: "Bronze Layer: Financial Transactions",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_51_FINANCIAL_TRANSACTIONS"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "52 — Insurance Claims",
      description: "Bronze Layer: Insurance Claims Ingestion",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_52_INSURANCE_CLAIMS"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "53 — Retail Pos",
      description: "Bronze Layer: Retail POS Transactions",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_53_RETAIL_POS"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "54 — Manufacturing Sensors",
      description: "Bronze Layer: Manufacturing Sensor Telemetry",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_54_MANUFACTURING_SENSORS"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "55 — Energy Meters",
      description: "Bronze Layer: Energy AMI Meter Readings",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_55_ENERGY_METERS"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "56 — Telecom Cdr",
      description: "Bronze Layer: Telecom CDR Ingestion",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_56_TELECOM_CDR"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "57 — Pharma Trials",
      description: "Bronze Layer: Pharma Clinical Trial Data Ingestion",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_57_PHARMA_TRIALS"] } as NotebookContent,
    },
    {
      itemType: 'notebook',
      displayName: "58 — Media Events",
      description: "Bronze Layer: Media Playback Events",
      content: { kind: 'notebook', defaultLang: "pyspark", cells: CELLS["CELLS_BRONZE_58_MEDIA_EVENTS"] } as NotebookContent,
    },
  ],
};

export default bundle;
