#!/bin/bash
# CSA Loom — UAT smoke runner for the jumpbox.
#
# Self-contained on purpose: the jumpbox has no checkout, so the smoke test is
# pasted in base64 and decoded here.
#
# THE ARTIFACT DIRECTORY IS THE SECURITY-RELEVANT PART OF THIS SCRIPT.
# It used to be `mkdir -p /tmp/loom-uat`. /tmp is world-writable and the
# jumpbox is multi-user, so any other local user could pre-create that path —
# as a directory they own, or as a symlink into one — and `mkdir -p` would
# succeed against BOTH without a word. The artifacts are full-page screenshots
# of an AUTHENTICATED console session (CodeQL js/insecure-temporary-file,
# alerts #323 / #330).
#
# A hardened creator was added to the repo for those alerts and this script
# never called it — the embedded copy below predated it and ran a bare
# mkdirSync. So the directory is now created HERE, once, before node starts,
# and the embedded copy does no mkdir at all.
set -euo pipefail

ART_DIR="${LOOM_UAT_ARTIFACT_DIR:-$HOME/.loom-uat}"

# -L before -d: a symlink to a directory answers yes to -d, so checking -d
# first would follow exactly the link this refuses.
if [ -L "$ART_DIR" ]; then
  echo "Refusing to use $ART_DIR: it is a symlink." >&2
  exit 1
fi
if [ -e "$ART_DIR" ] && [ ! -d "$ART_DIR" ]; then
  echo "Refusing to use $ART_DIR: it exists and is not a directory." >&2
  exit 1
fi

mkdir -m 700 -p "$ART_DIR"
# -m only applies to directories mkdir CREATES. One made earlier by a plain
# `mkdir -p` is 0755 under the default umask — ours, and world-readable. Repair
# it rather than trust the create flag.
chmod 700 "$ART_DIR"
export LOOM_UAT_ARTIFACT_DIR="$ART_DIR"

cd "$ART_DIR"

# The embedded smoke test. Regenerate with:
#   node -e "console.log(require('fs').readFileSync('apps/fiab-console/tests/uat-console-smoke.mjs').toString('base64'))"
# scripts/ci/check-temp-artifact-safety.mjs DECODES this blob and scans it, so a
# stale copy that reintroduces a fixed /tmp path fails CI instead of shipping.
echo 'IyEvdXNyL2Jpbi9lbnYgbm9kZQovLyBDU0EgTG9vbSBDb25zb2xlIOKAlCBVQVQgc21va2UgdGVzdAovLyBEZXNpZ25lZCB0byBydW4gb24gdGhlIFVBVCBqdW1wYm94ICh3aGljaCBoYXMgVk5ldC1pbnRlcm5hbCBhY2Nlc3MKLy8gdG8gdGhlIENvbnNvbGUpLiBWYWxpZGF0ZXMgYWxsIDggcGFuZXMgbG9hZCArIGJhc2ljIGludGVyYWN0aW9ucy4KLy8KLy8gVXNhZ2U6IG5vZGUgdWF0LWNvbnNvbGUtc21va2UubWpzIDxjb25zb2xlLXVybD4KLy8gT3V0cHV0OiBKU09OIHRvIHN0ZG91dCB3aXRoIHBhc3MvZmFpbCBwZXIgcGFuZSArIHNjcmVlbnNob3RzIGluIHRoZSBkaXJlY3RvcnkKLy8gICAgICAgICBuYW1lZCBieSBMT09NX1VBVF9BUlRJRkFDVF9ESVIsIHdoaWNoIHRoZSBydW5uZXIgc2NyaXB0IGNyZWF0ZXMgYW5kCi8vICAgICAgICAgdmFsaWRhdGVzIChtb2RlIDA3MDAsIG5vdCBhIHN5bWxpbmssIHVuZGVyICRIT01FIOKAlCBuZXZlciBzaGFyZWQgL3RtcCkuCgppbXBvcnQgeyBjaHJvbWl1bSB9IGZyb20gJ3BsYXl3cmlnaHQnOwppbXBvcnQgZnMgZnJvbSAnZnMnOwppbXBvcnQgcGF0aCBmcm9tICdwYXRoJzsKCmNvbnN0IENPTlNPTEVfVVJMID0gcHJvY2Vzcy5hcmd2WzJdIHx8IHByb2Nlc3MuZW52LkxPT01fQ09OU09MRV9VUkwgfHwKICAnaHR0cHM6Ly9sb29tLWNvbnNvbGUuaW50ZXJuYWwuZGVsaWdodGZ1bG1vc3MtOTYyMDJiZmQuZWFzdHVzMi5henVyZWNvbnRhaW5lcmFwcHMuaW8nOwovLyBUaGUgZGlyZWN0b3J5IGlzIGNyZWF0ZWQgKyB2YWxpZGF0ZWQgYnkgdWF0LXJ1bm5lci1maW5hbC5zaCBCRUZPUkUgbm9kZSBzdGFydHMuCi8vIFRoaXMgY29weSBkZWxpYmVyYXRlbHkgZG9lcyBubyBta2RpciBvZiBpdHMgb3duOiBhIGJhcmUKLy8gbWtkaXJTeW5jKCcvdG1wL2xvb20tdWF0Jywge3JlY3Vyc2l2ZTp0cnVlfSkgaGVyZSBpcyBleGFjdGx5IHRoZSBidWcgdGhpcwovLyByZXBsYWNlcyAoQ29kZVFMIGpzL2luc2VjdXJlLXRlbXBvcmFyeS1maWxlICMzMjMvIzMzMCkgYW5kIGR1cGxpY2F0aW5nIHRoZQovLyBjcmVhdGlvbiBsb2dpYyBpcyBob3cgdGhlIHR3byBjb3BpZXMgZHJpZnRlZCBhcGFydCBpbiB0aGUgZmlyc3QgcGxhY2UuCmNvbnN0IFNDUkVFTlNIT1RfRElSID0gcHJvY2Vzcy5lbnYuTE9PTV9VQVRfQVJUSUZBQ1RfRElSOwppZiAoIVNDUkVFTlNIT1RfRElSKSB7CiAgY29uc29sZS5lcnJvcignTE9PTV9VQVRfQVJUSUZBQ1RfRElSIGlzIG5vdCBzZXQuIFJ1biB0aGlzIHZpYSBzY3JpcHRzL2NzYS1sb29tL3VhdC1ydW5uZXItZmluYWwuc2gsJyk7CiAgY29uc29sZS5lcnJvcignd2hpY2ggY3JlYXRlcyB0aGUgYXJ0aWZhY3QgZGlyZWN0b3J5IHByaXZhdGVseSAoMDcwMCwgdW5kZXIgJEhPTUUpIGJlZm9yZSBpbnZva2luZyBub2RlLicpOwogIHByb2Nlc3MuZXhpdCgyKTsKfQoKY29uc3QgcmVzdWx0cyA9IHsgdXJsOiBDT05TT0xFX1VSTCwgc3RhcnRlZDogbmV3IERhdGUoKS50b0lTT1N0cmluZygpLCBwYW5lczogW10gfTsKCmFzeW5jIGZ1bmN0aW9uIHJ1blVBVCgpIHsKICBjb25zdCBicm93c2VyID0gYXdhaXQgY2hyb21pdW0ubGF1bmNoKHsgaGVhZGxlc3M6IHRydWUsIGFyZ3M6IFsnLS1uby1zYW5kYm94J10gfSk7CiAgY29uc3QgY29udGV4dCA9IGF3YWl0IGJyb3dzZXIubmV3Q29udGV4dCh7CiAgICBpZ25vcmVIVFRQU0Vycm9yczogdHJ1ZSwKICAgIHZpZXdwb3J0OiB7IHdpZHRoOiAxNDQwLCBoZWlnaHQ6IDkwMCB9LAogIH0pOwogIGNvbnN0IHBhZ2UgPSBhd2FpdCBjb250ZXh0Lm5ld1BhZ2UoKTsKCiAgcGFnZS5vbignY29uc29sZScsIG1zZyA9PiB7CiAgICBpZiAobXNnLnR5cGUoKSA9PT0gJ2Vycm9yJykgY29uc29sZS5lcnJvcignW3BhZ2UtY29uc29sZS1lcnJvcl0nLCBtc2cudGV4dCgpKTsKICB9KTsKICBwYWdlLm9uKCdwYWdlZXJyb3InLCBlcnIgPT4gY29uc29sZS5lcnJvcignW3BhZ2UtZXJyb3JdJywgZXJyLm1lc3NhZ2UpKTsKCiAgLy8gMS4gUm9vdCBwYWdlIGxvYWRzCiAgdHJ5IHsKICAgIGNvbnN0IHJlc3AgPSBhd2FpdCBwYWdlLmdvdG8oQ09OU09MRV9VUkwsIHsgd2FpdFVudGlsOiAnbmV0d29ya2lkbGUnLCB0aW1lb3V0OiAzMDAwMCB9KTsKICAgIHJlc3VsdHMucm9vdFN0YXR1cyA9IHJlc3Auc3RhdHVzKCk7CiAgICBhd2FpdCBwYWdlLnNjcmVlbnNob3QoeyBwYXRoOiBwYXRoLmpvaW4oU0NSRUVOU0hPVF9ESVIsICcwMC1yb290LnBuZycpLCBmdWxsUGFnZTogdHJ1ZSB9KTsKICB9IGNhdGNoIChlcnIpIHsKICAgIHJlc3VsdHMucm9vdEVycm9yID0gZXJyLm1lc3NhZ2U7CiAgICBhd2FpdCBicm93c2VyLmNsb3NlKCk7CiAgICByZXR1cm4gcmVzdWx0czsKICB9CgogIC8vIDIuIEVhY2ggcGFuZQogIGNvbnN0IHBhbmVzID0gWwogICAgeyBwYXRoOiAnLycsIG5hbWU6ICd3b3Jrc3BhY2VzJyB9LAogICAgeyBwYXRoOiAnL2xha2Vob3VzZScsIG5hbWU6ICdsYWtlaG91c2UnIH0sCiAgICB7IHBhdGg6ICcvd2FyZWhvdXNlJywgbmFtZTogJ3dhcmVob3VzZScgfSwKICAgIHsgcGF0aDogJy9ub3RlYm9vaycsIG5hbWU6ICdub3RlYm9vaycgfSwKICAgIHsgcGF0aDogJy9zZW1hbnRpYy1tb2RlbCcsIG5hbWU6ICdzZW1hbnRpYy1tb2RlbCcgfSwKICAgIHsgcGF0aDogJy9hY3RpdmF0b3InLCBuYW1lOiAnYWN0aXZhdG9yJyB9LAogICAgeyBwYXRoOiAnL2RhdGEtYWdlbnQnLCBuYW1lOiAnZGF0YS1hZ2VudCcgfSwKICAgIHsgcGF0aDogJy9zZXR1cCcsIG5hbWU6ICdzZXR1cC13aXphcmQnIH0sCiAgXTsKCiAgZm9yIChjb25zdCBwIG9mIHBhbmVzKSB7CiAgICBjb25zdCB1cmwgPSBgJHtDT05TT0xFX1VSTH0ke3AucGF0aH1gOwogICAgdHJ5IHsKICAgICAgY29uc3QgcmVzcCA9IGF3YWl0IHBhZ2UuZ290byh1cmwsIHsgd2FpdFVudGlsOiAnZG9tY29udGVudGxvYWRlZCcsIHRpbWVvdXQ6IDIwMDAwIH0pOwogICAgICBhd2FpdCBwYWdlLndhaXRGb3JUaW1lb3V0KDE1MDApOwogICAgICBhd2FpdCBwYWdlLnNjcmVlbnNob3QoeyBwYXRoOiBwYXRoLmpvaW4oU0NSRUVOU0hPVF9ESVIsIGAke3AubmFtZX0ucG5nYCksIGZ1bGxQYWdlOiB0cnVlIH0pOwogICAgICAvLyBGaW5kIHRoZSBsZWZ0LW5hdiBhbmQgdmVyaWZ5IHRoZSBhY3RpdmUgcGFuZSBpcyBoaWdobGlnaHRlZAogICAgICBjb25zdCBuYXZBY3RpdmUgPSBhd2FpdCBwYWdlLmxvY2F0b3IoJ2FbYXJpYS1jdXJyZW50PSJwYWdlIl0nKS5jb3VudCgpOwogICAgICBjb25zdCBoZWFkaW5nID0gYXdhaXQgcGFnZS5sb2NhdG9yKCdoMSwgaDInKS5maXJzdCgpLnRleHRDb250ZW50KHsgdGltZW91dDogMzAwMCB9KS5jYXRjaCgoKSA9PiBudWxsKTsKICAgICAgcmVzdWx0cy5wYW5lcy5wdXNoKHsKICAgICAgICBuYW1lOiBwLm5hbWUsCiAgICAgICAgc3RhdHVzOiByZXNwLnN0YXR1cygpLAogICAgICAgIG5hdkFjdGl2ZSwKICAgICAgICBoZWFkaW5nOiAoaGVhZGluZyB8fCAnJykudHJpbSgpLnN1YnN0cmluZygwLCA4MCksCiAgICAgICAgb2s6IHJlc3Auc3RhdHVzKCkgPT09IDIwMCB8fCByZXNwLnN0YXR1cygpID09PSA0MDEsIC8vIDQwMSBleHBlY3RlZCBmb3IgdW4tYXV0aGVkIEJGRiByb3V0ZXMKICAgICAgfSk7CiAgICB9IGNhdGNoIChlcnIpIHsKICAgICAgcmVzdWx0cy5wYW5lcy5wdXNoKHsgbmFtZTogcC5uYW1lLCBlcnJvcjogZXJyLm1lc3NhZ2UsIG9rOiBmYWxzZSB9KTsKICAgIH0KICB9CgogIGF3YWl0IGJyb3dzZXIuY2xvc2UoKTsKICByZXN1bHRzLmNvbXBsZXRlZCA9IG5ldyBEYXRlKCkudG9JU09TdHJpbmcoKTsKICByZXR1cm4gcmVzdWx0czsKfQoKcnVuVUFUKCkKICAudGhlbihyID0+IHsKICAgIGNvbnNvbGUubG9nKEpTT04uc3RyaW5naWZ5KHIsIG51bGwsIDIpKTsKICAgIGZzLndyaXRlRmlsZVN5bmMocGF0aC5qb2luKFNDUkVFTlNIT1RfRElSLCAndWF0LXJlc3VsdC5qc29uJyksIEpTT04uc3RyaW5naWZ5KHIsIG51bGwsIDIpKTsKICAgIHByb2Nlc3MuZXhpdChyLnBhbmVzLmV2ZXJ5KHAgPT4gcC5vaykgPyAwIDogMSk7CiAgfSkKICAuY2F0Y2goZXJyID0+IHsKICAgIGNvbnNvbGUuZXJyb3IoJ1VBVCBjcmFzaGVkOicsIGVycik7CiAgICBwcm9jZXNzLmV4aXQoMik7CiAgfSk7Cg==' | base64 -d > uat-console-smoke.mjs

if [ ! -d node_modules/playwright ]; then
  npm init -y >/dev/null
  npm install playwright --no-audit --no-fund >/dev/null 2>&1
fi

node uat-console-smoke.mjs "$@" 2>&1
