# Databricks notebook source
# MAGIC %md
# MAGIC # Bronze Layer: Pharma Clinical Trial Data Ingestion
# MAGIC
# MAGIC This notebook ingests raw clinical trial data (subjects, adverse events, visits)
# MAGIC into the Bronze layer for the Pharma & Life Sciences vertical.
# MAGIC
# MAGIC ## Data Source
# MAGIC - **Type:** Parquet files (generated by TrialGenerator)
# MAGIC - **Location:** Files/landing/pharma_trials/
# MAGIC - **Domains:** subjects, adverse_events, visits
# MAGIC
# MAGIC ## Target
# MAGIC - **Table:** bronze_pharma_trials
# MAGIC - **Format:** Delta Lake (append-only for 21 CFR Part 11 audit trail)
# MAGIC - **Compliance:** 21 CFR Part 11, GxP ALCOA+

# COMMAND ----------

# MAGIC %md
# MAGIC ## Configuration

# COMMAND ----------

from datetime import datetime

from pyspark.sql import SparkSession
from pyspark.sql.functions import (
    col,
    current_timestamp,
    input_file_name,
    lit,
)
from pyspark.sql.types import (
    BooleanType,
    DoubleType,
    IntegerType,
    StringType,
    StructField,
    StructType,
    TimestampType,
)

# Fabric parameter shim
try:
    DOMAIN = mssparkutils.widgets.get("domain", "subjects")  # noqa: F821
except Exception:
    DOMAIN = "subjects"

SOURCE_BASE = "Files/landing/pharma_trials"
TARGET_TABLE = "lh_bronze.bronze_pharma_trials"
BATCH_ID = datetime.now().strftime("%Y%m%d_%H%M%S")

print(f"Domain: {DOMAIN}")
print(f"Source: {SOURCE_BASE}/{DOMAIN}/")
print(f"Target: {TARGET_TABLE}")
print(f"Batch ID: {BATCH_ID}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Define Schemas
# MAGIC
# MAGIC Explicit schemas per domain for validation and performance.

# COMMAND ----------

subject_schema = StructType([
    StructField("subject_id", StringType(), False),
    StructField("site_id", StringType(), False),
    StructField("study_id", StringType(), False),
    StructField("phase", StringType(), True),
    StructField("therapeutic_area", StringType(), True),
    StructField("enrollment_dt", StringType(), True),
    StructField("arm", StringType(), True),
    StructField("status", StringType(), True),
    StructField("age", IntegerType(), True),
    StructField("sex", StringType(), True),
    StructField("race", StringType(), True),
    StructField("ethnicity", StringType(), True),
    StructField("_ingested_at", StringType(), True),
    StructField("_source", StringType(), True),
    StructField("_batch_id", StringType(), True),
])

ae_schema = StructType([
    StructField("ae_id", StringType(), False),
    StructField("subject_id", StringType(), False),
    StructField("study_id", StringType(), False),
    StructField("ae_term", StringType(), True),
    StructField("meddra_pt", StringType(), True),
    StructField("meddra_soc", StringType(), True),
    StructField("severity", StringType(), True),
    StructField("serious_flag", BooleanType(), True),
    StructField("onset_dt", StringType(), True),
    StructField("resolution_dt", StringType(), True),
    StructField("causality", StringType(), True),
    StructField("outcome", StringType(), True),
    StructField("action_taken", StringType(), True),
    StructField("_ingested_at", StringType(), True),
    StructField("_source", StringType(), True),
    StructField("_batch_id", StringType(), True),
])

visit_schema = StructType([
    StructField("visit_id", StringType(), False),
    StructField("subject_id", StringType(), False),
    StructField("study_id", StringType(), False),
    StructField("visit_type", StringType(), True),
    StructField("scheduled_dt", StringType(), True),
    StructField("actual_dt", StringType(), True),
    StructField("deviation_days", IntegerType(), True),
    StructField("protocol_deviation_flag", BooleanType(), True),
    StructField("systolic_bp", IntegerType(), True),
    StructField("diastolic_bp", IntegerType(), True),
    StructField("heart_rate", IntegerType(), True),
    StructField("weight_kg", DoubleType(), True),
    StructField("_ingested_at", StringType(), True),
    StructField("_source", StringType(), True),
    StructField("_batch_id", StringType(), True),
])

SCHEMAS = {
    "subjects": subject_schema,
    "adverse_events": ae_schema,
    "visits": visit_schema,
}

# COMMAND ----------

# MAGIC %md
# MAGIC ## Read Source Data

# COMMAND ----------

source_path = f"{SOURCE_BASE}/{DOMAIN}/"
schema = SCHEMAS.get(DOMAIN, subject_schema)

df_raw = spark.read \
    .schema(schema) \
    .parquet(source_path)

record_count = df_raw.count()
print(f"Source records for domain '{DOMAIN}': {record_count:,}")
df_raw.printSchema()

# COMMAND ----------

# MAGIC %md
# MAGIC ## Add Bronze Metadata
# MAGIC
# MAGIC Append-only ingestion with audit trail columns for 21 CFR Part 11.

# COMMAND ----------

df_bronze = df_raw \
    .withColumn("_bronze_batch_id", lit(BATCH_ID)) \
    .withColumn("_bronze_ingested_at", current_timestamp()) \
    .withColumn("_bronze_source_file", input_file_name()) \
    .withColumn("_bronze_domain", lit(DOMAIN))

# COMMAND ----------

# MAGIC %md
# MAGIC ## Write to Bronze (Append-Only)
# MAGIC
# MAGIC Append mode preserves every version for audit trail compliance.

# COMMAND ----------

df_bronze.write \
    .format("delta") \
    .mode("append") \
    .option("mergeSchema", "true") \
    .saveAsTable(TARGET_TABLE)

final_count = spark.table(TARGET_TABLE).count()
print(f"Bronze table '{TARGET_TABLE}' total records: {final_count:,}")
print(f"Batch '{BATCH_ID}' appended {record_count:,} {DOMAIN} records")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Data Quality Summary (Bronze)
# MAGIC
# MAGIC Minimal validation — just ensure critical identifiers are present.

# COMMAND ----------

from pyspark.sql.functions import count, sum as spark_sum, when

id_col = {"subjects": "subject_id", "adverse_events": "ae_id", "visits": "visit_id"}
pk = id_col.get(DOMAIN, "subject_id")

quality_df = df_bronze.agg(
    count("*").alias("total_records"),
    spark_sum(when(col(pk).isNull(), 1).otherwise(0)).alias("null_pk_count"),
    spark_sum(when(col("study_id").isNull(), 1).otherwise(0)).alias("null_study_count"),
)

quality_df.show()
print("Bronze ingestion complete — 21 CFR Part 11 audit trail preserved.")
