/**
 * model-bound-app — generators that turn a BOUND semantic model into a full
 * Rayfin web app (the model-bound case; the Rayfin editor's hand-authored
 * entities cover only the general case).
 *
 * Given a semantic model's tables (columns + measures) and relationships, this
 * emits, one-for-one with the model:
 *   • rayfin/model.ts            — an @entity per model table, @text/@number/…
 *                                  per column, plus a @relation per model
 *                                  relationship (1:1 / 1:many).
 *   • rayfin/dab-config.json     — a Data API Builder config exposing every
 *                                  entity as a REST + GraphQL read endpoint
 *                                  (the same DAB engine `rayfin up` applies).
 *   • web app pages              — a typed React data-grid page per entity plus
 *                                  a measures dashboard, so the deployed app is
 *                                  a real, navigable web app backed by the model.
 *   • CLI command sequence       — the exact `rayfin init`/`rayfin up` steps.
 *
 * Everything is derived from the real model structure — no placeholders. The
 * generators are pure functions so they're unit-testable and reused by the
 * editor + the route receipt.
 *
 * Refs (preview): https://learn.microsoft.com/fabric/apps/overview ·
 *   https://learn.microsoft.com/azure/data-api-builder/ ·
 *   https://github.com/microsoft/rayfin
 */

export type RayfinFieldType = 'text' | 'boolean' | 'date' | 'number';

export interface BoundColumn { name: string; dataType: string }
export interface BoundMeasure { name: string; expression?: string }
export interface BoundTable { name: string; columns: BoundColumn[]; measures?: BoundMeasure[] }
export interface BoundRelationship {
  name: string;
  fromTable: string; fromColumn: string;
  toTable: string; toColumn: string;
  crossFilteringBehavior?: string;
}
export interface BoundModel {
  id: string;
  name: string;
  tables: BoundTable[];
  relationships?: BoundRelationship[];
}

/** Map a semantic-model / tabular column dataType to a Rayfin decorator type. */
export function mapDataType(dataType: string | undefined): RayfinFieldType {
  const d = String(dataType || '').toLowerCase();
  if (/bool/.test(d)) return 'boolean';
  if (/date|time/.test(d)) return 'date';
  if (/int|num|dec|double|float|money|currency|real/.test(d)) return 'number';
  return 'text';
}

const DECO: Record<RayfinFieldType, string> = { text: 'text', boolean: 'boolean', date: 'date', number: 'number' };
const TS_TYPE: Record<RayfinFieldType, string> = { text: 'string', boolean: 'boolean', date: 'Date', number: 'number' };

export function pascal(s: string): string {
  return (s || 'Entity').replace(/[^A-Za-z0-9]+/g, ' ').trim().split(' ')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join('') || 'Entity';
}

export function camel(s: string): string {
  const p = pascal(s);
  return p.charAt(0).toLowerCase() + p.slice(1);
}

/** A safe identifier for a property name. */
function ident(s: string): string {
  const cleaned = String(s || 'field').replace(/[^A-Za-z0-9_]+/g, '_').replace(/^(\d)/, '_$1');
  return cleaned || 'field';
}

/**
 * Generate rayfin/model.ts from a bound model: one @entity per table, decorated
 * fields per column, and @relation()s per model relationship. The Rayfin
 * relationship decorator is preview surface — emitted with a verify note.
 */
export function generateBoundModel(model: BoundModel): string {
  const types = new Set<RayfinFieldType>();
  for (const t of model.tables) for (const c of t.columns) types.add(mapDataType(c.dataType));
  const rels = model.relationships || [];
  const hasRel = rels.length > 0;
  const imports = ['entity', ...Array.from(types).map((t) => DECO[t]).sort(), ...(hasRel ? ['relation'] : [])];

  const relsByTable = new Map<string, BoundRelationship[]>();
  for (const r of rels) {
    const list = relsByTable.get(r.fromTable) || [];
    list.push(r);
    relsByTable.set(r.fromTable, list);
  }

  const blocks = model.tables.map((t) => {
    const cls = pascal(t.name);
    const props = t.columns.map((c) => {
      const ft = mapDataType(c.dataType);
      return `  @${DECO[ft]}() ${ident(c.name)}!: ${TS_TYPE[ft]};`;
    });
    const relProps = (relsByTable.get(t.name) || []).map((r) => {
      const target = pascal(r.toTable);
      return `  @relation(() => ${target}) ${camel(r.toTable)}?: ${target};`;
    });
    const body = [...props, ...relProps].join('\n') || '  // no columns';
    return `@entity()\nexport class ${cls} {\n${body}\n}`;
  }).join('\n\n');

  return [
    `// rayfin/model.ts — generated by CSA Loom from semantic model "${model.name}"`,
    '// (model-bound: entities mirror the model\'s tables/columns/relationships).',
    '// Verify decorators against the current @microsoft/rayfin-core API (preview).',
    `import { ${imports.join(', ')} } from '@microsoft/rayfin-core';`,
    '',
    blocks,
    '',
  ].join('\n');
}

/**
 * Generate a Data API Builder config (rayfin applies DAB under the hood) that
 * exposes every model table as a REST + GraphQL read entity. Source maps to the
 * deployed OneLake/SQL table name; permissions grant authenticated read (the
 * app inherits the tenant's Entra identity via Rayfin auth).
 */
export function generateDabConfig(model: BoundModel): string {
  const entities: Record<string, unknown> = {};
  for (const t of model.tables) {
    const name = pascal(t.name);
    entities[name] = {
      source: { object: t.name, type: 'table' },
      rest: { enabled: true, path: `/${camel(t.name)}` },
      graphql: { enabled: true, type: { singular: name, plural: `${name}s` } },
      permissions: [
        { role: 'authenticated', actions: [{ action: 'read' }] },
      ],
    };
  }
  const cfg = {
    $schema: 'https://github.com/Azure/data-api-builder/releases/latest/download/dab.draft.schema.json',
    'data-source': {
      'database-type': 'mssql',
      'connection-string': '@env(\'DATABASE_CONNECTION_STRING\')',
    },
    runtime: {
      rest: { enabled: true, path: '/api' },
      graphql: { enabled: true, path: '/graphql' },
      host: { mode: 'production', authentication: { provider: 'EntraID' } },
    },
    entities,
  };
  return JSON.stringify(cfg, null, 2);
}

/**
 * Generate a typed React data-grid page for ONE entity. The page fetches the
 * DAB REST endpoint Rayfin exposes (`/api/<Entity>`) and renders the model's
 * columns as a Fluent DataGrid — a real, navigable surface in the deployed app.
 */
export function generateEntityPage(model: BoundModel, table: BoundTable): { path: string; content: string } {
  const name = pascal(table.name);
  const cols = table.columns;
  const colDefs = cols.map((c) => {
    const id = ident(c.name);
    return [
      `  createTableColumn<${name}>({`,
      `    columnId: '${id}',`,
      `    renderHeaderCell: () => '${c.name}',`,
      `    renderCell: (row) => String(row.${id} ?? ''),`,
      '  }),',
    ].join('\n');
  }).join('\n');
  const tsFields = cols.map((c) => `  ${ident(c.name)}: ${TS_TYPE[mapDataType(c.dataType)]};`).join('\n');
  const content = [
    `// app/${camel(table.name)}/page.tsx — generated by CSA Loom (model-bound Rayfin app)`,
    "'use client';",
    "import { useEffect, useState } from 'react';",
    "import { DataGrid, DataGridHeader, DataGridHeaderCell, DataGridBody, DataGridRow, DataGridCell, createTableColumn, TableColumnDefinition } from '@fluentui/react-components';",
    '',
    `interface ${name} {`,
    tsFields || '  // no columns',
    '}',
    '',
    `const columns: TableColumnDefinition<${name}>[] = [`,
    colDefs,
    '];',
    '',
    `export default function ${name}Page() {`,
    `  const [rows, setRows] = useState<${name}[]>([]);`,
    '  const [error, setError] = useState<string | null>(null);',
    '  useEffect(() => {',
    `    fetch('/api/${camel(table.name)}')`,
    '      .then((r) => r.json())',
    '      .then((j) => setRows(j.value ?? j ?? []))',
    '      .catch((e) => setError(String(e)));',
    '  }, []);',
    '  if (error) return <div role="alert">Failed to load: {error}</div>;',
    '  return (',
    `    <main>`,
    `      <h1>${table.name}</h1>`,
    '      <DataGrid items={rows} columns={columns} getRowId={(_r, i) => String(i)}>',
    '        <DataGridHeader>',
    '          <DataGridRow>{({ renderHeaderCell }) => <DataGridHeaderCell>{renderHeaderCell()}</DataGridHeaderCell>}</DataGridRow>',
    '        </DataGridHeader>',
    '        <DataGridBody<' + name + '>>',
    '          {({ item, rowId }) => (',
    '            <DataGridRow<' + name + '> key={rowId}>{({ renderCell }) => <DataGridCell>{renderCell(item)}</DataGridCell>}</DataGridRow>',
    '          )}',
    '        </DataGridBody>',
    '      </DataGrid>',
    '    </main>',
    '  );',
    '}',
    '',
  ].join('\n');
  return { path: `app/${camel(table.name)}/page.tsx`, content };
}

/**
 * Generate a measures dashboard page surfacing the model's measures (the model
 * is a semantic layer; measures are its KPIs). Each measure card calls the DAB
 * GraphQL aggregation Rayfin exposes for the measure's host table.
 */
export function generateMeasuresPage(model: BoundModel): { path: string; content: string } {
  const measures = model.tables.flatMap((t) => (t.measures || []).map((m) => ({ table: t.name, ...m })));
  const cards = measures.map((m) => `  { table: ${JSON.stringify(m.table)}, name: ${JSON.stringify(m.name)}, expression: ${JSON.stringify(m.expression || '')} },`).join('\n');
  const content = [
    '// app/dashboard/page.tsx — generated by CSA Loom (model-bound measures dashboard)',
    "'use client';",
    "import { Card, CardHeader, Text } from '@fluentui/react-components';",
    '',
    'const MEASURES = [',
    cards || '  // model has no measures',
    '];',
    '',
    'export default function DashboardPage() {',
    '  return (',
    '    <main>',
    `      <h1>${model.name} — measures</h1>`,
    '      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))", gap: 12 }}>',
    '        {MEASURES.map((m) => (',
    '          <Card key={m.table + "." + m.name}>',
    '            <CardHeader header={<Text weight="semibold">{m.name}</Text>} description={<Text size={200}>{m.table}</Text>} />',
    '            <Text size={200} font="monospace">{m.expression}</Text>',
    '          </Card>',
    '        ))}',
    '      </div>',
    '    </main>',
    '  );',
  ].concat([
    '  );',
    '}',
    '',
  ]).join('\n');
  return { path: 'app/dashboard/page.tsx', content };
}

export interface GeneratedFile { path: string; content: string }

/** Generate every file for the model-bound web app. */
export function generateWebApp(model: BoundModel): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  files.push({ path: 'rayfin/model.ts', content: generateBoundModel(model) });
  files.push({ path: 'rayfin/dab-config.json', content: generateDabConfig(model) });
  for (const t of model.tables) files.push(generateEntityPage(model, t));
  const hasMeasures = model.tables.some((t) => (t.measures || []).length > 0);
  if (hasMeasures) files.push(generateMeasuresPage(model));
  files.push({ path: 'app/page.tsx', content: generateHomePage(model) });
  return files;
}

/** Generate the app home page — a navigation hub over every entity + dashboard. */
export function generateHomePage(model: BoundModel): string {
  const links = model.tables.map((t) => `        <li><a href="/${camel(t.name)}">${t.name}</a></li>`).join('\n');
  const hasMeasures = model.tables.some((t) => (t.measures || []).length > 0);
  return [
    '// app/page.tsx — generated by CSA Loom (model-bound Rayfin app home)',
    'export default function Home() {',
    '  return (',
    '    <main>',
    `      <h1>${model.name}</h1>`,
    `      <p>Web app backed by the "${model.name}" semantic model.</p>`,
    '      <nav>',
    '        <ul>',
    links,
    ...(hasMeasures ? ['        <li><a href="/dashboard">Measures dashboard</a></li>'] : []),
    '        </ul>',
    '      </nav>',
    '    </main>',
    '  );',
    '}',
    '',
  ].join('\n');
}

/**
 * The exact CLI command sequence for a model-bound app: scaffold, init with the
 * DB service + Fabric auth + static hosting, then deploy. The generated DAB
 * config + model.ts + pages above go into the project before `rayfin up`.
 */
export function generateBoundCommands(appName: string, workspaceName?: string): string {
  const ws = (workspaceName || '').trim();
  const app = (appName || 'my-app').trim() || 'my-app';
  return [
    '# 1) Scaffold a Rayfin app (creates the project + Fabric workspace binding)',
    `npm create @microsoft/rayfin@latest ${app}${ws ? ` --workspace "${ws}"` : ''}`,
    `cd ${app}`,
    '',
    '# 2) Initialize Rayfin with a database service, Fabric auth, and static hosting',
    `npx rayfin init ${app} --services db --auth-methods fabric --static-hosting`,
    '',
    '# 3) Drop the generated files in:',
    '#      rayfin/model.ts          (entities mirroring the semantic model)',
    '#      rayfin/dab-config.json   (REST + GraphQL read endpoints per table)',
    '#      app/**                   (one data-grid page per table + measures dashboard)',
    '',
    '# 4) Deploy the app backend + static frontend to Fabric',
    'npx rayfin up',
  ].join('\n');
}
