#!/usr/bin/env node
/**
 * release-please-integrity — MUTATION PROOFS for both halves of #3393.
 *
 * TWO defects, one workflow:
 *
 *   (1) release PRs merged on statuses no test produced. The synthetic path is
 *       deleted; the wait-timeout now fails the lane instead of reporting a
 *       green run that bridged nothing (measured: run 31786503229, 2026-08-14).
 *   (2) merging release PR #3419 closed issue #3429 — an open P0 — because
 *       release-please renders every footer reference as ", closes #N" whatever
 *       the author wrote. #3431 wrote `Refs #3429`.
 *
 * WHY EVERY ASSERTION HERE CARRIES A CONTROL
 * ------------------------------------------
 * Both halves are "the thing must NOT happen" properties, and a test for an
 * absence passes trivially when its matcher has drifted off the subject. So:
 *
 *   * the neutralizer is proven on the LITERAL body of PR #3419, byte-for-byte
 *     from the API, not on a hand-typed approximation of it;
 *   * it is proven to leave a keyword-free body byte-IDENTICAL, so "it removed
 *     the keyword" cannot be satisfied by mangling everything;
 *   * it is run over the committed CHANGELOG.md, which is generated by the real
 *     release-please, so a matcher that stopped understanding that format
 *     produces 0 hits and FAILS here rather than reading as clean;
 *   * the detector and the rewriter are cross-checked against each other, so
 *     neither can go vacuously quiet alone;
 *   * every workflow invariant is fed a body with exactly that property removed
 *     and must flag it.
 *
 * Run: node --test scripts/ci/__tests__/release-please-integrity.test.mjs
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  CLOSING_KEYWORDS,
  findClosingKeywords,
  neutralizeClosingKeywords,
} from '../neutralize-release-close-keywords.mjs';
import {
  MIN_REQUIRED_CONTEXTS,
  SELF_TEST_CASES,
  judgeWorkflow,
  parseRequired,
  runSelfTest,
} from '../check-release-please-integrity.mjs';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
const WORKFLOW = path.join(REPO_ROOT, '.github', 'workflows', 'release-please.yml');

/**
 * The exact line from release PR #3419's body (read from
 * `gh api repos/{repo}/pulls/3419 --jq .body` on 2026-08-14) that closed #3429
 * when the PR merged. Kept verbatim: an approximation would let the matcher
 * drift away from what release-please actually emits without this noticing.
 */
const PR3419_LINE =
  '* **deploy:** the copilot-function lane cancelled its own deploys and its error asserted a lie ' +
  '([#3431](https://github.com/fgarofalo56/csa-inabox/issues/3431)) ' +
  '([1b555a0](https://github.com/fgarofalo56/csa-inabox/commit/1b555a02ed60a3feff8983949f85bc5ea844a909)), ' +
  'closes [#3429](https://github.com/fgarofalo56/csa-inabox/issues/3429)';

// ── half 2: the closing-keyword neutralizer ─────────────────────────────────

test('the LITERAL #3419 body line is detected and neutralized', () => {
  const found = findClosingKeywords(PR3419_LINE);
  assert.equal(found.length, 1, 'the line that closed a P0 must be detected exactly once');
  assert.equal(found[0].keyword, 'closes');

  const out = neutralizeClosingKeywords(PR3419_LINE);
  assert.equal(findClosingKeywords(out).length, 0, 'no closing keyword may survive');
  assert.match(out, /, refs \[#3429\]/, 'the reference is kept — only the keyword changes');
  assert.match(out, /issues\/3429\)$/, 'the link itself is untouched');
  // Nothing else on the line moved: same length, one word swapped.
  assert.equal(out.length, PR3419_LINE.length - 'closes'.length + 'refs'.length);
});

test('every GitHub closing keyword is caught, in every reference form', () => {
  const forms = [
    '#123',
    'GH-123',
    'owner/repo#123',
    '[#123](https://github.com/o/r/issues/123)',
    'https://github.com/o/r/issues/123',
  ];
  for (const kw of CLOSING_KEYWORDS) {
    for (const form of forms) {
      for (const sep of [' ', ': ', '  ']) {
        const body = `some text ${kw}${sep}${form} tail`;
        assert.equal(
          findClosingKeywords(body).length,
          1,
          `"${kw}${sep}${form}" must be detected`,
        );
        assert.equal(
          findClosingKeywords(neutralizeClosingKeywords(body)).length,
          0,
          `"${kw}${sep}${form}" must be neutralized`,
        );
      }
    }
  }
  // Capitalised footers are the common real shape (`Refs #3429`, `Closes #3426`).
  assert.equal(findClosingKeywords('Closes #3426').length, 1);
  assert.equal(findClosingKeywords('Fixed #1').length, 1);
});

test('NON-WEAKENING CONTROL: a body with no closing keyword is returned byte-identical', () => {
  // If this ever fails, "the keyword is gone" above is being satisfied by
  // mangling the body rather than by a targeted rewrite.
  const clean = [
    '### Bug Fixes',
    '',
    '* **ci:** something ([#3428](https://github.com/o/r/issues/3428))',
    '* prose that merely mentions #3429 in passing',
    'This change closes the loop on a long-running argument.',
    'refs #1, refs #2',
    'The fixture directory is fixed-width.',
  ].join('\n');
  assert.equal(findClosingKeywords(clean).length, 0, 'no closing reference present');
  assert.equal(neutralizeClosingKeywords(clean), clean, 'a clean body must not be touched at all');
});

test('NON-WEAKENING CONTROL: "closes" not followed by an issue reference is prose, not a keyword', () => {
  assert.equal(findClosingKeywords('this closes the loop').length, 0);
  assert.equal(findClosingKeywords('the door closed').length, 0);
  assert.equal(findClosingKeywords('a fix landed').length, 0);
  // …but the same word one character later IS a keyword.
  assert.equal(findClosingKeywords('this closes #7 for good').length, 1);
});

test('CORPUS CONTROL: the real CHANGELOG.md still trips the matcher', () => {
  // CHANGELOG.md is written by the real release-please. If the matcher drifts
  // off that format it finds zero here, which is indistinguishable from a clean
  // corpus — so a zero is a FAILURE, not a pass
  // (`guard_with_zero_population_needs_embedded_control`).
  const changelog = readFileSync(path.join(REPO_ROOT, 'CHANGELOG.md'), 'utf8');
  const found = findClosingKeywords(changelog);
  assert.ok(
    found.length >= 20,
    `expected the generated changelog to carry many "closes [#N]" references; found ${found.length}. Either the generator's format changed or this matcher has stopped matching it — refusing to read that as clean.`,
  );
  assert.equal(
    findClosingKeywords(neutralizeClosingKeywords(changelog)).length,
    0,
    'the neutralizer must clear every one of them',
  );
});

test('neutralizing is idempotent', () => {
  const once = neutralizeClosingKeywords(PR3419_LINE);
  assert.equal(neutralizeClosingKeywords(once), once);
});

test('the detector and the rewriter agree — neither can go quiet alone', () => {
  const body = `${PR3419_LINE}\nCloses #1\nFixes GH-2\nrefs #3`;
  const before = findClosingKeywords(body).length;
  assert.equal(before, 3, 'three real closing references, and `refs #3` is not one');
  assert.equal(findClosingKeywords(neutralizeClosingKeywords(body)).length, 0);
  // The rewrite must have changed exactly as many keywords as were detected.
  const changed = body.split(/\brefs\b/i).length - 1;
  const after = neutralizeClosingKeywords(body).split(/\brefs\b/i).length - 1;
  assert.equal(after - changed, before, 'one `refs` appears per detected keyword');
});

// ── half 1: the workflow invariants ─────────────────────────────────────────

test('every embedded control in the guard agrees', () => {
  const bad = runSelfTest();
  assert.deepEqual(bad, [], `embedded controls disagreed: ${JSON.stringify(bad)}`);
  assert.ok(SELF_TEST_CASES.length >= 10, 'the control set must not shrink to nothing');
});

test('the shipped release-please.yml satisfies every invariant', () => {
  const text = readFileSync(WORKFLOW, 'utf8');
  const v = judgeWorkflow(text, {
    workflowExists: (f) => existsSync(path.join(REPO_ROOT, '.github', 'workflows', f)),
  });
  assert.deepEqual(v.failures, [], `release-please.yml broke: ${JSON.stringify(v.failures)}`);
});

test('the REQUIRED manifest parses to 14 contexts, every one with a producer', () => {
  const required = parseRequired(readFileSync(WORKFLOW, 'utf8'));
  assert.equal(required.length, MIN_REQUIRED_CONTEXTS);
  assert.deepEqual(
    required.filter((r) => r.workflow === ''),
    [],
    'a context with no producer is a context nothing can verify',
  );
  assert.deepEqual(
    [...new Set(required.map((r) => r.workflow))].sort(),
    ['fiab-console-ci.yml', 'loom-guardrails.yml', 'test.yml', 'validate.yml'],
  );
});

test('MUTATION: re-introducing a producer-less context on the REAL file is caught', () => {
  const text = readFileSync(WORKFLOW, 'utf8');
  const broken = text.replace('"PowerShell Lint|validate.yml"', '"PowerShell Lint|"');
  assert.notEqual(broken, text, 'the mutation must actually apply — a no-op edit proves nothing');
  const ids = judgeWorkflow(broken).failures.map((f) => f.id);
  assert.ok(ids.includes('producerless-context'), `expected producerless-context, got ${ids}`);
});

test('MUTATION: re-introducing a synthetic success post on the REAL file is caught', () => {
  const text = readFileSync(WORKFLOW, 'utf8');
  // The exact shape #3393 records: a second unconditional success status.
  const broken = text.replace(
    '            echo "::notice::0 synthetic statuses posted',
    '            gh api -X POST "repos/x/statuses/y" -f state=success -f context="z"\n' +
      '            echo "::notice::0 synthetic statuses posted',
  );
  assert.notEqual(broken, text, 'the mutation must actually apply');
  const ids = judgeWorkflow(broken).failures.map((f) => f.id);
  assert.ok(ids.includes('multiple-success-sites'), `expected multiple-success-sites, got ${ids}`);
});

test('MUTATION: making the timeout non-fatal again on the REAL file is caught', () => {
  const text = readFileSync(WORKFLOW, 'utf8');
  // replaceAll, not replace: the file now marks UNVERIFIED on several distinct
  // failure paths, and this guard's invariant is only that the marker EXISTS.
  // Removing one path is NOT caught here — deliberately. That case belongs to
  // the behavioural suite, where each of the three ungraded states asserts a
  // non-zero exit, so dropping any single increment fails a test there.
  // Saying so rather than implying this structural check is finer than it is.
  const broken = text.replaceAll('UNVERIFIED=$((UNVERIFIED + 1))', 'true # noted');
  assert.notEqual(broken, text, 'the mutation must actually apply');
  assert.ok(!broken.includes('UNVERIFIED=$((UNVERIFIED + 1))'), 'every increment must really be gone');
  const ids = judgeWorkflow(broken).failures.map((f) => f.id);
  assert.ok(ids.includes('no-unverified-marker'), `expected no-unverified-marker, got ${ids}`);
});

test('MUTATION: dropping the neutralizer from the REAL file is caught', () => {
  const text = readFileSync(WORKFLOW, 'utf8');
  const broken = text
    .split('\n')
    .filter((l) => !l.includes('neutralize-release-close-keywords.mjs'))
    .join('\n');
  assert.notEqual(broken, text, 'the mutation must actually apply');
  const ids = judgeWorkflow(broken).failures.map((f) => f.id);
  assert.ok(ids.includes('no-neutralizer'), `expected no-neutralizer, got ${ids}`);
});

test('MUTATION: dropping only the --check read-back is caught', () => {
  const text = readFileSync(WORKFLOW, 'utf8');
  const broken = text
    .split('\n')
    .filter((l) => !(l.includes('neutralize-release-close-keywords.mjs') && l.includes('--check')))
    .join('\n');
  assert.notEqual(broken, text, 'the mutation must actually apply');
  const ids = judgeWorkflow(broken).failures.map((f) => f.id);
  assert.ok(ids.includes('no-neutralizer-readback'), `expected no-neutralizer-readback, got ${ids}`);
});

test('the guard reads LOGICAL lines — a continuation-split success post is still seen (#3420)', () => {
  // This is the shape in the real file. A physical-line guard sees `gh api …`
  // and `-f state=success` as different lines and finds no site at all, which
  // would read as "no synthetic status here" — a clean verdict from a blind
  // scanner.
  const wf = [
    'jobs:',
    '  j:',
    '    steps:',
    '      - run: |',
    '          REQUIRED_CHECKS=(',
    ...Array.from({ length: MIN_REQUIRED_CONTEXTS }, (_, i) => `            "C${i}|p.yml"`),
    '          )',
    '          node scripts/ci/neutralize-release-close-keywords.mjs a > b',
    '          node scripts/ci/neutralize-release-close-keywords.mjs --check c',
    '          UNVERIFIED=0',
    '          gh api --paginate "repos/${REPO}/commits/${sha}/check-runs?per_page=100"',
    '          gh api --paginate "repos/${REPO}/actions/runs?head_sha=$1&event=workflow_dispatch&per_page=100"',
    '          UNVERIFIED=$((UNVERIFIED + 1))',
    '          gh api -X POST "u" \\',
    '            -f state=failure',
    '          if [ "${verdict}" != "completed/success" ]; then continue; fi',
    '          gh api -X POST "u" \\',
    '            -f state=success \\',
    '            -f context="${ctx}"',
    '          if [ "${UNVERIFIED}" -ne 0 ]; then',
    '            exit 1',
    '          fi',
  ].join('\n');
  const v = judgeWorkflow(wf);
  const ids = v.failures.map((f) => f.id);
  assert.ok(!ids.includes('no-success-site'), `the folded success site must be visible; got ${ids}`);
  assert.deepEqual(v.failures, [], `expected a clean verdict, got ${JSON.stringify(v.failures)}`);
});
