#!/usr/bin/env python3
"""
Synthetic Clinical Data Generator (Tribal Health)

Generates ENTIRELY SYNTHETIC clinical data aligned with IHS/tribal
health analytics patterns. NO real patient data is used or referenced.
All generated data is FHIR-aligned in structure and uses published
IHS disease prevalence rates for realistic distributions.

Outputs CSV files aligned with tribal-health bronze dbt models:
  - patient_demographics.csv  (brz_patient_demographics)
  - encounters.csv            (brz_encounters)
  - facilities.csv            (brz_facilities)

Usage:
    python generate_synthetic_clinical.py --patients 500 --encounters 2000
    python generate_synthetic_clinical.py --dataset patients --count 1000
    python generate_synthetic_clinical.py --dataset encounters --count 5000 --start-date 2023-01-01
    python generate_synthetic_clinical.py --dataset facilities
    python generate_synthetic_clinical.py --dataset all --output-dir ./data --seed 42
    python generate_synthetic_clinical.py --help

IMPORTANT: ALL data generated by this tool is ENTIRELY SYNTHETIC.
No real Protected Health Information (PHI) is generated, stored, or used.
This tool is designed for development, testing, and demonstration purposes only.
"""

import argparse
import csv
import json
import logging
import random
import sys
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Reference data (synthetic / publicly available categories)
# ---------------------------------------------------------------------------

# Tribal affiliations (public knowledge, not PHI)
TRIBAL_AFFILIATIONS = [
    "Navajo Nation", "Cherokee Nation", "Oglala Sioux Tribe",
    "Choctaw Nation", "Muscogee (Creek) Nation", "Rosebud Sioux Tribe",
    "Standing Rock Sioux Tribe", "Blackfeet Nation", "Crow Tribe",
    "Northern Cheyenne Tribe", "Fort Peck Tribes", "Tohono O'odham Nation",
    "Gila River Indian Community", "White Mountain Apache Tribe",
    "San Carlos Apache Tribe", "Pueblo of Zuni", "Hopi Tribe",
    "Confederated Salish and Kootenai Tribes", "Nez Perce Tribe",
    "Yakama Nation",
]

# IHS Service Units (public info from IHS organizational structure)
SERVICE_UNITS = [
    "Chinle", "Crownpoint", "Gallup", "Kayenta", "Shiprock",
    "Tuba City", "Window Rock", "Fort Defiance", "Pine Ridge",
    "Rosebud", "Eagle Butte", "Rapid City", "Billings",
    "Browning", "Hardin", "Fort Belknap", "Whiteriver",
    "San Carlos", "Sells", "Sacaton",
]

# ICD-10 codes and descriptions (publicly available coding standard)
ICD10_CODES = {
    # Diabetes (high prevalence in AI/AN populations per published IHS data)
    "E11.9": ("Type 2 diabetes mellitus without complications", 0.12),
    "E11.65": ("Type 2 diabetes mellitus with hyperglycemia", 0.06),
    "E11.40": ("Type 2 diabetes with diabetic neuropathy", 0.04),
    "E11.22": ("Type 2 diabetes with diabetic kidney disease", 0.03),
    "E11.319": ("Type 2 diabetes with diabetic retinopathy", 0.02),
    # Cardiovascular
    "I10": ("Essential hypertension", 0.10),
    "I25.10": ("Atherosclerotic heart disease", 0.03),
    "I50.9": ("Heart failure, unspecified", 0.02),
    # Mental health
    "F32.9": ("Major depressive disorder, single episode", 0.06),
    "F41.1": ("Generalized anxiety disorder", 0.05),
    "F10.20": ("Alcohol use disorder, moderate", 0.04),
    "F17.210": ("Nicotine dependence, cigarettes", 0.03),
    # Respiratory
    "J06.9": ("Acute upper respiratory infection", 0.04),
    "J44.1": ("COPD with acute exacerbation", 0.02),
    "J45.20": ("Mild intermittent asthma", 0.03),
    # Musculoskeletal
    "M54.5": ("Low back pain", 0.04),
    "M17.11": ("Primary osteoarthritis, right knee", 0.03),
    # Obesity
    "E66.01": ("Morbid obesity due to excess calories", 0.05),
    # Injury
    "S62.309A": ("Unspecified fracture of wrist", 0.02),
    "S06.0X0A": ("Concussion without loss of consciousness", 0.01),
    # Dental
    "K02.9": ("Dental caries, unspecified", 0.04),
    "K05.10": ("Chronic gingivitis, plaque induced", 0.03),
    # Prenatal / women's health
    "Z34.90": ("Encounter for supervision of normal pregnancy", 0.02),
    "O24.410": ("Gestational diabetes mellitus in pregnancy", 0.01),
}

ENCOUNTER_TYPES = [
    ("Office Visit", 0.40),
    ("Emergency", 0.10),
    ("Inpatient", 0.05),
    ("Urgent Care", 0.08),
    ("Telehealth", 0.12),
    ("Behavioral Health", 0.08),
    ("Dental", 0.10),
    ("Pharmacy", 0.05),
    ("Community Health", 0.02),
]

PROVIDER_TYPES = [
    "Physician", "Nurse Practitioner", "Physician Assistant",
    "Dentist", "Psychologist", "Social Worker", "Pharmacist",
    "Community Health Representative", "Public Health Nurse",
    "Traditional Healer",
]

DISPOSITIONS = [
    ("Discharged", 0.70),
    ("Follow-up Scheduled", 0.15),
    ("Referred to Specialist", 0.06),
    ("Admitted", 0.04),
    ("Against Medical Advice", 0.02),
    ("Transferred", 0.02),
    ("Observation", 0.01),
]

FACILITY_TYPES = [
    "IHS Hospital", "IHS Health Center", "Tribal Hospital",
    "Tribal Health Center", "Urban Indian Health Center",
    "Contract Health Service", "Community Health Station",
]

SERVICES_OFFERED = [
    "Primary Care", "Emergency", "Dental", "Behavioral Health",
    "Pharmacy", "Laboratory", "Radiology", "Obstetrics",
    "Pediatrics", "Optometry", "Physical Therapy",
    "Community Health", "Diabetes Prevention", "Substance Abuse Treatment",
    "Traditional Medicine", "Public Health Nursing", "Nutrition",
    "WIC", "Immunizations",
]

AGE_GROUPS = [
    ("0-4", 0.07), ("5-14", 0.12), ("15-24", 0.14),
    ("25-34", 0.16), ("35-44", 0.14), ("45-54", 0.13),
    ("55-64", 0.11), ("65-74", 0.08), ("75+", 0.05),
]

ELIGIBILITY_STATUSES = [
    ("Active", 0.80), ("Pending", 0.05), ("Inactive", 0.10), ("Referred", 0.05),
]


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------
class SyntheticClinicalGenerator:
    """Generate synthetic clinical data for tribal health analytics."""

    def __init__(self, seed: int = 42):
        """Initialize with reproducible random seed.

        Args:
            seed: Random seed for reproducibility.
        """
        self.rng = random.Random(seed)
        self._patient_cache: dict[str, dict[str, Any]] = {}

    def _weighted_choice(self, options: list[tuple[str, float]]) -> str:
        """Select from weighted options."""
        items = [o[0] for o in options]
        weights = [o[1] for o in options]
        return self.rng.choices(items, weights=weights, k=1)[0]

    def _random_date(self, start: datetime, end: datetime) -> datetime:
        """Generate random datetime between start and end."""
        delta = end - start
        random_days = self.rng.randint(0, max(delta.days, 1))
        return start + timedelta(days=random_days)

    def _generate_zip(self) -> str:
        """Generate a synthetic 5-digit ZIP code in IHS service areas."""
        prefixes = ["860", "863", "865", "870", "873", "875", "590", "592",
                     "577", "573", "570", "793", "794", "980", "985", "993"]
        prefix = self.rng.choice(prefixes)
        suffix = f"{self.rng.randint(0, 99):02d}"
        return prefix + suffix

    # ===================================================================
    # Patient Demographics
    # ===================================================================
    def generate_patients(self, count: int = 150) -> list[dict[str, Any]]:
        """Generate synthetic patient demographic records.

        Args:
            count: Number of patient records.

        Returns:
            List of dicts matching brz_patient_demographics columns.
        """
        records: list[dict[str, Any]] = []
        enrollment_start = datetime(2018, 1, 1)
        enrollment_end = datetime(2024, 12, 31)

        for _ in range(count):
            patient_id = f"SYN-{self.rng.randint(100000, 999999)}"
            tribal = self.rng.choice(TRIBAL_AFFILIATIONS)
            service_unit = self.rng.choice(SERVICE_UNITS)
            age_group = self._weighted_choice(AGE_GROUPS)
            gender = self.rng.choice(["M", "F"])
            zip_code = self._generate_zip()
            enrollment_date = self._random_date(enrollment_start, enrollment_end).strftime("%Y-%m-%d")
            eligibility = self._weighted_choice(ELIGIBILITY_STATUSES)

            record = {
                "patient_id": patient_id,
                "tribal_affiliation": tribal,
                "service_unit": service_unit,
                "age_group": age_group,
                "gender": gender,
                "zip_code": zip_code,
                "enrollment_date": enrollment_date,
                "eligibility_status": eligibility,
            }

            records.append(record)
            self._patient_cache[patient_id] = record

        logger.info("Generated %d synthetic patient records", len(records))
        return records

    # ===================================================================
    # Encounters
    # ===================================================================
    def generate_encounters(
        self,
        count: int = 200,
        start_date: str = "2023-01-01",
        end_date: str = "2024-12-31",
    ) -> list[dict[str, Any]]:
        """Generate synthetic clinical encounter records.

        Args:
            count: Number of encounter records.
            start_date: Start date YYYY-MM-DD.
            end_date: End date YYYY-MM-DD.

        Returns:
            List of dicts matching brz_encounters columns.
        """
        records: list[dict[str, Any]] = []
        start_dt = datetime.strptime(start_date, "%Y-%m-%d")
        end_dt = datetime.strptime(end_date, "%Y-%m-%d")

        if not self._patient_cache:
            self.generate_patients(150)

        patient_ids = list(self._patient_cache.keys())
        facility_ids = [f"FAC-{self.rng.randint(1000, 9999)}" for _ in range(25)]

        icd10_items = list(ICD10_CODES.items())
        icd10_codes_only = [code for code, _ in icd10_items]
        icd10_weights = [info[1] for _, info in icd10_items]

        for _ in range(count):
            encounter_id = f"ENC-{self.rng.randint(1000000, 9999999)}"
            patient_id = self.rng.choice(patient_ids)
            facility_id = self.rng.choice(facility_ids)
            encounter_date = self._random_date(start_dt, end_dt).strftime("%Y-%m-%d")
            encounter_type = self._weighted_choice(ENCOUNTER_TYPES)

            primary_dx = self.rng.choices(icd10_codes_only, weights=icd10_weights, k=1)[0]

            num_secondary = self.rng.choices([0, 1, 2, 3], weights=[0.4, 0.3, 0.2, 0.1], k=1)[0]
            secondary_codes = []
            if num_secondary > 0:
                secondary_codes = self.rng.choices(icd10_codes_only, weights=icd10_weights, k=num_secondary)
                secondary_codes = [c for c in secondary_codes if c != primary_dx]

            provider_type = self.rng.choice(PROVIDER_TYPES)
            disposition = self._weighted_choice(DISPOSITIONS)

            records.append({
                "encounter_id": encounter_id,
                "patient_id": patient_id,
                "facility_id": facility_id,
                "encounter_date": encounter_date,
                "encounter_type": encounter_type,
                "primary_dx_icd10": primary_dx,
                "secondary_dx_codes": "|".join(secondary_codes) if secondary_codes else "",
                "provider_type": provider_type,
                "disposition": disposition,
            })

        logger.info("Generated %d synthetic encounter records", len(records))
        return records

    # ===================================================================
    # Facilities
    # ===================================================================
    def generate_facilities(self, count: int = 25) -> list[dict[str, Any]]:
        """Generate synthetic IHS/tribal facility records.

        Args:
            count: Number of facility records.

        Returns:
            List of dicts matching brz_facilities columns.
        """
        records: list[dict[str, Any]] = []
        states = ["AZ", "NM", "SD", "MT", "OK", "WA", "ND", "MN", "WI", "AK"]

        used_names = set()
        for i in range(count):
            facility_id = f"FAC-{1000 + i}"
            facility_type = self.rng.choice(FACILITY_TYPES)
            service_unit = self.rng.choice(SERVICE_UNITS)
            tribal = self.rng.choice(TRIBAL_AFFILIATIONS)
            state = self.rng.choice(states)

            base_name = f"{service_unit} {facility_type}"
            if base_name in used_names:
                base_name = f"{tribal.split()[0]} {facility_type}"
            used_names.add(base_name)

            if "Hospital" in facility_type:
                bed_count = self.rng.randint(20, 150)
                provider_count = self.rng.randint(15, 80)
            elif "Health Center" in facility_type:
                bed_count = self.rng.randint(0, 20)
                provider_count = self.rng.randint(5, 30)
            else:
                bed_count = 0
                provider_count = self.rng.randint(2, 10)

            num_services = self.rng.randint(3, min(10, len(SERVICES_OFFERED)))
            services = self.rng.sample(SERVICES_OFFERED, num_services)

            records.append({
                "facility_id": facility_id,
                "facility_name": base_name,
                "facility_type": facility_type,
                "service_unit": service_unit,
                "tribal_affiliation": tribal,
                "state": state,
                "bed_count": bed_count,
                "provider_count": provider_count,
                "services_offered": "|".join(services),
            })

        logger.info("Generated %d synthetic facility records", len(records))
        return records

    # ===================================================================
    # Output
    # ===================================================================
    def write_csv(self, records: list[dict[str, Any]], output_path: str) -> str:
        """Write records to CSV."""
        if not records:
            logger.warning("No records to write for %s", output_path)
            return output_path

        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)

        fieldnames = list(records[0].keys())
        with open(path, "w", newline="", encoding="utf-8") as fh:
            writer = csv.DictWriter(fh, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(records)

        logger.info("Wrote %d records to %s", len(records), path)
        return str(path.resolve())

    def write_json(self, records: list[dict[str, Any]], output_path: str) -> str:
        """Write records to JSON (FHIR-like structure)."""
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)

        fhir_bundle = {
            "resourceType": "Bundle",
            "type": "collection",
            "meta": {
                "generated": datetime.utcnow().isoformat(),
                "generator": "csa-inabox/synthetic-clinical",
                "synthetic": True,
                "disclaimer": "ALL DATA IS ENTIRELY SYNTHETIC. No real PHI.",
            },
            "entry": [{"resource": r} for r in records],
            "total": len(records),
        }

        with open(path, "w", encoding="utf-8") as fh:
            json.dump(fhir_bundle, fh, indent=2, default=str)

        logger.info("Wrote %d records (FHIR bundle) to %s", len(records), path)
        return str(path.resolve())


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description=(
            "Generate synthetic clinical data for tribal health analytics.\n\n"
            "IMPORTANT: ALL generated data is ENTIRELY SYNTHETIC.\n"
            "No real PHI is created, stored, or referenced."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Generate all datasets
  python generate_synthetic_clinical.py --dataset all --output-dir ./data

  # Generate 500 patients with seed for reproducibility
  python generate_synthetic_clinical.py --dataset patients --count 500 --seed 42

  # Generate 2000 encounters
  python generate_synthetic_clinical.py --dataset encounters --count 2000 \\
      --start-date 2023-01-01 --end-date 2024-06-30

  # Generate facilities
  python generate_synthetic_clinical.py --dataset facilities --count 30

DISCLAIMER: This tool generates ENTIRELY SYNTHETIC data for development
and testing purposes. No real patient data is used or referenced.
        """,
    )

    parser.add_argument(
        "--dataset",
        choices=["patients", "encounters", "facilities", "all"],
        default="all",
        help="Which dataset to generate (default: all)",
    )
    parser.add_argument(
        "--count",
        type=int,
        default=None,
        help="Number of records (default: 150 patients, 200 encounters, 25 facilities)",
    )
    parser.add_argument(
        "--patients",
        type=int,
        default=150,
        help="Number of patient records when --dataset=all (default: 150)",
    )
    parser.add_argument(
        "--encounters",
        type=int,
        default=200,
        help="Number of encounter records when --dataset=all (default: 200)",
    )
    parser.add_argument(
        "--facilities-count",
        type=int,
        default=25,
        help="Number of facility records when --dataset=all (default: 25)",
    )
    parser.add_argument(
        "--start-date",
        default="2023-01-01",
        help="Encounter start date YYYY-MM-DD (default: 2023-01-01)",
    )
    parser.add_argument(
        "--end-date",
        default="2024-12-31",
        help="Encounter end date YYYY-MM-DD (default: 2024-12-31)",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for reproducibility (default: 42)",
    )
    parser.add_argument(
        "--output-dir",
        default="./output",
        help="Output directory",
    )
    parser.add_argument(
        "--output-format",
        choices=["csv", "json", "both"],
        default="csv",
        help="Output format (default: csv)",
    )
    parser.add_argument(
        "--log-level",
        choices=["DEBUG", "INFO", "WARNING", "ERROR"],
        default="INFO",
    )

    return parser.parse_args()


def main() -> int:
    """Entry point."""
    args = parse_args()
    logging.getLogger().setLevel(getattr(logging, args.log_level))

    logger.info("=" * 60)
    logger.info("SYNTHETIC CLINICAL DATA GENERATOR")
    logger.info("ALL DATA IS ENTIRELY SYNTHETIC - NO REAL PHI")
    logger.info("=" * 60)

    generator = SyntheticClinicalGenerator(seed=args.seed)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    results: dict[str, int] = {}

    # ---- Patients ----
    if args.dataset in ("patients", "all"):
        count = args.count if args.count and args.dataset == "patients" else args.patients
        logger.info("=== Generating Synthetic Patient Demographics ===")
        patients = generator.generate_patients(count=count)
        if args.output_format in ("csv", "both"):
            generator.write_csv(patients, str(output_dir / "patient_demographics.csv"))
        if args.output_format in ("json", "both"):
            generator.write_json(patients, str(output_dir / "patient_demographics.json"))
        results["patients"] = len(patients)

    # ---- Encounters ----
    if args.dataset in ("encounters", "all"):
        count = args.count if args.count and args.dataset == "encounters" else args.encounters
        logger.info("=== Generating Synthetic Encounters ===")
        encounters = generator.generate_encounters(
            count=count,
            start_date=args.start_date,
            end_date=args.end_date,
        )
        if args.output_format in ("csv", "both"):
            generator.write_csv(encounters, str(output_dir / "encounters.csv"))
        if args.output_format in ("json", "both"):
            generator.write_json(encounters, str(output_dir / "encounters.json"))
        results["encounters"] = len(encounters)

    # ---- Facilities ----
    if args.dataset in ("facilities", "all"):
        count = args.count if args.count and args.dataset == "facilities" else args.facilities_count
        logger.info("=== Generating Synthetic Facilities ===")
        facilities = generator.generate_facilities(count=count)
        if args.output_format in ("csv", "both"):
            generator.write_csv(facilities, str(output_dir / "facilities.csv"))
        if args.output_format in ("json", "both"):
            generator.write_json(facilities, str(output_dir / "facilities.json"))
        results["facilities"] = len(facilities)

    # ---- Summary ----
    logger.info("=" * 60)
    logger.info("Generation Summary (ALL DATA IS SYNTHETIC):")
    for dataset_name, count in results.items():
        logger.info("  %-14s  %d records", dataset_name, count)
    logger.info("Output directory: %s", output_dir.resolve())
    logger.info("Seed: %d", args.seed)
    logger.info("=" * 60)

    return 0


if __name__ == "__main__":
    sys.exit(main())
