#!/usr/bin/env bash
# open-auto-fix-pr.sh — open a PR for the branch the Claude Code action pushed.
# ---------------------------------------------------------------------------
# Invoked by .github/workflows/copilot-auto-fix.yml. Extracted from that
# workflow's `run:` block per #3034: the multi-line PR body passed to
# `gh pr create --body "..."` had continuation lines at column 0, which
# terminated the YAML block scalar and made the whole workflow file invalid
# YAML — GitHub created runs with jobs=0 and the auto-fix pipeline never
# executed once. Multi-line strings belong in a script file, not escaped
# into a workflow.
#
# Required env (the workflow provides these):
#   GH_TOKEN       token for gh
#   ISSUE_NUMBER   the triggering issue number
#   ISSUE_TITLE    the SANITIZED issue title (never the raw one)
set -euo pipefail

: "${GH_TOKEN:?GH_TOKEN must be set by the caller}"
: "${ISSUE_NUMBER:?ISSUE_NUMBER must be set by the caller}"
: "${ISSUE_TITLE:?ISSUE_TITLE must be set by the caller}"

# Find the most recent claude/issue-<N>-* branch on origin.
BRANCH=$(git ls-remote --heads origin "claude/issue-${ISSUE_NUMBER}-*" \
  | awk '{print $2}' \
  | sed 's|refs/heads/||' \
  | sort -r \
  | head -1)
if [ -z "$BRANCH" ]; then
  echo "::warning::No claude/issue-${ISSUE_NUMBER}-* branch found — Claude probably commented without making changes."
  exit 0
fi
# Skip if a PR already exists for this branch
if gh pr list --head "$BRANCH" --state open --json number -q '.[0].number' | grep -q .; then
  echo "PR already open for $BRANCH"
  exit 0
fi
# Title prefix matches the auto-merge workflow's ``(auto-fix #N)`` regex.
PR_TITLE="fix: ${ISSUE_TITLE} (auto-fix #${ISSUE_NUMBER})"
# Truncate to 240 chars total — title length cap.
if [ ${#PR_TITLE} -gt 240 ]; then PR_TITLE="${PR_TITLE:0:237}..."; fi

PR_BODY="Auto-fix produced by the Copilot Auto-fix workflow on issue #${ISSUE_NUMBER}.

Branch \`$BRANCH\` was opened by the Claude Code action. The auto-merge workflow will evaluate denylist + safelist + diff content scan; if all checks pass and the diff is contained in safelisted paths, GitHub auto-merge will be enabled.

Closes #${ISSUE_NUMBER}

🤖 Auto-generated by Claude Code GitHub Action"

gh pr create \
  --base main --head "$BRANCH" \
  --title "$PR_TITLE" \
  --body "$PR_BODY"
