// CSA Loom — Azure Commercial parameters
// Per AMENDMENTS A4 + per-boundary dispatch matrix (architecture.md §4.3)
//
// Status: PARAMETER SCAFFOLDED — values aligned with PRD §7.3.1

using '../main.bicep'

// ---------- Bring-your-own existing services (reuse instead of provision-new) ----------
// Generate with: bash scripts/csa-loom/byo-wizard.sh --boundary commercial
// >>> BYO-WIZARD START (regenerated by scripts/csa-loom/byo-wizard.sh — edit env vars or re-run the wizard)
// ---------- ADOPT-OR-CREATE plan (replaces the per-service EXISTING_* params) ----------
// main.bicep no longer declares 36 `existing*` scalars; it declares ONE `adopt`
// object keyed by the service key in apps/fiab-console/lib/deploy/adoption-catalog.ts.
// That is what freed the ARM parameter budget (251 -> 216 of 256) so networking,
// storage, Log Analytics and ACR adoption become possible at all.
//
// TWO input paths, and the explicit plan always wins:
//
//   1. LOOM_ADOPT_JSON - the whole plan as one JSON document, emitted by
//      `planToArmParameters()` (apps/fiab-console/lib/deploy/plan-to-arm.ts).
//      This is the first-class path every deploy tier uses.
//   2. The legacy per-service EXISTING_* environment variables below, kept
//      working verbatim so byo-wizard.sh / scan-and-deploy.sh / a hand-exported
//      shell keep behaving exactly as before.
//
// `union(legacy, plan)` means a service present in BOTH resolves to the plan's
// decision. A service in NEITHER is absent from the object, and main.bicep's
// `adoptMode()` defaults an absent key to 'create' - so an empty environment
// still produces a complete greenfield deployment.
//
// NOTE: setting an EXISTING_* name now also SUPPRESSES the matching new resource
// (main.bicep's provision<Service> vars). Previously several services - Purview,
// Maps, Foundry, Synapse, Databricks, ADF - rebound the Console env to the
// existing resource while STILL deploying a duplicate beside it.
var legacyAdoptFromEnv = union(
  empty(readEnvironmentVariable('EXISTING_AI_SEARCH_SERVICE', '')) ? {} : { aisearch: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_AI_SEARCH_SERVICE', ''), rg: readEnvironmentVariable('EXISTING_AI_SEARCH_RG', ''), sub: readEnvironmentVariable('EXISTING_AI_SEARCH_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_APIM', '')) ? {} : { apim: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_APIM', ''), rg: readEnvironmentVariable('EXISTING_APIM_RG', ''), sub: readEnvironmentVariable('EXISTING_APIM_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_KUSTO_CLUSTER', '')) ? {} : { adx: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_KUSTO_CLUSTER', ''), rg: readEnvironmentVariable('EXISTING_KUSTO_RG', ''), sub: readEnvironmentVariable('EXISTING_KUSTO_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_AOAI', '')) ? {} : { foundry: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_AOAI', ''), rg: readEnvironmentVariable('EXISTING_AOAI_RG', ''), sub: readEnvironmentVariable('EXISTING_AOAI_SUB', '') }, extra: { chatDeployment: readEnvironmentVariable('EXISTING_AOAI_CHAT_DEPLOYMENT', ''), embedDeployment: readEnvironmentVariable('EXISTING_AOAI_EMBED_DEPLOYMENT', ''), miniDeployment: readEnvironmentVariable('EXISTING_AOAI_MINI_DEPLOYMENT', ''), strongDeployment: readEnvironmentVariable('EXISTING_AOAI_STRONG_DEPLOYMENT', '') } } },
  empty(readEnvironmentVariable('EXISTING_PURVIEW', '')) ? {} : { purview: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_PURVIEW', ''), rg: readEnvironmentVariable('EXISTING_PURVIEW_RG', ''), sub: readEnvironmentVariable('EXISTING_PURVIEW_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_SYNAPSE', '')) ? {} : { synapse: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_SYNAPSE', ''), rg: readEnvironmentVariable('EXISTING_SYNAPSE_RG', ''), sub: readEnvironmentVariable('EXISTING_SYNAPSE_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT', '')) ? {} : { cosmos: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT', ''), rg: readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT_RG', ''), sub: readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_EVENTHUB_NAMESPACE', '')) ? {} : { eventhubs: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_EVENTHUB_NAMESPACE', ''), rg: readEnvironmentVariable('EXISTING_EVENTHUB_RG', ''), sub: readEnvironmentVariable('EXISTING_EVENTHUB_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_ASA_JOB', '')) ? {} : { streamanalytics: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_ASA_JOB', ''), rg: readEnvironmentVariable('EXISTING_ASA_RG', ''), sub: readEnvironmentVariable('EXISTING_ASA_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_DATABRICKS', '')) ? {} : { databricks: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_DATABRICKS', ''), rg: readEnvironmentVariable('EXISTING_DATABRICKS_RG', ''), sub: readEnvironmentVariable('EXISTING_DATABRICKS_SUB', '') }, extra: { hostname: readEnvironmentVariable('EXISTING_DATABRICKS_HOSTNAME', '') } } },
  empty(readEnvironmentVariable('EXISTING_ADF', '')) ? {} : { adf: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_ADF', ''), rg: readEnvironmentVariable('EXISTING_ADF_RG', ''), sub: readEnvironmentVariable('EXISTING_ADF_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_AZURE_MAPS_ACCOUNT', '')) ? {} : { maps: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_AZURE_MAPS_ACCOUNT', ''), rg: readEnvironmentVariable('EXISTING_AZURE_MAPS_RG', ''), sub: readEnvironmentVariable('EXISTING_AZURE_MAPS_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_AML_WORKSPACE', '')) ? {} : { aml: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_AML_WORKSPACE', ''), rg: readEnvironmentVariable('EXISTING_AML_RG', ''), sub: readEnvironmentVariable('EXISTING_AML_SUB', '') } } }
)
param adopt = union(legacyAdoptFromEnv, json(readEnvironmentVariable('LOOM_ADOPT_JSON', '{}')))
param fabricEnabled              = (toLower(readEnvironmentVariable('FABRIC_ENABLED', 'false')) == 'true')
// <<< BYO-WIZARD END

param environment = 'AzureCloud'
param location = 'eastus2'
param boundary = 'Commercial'
param deploymentMode = 'single-sub'   // or 'multi-sub'
// audit-t157: tenant = first-run install (deploys the hub + DLZ). Add-landing-zone uses dlz-attach via the orchestrator, never this param file.
param topology = 'tenant'

// Compute
param containerPlatform = 'containerApps'
// Setup Orchestrator — on by default (Container Apps boundary). The Console UAMI
// gets Contributor on the target sub so the Setup Wizard's Deploy runs the real
// subscription-scoped ARM deployment. LOOM_SETUP_TEMPLATE_URI = published main.json.
param setupOrchestratorEnabled = bool(readEnvironmentVariable('LOOM_SETUP_ORCHESTRATOR_ENABLED', 'true'))
param setupTemplateUri = readEnvironmentVariable('LOOM_SETUP_TEMPLATE_URI', '')
param functionsHostSku = 'FlexConsumption'
param apimSku = 'PremiumV2'

// Catalog
param catalogPrimary = 'unity-catalog-managed'

// AI orchestration
param agentOrchestrator = 'foundry-agent-service'
param foundryPortalEnabled = true

// Capacity sizing
param capacitySku = 'F8'

// Databricks feature flags
param databricksUnityCatalogEnabled = true
param databricksSqlWarehouseEnabled = true
// Set to your Databricks ACCOUNT id (GUID) to configure Unity Catalog by default
// (regional metastore + default catalog + Console-UAMI account_admin), so Browse >
// Unity Catalog shows a real configured catalog. Requires a one-time step making
// The Console UAMI a Databricks account admin — docs/fiab/catalog/metastores.md.
// Sourced from the LOOM_DATABRICKS_ACCOUNT_ID env var so a stock `azd up` with it
// set configures UC with no param-file edit. Unset = UC enabled later via the
// post-deploy bootstrap workflow (never a hard deploy blocker).
param databricksAccountId = readEnvironmentVariable('LOOM_DATABRICKS_ACCOUNT_ID', '')

// Security
param defenderForAIEnabled = true
// Azure AI Content Safety — copilot persona moderation (Prompt Shields + harm
// analyze). Available in Commercial; wires LOOM_CONTENT_SAFETY_ENDPOINT.
param contentSafetyEnabled = true
// Purview defaults OFF — many Microsoft tenants already have an
// Enterprise-tier tenant-level Purview account (only one allowed per
// tenant). Operator opts in once they've decided whether to reuse the
// existing account (preferred) or scope a new one.
param purviewEnabled = true
// /admin/security Purview tab — point at an EXISTING Purview account
// to enable inline source/scan/glossary/domain management. Leave empty
// to gate the tab behind a structured NotConfigured MessageBar (the
// no-vaporware-compliant fallback). Pull the short account name from
// `az purview account list`.
param loomPurviewAccount = readEnvironmentVariable('LOOM_PURVIEW_ACCOUNT', '')
// #229 cross-region Purview safety valve (empty = hub location).
param purviewLocation = readEnvironmentVariable('LOOM_PURVIEW_LOCATION', '')
// Azure Maps — leave EXISTING_AZURE_MAPS_ACCOUNT unset to DEPLOY a fresh Gen2
// account (azure-maps.bicep, default for Commercial/GCC). Set it to bring your
// own existing account; the module is skipped and the env binds to your name.
param loomAzureMapsAccount = readEnvironmentVariable('EXISTING_AZURE_MAPS_ACCOUNT', '')
// /admin/security Information Protection + DLP tabs — both default OFF
// until the post-deploy bootstrap workflow grants the Graph AppRoles
// AND a Tenant Administrator clicks Grant admin consent. After that,
// flip these to true and redeploy admin-plane.
param loomMipEnabled = false
// DLP defaults ON: the post-deploy bootstrap grants the DLP AppRoles by
// default, so the /admin/security DLP tab is wired out of the box (alerts +
// violations + Azure-native restrict-access). The policy segment + simulate
// honest-gate where the Graph DLP preview isn't enabled.
param loomDlpEnabled = true
// DLP policy CRUD via the SCC PowerShell sidecar. Opt-in (off by default) — the
// SCC app + auth cert must be provisioned in post-deploy bootstrap first. DLP
// reads/alerts/violations + Azure-native Restrict-access work without it.
param loomDlpAdminEnabled = false
param loomIdentityPickerEnabled = false
param loomDomainGroupProvisioningEnabled = false
param storageRequireCmk = false
param keyVaultHsmIsolated = false

// OpenAI
param openaiLocation = 'eastus2'
param openaiEmbeddingsLocation = 'eastus2'
param openaiChatModel = 'gpt-4o'
// Deploy-readiness (opt-out): provision the dedicated AOAI account (aifndry-loom-<location>)
// + gpt-4o chat + embedding deployments so Copilot / data-agents / AI-functions
// work on first login. Set false to skip (those surfaces then honest-gate).
param agentFoundryEnabled = true
param openaiEmbeddingsModel = 'text-embedding-3-large'

// Power BI
param powerBiSku = 'F64'

// Role-assignment drift guard — set LOOM_SKIP_ROLE_GRANTS=true when
// re-provisioning an environment that already has the RBAC grants, so
// ARM doesn't fail with RoleAssignmentExists. Defaults false for fresh
// deploys.
param skipRoleGrants = readEnvironmentVariable('LOOM_SKIP_ROLE_GRANTS', 'false') == 'true'

// Network
param hubVnetCidr = '10.0.0.0/16'

// Identity. Empty (not a placeholder GUID) so a blank is DETECTABLE as blank:
// when no admin group / oid is supplied, admin-plane falls back to the deploying
// principal (deployer().objectId) as the bootstrap admin so the push-button path
// is never locked out of /admin/* (GH #1383). Set LOOM_ADMIN_ENTRA_GROUP_ID to
// your FiaB Admins security-group OID for a production multi-admin bootstrap.
param adminEntraGroupId = readEnvironmentVariable('LOOM_ADMIN_ENTRA_GROUP_ID', '')

// Feature-Permissions bootstrap admin — who can open /admin/* (Feature
// Permissions, Domains, Security, …) BEFORE any grants exist. Without one of
// these set, even the deployer gets "Access denied (403)" on /admin/permissions.
// Set your admin SECURITY-GROUP OID (recommended) and/or a single user OID;
// members bypass the feature gate with full Admin.
//   az ad signed-in-user show --query id -o tsv          # your user OID
//   az ad group show --group "<name>" --query id -o tsv  # admin group OID
//
// #3090 — this used to read `readEnvironmentVariable('LOOM_TENANT_ADMIN_GROUP_ID',
// adminEntraGroupId)` and the comment above it claimed "the group defaults to
// the FiaB Admins group above, so setting that one GUID covers both". That was
// FALSE for every CI deploy. `adminEntraGroupId` here resolves to THIS FILE's
// own expression at bicep COMPILE time — readEnvironmentVariable(
// 'LOOM_ADMIN_ENTRA_GROUP_ID','') — and NOT to the
// `--parameters adminEntraGroupId=…` override the deploy workflows pass. So the
// compiled paramfile emitted loomTenantAdminGroupId='' as an EXPLICIT value,
// the console shipped with both bootstrap bindings empty, and /admin/* was shut
// for every user. Reading the environment variable directly makes the two
// sources agree; deploy-fiab-commercial.yml ALSO passes the parameter
// explicitly so the binding never depends on runner environment alone.
param loomTenantAdminGroupId = readEnvironmentVariable('LOOM_TENANT_ADMIN_GROUP_ID', readEnvironmentVariable('LOOM_ADMIN_ENTRA_GROUP_ID', ''))
param loomTenantAdminOid = readEnvironmentVariable('LOOM_TENANT_ADMIN_OID', '')

// Day-1 service posture (deploy-readiness: everything ON by default / opt-out).
// APIM backs the API Marketplace; the hub Azure Firewall hardens egress. Both
// default true in main.bicep now — set explicitly here so the posture is visible
// in the param file (bicep+bootstrap sync). Flip to false to opt out.
param apimEnabled = true
param hubFirewallEnabled = true

// Front Door: ON, and the ONLY capability flag this file was silently getting
// wrong (measured 2026-08-10).
//
// main.bicep declares `param frontDoorEnabled bool = false`, and this file did
// not set it — while commercial-full.bicepparam sets it `true` and the LIVE
// Commercial estate has an Active Front Door profile serving a vanity endpoint.
// So the estate was BUILT with Front Door and every routine deploy through
// deploy-fiab-commercial.yml (which uses THIS file, not -full) then ran as if it
// did not exist. It is an omission, not a decision: the flag appears nowhere in
// this file, in docs/, or in .claude/, and default-ON/opt-out is a standing rule.
//
// What `fdOn` gates in admin-plane/main.bicep, all of which took the fallback:
//   - SIX ACA jobs get `loomUrl: fdOn ? frontDoorPublicUrl : 'http://loom-console'`.
//     That is not cosmetic. It is the root cause of the J3 synthetic-journey
//     outage: e2e/_lib/uat.ts minted a `Secure` session cookie, a Secure cookie
//     is never sent over http, so the UAT browser context was unauthenticated and
//     every client call 401'd (fixed defensively in #3181 — this fixes the cause).
//   - `effectiveMsalConsoleHosts` (line ~2553) drops the Front Door hostname from
//     the console-hosts list the MSAL app registration is built from.
//   - `vanityPublicUrl` / `vanityCnameTarget` / `vanityDnsTxtName` outputs go empty.
//   - The Front Door resource is never reconciled by a routine deploy at all.
//
// Verified NOT a wider divergence: of the 16 bool flags commercial-full sets that
// this file omits, 12 already default true in main.bicep, `deployAppsEnabled` is
// passed explicitly by the workflow, `atlasOnAksEnabled` is false in both, and
// `appGatewayEnabled` defaults false and is correct — there is genuinely no
// Application Gateway in the estate. This one flag was the whole gap.
//
// The `What-If (FIAB vs live Commercial estate)` check on this PR is the receipt
// for what turning it on actually changes against the running estate.
param frontDoorEnabled = true

// Multi-sub mode (empty for single-sub)
param dlzSubscriptionIds = []
param dlzDomainNames = []

// Tags
param complianceTags = {
  Environment: 'Commercial'
  CSA_Loom: 'true'
  FedRAMP_Level: 'High'
  Data_Classification: 'Standard'
}

// =====================================================================
// Data-engineering backends — ON by default (opt-out). Set any to false to
// skip that provision; the console editor then honest-gates (LOOM_* env blanked)
// instead of 502-ing. See docs/fiab/prp/deploy-readiness-100pct.md.
// =====================================================================
param loomSynapseEnabled = true
param loomDatabricksEnabled = true
param loomDataFactoryEnabled = true
param loomSelfHostedIrEnabled = true

// =====================================================================
// Container image tags (refs #2775) — THE RECONCILE'S IMAGE-IMMUTABILITY PIN.
//
// This block did not exist, so `appImageTags` fell through to main.bicep's
// default of 'v0.1' for every app while production runs commit-SHA tags. That
// is the single reason the nightly reconcile had to run with
// `deployAppsEnabled=false`: turning it on is the ONLY way any LOOM_* env var
// reaches the running Console (app-deployments.bicep is gated on it), but doing
// so would also have rewritten loom-console to a `v0.1` that does not exist.
// Infra reconciled; configuration never did. That is what "185 of 192
// configured" was measuring — LOOM_RISINGWAVE_URL and
// LOOM_DUCKLAKE_CATALOG_URL are declared in admin-plane/main.bicep and gated on
// `deployAppsEnabled`, so they had never been applied.
//
// `.github/workflows/deploy-fiab-commercial.yml` now reads the tag every
// Container App is ACTUALLY running (read-only `az containerapp list`, via
// scripts/ci/reconcile-resolve.mjs) and exports these env vars, so each
// readEnvironmentVariable below resolves to the tag already deployed and the
// ARM PUT is a no-op for the image. Same mechanism gcc-high.bicepparam and
// commercial-full.bicepparam already use — this file was simply missing it.
//
// EVERY value here MUST stay a readEnvironmentVariable(...). A literal tag is
// applied over whatever is running, which is the outage this block prevents;
// check-reconcile-safety.mjs (I4) fails the build if one appears, and pins each
// env-var name to the one reconcile-resolve.mjs exports.
//
// The 'v0.1' fallbacks match what full-app-deploy-commercial.yml and
// build-fiab-images-acr-tasks.yml push by default, so a FIRST-RUN install (no
// running estate to read tags from) still resolves to real images.
// =====================================================================
param appImageTags = {
  console: readEnvironmentVariable('LOOM_CONSOLE_TAG', 'v0.1')
  mcp: readEnvironmentVariable('LOOM_MCP_TAG', 'v0.1')
  mcpBridge: readEnvironmentVariable('LOOM_MCP_BRIDGE_TAG', 'v0.1')
  orchestrator: readEnvironmentVariable('LOOM_ORCHESTRATOR_TAG', 'v0.1')
  activator: readEnvironmentVariable('LOOM_ACTIVATOR_TAG', 'v0.1')
  mirroring: readEnvironmentVariable('LOOM_MIRRORING_TAG', 'v0.1')
  directLake: readEnvironmentVariable('LOOM_DIRECTLAKE_TAG', 'v0.1')
  maf: readEnvironmentVariable('LOOM_MAF_TAG', 'v0.1')
  setupOrchestrator: readEnvironmentVariable('LOOM_SETUP_ORCHESTRATOR_TAG', 'v0.1')
  scriptRunner: readEnvironmentVariable('LOOM_SCRIPT_RUNNER_TAG', 'v0.1')
  wrangler: readEnvironmentVariable('LOOM_WRANGLER_TAG', 'v0.1')
  // dbtRunner is NOT a duplicate of console. admin-plane/main.bicep used to pass
  // `appImageTags.console` to integration/dbt-runner.bicep, which builds
  // `loom-dbt-runner:${imageTag}` — one key, two repositories, two different
  // running tags. Split in the same PR that added this block.
  dbtRunner: readEnvironmentVariable('LOOM_DBT_RUNNER_TAG', 'v0.1')
  transformRunner: readEnvironmentVariable('LOOM_TRANSFORM_RUNNER_TAG', 'v0.1')
  mapsTiles: readEnvironmentVariable('LOOM_MAPS_TILES_TAG', 'v1')
  duckdb: readEnvironmentVariable('LOOM_DUCKDB_TAG', 'v0.1')
  loomMigrate: readEnvironmentVariable('LOOM_MIGRATE_TAG', 'v0.1')
  risingwave: readEnvironmentVariable('LOOM_RISINGWAVE_TAG', 'v0.1')
  // loom-unity (#2681) — the Unity-Catalog-compatible OSS metastore.
  // admin-plane/main.bicep now deploys it DEFAULT-ON on every boundary (it was
  // an out-of-band standalone entrypoint before), so this image is a hard
  // prerequisite of the apps phase — and declaring it HERE is what puts it in
  // the Commercial lane resolve-image-preflight-refs.mjs assertion set.
  unity: readEnvironmentVariable('LOOM_UNITY_TAG', 'v0.1')
  // loom-trino (#2678) — the N7e Federated SQL engine behind SQL Lab.
  // admin-plane/main.bicep deploys data-plane/loom-trino-aca.bicep DEFAULT-ON
  // and passes `appImageTags.?trino ?? 'v0.1'`, so an apps-enabled deploy PULLS
  // `loom-trino:v0.1` — but this block did not declare the key, so the optional
  // chain silently took the fallback and NOTHING preflighted or signature-
  // verified that image. Exactly the loom-duckdb / loom-unity shape: a new
  // DEFAULT-ON image whose paramfile key was never added, so the guard set
  // could not see it. Declaring it HERE is what puts it in the Commercial lane
  // resolve-image-preflight-refs.mjs assertion set AND in the SC1 verify set
  // derived from that contract (refs #3035). Caught by
  // check-full-app-deploy-contract.mjs when loom-trino joined the build matrix.
  trino: readEnvironmentVariable('LOOM_TRINO_TAG', 'v0.1')
}

// SIGN-IN + LOOM-UNITY-AUDIENCE DURABILITY (#2681). An Entra app registration is
// a Microsoft Graph object ARM cannot create, so this reads the estate's existing
// one out of the environment; deploy-fiab-commercial.yml resolves it (Key Vault
// record → live Console app) into LOOM_MSAL_CLIENT_ID immediately before the
// deploy. Without this line that export is INERT — the param falls back to
// main.bicep's `''` default — and each reconcile both blanks sign-in and
// RE-SEALS the Loom Unity catalog, because admin-plane/main.bicep passes this
// value as the catalog's entraClientId and the module deploys SEALED rather than
// anonymous when no audience can be pinned. Empty is the correct answer on a
// genuinely fresh subscription; csa-loom-post-deploy-bootstrap.yml creates the
// registration and unseals the catalog. Mirrors gcc-high/il5.bicepparam.
param loomMsalClientId = readEnvironmentVariable('LOOM_MSAL_CLIENT_ID', '')
