// CSA Loom — Azure Commercial parameters
// Per AMENDMENTS A4 + per-boundary dispatch matrix (architecture.md §4.3)
//
// Status: PARAMETER SCAFFOLDED — values aligned with PRD §7.3.1

using '../main.bicep'

// ---------- Bring-your-own existing services (reuse instead of provision-new) ----------
// Generate with: bash scripts/csa-loom/byo-wizard.sh --boundary commercial
// >>> BYO-WIZARD START (regenerated by scripts/csa-loom/byo-wizard.sh — edit env vars or re-run the wizard)
param existingAiSearchService    = readEnvironmentVariable('EXISTING_AI_SEARCH_SERVICE', '')
param existingAiSearchRg         = readEnvironmentVariable('EXISTING_AI_SEARCH_RG', '')
param existingAiSearchSub        = readEnvironmentVariable('EXISTING_AI_SEARCH_SUB', '')
param existingApimName           = readEnvironmentVariable('EXISTING_APIM', '')
param existingApimRg             = readEnvironmentVariable('EXISTING_APIM_RG', '')
param existingApimSub            = readEnvironmentVariable('EXISTING_APIM_SUB', '')
param existingAdxClusterName     = readEnvironmentVariable('EXISTING_KUSTO_CLUSTER', '')
param existingAdxClusterRg       = readEnvironmentVariable('EXISTING_KUSTO_RG', '')
param existingAdxClusterSub      = readEnvironmentVariable('EXISTING_KUSTO_SUB', '')
param existingFoundryAccountName = readEnvironmentVariable('EXISTING_AOAI', '')
param existingFoundryRg          = readEnvironmentVariable('EXISTING_AOAI_RG', '')
param existingFoundrySub         = readEnvironmentVariable('EXISTING_AOAI_SUB', '')
param existingPurviewAccount     = readEnvironmentVariable('EXISTING_PURVIEW', '')
param existingPurviewRg          = readEnvironmentVariable('EXISTING_PURVIEW_RG', '')
param existingPurviewSub         = readEnvironmentVariable('EXISTING_PURVIEW_SUB', '')
param existingSynapseWorkspace   = readEnvironmentVariable('EXISTING_SYNAPSE', '')
param existingSynapseRg          = readEnvironmentVariable('EXISTING_SYNAPSE_RG', '')
param existingSynapseSub         = readEnvironmentVariable('EXISTING_SYNAPSE_SUB', '')
param existingCosmosAccount      = readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT', '')
param existingCosmosRg           = readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT_RG', '')
param existingCosmosSub          = readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT_SUB', '')
param existingEventHubNamespace  = readEnvironmentVariable('EXISTING_EVENTHUB_NAMESPACE', '')
param existingEventHubRg         = readEnvironmentVariable('EXISTING_EVENTHUB_RG', '')
param existingEventHubSub        = readEnvironmentVariable('EXISTING_EVENTHUB_SUB', '')
param existingDatabricksWorkspace = readEnvironmentVariable('EXISTING_DATABRICKS', '')
param existingDatabricksRg       = readEnvironmentVariable('EXISTING_DATABRICKS_RG', '')
param existingDatabricksSub      = readEnvironmentVariable('EXISTING_DATABRICKS_SUB', '')
param existingDatabricksHostname = readEnvironmentVariable('EXISTING_DATABRICKS_HOSTNAME', '')
param fabricEnabled              = (toLower(readEnvironmentVariable('FABRIC_ENABLED', 'false')) == 'true')
// <<< BYO-WIZARD END

param environment = 'AzureCloud'
param location = 'eastus2'
param boundary = 'Commercial'
param deploymentMode = 'single-sub'   // or 'multi-sub'
// audit-t157: tenant = first-run install (deploys the hub + DLZ). Add-landing-zone uses dlz-attach via the orchestrator, never this param file.
param topology = 'tenant'

// Compute
param containerPlatform = 'containerApps'
// Setup Orchestrator — on by default (Container Apps boundary). The Console UAMI
// gets Contributor on the target sub so the Setup Wizard's Deploy runs the real
// subscription-scoped ARM deployment. LOOM_SETUP_TEMPLATE_URI = published main.json.
param setupOrchestratorEnabled = bool(readEnvironmentVariable('LOOM_SETUP_ORCHESTRATOR_ENABLED', 'true'))
param setupTemplateUri = readEnvironmentVariable('LOOM_SETUP_TEMPLATE_URI', '')
param functionsHostSku = 'FlexConsumption'
param apimSku = 'PremiumV2'

// Catalog
param catalogPrimary = 'unity-catalog-managed'

// AI orchestration
param agentOrchestrator = 'foundry-agent-service'
param foundryPortalEnabled = true

// Capacity sizing
param capacitySku = 'F8'

// Databricks feature flags
param databricksUnityCatalogEnabled = true
param databricksSqlWarehouseEnabled = true
// Set to your Databricks ACCOUNT id (GUID) to configure Unity Catalog by default
// (regional metastore + default catalog + Console-UAMI account_admin), so Browse >
// Unity Catalog shows a real configured catalog. Requires a one-time step making
// the Console UAMI a Databricks account admin — docs/fiab/catalog/metastores.md.
// Empty = UC enabled later via the post-deploy bootstrap workflow.
param databricksAccountId = ''

// Security
param defenderForAIEnabled = true
// Azure AI Content Safety — copilot persona moderation (Prompt Shields + harm
// analyze). Available in Commercial; wires LOOM_CONTENT_SAFETY_ENDPOINT.
param contentSafetyEnabled = true
// Purview defaults OFF — many Microsoft tenants already have an
// Enterprise-tier tenant-level Purview account (only one allowed per
// tenant). Operator opts in once they've decided whether to reuse the
// existing account (preferred) or scope a new one.
param purviewEnabled = true
// /admin/security Purview tab — point at an EXISTING Purview account
// to enable inline source/scan/glossary/domain management. Leave empty
// to gate the tab behind a structured NotConfigured MessageBar (the
// no-vaporware-compliant fallback). Pull the short account name from
// `az purview account list`.
param loomPurviewAccount = readEnvironmentVariable('LOOM_PURVIEW_ACCOUNT', '')
// Azure Maps — leave EXISTING_AZURE_MAPS_ACCOUNT unset to DEPLOY a fresh Gen2
// account (azure-maps.bicep, default for Commercial/GCC). Set it to bring your
// own existing account; the module is skipped and the env binds to your name.
param loomAzureMapsAccount = readEnvironmentVariable('EXISTING_AZURE_MAPS_ACCOUNT', '')
// /admin/security Information Protection + DLP tabs — both default OFF
// until the post-deploy bootstrap workflow grants the Graph AppRoles
// AND a Tenant Administrator clicks Grant admin consent. After that,
// flip these to true and redeploy admin-plane.
param loomMipEnabled = false
// DLP defaults ON: the post-deploy bootstrap grants the DLP AppRoles by
// default, so the /admin/security DLP tab is wired out of the box (alerts +
// violations + Azure-native restrict-access). The policy segment + simulate
// honest-gate where the Graph DLP preview isn't enabled.
param loomDlpEnabled = true
param loomIdentityPickerEnabled = false
param loomDomainGroupProvisioningEnabled = false
param storageRequireCmk = false
param keyVaultHsmIsolated = false

// OpenAI
param openaiLocation = 'eastus2'
param openaiEmbeddingsLocation = 'eastus2'
param openaiChatModel = 'gpt-4o'
param openaiEmbeddingsModel = 'text-embedding-3-large'

// Power BI
param powerBiSku = 'F64'

// Role-assignment drift guard — set LOOM_SKIP_ROLE_GRANTS=true when
// re-provisioning an environment that already has the RBAC grants, so
// ARM doesn't fail with RoleAssignmentExists. Defaults false for fresh
// deploys.
param skipRoleGrants = readEnvironmentVariable('LOOM_SKIP_ROLE_GRANTS', 'false') == 'true'

// Network
param hubVnetCidr = '10.0.0.0/16'

// Identity
param adminEntraGroupId = '<replace-with-FiaB-Admins-group-guid>'

// Feature-Permissions bootstrap admin — who can open /admin/* (Feature
// Permissions, Domains, Security, …) BEFORE any grants exist. Without one of
// these set, even the deployer gets "Access denied (403)" on /admin/permissions.
// Set your admin SECURITY-GROUP OID (recommended) and/or a single user OID;
// members bypass the feature gate with full Admin. The group defaults to the
// FiaB Admins group above, so setting that one GUID covers both.
//   az ad signed-in-user show --query id -o tsv          # your user OID
//   az ad group show --group "<name>" --query id -o tsv  # admin group OID
param loomTenantAdminGroupId = readEnvironmentVariable('LOOM_TENANT_ADMIN_GROUP_ID', adminEntraGroupId)
param loomTenantAdminOid = readEnvironmentVariable('LOOM_TENANT_ADMIN_OID', '')

// Multi-sub mode (empty for single-sub)
param dlzSubscriptionIds = []
param dlzDomainNames = []

// Tags
param complianceTags = {
  Environment: 'Commercial'
  CSA_Loom: 'true'
  FedRAMP_Level: 'High'
  Data_Classification: 'Standard'
}
