// CSA Loom — GCC-High / IL4 parameters (Azure Government)
// v3 audit (2026-05): aligned with commercial-full deployment surface so
// every flag main.bicep accepts is set explicitly. Cloud-specific values
// (regions, SKUs, orchestrator) flip per the per-boundary dispatch matrix.
//
// Per AMENDMENTS A1 + per-boundary dispatch matrix:
// - Container Apps NOT at IL4 → AKS
// - Databricks UC + SQL Warehouse NOT in Gov → Hive metastore + Synapse Serverless
// - Foundry portal NOT at IL4 → classic Azure ML Hub
// - Foundry Agent Service Gov-GA unconfirmed → MAF + AOAI direct
// - Defender for Cloud AI Threat Protection Commercial-only → Sentinel pipeline
// - APIM Premium v2 not confirmed in Gov → classic Premium
// - Functions Flex Consumption not in Gov → EP1
// - OpenAI Content Safety NOT at IL4 → self-hosted Presidio
// - OpenAI Batch API NOT in Gov
// - AI Search GA-region surface limited in Gov — default off; opt in once
//   region capacity confirmed.
// - Purview: prefer tenant-level Enterprise Purview (Gov tenants already
//   typically have one). Set false here; reuse the existing account.

using '../main.bicep'

// ---------- Bring-your-own existing services (reuse instead of provision-new) ----------
// Gov boundary: no Microsoft Fabric (fabricEnabled hard-false). Generate with:
//   bash scripts/csa-loom/byo-wizard.sh --boundary gcc-high
// >>> BYO-WIZARD START (regenerated by scripts/csa-loom/byo-wizard.sh — edit env vars or re-run the wizard)
param existingAiSearchService    = readEnvironmentVariable('EXISTING_AI_SEARCH_SERVICE', '')
param existingAiSearchRg         = readEnvironmentVariable('EXISTING_AI_SEARCH_RG', '')
param existingAiSearchSub        = readEnvironmentVariable('EXISTING_AI_SEARCH_SUB', '')
param existingApimName           = readEnvironmentVariable('EXISTING_APIM', '')
param existingApimRg             = readEnvironmentVariable('EXISTING_APIM_RG', '')
param existingApimSub            = readEnvironmentVariable('EXISTING_APIM_SUB', '')
param existingAdxClusterName     = readEnvironmentVariable('EXISTING_KUSTO_CLUSTER', '')
param existingAdxClusterRg       = readEnvironmentVariable('EXISTING_KUSTO_RG', '')
param existingAdxClusterSub      = readEnvironmentVariable('EXISTING_KUSTO_SUB', '')
param existingFoundryAccountName = readEnvironmentVariable('EXISTING_AOAI', '')
param existingFoundryRg          = readEnvironmentVariable('EXISTING_AOAI_RG', '')
param existingFoundrySub         = readEnvironmentVariable('EXISTING_AOAI_SUB', '')
param existingFoundryChatDeployment  = readEnvironmentVariable('EXISTING_AOAI_CHAT_DEPLOYMENT', '')
param existingFoundryEmbedDeployment = readEnvironmentVariable('EXISTING_AOAI_EMBED_DEPLOYMENT', '')
param existingPurviewAccount     = readEnvironmentVariable('EXISTING_PURVIEW', '')
param existingPurviewRg          = readEnvironmentVariable('EXISTING_PURVIEW_RG', '')
param existingPurviewSub         = readEnvironmentVariable('EXISTING_PURVIEW_SUB', '')
param existingSynapseWorkspace   = readEnvironmentVariable('EXISTING_SYNAPSE', '')
param existingSynapseRg          = readEnvironmentVariable('EXISTING_SYNAPSE_RG', '')
param existingSynapseSub         = readEnvironmentVariable('EXISTING_SYNAPSE_SUB', '')
param existingCosmosAccount      = readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT', '')
param existingCosmosRg           = readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT_RG', '')
param existingCosmosSub          = readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT_SUB', '')
param existingEventHubNamespace  = readEnvironmentVariable('EXISTING_EVENTHUB_NAMESPACE', '')
param existingEventHubRg         = readEnvironmentVariable('EXISTING_EVENTHUB_RG', '')
param existingEventHubSub        = readEnvironmentVariable('EXISTING_EVENTHUB_SUB', '')
param existingAsaJob             = readEnvironmentVariable('EXISTING_ASA_JOB', '')
param existingAsaRg              = readEnvironmentVariable('EXISTING_ASA_RG', '')
param existingAsaSub             = readEnvironmentVariable('EXISTING_ASA_SUB', '')
param existingDatabricksWorkspace = readEnvironmentVariable('EXISTING_DATABRICKS', '')
param existingDatabricksRg       = readEnvironmentVariable('EXISTING_DATABRICKS_RG', '')
param existingDatabricksSub      = readEnvironmentVariable('EXISTING_DATABRICKS_SUB', '')
param existingDatabricksHostname = readEnvironmentVariable('EXISTING_DATABRICKS_HOSTNAME', '')
param fabricEnabled              = false
// <<< BYO-WIZARD END

param environment = 'AzureUSGovernment'
param location = 'usgovvirginia'
param boundary = 'GCC-High'
param loomAzureCloud = 'AzureUSGovernment'   // Console AZURE_CLOUD discriminator (GCC-High runs on AzureUSGovernment endpoints)
param deploymentMode = 'multi-sub'   // most federal customers use multi-sub
// audit-t157: tenant = first-run install (deploys the hub + DLZ). Add-landing-zone uses dlz-attach via the orchestrator, never this param file.
param topology = 'tenant'

// Compute (Gov differences)
// containerApps: Microsoft.App (Azure Container Apps) is LIVE-verified GA in the
// USGov regions (US Gov Virginia / Arizona / Texas) this param targets — see
// docs/fiab/gov-parity-audit.md GOV-3. The prior 'aks' selection assumed ACA was
// unavailable in Gov; that assumption is superseded. The AKS path is left intact
// for boundaries/regions that require it (flip this back + register the AKS
// EnableAPIServerVnetIntegrationPreview feature to use it).
param containerPlatform = 'containerApps' // ACA GA in USGov Virginia/Arizona/Texas (GOV-3)
param functionsHostSku = 'EP1'            // Flex not in Gov
param apimSku = 'Premium'                 // v2 not confirmed in Gov

// Catalog (Gov-IL4)
param catalogPrimary = 'purview'          // UC managed not yet in Gov

// AI orchestration (Gov)
param agentOrchestrator = 'maf'           // Microsoft Agent Framework + AOAI direct
param foundryPortalEnabled = false        // Foundry portal NOT at IL4
// MAF orchestration tier (loom-copilot-maf) — the Gov AOAI-direct copilot
// backend. It deploys as an Azure Container App. Now that this boundary runs on
// the Container Apps compute path (containerPlatform above — ACA is GA in the
// USGov regions, GOV-3), the MAF tier CAN activate here. It is kept FALSE as the
// conservative default: the Console copilot-orchestrator uses Gov AOAI-direct,
// which is the real, working backend, and enabling MAF requires the
// loom-copilot-maf image in ACR first. Flip to true (with the image pushed) to
// stand up the dedicated MAF tier. The flag is threaded through main.bicep
// (test_main_bicep_threads_copilot_maf_enabled); its activation gate additionally
// requires containerPlatform==containerApps + deployAppsEnabled.
// See docs/fiab/runbooks/il5-gcch-fullstack-verification.md (gap #2/#3).
param copilotMafEnabled = false

// Capacity sizing
param capacitySku = 'F8'

// Databricks (Gov constraints)
param databricksUnityCatalogEnabled = false  // NOT in usgovaz/usgovva
param databricksSqlWarehouseEnabled = false  // NOT in Gov

// Security
param defenderForAIEnabled = false        // Commercial-only → Sentinel workaround
param purviewEnabled = false              // Reuse tenant Enterprise Purview
param atlasOnAksEnabled = false           // IL5-only
param storageRequireCmk = false           // recommended at IL4; required at IL5
param keyVaultHsmIsolated = false         // IL5 only

// OpenAI (Gov endpoints + region constraints)
param openaiLocation = 'usgovvirginia'              // chat models
param openaiEmbeddingsLocation = 'usgovarizona'     // embeddings Standard mode only here
param openaiChatModel = 'gpt-4o'
// Deploy-readiness (opt-out): provision the dedicated AOAI account + gpt-4o chat
// + embedding deployments so Copilot / data-agents / AI-functions work on first
// login. Set false to skip (those surfaces then honest-gate). In Gov boundaries
// the model/version may be pinned via foundry-project.bicep params if a region
// lacks gpt-4o GlobalStandard.
param agentFoundryEnabled = true
param openaiEmbeddingsModel = 'text-embedding-3-large'

// Power BI
param powerBiSku = 'F64'                  // F-SKU available in GCC-H

// Azure Maps — NOT available in GCC-High. azure-maps.bicep already gates on
// boundary == Commercial || GCC, so this is documentary; the geo-map / map
// editors render their honest-gate MessageBars here.
param azureMapsEnabled = false

// Network
param hubVnetCidr = '10.0.0.0/16'

// Identity (Gov tenant)
param adminEntraGroupId = readEnvironmentVariable('LOOM_ADMIN_ENTRA_GROUP_ID', '')

// Loom version + image tags
param loomVersion = readEnvironmentVariable('LOOM_VERSION', 'v3.0')
param appImageTags = {
  console: readEnvironmentVariable('LOOM_CONSOLE_TAG', 'v0.1')
  mcp: readEnvironmentVariable('LOOM_MCP_TAG', 'v0.1')
  mcpBridge: readEnvironmentVariable('LOOM_MCP_BRIDGE_TAG', 'v0.1')
  orchestrator: readEnvironmentVariable('LOOM_ORCHESTRATOR_TAG', 'v0.1')
  activator: readEnvironmentVariable('LOOM_ACTIVATOR_TAG', 'v0.1')
  mirroring: readEnvironmentVariable('LOOM_MIRRORING_TAG', 'v0.1')
  directLake: readEnvironmentVariable('LOOM_DIRECTLAKE_TAG', 'v0.1')
  // These keys MUST be present: admin-plane/main.bicep builds image strings from
  // appImageTags.{setupOrchestrator,maf,scriptRunner,wrangler} even when the
  // corresponding app is gated off. A missing key fails template evaluation
  // ("property 'setupOrchestrator' doesn't exist") and aborts the whole nested
  // deployment. setup-orchestrator + copilot-maf are in the sovereign release
  // image matrix; script-runner + wrangler are NOT built for GCC-High/IL5 and are
  // boundary-gated off in admin-plane/main.bicep, so their tag is only a
  // placeholder that never gets pulled.
  setupOrchestrator: readEnvironmentVariable('LOOM_SETUP_ORCHESTRATOR_TAG', 'v0.1')
  maf: readEnvironmentVariable('LOOM_MAF_TAG', 'v0.1')
  scriptRunner: readEnvironmentVariable('LOOM_SCRIPT_RUNNER_TAG', 'v0.1')
  wrangler: readEnvironmentVariable('LOOM_WRANGLER_TAG', 'v0.1')
  // loom-duckdb — the N2b/N3 DuckDB serving tier admin-plane/main.bicep now
  // deploys BY DEFAULT (duckdbTierActive). STATED EXPLICITLY rather than left to
  // the module's `?? 'v0.1'` fallback because this is the tag the GOV TEMPLATE
  // pulls, and it has to match what the Gov producer stamps:
  //   producer .github/workflows/gov-provision-dataplane-images.yml
  //            image_tag input, default v0.1  ->  az acr build --image loom-duckdb:v0.1
  //   template <acr>/loom-duckdb:v0.1
  // Round 2 had the producer stamp only the short SHA + `latest` while the
  // template asked for v0.1 — a tag nothing produced, so the Gov app could never
  // have pulled. Override BOTH sides together or neither.
  // .github/workflows/deploy-fiab-gcch.yml image-preflights this tag against the
  // Gov ACR before it adopts the live estate.
  duckdb: readEnvironmentVariable('LOOM_DUCKDB_TAG', 'v0.1')
  // loom-migrate (M1 estate-assessment reader) + loom-risingwave (N7a stateful
  // streaming-SQL tier) are DEFAULT-ON in EVERY Container Apps boundary as of
  // 2026-07-28, GCC-High included — admin-plane/main.bicep deploys both and wires
  // LOOM_MIGRATE_URL / LOOM_RISINGWAVE_URL. Unlike script-runner and wrangler,
  // these tags ARE pulled here, so both images MUST be in the sovereign ACR
  // before an apps-enabled deploy (same precondition as loom-console).
  //
  // BUILD THEM WITH (either works; both use server-side `az acr build`, which is
  // the ONLY mechanism that reaches a publicNetworkAccess=Disabled Gov ACR):
  //   .github/workflows/build-fiab-images-acr-tasks.yml  boundary=GCC-High
  //     → the full image set, AZURE_GOV_* creds + `az cloud set`.
  //   .github/workflows/gov-provision-streaming-migrate.yml  mode=build-only
  //     → just these two, plus (mode=build-and-deploy) the incremental
  //       Container Apps + env wiring for an estate that is already up.
  // NOT build-fiab-images.yml: it authenticates with the COMMERCIAL service
  // principal, never calls `az cloud set --name AzureUSGovernment`, and pushes
  // client-side via docker/build-push-action, so it can neither authenticate to
  // a Gov subscription nor reach a private Gov registry. It now hard-fails when
  // dispatched with a Gov boundary instead of silently producing nothing.
  loomMigrate: readEnvironmentVariable('LOOM_MIGRATE_TAG', 'v0.1')
  risingwave: readEnvironmentVariable('LOOM_RISINGWAVE_TAG', 'v0.1')
  // loom-unity (#2681) — the Unity-Catalog-compatible OSS metastore.
  // admin-plane/main.bicep now deploys it DEFAULT-ON on every boundary (it was
  // an out-of-band standalone entrypoint before), so this image is a hard
  // prerequisite of the apps phase — a missing manifest fails the Container App
  // PUT with MANIFEST_UNKNOWN, not just the feature.
  unity: readEnvironmentVariable('LOOM_UNITY_TAG', 'v0.1')
}

// Azure Database for PostgreSQL Flexible Server IS available in Azure
// Government — Microsoft Learn lists US Gov Virginia, US Gov Arizona and US Gov
// Texas as supported regions (Intel v3/v4 compute; US Gov Virginia additionally
// carries zone-redundant HA and geo-redundant backup):
//   https://learn.microsoft.com/azure/postgresql/overview#azure-regions
//   https://learn.microsoft.com/azure/azure-government/compare-azure-government-global-azure#databases
// So the `false` default below is NOT a sovereign service gap, and flipping it
// true is the right END STATE for `loom_default_on_opt_out`.
//
// ROUND-4: THE FLIP IS DELIBERATELY NOT IN THIS PR. It stays `false` because
// `postgresQuotaAvailable` gates TWO hosts, and enabling it here would drag the
// OSS Airflow host into a sovereign boundary with two unrelated defects:
//   1. SUPPLY CHAIN. `admin-plane/airflow.bicep` defaults `airflowImage` to
//      `apache/airflow:2.10.5-python3.12` — an anonymous DOCKER HUB pull. No
//      caller passes an ACR-mirrored override, and no image producer mirrors it,
//      so a locked-egress / air-gapped GCC-High or IL5 CAE cannot pull it at all
//      (and nothing Trivy-scans or cosign-verifies it on the way in).
//   2. NETWORK POSTURE. `admin-plane/main.bicep` invokes airflow.bicep with
//      `privateEndpointsEnabled: false`, which resolves to
//      `publicNetworkAccess: 'Enabled'` plus a `0.0.0.0` firewall rule
//      (`AllowAllAzureServicesAndResourcesWithinAzureIps`) on its metadata
//      Postgres. That is an accepted documented carve-out in Commercial; turning
//      it on in GCC-High / IL5 is a decision that needs its own review, not a
//      side effect of a DuckLake PR.
// Both belong to the same follow-up as the s3proxy ACR mirror (see the PR
// description): mirror `apache/airflow` into each cloud's ACR, wire
// `airflowImage`, give that Postgres a private endpoint — THEN flip this true.
//
// Consequence, stated plainly: on GCC-High the N8 DuckLake catalog store is
// SKIPPED by default and the editor honest-gates with a Fix-it. That is the
// pre-existing state (unchanged by this PR), not a new gate. The DuckDB serving
// tier itself is NOT affected — it has no Postgres dependency and deploys by
// default in both Gov boundaries.
param postgresQuotaAvailable = bool(readEnvironmentVariable('LOOM_POSTGRES_QUOTA_AVAILABLE', 'false'))

// MSAL — Gov tenant client id+secret via env (don't commit)
param loomMsalClientId = readEnvironmentVariable('LOOM_MSAL_CLIENT_ID', '')
param loomMsalClientSecret = readEnvironmentVariable('LOOM_MSAL_CLIENT_SECRET', '')

// Multi-sub (one sub per DLZ for production federal)
param dlzSubscriptionIds = [
  // '<dlz-1-sub-id>'
  // '<dlz-2-sub-id>'
]
param dlzDomainNames = [
  // 'mission-ops'
  // 'finance'
]

// Feature flags — Gov defaults. AI Search OFF (region capacity TBD).
// Front Door NOT certified for IL5 but is for GCC-H — enabled here.
param deployAppsEnabled = true
param aiFoundryEnabled = true
// Azure AI Content Safety IS available in GCC-High (USGovArizona / USGovVirginia)
// — Text, Prompt Shield, and Protected Material Text are all supported per the
// Microsoft Learn region matrix. Wires LOOM_CONTENT_SAFETY_ENDPOINT.
param contentSafetyEnabled = true
param apimEnabled = true
param hubFirewallEnabled = true
// Azure AI Search IS GA in the USGov regions this param targets (US Gov
// Virginia + US Gov Arizona). Operator green-light (gov 89/89 provision drive,
// 2026-07-20): stand it up so the AI Search index / RAG surfaces
// (svc-aisearch → LOOM_AI_SEARCH_SERVICE) are backed by a real service instead
// of honest-gating. If a target region hits capacity at deploy time the ARM
// call fails honestly (not vaporware) — flip back to false or set the EXISTING_*
// AI Search vars to reuse a tenant service.
param aiSearchEnabled = true
// Azure Analysis Services is NOT available in GCC-High — pin OFF (main.bicep now
// defaults aasEnabled=true for Commercial day-one). The semantic-model surfaces
// fall back to Synapse-Serverless / Loom-native here per the documented boundary.
param aasEnabled = false
param adxEnabled = true
// RTI backends — Event Hubs + Stream Analytics ON by default (opt-out). Entra-
// only auth (the only IL5/GCC-High-allowed posture). Set the env var to 'false'
// to skip, or reuse an existing namespace/job via the EXISTING_* vars above.
param loomEventHubEnabled = bool(readEnvironmentVariable('LOOM_EVENTHUB_ENABLED', 'true'))
param loomStreamAnalyticsEnabled = bool(readEnvironmentVariable('LOOM_STREAM_ANALYTICS_ENABLED', 'true'))
// no-op here (containerPlatform=='aks' fails the setupOrchestratorActive gate); on
// AKS the orchestrator runs via the cluster GitOps path as the same Console UAMI.
param setupOrchestratorEnabled = bool(readEnvironmentVariable('LOOM_SETUP_ORCHESTRATOR_ENABLED', 'true'))
param setupTemplateUri = readEnvironmentVariable('LOOM_SETUP_TEMPLATE_URI', '')
// Gremlin (graph editor) + NoSQL vector. Gov suffix gremlin.cosmos.azure.us
// is selected automatically from boundary='GCC-High'.
param cosmosGraphVectorEnabled = true
param vpnGatewayEnabled = true
param appGatewayEnabled = true
param frontDoorEnabled = true

// Tags
param complianceTags = {
  Environment: 'GCC-High'
  CSA_Loom: 'true'
  FedRAMP_Level: 'High'
  DISA_IL: 'IL4'
  Data_Classification: 'CUI'
  M365_Boundary: 'GCC-High'
}

// =====================================================================
// Data-engineering backends — ON by default (opt-out). Set any to false to
// skip that provision; the console editor then honest-gates (LOOM_* env blanked)
// instead of 502-ing. See docs/fiab/prp/deploy-readiness-100pct.md.
// =====================================================================
param loomSynapseEnabled = true
param loomDatabricksEnabled = true
param loomDataFactoryEnabled = true
param loomSelfHostedIrEnabled = true

// =====================================================================
// Graph-native / built-in surfaces — ON in GCC-High (gov 89/89 provision
// drive, 2026-07-20). None of these require Microsoft Fabric; all run on
// Azure-native / Microsoft Graph backends that work in the Gov boundary
// (Graph via graph.microsoft.us, built-in Loom MCP tool surface).
// =====================================================================
// Workspace ↔ M365 group link (svc-m365-link → LOOM_WORKSPACE_M365_LINK).
// Backed by Microsoft Graph. The Console UAMI needs the Group.ReadWrite.All
// AppRole to CREATE a group (scripts/csa-loom/grant-identity-graph-approles.sh
// + admin consent) — a real, documented data-plane grant, not a fake config.
param loomWorkspaceM365LinkEnabled = true
// OneDrive / SharePoint OneLake shortcuts (svc-sharepoint-shortcuts →
// LOOM_SHAREPOINT_SHORTCUTS_ENABLED). Backed by Microsoft Graph
// (Sites.Read.All + Files.Read.All AppRoles — grant-shortcut-graph-approles.sh).
param loomSharepointShortcutsEnabled = true
// Fabric IQ MCP bridge external-token surface (svc-iq-mcp → LOOM_IQ_MCP_ENABLED).
// Built-in Loom tool surface exposed to external agents via Bearer auth; no
// external resource required.
param loomIqMcpEnabled = true
