// CSA Loom — GCC-High / IL4 parameters (Azure Government)
// v3 audit (2026-05): aligned with commercial-full deployment surface so
// every flag main.bicep accepts is set explicitly. Cloud-specific values
// (regions, SKUs, orchestrator) flip per the per-boundary dispatch matrix.
//
// Per AMENDMENTS A1 + per-boundary dispatch matrix:
// - Container Apps NOT at IL4 → AKS
// - Databricks UC + SQL Warehouse NOT in Gov → Hive metastore + Synapse Serverless
// - Foundry portal NOT at IL4 → classic Azure ML Hub
// - Foundry Agent Service Gov-GA unconfirmed → MAF + AOAI direct
// - Defender for Cloud AI Threat Protection Commercial-only → Sentinel pipeline
// - APIM Premium v2 not confirmed in Gov → classic Premium
// - Functions Flex Consumption not in Gov → EP1
// - OpenAI Content Safety NOT at IL4 → self-hosted Presidio
// - OpenAI Batch API NOT in Gov
// - AI Search GA-region surface limited in Gov — default off; opt in once
//   region capacity confirmed.
// - Purview: prefer tenant-level Enterprise Purview (Gov tenants already
//   typically have one). Set false here; reuse the existing account.

using '../main.bicep'

// ---------- Bring-your-own existing services (reuse instead of provision-new) ----------
// Gov boundary: no Microsoft Fabric (fabricEnabled hard-false). Generate with:
//   bash scripts/csa-loom/byo-wizard.sh --boundary gcc-high
// >>> BYO-WIZARD START (regenerated by scripts/csa-loom/byo-wizard.sh — edit env vars or re-run the wizard)
// ---------- ADOPT-OR-CREATE plan (replaces the per-service EXISTING_* params) ----------
// main.bicep no longer declares 36 `existing*` scalars; it declares ONE `adopt`
// object keyed by the service key in apps/fiab-console/lib/deploy/adoption-catalog.ts.
// That is what freed the ARM parameter budget (251 -> 216 of 256) so networking,
// storage, Log Analytics and ACR adoption become possible at all.
//
// TWO input paths, and the explicit plan always wins:
//
//   1. LOOM_ADOPT_JSON - the whole plan as one JSON document, emitted by
//      `planToArmParameters()` (apps/fiab-console/lib/deploy/plan-to-arm.ts).
//      This is the first-class path every deploy tier uses.
//   2. The legacy per-service EXISTING_* environment variables below, kept
//      working verbatim so byo-wizard.sh / scan-and-deploy.sh / a hand-exported
//      shell keep behaving exactly as before.
//
// `union(legacy, plan)` means a service present in BOTH resolves to the plan's
// decision. A service in NEITHER is absent from the object, and main.bicep's
// `adoptMode()` defaults an absent key to 'create' - so an empty environment
// still produces a complete greenfield deployment.
//
// NOTE: setting an EXISTING_* name now also SUPPRESSES the matching new resource
// (main.bicep's provision<Service> vars). Previously several services - Purview,
// Maps, Foundry, Synapse, Databricks, ADF - rebound the Console env to the
// existing resource while STILL deploying a duplicate beside it.
// ── #3446 — Azure Maps BYO/adopt env names, ALL THREE SPELLINGS ──────────────
// Loom's own producers disagree about what the Maps reuse env vars are called,
// and until this change the .bicepparam files read exactly ONE of the three, so
// setting either of the other two was silently inert. Measured on this tree:
//
//   apps/fiab-console/lib/deploy/adoption-catalog.ts:508
//       legacyEnv { name: 'EXISTING_AZURE_MAPS_ACCOUNT', rg: 'EXISTING_AZURE_MAPS_RG',
//                   sub: 'EXISTING_AZURE_MAPS_SUB' }            ← what params read
//   apps/fiab-console/lib/setup/scan-services.ts:205
//       envName: 'EXISTING_AZURE_MAPS'  (rg/sub DO match)        ← Setup Wizard scan
//   apps/fiab-console/app/api/setup/discover-services/route.ts:101
//       { name: 'EXISTING_MAPS', rg: 'EXISTING_MAPS_RG', sub: 'EXISTING_MAPS_SUB' }
//   scripts/csa-loom/scan-and-deploy.sh:186   (same EXISTING_MAPS triple)
//
// So the drift is not one variable: the third spelling diverges on rg and sub
// TOO, which is why bridging only the name would still bind an adopted account
// to the wrong resource group. All three are accepted here, name/rg/sub each.
//
// PARAMS-SIDE bridge on purpose: making the producers agree means editing
// scan-services.ts / discover-services/route.ts, which this change does not own.
// Accepting every spelling is strictly additive — no operator who set the
// canonical EXISTING_AZURE_MAPS_ACCOUNT sees any change — and it keeps the
// canonical literals present so check-adoption-catalog-sync.mjs's A10 check
// (catalog legacyEnv names must still be read by commercial-full.bicepparam)
// keeps passing. Precedence is canonical-first, so a tree that sets two
// spellings resolves deterministically rather than by union() ordering.
var mapsAdoptName = !empty(readEnvironmentVariable('EXISTING_AZURE_MAPS_ACCOUNT', ''))
  ? readEnvironmentVariable('EXISTING_AZURE_MAPS_ACCOUNT', '')
  : (!empty(readEnvironmentVariable('EXISTING_AZURE_MAPS', ''))
      ? readEnvironmentVariable('EXISTING_AZURE_MAPS', '')
      : readEnvironmentVariable('EXISTING_MAPS', ''))
var mapsAdoptRg = !empty(readEnvironmentVariable('EXISTING_AZURE_MAPS_RG', ''))
  ? readEnvironmentVariable('EXISTING_AZURE_MAPS_RG', '')
  : readEnvironmentVariable('EXISTING_MAPS_RG', '')
var mapsAdoptSub = !empty(readEnvironmentVariable('EXISTING_AZURE_MAPS_SUB', ''))
  ? readEnvironmentVariable('EXISTING_AZURE_MAPS_SUB', '')
  : readEnvironmentVariable('EXISTING_MAPS_SUB', '')

var legacyAdoptFromEnv = union(
  empty(readEnvironmentVariable('EXISTING_AI_SEARCH_SERVICE', '')) ? {} : { aisearch: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_AI_SEARCH_SERVICE', ''), rg: readEnvironmentVariable('EXISTING_AI_SEARCH_RG', ''), sub: readEnvironmentVariable('EXISTING_AI_SEARCH_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_APIM', '')) ? {} : { apim: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_APIM', ''), rg: readEnvironmentVariable('EXISTING_APIM_RG', ''), sub: readEnvironmentVariable('EXISTING_APIM_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_KUSTO_CLUSTER', '')) ? {} : { adx: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_KUSTO_CLUSTER', ''), rg: readEnvironmentVariable('EXISTING_KUSTO_RG', ''), sub: readEnvironmentVariable('EXISTING_KUSTO_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_AOAI', '')) ? {} : { foundry: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_AOAI', ''), rg: readEnvironmentVariable('EXISTING_AOAI_RG', ''), sub: readEnvironmentVariable('EXISTING_AOAI_SUB', '') }, extra: { chatDeployment: readEnvironmentVariable('EXISTING_AOAI_CHAT_DEPLOYMENT', ''), embedDeployment: readEnvironmentVariable('EXISTING_AOAI_EMBED_DEPLOYMENT', ''), miniDeployment: readEnvironmentVariable('EXISTING_AOAI_MINI_DEPLOYMENT', ''), strongDeployment: readEnvironmentVariable('EXISTING_AOAI_STRONG_DEPLOYMENT', '') } } },
  empty(readEnvironmentVariable('EXISTING_PURVIEW', '')) ? {} : { purview: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_PURVIEW', ''), rg: readEnvironmentVariable('EXISTING_PURVIEW_RG', ''), sub: readEnvironmentVariable('EXISTING_PURVIEW_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_SYNAPSE', '')) ? {} : { synapse: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_SYNAPSE', ''), rg: readEnvironmentVariable('EXISTING_SYNAPSE_RG', ''), sub: readEnvironmentVariable('EXISTING_SYNAPSE_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT', '')) ? {} : { cosmos: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT', ''), rg: readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT_RG', ''), sub: readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_EVENTHUB_NAMESPACE', '')) ? {} : { eventhubs: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_EVENTHUB_NAMESPACE', ''), rg: readEnvironmentVariable('EXISTING_EVENTHUB_RG', ''), sub: readEnvironmentVariable('EXISTING_EVENTHUB_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_ASA_JOB', '')) ? {} : { streamanalytics: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_ASA_JOB', ''), rg: readEnvironmentVariable('EXISTING_ASA_RG', ''), sub: readEnvironmentVariable('EXISTING_ASA_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_DATABRICKS', '')) ? {} : { databricks: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_DATABRICKS', ''), rg: readEnvironmentVariable('EXISTING_DATABRICKS_RG', ''), sub: readEnvironmentVariable('EXISTING_DATABRICKS_SUB', '') }, extra: { hostname: readEnvironmentVariable('EXISTING_DATABRICKS_HOSTNAME', '') } } },
  empty(readEnvironmentVariable('EXISTING_ADF', '')) ? {} : { adf: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_ADF', ''), rg: readEnvironmentVariable('EXISTING_ADF_RG', ''), sub: readEnvironmentVariable('EXISTING_ADF_SUB', '') } } },
  empty(mapsAdoptName) ? {} : { maps: { mode: 'adopt', target: { name: mapsAdoptName, rg: mapsAdoptRg, sub: mapsAdoptSub } } },
  empty(readEnvironmentVariable('EXISTING_AML_WORKSPACE', '')) ? {} : { aml: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_AML_WORKSPACE', ''), rg: readEnvironmentVariable('EXISTING_AML_RG', ''), sub: readEnvironmentVariable('EXISTING_AML_SUB', '') } } }
)
param adopt = union(legacyAdoptFromEnv, json(readEnvironmentVariable('LOOM_ADOPT_JSON', '{}')))
param fabricEnabled              = false
// <<< BYO-WIZARD END

param environment = 'AzureUSGovernment'
param location = 'usgovvirginia'
param boundary = 'GCC-High'
param loomAzureCloud = 'AzureUSGovernment'   // Console AZURE_CLOUD discriminator (GCC-High runs on AzureUSGovernment endpoints)
param deploymentMode = 'multi-sub'   // most federal customers use multi-sub
// audit-t157: tenant = first-run install (deploys the hub + DLZ). Add-landing-zone uses dlz-attach via the orchestrator, never this param file.
param topology = 'tenant'

// Compute (Gov differences)
// containerApps: Microsoft.App (Azure Container Apps) is LIVE-verified GA in the
// USGov regions (US Gov Virginia / Arizona / Texas) this param targets — see
// docs/fiab/gov-parity-audit.md GOV-3. The prior 'aks' selection assumed ACA was
// unavailable in Gov; that assumption is superseded. The AKS path is left intact
// for boundaries/regions that require it (flip this back + register the AKS
// EnableAPIServerVnetIntegrationPreview feature to use it).
param containerPlatform = 'containerApps' // ACA GA in USGov Virginia/Arizona/Texas (GOV-3)
param functionsHostSku = 'EP1'            // Flex not in Gov
param apimSku = 'Premium'                 // v2 not confirmed in Gov

// Catalog (Gov-IL4)
param catalogPrimary = 'purview'          // UC managed not yet in Gov

// AI orchestration (Gov)
param agentOrchestrator = 'maf'           // Microsoft Agent Framework + AOAI direct
param foundryPortalEnabled = false        // Foundry portal NOT at IL4
// MAF orchestration tier (loom-copilot-maf) — the Gov AOAI-direct copilot
// backend. It deploys as an Azure Container App. Now that this boundary runs on
// the Container Apps compute path (containerPlatform above — ACA is GA in the
// USGov regions, GOV-3), the MAF tier CAN activate here. It is kept FALSE as the
// conservative default: the Console copilot-orchestrator uses Gov AOAI-direct,
// which is the real, working backend, and enabling MAF requires the
// loom-copilot-maf image in ACR first. Flip to true (with the image pushed) to
// stand up the dedicated MAF tier. The flag is threaded through main.bicep
// (test_main_bicep_threads_copilot_maf_enabled); its activation gate additionally
// requires containerPlatform==containerApps + deployAppsEnabled.
// See docs/fiab/runbooks/il5-gcch-fullstack-verification.md (gap #2/#3).
param copilotMafEnabled = false

// Capacity sizing
param capacitySku = 'F8'

// Databricks (Gov constraints)
param databricksUnityCatalogEnabled = false  // NOT in usgovaz/usgovva
param databricksSqlWarehouseEnabled = false  // NOT in Gov

// Security
param defenderForAIEnabled = false        // Commercial-only → Sentinel workaround
param purviewEnabled = false              // Reuse tenant Enterprise Purview
param atlasOnAksEnabled = false           // IL5-only
param storageRequireCmk = false           // recommended at IL4; required at IL5
param keyVaultHsmIsolated = false         // IL5 only

// OpenAI (Gov endpoints + region constraints)
param openaiLocation = 'usgovvirginia'              // chat models
param openaiEmbeddingsLocation = 'usgovarizona'     // embeddings Standard mode only here
param openaiChatModel = 'gpt-4o'
// Deploy-readiness (opt-out): provision the dedicated AOAI account + gpt-4o chat
// + embedding deployments so Copilot / data-agents / AI-functions work on first
// login. Set false to skip (those surfaces then honest-gate). In Gov boundaries
// the model/version may be pinned via foundry-project.bicep params if a region
// lacks gpt-4o GlobalStandard.
param agentFoundryEnabled = true
param openaiEmbeddingsModel = 'text-embedding-3-large'

// Power BI
param powerBiSku = 'F64'                  // F-SKU available in GCC-H

// Azure Maps — NOT available in GCC-High. azure-maps.bicep already gates on
// boundary == Commercial || GCC, so this is documentary; the geo-map / map
// editors render their honest-gate MessageBars here.
param azureMapsEnabled = false

// Network
param hubVnetCidr = '10.0.0.0/16'

// Identity (Gov tenant)
param adminEntraGroupId = readEnvironmentVariable('LOOM_ADMIN_ENTRA_GROUP_ID', '')

// Bootstrap tenant admin — who can open /admin/* BEFORE any feature grants
// exist. Declared HERE (it was absent until #3090, so the bicep default '' was
// the only possible value and the GCC-High console shipped with the admin gate
// shut for every user, exactly as Commercial did). deploy-fiab-gcch.yml passes
// loomTenantAdminGroupId EXPLICITLY on the command line; the environment
// variable below is what a by-hand `-p params/gcc-high.bicepparam` run reads.
// It must NOT be written as `readEnvironmentVariable('…', adminEntraGroupId)` —
// that resolves adminEntraGroupId to THIS FILE's value at compile time, never
// to a `--parameters adminEntraGroupId=…` override, which is the precise trap
// that produced the live defect.
param loomTenantAdminGroupId = readEnvironmentVariable('LOOM_TENANT_ADMIN_GROUP_ID', readEnvironmentVariable('LOOM_ADMIN_ENTRA_GROUP_ID', ''))
param loomTenantAdminOid = readEnvironmentVariable('LOOM_TENANT_ADMIN_OID', '')

// Loom version + image tags
param loomVersion = readEnvironmentVariable('LOOM_VERSION', 'v3.0')
param appImageTags = {
  console: readEnvironmentVariable('LOOM_CONSOLE_TAG', 'v0.1')
  mcp: readEnvironmentVariable('LOOM_MCP_TAG', 'v0.1')
  mcpBridge: readEnvironmentVariable('LOOM_MCP_BRIDGE_TAG', 'v0.1')
  orchestrator: readEnvironmentVariable('LOOM_ORCHESTRATOR_TAG', 'v0.1')
  activator: readEnvironmentVariable('LOOM_ACTIVATOR_TAG', 'v0.1')
  mirroring: readEnvironmentVariable('LOOM_MIRRORING_TAG', 'v0.1')
  directLake: readEnvironmentVariable('LOOM_DIRECTLAKE_TAG', 'v0.1')
  // These keys MUST be present: admin-plane/main.bicep builds image strings from
  // appImageTags.{setupOrchestrator,maf,scriptRunner,wrangler} even when the
  // corresponding app is gated off. A missing key fails template evaluation
  // ("property 'setupOrchestrator' doesn't exist") and aborts the whole nested
  // deployment. setup-orchestrator + copilot-maf are in the sovereign release
  // image matrix; script-runner + wrangler are NOT built for GCC-High/IL5 and are
  // boundary-gated off in admin-plane/main.bicep, so their tag is only a
  // placeholder that never gets pulled.
  setupOrchestrator: readEnvironmentVariable('LOOM_SETUP_ORCHESTRATOR_TAG', 'v0.1')
  maf: readEnvironmentVariable('LOOM_MAF_TAG', 'v0.1')
  scriptRunner: readEnvironmentVariable('LOOM_SCRIPT_RUNNER_TAG', 'v0.1')
  wrangler: readEnvironmentVariable('LOOM_WRANGLER_TAG', 'v0.1')
  // loom-duckdb — the N2b/N3 DuckDB serving tier admin-plane/main.bicep now
  // deploys BY DEFAULT (duckdbTierActive). STATED EXPLICITLY rather than left to
  // the module's `?? 'v0.1'` fallback because this is the tag the GOV TEMPLATE
  // pulls, and it has to match what the Gov producer stamps:
  //   producer .github/workflows/gov-provision-dataplane-images.yml
  //            image_tag input, default v0.1  ->  az acr build --image loom-duckdb:v0.1
  //   template <acr>/loom-duckdb:v0.1
  // Round 2 had the producer stamp only the short SHA + `latest` while the
  // template asked for v0.1 — a tag nothing produced, so the Gov app could never
  // have pulled. Override BOTH sides together or neither.
  // .github/workflows/deploy-fiab-gcch.yml image-preflights this tag against the
  // Gov ACR before it adopts the live estate.
  duckdb: readEnvironmentVariable('LOOM_DUCKDB_TAG', 'v0.1')
  // loom-migrate (M1 estate-assessment reader) + loom-risingwave (N7a stateful
  // streaming-SQL tier) are DEFAULT-ON in EVERY Container Apps boundary as of
  // 2026-07-28, GCC-High included — admin-plane/main.bicep deploys both and wires
  // LOOM_MIGRATE_URL / LOOM_RISINGWAVE_URL. Unlike script-runner and wrangler,
  // these tags ARE pulled here, so both images MUST be in the sovereign ACR
  // before an apps-enabled deploy (same precondition as loom-console).
  //
  // BUILD THEM WITH (either works; both use server-side `az acr build`, which is
  // the ONLY mechanism that reaches a publicNetworkAccess=Disabled Gov ACR):
  //   .github/workflows/build-fiab-images-acr-tasks.yml  boundary=GCC-High
  //     → the full image set, AZURE_GOV_* creds + `az cloud set`.
  //   .github/workflows/gov-provision-streaming-migrate.yml  mode=build-only
  //     → just these two, plus (mode=build-and-deploy) the incremental
  //       Container Apps + env wiring for an estate that is already up.
  // NOT build-fiab-images.yml: it authenticates with the COMMERCIAL service
  // principal, never calls `az cloud set --name AzureUSGovernment`, and pushes
  // client-side via docker/build-push-action, so it can neither authenticate to
  // a Gov subscription nor reach a private Gov registry. It now hard-fails when
  // dispatched with a Gov boundary instead of silently producing nothing.
  loomMigrate: readEnvironmentVariable('LOOM_MIGRATE_TAG', 'v0.1')
  risingwave: readEnvironmentVariable('LOOM_RISINGWAVE_TAG', 'v0.1')
  // loom-directlake (#3291) -- the HYP-5 Direct Lake columnar scan/frame service,
  // DEFAULT-ON via compute/loom-directlake-app.bicep. A SEPARATE key from
  // `directLake` above, which pins the loom-direct-lake-shim image: two apps,
  // two repos, one key would recreate the #2775 defect.
  directLakeSvc: readEnvironmentVariable('LOOM_DIRECTLAKE_SVC_TAG', 'v0.1')
  // loom-unity (#2681) — the Unity-Catalog-compatible OSS metastore.
  // admin-plane/main.bicep now deploys it DEFAULT-ON on every boundary (it was
  // an out-of-band standalone entrypoint before), so this image is a hard
  // prerequisite of the apps phase — a missing manifest fails the Container App
  // PUT with MANIFEST_UNKNOWN, not just the feature.
  unity: readEnvironmentVariable('LOOM_UNITY_TAG', 'v0.1')
  // loom-trino (N7e) — the DEFAULT-ON Federated SQL engine. Together with the
  // Iceberg REST Catalog (which runs the loom-unity image above) this IS the
  // external-engine federation product for a boundary with no Databricks Unity
  // Catalog, so the tag contract matters here more than in Commercial:
  //   producer .github/workflows/gov-provision-dataplane-images.yml
  //            image_tag input, default v0.1 -> az acr build --image loom-trino:v0.1
  //   template <acr>/loom-trino:v0.1  (admin-plane reads appImageTags.?trino ?? 'v0.1')
  // Stated explicitly so the tag is operator-settable per boundary instead of
  // being pinned by a fallback with no lever, exactly like duckdb/unity above.
  trino: readEnvironmentVariable('LOOM_TRINO_TAG', 'v0.1')
}

// Azure Database for PostgreSQL Flexible Server IS available in Azure
// Government — Microsoft Learn lists US Gov Virginia, US Gov Arizona and US Gov
// Texas as supported regions (Intel v3/v4 compute; US Gov Virginia additionally
// carries zone-redundant HA and geo-redundant backup):
//   https://learn.microsoft.com/azure/postgresql/overview#azure-regions
//   https://learn.microsoft.com/azure/azure-government/compare-azure-government-global-azure#databases
// So the `false` default below is NOT a sovereign service gap, and flipping it
// true is the right END STATE for `loom_default_on_opt_out`.
//
// ROUND-4: THE FLIP IS DELIBERATELY NOT IN THIS PR. It stays `false` because
// enabling it here would drag the OSS Airflow host into a sovereign boundary
// with two unrelated defects:
//   1. SUPPLY CHAIN. `admin-plane/airflow.bicep` defaults `airflowImage` to
//      `apache/airflow:2.10.5-python3.12` — an anonymous DOCKER HUB pull. No
//      caller passes an ACR-mirrored override, and no image producer mirrors it,
//      so a locked-egress / air-gapped GCC-High or IL5 CAE cannot pull it at all
//      (and nothing Trivy-scans or cosign-verifies it on the way in).
//   2. NETWORK POSTURE. `admin-plane/main.bicep` invokes airflow.bicep with
//      `privateEndpointsEnabled: false`, which resolves to
//      `publicNetworkAccess: 'Enabled'` plus a `0.0.0.0` firewall rule
//      (`AllowAllAzureServicesAndResourcesWithinAzureIps`) on its metadata
//      Postgres. That is an accepted documented carve-out in Commercial; turning
//      it on in GCC-High / IL5 is a decision that needs its own review, not a
//      side effect of a DuckLake PR.
// Both belong to the same follow-up as the s3proxy ACR mirror (see the PR
// description): mirror `apache/airflow` into each cloud's ACR, wire
// `airflowImage`, give that Postgres a private endpoint — THEN flip this true.
//
// ── BLAST RADIUS OF THE FLIP — WHAT THIS FLAG ACTUALLY GATES ────────────────
// Kept current deliberately: an earlier revision of this note said "TWO hosts",
// which was already understated when it was written (loom-unity made it three)
// and is now wrong by two more. Whoever performs the follow-up flip is turning
// on ALL of the following at once, in a sovereign boundary, and owns the review
// of each — that is precisely the "side effect of a DuckLake PR" hazard this
// note exists to prevent, and it must not be re-created in reverse.
//
//   1. OSS Airflow metadata DB    admin-plane/airflow.bicep
//                                 (via airflowPostgresAllowed; per-capability
//                                  key loomBackends.airflowPostgres) — carries
//                                  BOTH defects above.
//   2. N8 DuckLake catalog store  data-plane/ducklake-catalog-postgres.bicep
//                                 (via postgresStoresAllowed; key
//                                  loomBackends.postgresStores).
//   3. Loom Unity metastore       data-plane/loom-unity-postgres.bicep
//                                 (via postgresStoresAllowed — SAME key as 2, so
//                                  they flip together). Today Unity still runs:
//                                  it falls back to the EmptyDir H2 store, a
//                                  functional catalog whose metadata does not
//                                  survive a restart.
//   4. Weave ontology AGE store   landing-zone/postgres-weave.bicep  [3449d]
//                                 Also backs LOOM_PGVECTOR_HOST. On the tenant
//                                  topology this boundary uses, the per-capability
//                                  key is loomBackends.weavePostgres, so Weave
//                                  CAN be turned on alone without 1-3. On
//                                  single-sub / multi-sub / dlz-attach there is
//                                  no such key (landing-zone/main.bicep is not
//                                  handed loomBackends) — a named gap, not a
//                                  silent one.
//   5. Lakebase Postgres          deploy-planner/postgres.bicep       [3449d]
//                                 Only when postgresEnabled is ALSO true; that
//                                  defaults false and no shipped .bicepparam
//                                  sets it, so this row is inert today.
//
// Consequence, stated plainly: on GCC-High the N8 DuckLake catalog store is
// SKIPPED by default and the editor honest-gates with a Fix-it. That is the
// pre-existing state, not a new gate. NEW in 3449d: the Weave ontology store is
// skipped too, and svc-weave-ontology honest-gates on LOOM_WEAVE_PG_FQDN — that
// converts a HARD DEPLOY FAILURE (the ParameterOutOfRange leaf on
// psql-loom-weave-default-*, GitHub Actions run 32019775757, deploy-fiab-gcch,
// 2026-08-17) into a registered gate. It does NOT give GCC-High an ontology
// graph store; under .claude/rules/cloud-parity.md that capability remains
// INCOMPLETE here until an Azure-native/OSS substitute backs it. That rule
// requires such a lag be a TRACKED defect with an owner and a date, never a
// silent state, so it is tracked as ISSUE #3788 — do not treat this prose as
// the tracking. The DuckDB serving tier is NOT affected — it has no Postgres
// dependency and deploys by default in both Gov boundaries.
param postgresQuotaAvailable = bool(readEnvironmentVariable('LOOM_POSTGRES_QUOTA_AVAILABLE', 'false'))

// MSAL — Gov tenant client id+secret via env (don't commit)
param loomMsalClientId = readEnvironmentVariable('LOOM_MSAL_CLIENT_ID', '')
param loomMsalClientSecret = readEnvironmentVariable('LOOM_MSAL_CLIENT_SECRET', '')

// Multi-sub (one sub per DLZ for production federal)
param dlzSubscriptionIds = [
  // '<dlz-1-sub-id>'
  // '<dlz-2-sub-id>'
]
param dlzDomainNames = [
  // 'mission-ops'
  // 'finance'
]

// Feature flags — Gov defaults. AI Search OFF (region capacity TBD).
// Front Door NOT certified for IL5 but is for GCC-H — enabled here.
param deployAppsEnabled = true
param aiFoundryEnabled = true
// Azure AI Content Safety IS available in GCC-High (USGovArizona / USGovVirginia)
// — Text, Prompt Shield, and Protected Material Text are all supported per the
// Microsoft Learn region matrix. Wires LOOM_CONTENT_SAFETY_ENDPOINT.
param contentSafetyEnabled = true
param apimEnabled = true
param hubFirewallEnabled = true
// Azure AI Search IS GA in the USGov regions this param targets (US Gov
// Virginia + US Gov Arizona). Operator green-light (gov 89/89 provision drive,
// 2026-07-20): stand it up so the AI Search index / RAG surfaces
// (svc-aisearch → LOOM_AI_SEARCH_SERVICE) are backed by a real service instead
// of honest-gating. If a target region hits capacity at deploy time the ARM
// call fails honestly (not vaporware) — flip back to false or set the EXISTING_*
// AI Search vars to reuse a tenant service.
param aiSearchEnabled = true
// Azure Analysis Services is NOT available in GCC-High — pin OFF (main.bicep now
// defaults aasEnabled=true for Commercial day-one). The semantic-model surfaces
// fall back to Synapse-Serverless / Loom-native here per the documented boundary.
param aasEnabled = false
param adxEnabled = true
// RTI backends — Event Hubs + Stream Analytics ON by default (opt-out). Entra-
// only auth (the only IL5/GCC-High-allowed posture). Set the env var to 'false'
// to skip, or reuse an existing namespace/job via the EXISTING_* vars above.
param loomEventHubEnabled = bool(readEnvironmentVariable('LOOM_EVENTHUB_ENABLED', 'true'))
param loomStreamAnalyticsEnabled = bool(readEnvironmentVariable('LOOM_STREAM_ANALYTICS_ENABLED', 'true'))
// no-op here (containerPlatform=='aks' fails the setupOrchestratorActive gate); on
// AKS the orchestrator runs via the cluster GitOps path as the same Console UAMI.
param setupOrchestratorEnabled = bool(readEnvironmentVariable('LOOM_SETUP_ORCHESTRATOR_ENABLED', 'true'))
param setupTemplateUri = readEnvironmentVariable('LOOM_SETUP_TEMPLATE_URI', '')
// Gremlin (graph editor) + NoSQL vector. Gov suffix gremlin.cosmos.azure.us
// is selected automatically from boundary='GCC-High'.
param cosmosGraphVectorEnabled = true
param vpnGatewayEnabled = true
param appGatewayEnabled = true
param frontDoorEnabled = true

// Tags
param complianceTags = {
  Environment: 'GCC-High'
  CSA_Loom: 'true'
  FedRAMP_Level: 'High'
  DISA_IL: 'IL4'
  Data_Classification: 'CUI'
  M365_Boundary: 'GCC-High'
}

// =====================================================================
// Data-engineering backends — ON by default (opt-out). Set any to false to
// skip that provision; the console editor then honest-gates (LOOM_* env blanked)
// instead of 502-ing. See docs/fiab/prp/deploy-readiness-100pct.md.
// =====================================================================
param loomSynapseEnabled = true
param loomDatabricksEnabled = true
param loomDataFactoryEnabled = true
param loomSelfHostedIrEnabled = true

// =====================================================================
// Graph-native / built-in surfaces — ON in GCC-High (gov 89/89 provision
// drive, 2026-07-20). None of these require Microsoft Fabric; all run on
// Azure-native / Microsoft Graph backends that work in the Gov boundary
// (Graph via graph.microsoft.us, built-in Loom MCP tool surface).
// =====================================================================
// Workspace ↔ M365 group link (svc-m365-link → LOOM_WORKSPACE_M365_LINK).
// Backed by Microsoft Graph. The Console UAMI needs the Group.ReadWrite.All
// AppRole to CREATE a group (scripts/csa-loom/grant-identity-graph-approles.sh
// + admin consent) — a real, documented data-plane grant, not a fake config.
param loomWorkspaceM365LinkEnabled = true
// OneDrive / SharePoint OneLake shortcuts (svc-sharepoint-shortcuts →
// LOOM_SHAREPOINT_SHORTCUTS_ENABLED). Backed by Microsoft Graph
// (Sites.Read.All + Files.Read.All AppRoles — grant-shortcut-graph-approles.sh).
param loomSharepointShortcutsEnabled = true
// Fabric IQ MCP bridge external-token surface (svc-iq-mcp → LOOM_IQ_MCP_ENABLED).
// Built-in Loom tool surface exposed to external agents via Bearer auth; no
// external resource required.
param loomIqMcpEnabled = true
