// CSA Loom — GCC parameters
// GCC = M365 GCC tenant + Azure Commercial subscriptions
// Critical GCC gate: F-SKU not supported → no Direct Lake parity in GCC
//
// Status: APPS-ENABLED as of #4071/#3078 — this file deploys the Container App
// tier (deployAppsEnabled = true, below) and a public Front Door ingress, the
// same shape commercial-full / gcc-high / il5 / tenant-dmlz carry. It has NOT
// yet produced a live receipt: deploy-fiab-gcc is disabled_manually and the
// AZURE_GCC_* credential set does not exist, so nothing here is claimed to have
// been verified against a real GCC subscription (deploy-integrity.md R4).

using '../main.bicep'

// ---------- Bring-your-own existing services (reuse instead of provision-new) ----------
// Gov boundary: no Microsoft Fabric (fabricEnabled hard-false). Generate with:
//   bash scripts/csa-loom/byo-wizard.sh --boundary gcc
// >>> BYO-WIZARD START (regenerated by scripts/csa-loom/byo-wizard.sh — edit env vars or re-run the wizard)
// ---------- ADOPT-OR-CREATE plan (replaces the per-service EXISTING_* params) ----------
// main.bicep no longer declares 36 `existing*` scalars; it declares ONE `adopt`
// object keyed by the service key in apps/fiab-console/lib/deploy/adoption-catalog.ts.
// That is what freed the ARM parameter budget (251 -> 216 of 256) so networking,
// storage, Log Analytics and ACR adoption become possible at all.
//
// TWO input paths, and the explicit plan always wins:
//
//   1. LOOM_ADOPT_JSON - the whole plan as one JSON document, emitted by
//      `planToArmParameters()` (apps/fiab-console/lib/deploy/plan-to-arm.ts).
//      This is the first-class path every deploy tier uses.
//   2. The legacy per-service EXISTING_* environment variables below, kept
//      working verbatim so byo-wizard.sh / scan-and-deploy.sh / a hand-exported
//      shell keep behaving exactly as before.
//
// `union(legacy, plan)` means a service present in BOTH resolves to the plan's
// decision. A service in NEITHER is absent from the object, and main.bicep's
// `adoptMode()` defaults an absent key to 'create' - so an empty environment
// still produces a complete greenfield deployment.
//
// NOTE: setting an EXISTING_* name now also SUPPRESSES the matching new resource
// (main.bicep's provision<Service> vars). Previously several services - Purview,
// Maps, Foundry, Synapse, Databricks, ADF - rebound the Console env to the
// existing resource while STILL deploying a duplicate beside it.
// ── #3446 — Azure Maps BYO/adopt env names, ALL THREE SPELLINGS ──────────────
// Loom's own producers disagree about what the Maps reuse env vars are called,
// and until this change the .bicepparam files read exactly ONE of the three, so
// setting either of the other two was silently inert. Measured on this tree:
//
//   apps/fiab-console/lib/deploy/adoption-catalog.ts:508
//       legacyEnv { name: 'EXISTING_AZURE_MAPS_ACCOUNT', rg: 'EXISTING_AZURE_MAPS_RG',
//                   sub: 'EXISTING_AZURE_MAPS_SUB' }            ← what params read
//   apps/fiab-console/lib/setup/scan-services.ts:205
//       envName: 'EXISTING_AZURE_MAPS'  (rg/sub DO match)        ← Setup Wizard scan
//   apps/fiab-console/app/api/setup/discover-services/route.ts:101
//       { name: 'EXISTING_MAPS', rg: 'EXISTING_MAPS_RG', sub: 'EXISTING_MAPS_SUB' }
//   scripts/csa-loom/scan-and-deploy.sh:186   (same EXISTING_MAPS triple)
//
// So the drift is not one variable: the third spelling diverges on rg and sub
// TOO, which is why bridging only the name would still bind an adopted account
// to the wrong resource group. All three are accepted here, name/rg/sub each.
//
// PARAMS-SIDE bridge on purpose: making the producers agree means editing
// scan-services.ts / discover-services/route.ts, which this change does not own.
// Accepting every spelling is strictly additive — no operator who set the
// canonical EXISTING_AZURE_MAPS_ACCOUNT sees any change — and it keeps the
// canonical literals present so check-adoption-catalog-sync.mjs's A10 check
// (catalog legacyEnv names must still be read by commercial-full.bicepparam)
// keeps passing. Precedence is canonical-first, so a tree that sets two
// spellings resolves deterministically rather than by union() ordering.
var mapsAdoptName = !empty(readEnvironmentVariable('EXISTING_AZURE_MAPS_ACCOUNT', ''))
  ? readEnvironmentVariable('EXISTING_AZURE_MAPS_ACCOUNT', '')
  : (!empty(readEnvironmentVariable('EXISTING_AZURE_MAPS', ''))
      ? readEnvironmentVariable('EXISTING_AZURE_MAPS', '')
      : readEnvironmentVariable('EXISTING_MAPS', ''))
var mapsAdoptRg = !empty(readEnvironmentVariable('EXISTING_AZURE_MAPS_RG', ''))
  ? readEnvironmentVariable('EXISTING_AZURE_MAPS_RG', '')
  : readEnvironmentVariable('EXISTING_MAPS_RG', '')
var mapsAdoptSub = !empty(readEnvironmentVariable('EXISTING_AZURE_MAPS_SUB', ''))
  ? readEnvironmentVariable('EXISTING_AZURE_MAPS_SUB', '')
  : readEnvironmentVariable('EXISTING_MAPS_SUB', '')

var legacyAdoptFromEnv = union(
  empty(readEnvironmentVariable('EXISTING_AI_SEARCH_SERVICE', '')) ? {} : { aisearch: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_AI_SEARCH_SERVICE', ''), rg: readEnvironmentVariable('EXISTING_AI_SEARCH_RG', ''), sub: readEnvironmentVariable('EXISTING_AI_SEARCH_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_APIM', '')) ? {} : { apim: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_APIM', ''), rg: readEnvironmentVariable('EXISTING_APIM_RG', ''), sub: readEnvironmentVariable('EXISTING_APIM_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_KUSTO_CLUSTER', '')) ? {} : { adx: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_KUSTO_CLUSTER', ''), rg: readEnvironmentVariable('EXISTING_KUSTO_RG', ''), sub: readEnvironmentVariable('EXISTING_KUSTO_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_AOAI', '')) ? {} : { foundry: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_AOAI', ''), rg: readEnvironmentVariable('EXISTING_AOAI_RG', ''), sub: readEnvironmentVariable('EXISTING_AOAI_SUB', '') }, extra: { chatDeployment: readEnvironmentVariable('EXISTING_AOAI_CHAT_DEPLOYMENT', ''), embedDeployment: readEnvironmentVariable('EXISTING_AOAI_EMBED_DEPLOYMENT', ''), miniDeployment: readEnvironmentVariable('EXISTING_AOAI_MINI_DEPLOYMENT', ''), strongDeployment: readEnvironmentVariable('EXISTING_AOAI_STRONG_DEPLOYMENT', '') } } },
  empty(readEnvironmentVariable('EXISTING_PURVIEW', '')) ? {} : { purview: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_PURVIEW', ''), rg: readEnvironmentVariable('EXISTING_PURVIEW_RG', ''), sub: readEnvironmentVariable('EXISTING_PURVIEW_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_SYNAPSE', '')) ? {} : { synapse: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_SYNAPSE', ''), rg: readEnvironmentVariable('EXISTING_SYNAPSE_RG', ''), sub: readEnvironmentVariable('EXISTING_SYNAPSE_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT', '')) ? {} : { cosmos: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT', ''), rg: readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT_RG', ''), sub: readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_EVENTHUB_NAMESPACE', '')) ? {} : { eventhubs: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_EVENTHUB_NAMESPACE', ''), rg: readEnvironmentVariable('EXISTING_EVENTHUB_RG', ''), sub: readEnvironmentVariable('EXISTING_EVENTHUB_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_ASA_JOB', '')) ? {} : { streamanalytics: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_ASA_JOB', ''), rg: readEnvironmentVariable('EXISTING_ASA_RG', ''), sub: readEnvironmentVariable('EXISTING_ASA_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_DATABRICKS', '')) ? {} : { databricks: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_DATABRICKS', ''), rg: readEnvironmentVariable('EXISTING_DATABRICKS_RG', ''), sub: readEnvironmentVariable('EXISTING_DATABRICKS_SUB', '') }, extra: { hostname: readEnvironmentVariable('EXISTING_DATABRICKS_HOSTNAME', '') } } },
  empty(readEnvironmentVariable('EXISTING_ADF', '')) ? {} : { adf: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_ADF', ''), rg: readEnvironmentVariable('EXISTING_ADF_RG', ''), sub: readEnvironmentVariable('EXISTING_ADF_SUB', '') } } },
  empty(mapsAdoptName) ? {} : { maps: { mode: 'adopt', target: { name: mapsAdoptName, rg: mapsAdoptRg, sub: mapsAdoptSub } } },
  empty(readEnvironmentVariable('EXISTING_AML_WORKSPACE', '')) ? {} : { aml: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_AML_WORKSPACE', ''), rg: readEnvironmentVariable('EXISTING_AML_RG', ''), sub: readEnvironmentVariable('EXISTING_AML_SUB', '') } } }
)
param adopt = union(legacyAdoptFromEnv, json(readEnvironmentVariable('LOOM_ADOPT_JSON', '{}')))
param fabricEnabled              = false
// <<< BYO-WIZARD END

// RTI (Real-Time Intelligence) backends — Event Hubs + Stream Analytics ON by
// default (opt-out). Set the env var to 'false' to skip the cost, or reuse an
// existing namespace/job via the EXISTING_* vars above.
param loomEventHubEnabled = bool(readEnvironmentVariable('LOOM_EVENTHUB_ENABLED', 'true'))
param loomStreamAnalyticsEnabled = bool(readEnvironmentVariable('LOOM_STREAM_ANALYTICS_ENABLED', 'true'))

param environment = 'AzureCloud'
param location = 'eastus'
param boundary = 'GCC'
param deploymentMode = 'single-sub'
// audit-t157: tenant = first-run install (deploys the hub + DLZ). Add-landing-zone uses dlz-attach via the orchestrator, never this param file.
param topology = 'tenant'

// Compute (same as Commercial — GCC runs on Azure public)
param containerPlatform = 'containerApps'
// Console AZURE_CLOUD discriminator, stated the way gcc-high.bicepparam:111 and
// il5.bicepparam:108 state theirs. GCC runs on AZURE COMMERCIAL endpoints under
// an M365 GCC identity, so the value is 'AzureCloud' — the SAME value
// modules/admin-plane/main.bicep already derives when this param is empty
// (`boundary == 'GCC-High' || boundary == 'IL5' ? 'AzureUSGovernment' :
// 'AzureCloud'`). This changes no rendered value; it removes the dependence on
// that derivation, which is the only reason the sovereign siblings state it.
param loomAzureCloud = 'AzureCloud'
// ── #3078 CLOSED HERE: THE GCC BOUNDARY NOW DEPLOYS ITS CONTAINER APPS ───────
// This file used to leave `deployAppsEnabled` unset, and main.bicep defaults it
// FALSE, so `containerPlatform = 'containerApps'` above bought nothing: the
// `appDeployments` nested deployment was skipped and GCC stood up ZERO Container
// Apps — no loom-console, no loom-unity, no loom-trino, no iceberg-catalog.
// Every other apps-enabled boundary (commercial-full, gcc-high, il5,
// tenant-dmlz) sets it `= true`; GCC was the odd one out, which cloud-parity.md
// calls INCOMPLETE rather than "Commercial-first".
//
// WHY IT WAS HELD FALSE, AND WHAT CHANGED. The hold was correct and its reason
// was precise: there was no GCC image producer, so flipping this blind converts
// a passing-but-empty deploy into one that fails every Container App PUT with
// MANIFEST_UNKNOWN. That is now addressed — build-fiab-images-acr-tasks.yml
// carries a `GCC` boundary that logs in with the AZURE_GCC_* secret set, stays
// in Azure Commercial (no `az cloud set`), resolves rg-csa-loom-admin-eastus and
// server-side `az acr build`s every app image into the GCC estate's own ACR.
//
// ORDERING IS STILL LOAD-BEARING, and it is not a property of this file. The
// documented two-phase image path (no-vaporware.md) still applies to a
// GREENFIELD GCC subscription: provision infra with `deployAppsEnabled=false` on
// the command line, run the producer, THEN apply with this file. A brownfield
// reconcile is safe because deploy-fiab-gcc.yml now image-preflights every
// deploy-referenced tag against the GCC ACR before the what-if and REFUSES on a
// missing one, rather than discovering it as a failed nested deployment over a
// live estate.
param deployAppsEnabled = true
// Setup Orchestrator — on by default (Container Apps boundary). The Console UAMI
// gets Contributor on the target sub so the Setup Wizard's Deploy runs the real
// subscription-scoped ARM deployment. LOOM_SETUP_TEMPLATE_URI = published main.json.
param setupOrchestratorEnabled = bool(readEnvironmentVariable('LOOM_SETUP_ORCHESTRATOR_ENABLED', 'true'))
param setupTemplateUri = readEnvironmentVariable('LOOM_SETUP_TEMPLATE_URI', '')
param functionsHostSku = 'FlexConsumption'
param apimSku = 'PremiumV2'

// Catalog
param catalogPrimary = 'unity-catalog-managed'

// AI orchestration
param agentOrchestrator = 'foundry-agent-service'
param foundryPortalEnabled = true

// Capacity sizing
param capacitySku = 'F8'

// Databricks (same as Commercial)
param databricksUnityCatalogEnabled = true
param databricksSqlWarehouseEnabled = true
// Databricks ACCOUNT id (GUID) — configures Unity Catalog by default. GCC uses the
// same accounts.azuredatabricks.net account plane. Requires the Console UAMI to be
// a Databricks account admin (one-time) — docs/fiab/catalog/metastores.md.
// Sourced from LOOM_DATABRICKS_ACCOUNT_ID so a stock deploy with it set configures
// UC with no param-file edit. Unset = UC enabled later via the bootstrap workflow.
param databricksAccountId = readEnvironmentVariable('LOOM_DATABRICKS_ACCOUNT_ID', '')

// Security
param defenderForAIEnabled = true
// Azure AI Content Safety — copilot persona moderation. GCC runs on Commercial
// Azure endpoints, so Content Safety is available; wires LOOM_CONTENT_SAFETY_ENDPOINT.
param contentSafetyEnabled = true
param purviewEnabled = true
// #229 cross-region Purview safety valve (empty = hub location).
param purviewLocation = readEnvironmentVariable('LOOM_PURVIEW_LOCATION', '')
param storageRequireCmk = false
param keyVaultHsmIsolated = false

// OpenAI (Azure public endpoints; M365 GCC identity isolation)
param openaiLocation = 'eastus'
param openaiEmbeddingsLocation = 'eastus'
param openaiChatModel = 'gpt-4o'
// Deploy-readiness (opt-out): provision the dedicated AOAI account + gpt-4o chat
// + embedding deployments so Copilot / data-agents / AI-functions work on first
// login. Set false to skip (those surfaces then honest-gate). In Gov boundaries
// the model/version may be pinned via foundry-project.bicep params if a region
// lacks gpt-4o GlobalStandard.
param agentFoundryEnabled = true
param openaiEmbeddingsModel = 'text-embedding-3-large'

// Power BI — GCC limitation
param powerBiSku = 'P1'   // P-SKU only; F-SKU NOT in GCC

// Azure Maps — Gen2 account deploys by default in GCC (azure-maps.bicep gates
// on boundary == Commercial || GCC). Set EXISTING_AZURE_MAPS_ACCOUNT to bring
// your own; leave unset to provision a fresh account + bind the env automatically.
param loomAzureMapsAccount = mapsAdoptName

// Network
param hubVnetCidr = '10.0.0.0/16'

// Identity
param adminEntraGroupId = readEnvironmentVariable('LOOM_ADMIN_ENTRA_GROUP_ID', '')

// Bootstrap tenant admin — who can open /admin/* BEFORE any feature grants
// exist. Declared HERE (absent until #3090, so the bicep default '' was the
// only possible value and the GCC console shipped with the admin gate shut for
// every user). deploy-fiab-gcc.yml passes loomTenantAdminGroupId EXPLICITLY on
// the command line; the environment variable below is what a by-hand
// `-p params/gcc.bicepparam` run reads. It must NOT be written as
// `readEnvironmentVariable('…', adminEntraGroupId)` — that resolves
// adminEntraGroupId to THIS FILE's value at compile time, never to a
// `--parameters adminEntraGroupId=…` override, which is the precise trap that
// produced the live defect.
param loomTenantAdminGroupId = readEnvironmentVariable('LOOM_TENANT_ADMIN_GROUP_ID', readEnvironmentVariable('LOOM_ADMIN_ENTRA_GROUP_ID', ''))
param loomTenantAdminOid = readEnvironmentVariable('LOOM_TENANT_ADMIN_OID', '')

// Day-1 service posture (deploy-readiness: everything ON by default / opt-out).
// GCC supports APIM + Azure Maps + the hub Azure Firewall; default true in
// main.bicep — set explicitly so the posture is visible (bicep+bootstrap sync).
param apimEnabled = true
param hubFirewallEnabled = true
// ── PUBLIC INGRESS — REQUIRED, NOT COSMETIC, ONCE APPS ARE ON ────────────────
// main.bicep defaults `frontDoorEnabled` FALSE and this file set it nowhere, so
// GCC inherited false while commercial, commercial-full, gcc-high and
// tenant-dmlz all set it true (il5 is the only deliberate false, and its stated
// reason — Front Door is not certified at IL5 — does not apply to a boundary
// running on Azure Commercial).
//
// It is COUPLED to deployAppsEnabled above, which is why it is flipped in the
// same change rather than left for later. container-platform.bicep creates the
// Container Apps environment with `internal: true`, so `output consoleUrl`
// resolves only inside the hub VNet. scripts/ci/resolve-smoke-console-url.mjs
// therefore accepts ONLY `vanityPublicUrl` / `frontDoorPublicUrl` and FAILS
// CLOSED when neither exists — its own header names GCC-High's
// frontDoorEnabled+deployAppsEnabled pair as the construction that guarantees
// one. Enabling apps without this would give deploy-fiab-gcc.yml a Console it
// provisions and then cannot honestly probe: a red smoke step over a healthy
// estate, or (worse) a lane that reports green having measured nothing.
//
// The Front Door origin is the CAE over Private Link — NOT the Application
// Gateway (admin-plane/main.bicep invokes front-door.bicep with `caeId` +
// `consoleFqdn`), so this stands alone and does not imply appGatewayEnabled.
// The FD -> CAE private-endpoint connection is AUTO-APPROVED here: the
// `scriptIdentityId: (boundary == 'GCC-High' || boundary == 'IL5') ? '' : …`
// branch passes the Console UAMI on this boundary, so a clean GCC deploy needs
// no portal "Approve" step (auto-bind-by-default.md).
param frontDoorEnabled = true

// Multi-sub
param dlzSubscriptionIds = []
param dlzDomainNames = []

// Tags
param complianceTags = {
  Environment: 'GCC'
  CSA_Loom: 'true'
  FedRAMP_Level: 'High'
  Data_Classification: 'CUI-low'
  M365_Boundary: 'GCC'
}

// =====================================================================
// Data-engineering backends — ON by default (opt-out). Set any to false to
// skip that provision; the console editor then honest-gates (LOOM_* env blanked)
// instead of 502-ing. See docs/fiab/prp/deploy-readiness-100pct.md.
// =====================================================================
param loomSynapseEnabled = true
param loomDatabricksEnabled = true
param loomDataFactoryEnabled = true
param loomSelfHostedIrEnabled = true

// =====================================================================
// MSAL — the Gov tenant client id, read from the deploy job's environment
// (never committed), exactly as gcc-high.bicepparam:357 and il5.bicepparam do.
// =====================================================================
// #4224. This line was MISSING from this file alone, which is worse than the
// gap it looks like: without it the param takes main.bicep's `param
// loomMsalClientId string = ''` default, so every GCC deploy rendered an EMPTY
// client id PERMANENTLY — no environment value could reach the template, and
// adding a resolver step to the workflow would have been inert.
//
// An Entra app registration is a Microsoft Graph object ARM cannot create; it is
// minted once by csa-loom-post-deploy-bootstrap and only RE-READ here. A
// declarative ACA template DROPS every env var it does not declare, so an empty
// render blanks LOOM_MSAL_CLIENT_ID (sign-in dark) and empties
// LOOM_UNITY_CLIENT_ID / LOOM_UNITY_AUDIENCE with it — sealing the Iceberg REST
// catalog behind the `.invalid` sentinel audience no tenant can mint
// (iceberg-catalog-aca.bicep, svc-loom-unity-authz).
//
// Latent rather than live: GCC is `disabled_manually` with zero credentials
// (#4071), so this lane has not run. It would have fired on the first run after
// re-enablement, which is the worst moment to find it.
param loomMsalClientId = readEnvironmentVariable('LOOM_MSAL_CLIENT_ID', '')
// The SECOND half of the same #4224 defect, and it was still open: every other
// shipped params file (commercial-full:292, gcc-high:358, il5:335,
// tenant-dmlz:193) reads LOOM_MSAL_CLIENT_SECRET and this file read it NOWHERE,
// so main.bicep's `param loomMsalClientSecret string = ''` was the only value a
// GCC deploy could ever render — no environment value could reach the template
// and a resolver step in the workflow would have been inert, exactly as the
// client-id half was. Strictly additive: with the variable unset this resolves
// to the same '' it resolved to before. The VALUE is never committed and never
// printed; it is supplied by the deploy job's environment only.
param loomMsalClientSecret = readEnvironmentVariable('LOOM_MSAL_CLIENT_SECRET', '')

// =====================================================================
// DELIBERATELY INHERITED FROM main.bicep — stated so the posture is visible
// rather than accidental, since GCC now deploys apps and these flags start
// mattering. Each names what it resolves to and why that is the right answer
// for a boundary that runs on AZURE COMMERCIAL under an M365 GCC identity.
// =====================================================================
// appImageTags        -> main.bicep's default object, i.e. `v0.1` for EVERY app.
//   NOT overridden here on purpose. gcc-high/il5 override it with
//   `readEnvironmentVariable('LOOM_<X>_TAG','v0.1')` reads, and #3161 is what
//   that costs: a deploy step with those variables out of scope silently writes
//   the mutable default over a SHA-pinned app. main.bicep's default already
//   carries every key modules/admin-plane/main.bicep dereferences, and `v0.1`
//   is exactly what build-fiab-images-acr-tasks.yml stamps, so the tag contract
//   holds with no env surface to get out of sync.
// aasEnabled          -> true. Analysis Services IS available on Azure
//   Commercial; gcc-high/il5 pin it false because it is not available there.
//   deploy-fiab-gcc.yml already carries the #3948 AAS settle/re-suspend pair
//   for exactly this inherited true.
// azureMapsEnabled    -> true. azure-maps.bicep gates on
//   `boundary == Commercial || GCC`, so Maps is genuinely available here and
//   gcc-high/il5's false does not transfer.
// adxEnabled / aiFoundryEnabled / aiSearchEnabled / cosmosGraphVectorEnabled /
// vpnGatewayEnabled   -> true, matching gcc-high.
// atlasOnAksEnabled / copilotMafEnabled -> false, matching gcc-high.
//
// NEEDS AN OPERATOR VALUE — NOT decided here (see the PR body):
//   appGatewayEnabled     inherits FALSE; commercial-full, gcc-high, il5 and
//                         tenant-dmlz all set it TRUE. Cost-material (WAF_v2)
//                         and NOT required for public ingress, because Front
//                         Door originates on the CAE directly.
//   postgresQuotaAvailable inherits TRUE (Commercial's posture). gcc-high/il5
//                         hold it FALSE deliberately — see the long blast-radius
//                         note in gcc-high.bicepparam: it turns on the OSS
//                         Airflow metadata Postgres, whose image is an anonymous
//                         Docker Hub pull and whose network posture is
//                         publicNetworkAccess=Enabled + a 0.0.0.0 Azure-services
//                         firewall rule. That is an accepted documented carve-out
//                         in Commercial; whether it is acceptable in a CUI-low
//                         M365 GCC boundary is a compliance decision.
//   loomVersion           inherits main.bicep's '0.45.0' (the release-please
//                         manifest version); the siblings pin it via LOOM_VERSION.
