// CSA Loom — DoD IL5 parameters (Azure Government, IL5-accredited services only)
//
// Per the per-boundary dispatch matrix + v3 audit (2026-05). Differences vs
// GCC-High:
//
// - storageRequireCmk: true (IL5 mandates CMK)
// - keyVaultHsmIsolated: true (Premium HSM, isolated key pool)
// - frontDoorEnabled: false (Front Door not IL5-certified — use AGW only)
// - aiFoundryEnabled: false (Foundry Hub not certified IL5 yet — MAF + AOAI direct)
// - atlasOnAksEnabled: true (Atlas on AKS replaces Purview at IL5)
// - aiSearchEnabled: false (limited IL5 region surface)
//
// Storage CMK key URI: set via env `LOOM_STORAGE_CMK_KEY_URI` once provisioned
// in the IL5 Key Vault (out-of-band — wrapped by an HSM-isolated key).
// main.bicep will receive it through a future param; today storageRequireCmk
// triggers the CMK code path against a key resolved by the storage module.

using '../main.bicep'

// ---------- Bring-your-own existing services (reuse instead of provision-new) ----------
// Gov boundary: no Microsoft Fabric (fabricEnabled hard-false). Generate with:
//   bash scripts/csa-loom/byo-wizard.sh --boundary il5
// >>> BYO-WIZARD START (regenerated by scripts/csa-loom/byo-wizard.sh — edit env vars or re-run the wizard)
param existingAiSearchService    = readEnvironmentVariable('EXISTING_AI_SEARCH_SERVICE', '')
param existingAiSearchRg         = readEnvironmentVariable('EXISTING_AI_SEARCH_RG', '')
param existingAiSearchSub        = readEnvironmentVariable('EXISTING_AI_SEARCH_SUB', '')
param existingApimName           = readEnvironmentVariable('EXISTING_APIM', '')
param existingApimRg             = readEnvironmentVariable('EXISTING_APIM_RG', '')
param existingApimSub            = readEnvironmentVariable('EXISTING_APIM_SUB', '')
param existingAdxClusterName     = readEnvironmentVariable('EXISTING_KUSTO_CLUSTER', '')
param existingAdxClusterRg       = readEnvironmentVariable('EXISTING_KUSTO_RG', '')
param existingAdxClusterSub      = readEnvironmentVariable('EXISTING_KUSTO_SUB', '')
param existingFoundryAccountName = readEnvironmentVariable('EXISTING_AOAI', '')
param existingFoundryRg          = readEnvironmentVariable('EXISTING_AOAI_RG', '')
param existingFoundrySub         = readEnvironmentVariable('EXISTING_AOAI_SUB', '')
param existingFoundryChatDeployment  = readEnvironmentVariable('EXISTING_AOAI_CHAT_DEPLOYMENT', '')
param existingFoundryEmbedDeployment = readEnvironmentVariable('EXISTING_AOAI_EMBED_DEPLOYMENT', '')
param existingPurviewAccount     = readEnvironmentVariable('EXISTING_PURVIEW', '')
param existingPurviewRg          = readEnvironmentVariable('EXISTING_PURVIEW_RG', '')
param existingPurviewSub         = readEnvironmentVariable('EXISTING_PURVIEW_SUB', '')
param existingSynapseWorkspace   = readEnvironmentVariable('EXISTING_SYNAPSE', '')
param existingSynapseRg          = readEnvironmentVariable('EXISTING_SYNAPSE_RG', '')
param existingSynapseSub         = readEnvironmentVariable('EXISTING_SYNAPSE_SUB', '')
param existingCosmosAccount      = readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT', '')
param existingCosmosRg           = readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT_RG', '')
param existingCosmosSub          = readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT_SUB', '')
param existingEventHubNamespace  = readEnvironmentVariable('EXISTING_EVENTHUB_NAMESPACE', '')
param existingEventHubRg         = readEnvironmentVariable('EXISTING_EVENTHUB_RG', '')
param existingEventHubSub        = readEnvironmentVariable('EXISTING_EVENTHUB_SUB', '')
param existingAsaJob             = readEnvironmentVariable('EXISTING_ASA_JOB', '')
param existingAsaRg              = readEnvironmentVariable('EXISTING_ASA_RG', '')
param existingAsaSub             = readEnvironmentVariable('EXISTING_ASA_SUB', '')
param existingDatabricksWorkspace = readEnvironmentVariable('EXISTING_DATABRICKS', '')
param existingDatabricksRg       = readEnvironmentVariable('EXISTING_DATABRICKS_RG', '')
param existingDatabricksSub      = readEnvironmentVariable('EXISTING_DATABRICKS_SUB', '')
param existingDatabricksHostname = readEnvironmentVariable('EXISTING_DATABRICKS_HOSTNAME', '')
param fabricEnabled              = false
// <<< BYO-WIZARD END

param environment = 'AzureUSGovernment'
param location = 'usgovvirginia'
param boundary = 'IL5'
param loomAzureCloud = 'AzureUSGovernment'   // Console AZURE_CLOUD discriminator (IL5 runs on AzureUSGovernment endpoints)
param deploymentMode = 'multi-sub'
// audit-t157: tenant = first-run install (deploys the hub + DLZ). Add-landing-zone uses dlz-attach via the orchestrator, never this param file.
param topology = 'tenant'

// Compute (IL5 differences)
// containerApps: Microsoft.App (Azure Container Apps) is LIVE-verified GA in the
// USGov regions (US Gov Virginia / Arizona / Texas) this param targets (location
// below = usgovvirginia) — see docs/fiab/gov-parity-audit.md GOV-3. The prior
// 'aks' selection assumed ACA was unavailable in Gov; that assumption is
// superseded. IL5 workloads must confirm the ACA IL5 authorization scope for
// their accreditation; if AKS is required, flip this back to 'aks' and register
// the AKS EnableAPIServerVnetIntegrationPreview feature in the subscription.
param containerPlatform = 'containerApps' // ACA GA in USGov Virginia/Arizona/Texas (GOV-3)
param functionsHostSku = 'EP1'
param apimSku = 'Premium'

// Catalog (IL5)
param catalogPrimary = 'atlas-aks'        // Atlas on AKS — Purview Data Map not IL5-accredited

// AI orchestration (IL5)
param agentOrchestrator = 'maf'           // Foundry Agent Service NOT IL5
param foundryPortalEnabled = false
// MAF orchestration tier (loom-copilot-maf) — the Gov AOAI-direct copilot
// backend for boundaries with no AI Foundry Hub (IL5). It deploys as an Azure
// Container App. Now that this boundary runs on the Container Apps compute path
// (containerPlatform above — ACA is GA in the USGov regions, GOV-3), the MAF tier
// CAN activate here. It is kept FALSE as the conservative default: the Console
// copilot-orchestrator uses Gov AOAI-direct, which is the real, working backend
// at IL5, and enabling MAF requires the loom-copilot-maf image in ACR first.
// Flip to true (with the image pushed) to stand up the dedicated MAF tier. The
// flag is threaded through main.bicep (test_main_bicep_threads_copilot_maf_enabled);
// its activation gate additionally requires containerPlatform==containerApps +
// deployAppsEnabled. See docs/fiab/runbooks/il5-gcch-fullstack-verification.md (gap #2/#3).
param copilotMafEnabled = false

// Capacity sizing
param capacitySku = 'F8'

// Databricks (IL5: same Gov constraints as IL4)
param databricksUnityCatalogEnabled = false
param databricksSqlWarehouseEnabled = false

// Security (IL5 hardening)
param defenderForAIEnabled = false        // Sentinel pipeline
param purviewEnabled = false              // Atlas on AKS instead
param atlasOnAksEnabled = true
param storageRequireCmk = true            // IL5 mandated
param keyVaultHsmIsolated = true          // IL5 mandated
// CMK1 — Cosmos CMK-at-rest is likewise IL5-MANDATED, and rides the drConfig
// bag (256-param cap: never a new top-level param). It needs two estate-
// specific values that only exist once the IL5 Key Vault + UAMI are
// provisioned, so it cannot be hard-coded here — at deploy time pass:
//   drConfig={cosmosRequireCmk:true,
//             cosmosCmkKeyUri:'<VERSIONLESS https://<vault>.vault.usgovcloudapi.net/keys/<key>>',
//             cosmosCmkIdentityId:'<UAMI resource id w/ Key Vault Crypto Service Encryption User>'}
// (az deployment sub create … -p il5.bicepparam -p drConfig=@drconfig.json).
// Applies to the hub Console store + every DLZ state/graph/vector account; the
// svc-dr-restore-posture audit row then asserts it via live ARM
// (LOOM_COSMOS_REQUIRE_CMK=true).

// OpenAI (Gov endpoints + region constraints)
param openaiLocation = 'usgovvirginia'
param openaiEmbeddingsLocation = 'usgovarizona'
param openaiChatModel = 'gpt-4o'
// Deploy-readiness (opt-out): provision the dedicated AOAI account + gpt-4o chat
// + embedding deployments so Copilot / data-agents / AI-functions work on first
// login. Set false to skip (those surfaces then honest-gate). In Gov boundaries
// the model/version may be pinned via foundry-project.bicep params if a region
// lacks gpt-4o GlobalStandard.
param agentFoundryEnabled = true
param openaiEmbeddingsModel = 'text-embedding-3-large'

// Power BI
param powerBiSku = 'F64'

// Azure Maps — NOT available in IL5. azure-maps.bicep already gates on
// boundary == Commercial || GCC, so this is documentary; the geo-map / map
// editors render their honest-gate MessageBars here.
param azureMapsEnabled = false

// Network
param hubVnetCidr = '10.0.0.0/16'

// Identity (Gov tenant)
param adminEntraGroupId = readEnvironmentVariable('LOOM_ADMIN_ENTRA_GROUP_ID', '')

// Loom version + image tags
param loomVersion = readEnvironmentVariable('LOOM_VERSION', 'v3.0')
param appImageTags = {
  console: readEnvironmentVariable('LOOM_CONSOLE_TAG', 'v3.0')
  mcp: readEnvironmentVariable('LOOM_MCP_TAG', 'v0.7')
  orchestrator: readEnvironmentVariable('LOOM_ORCHESTRATOR_TAG', 'v0.7')
  activator: readEnvironmentVariable('LOOM_ACTIVATOR_TAG', 'v0.7')
  mirroring: readEnvironmentVariable('LOOM_MIRRORING_TAG', 'v0.7')
  directLake: readEnvironmentVariable('LOOM_DIRECTLAKE_TAG', 'v0.7')
}

// MSAL — IL5 tenant client id+secret via env (don't commit)
param loomMsalClientId = readEnvironmentVariable('LOOM_MSAL_CLIENT_ID', '')
param loomMsalClientSecret = readEnvironmentVariable('LOOM_MSAL_CLIENT_SECRET', '')

// Multi-sub
param dlzSubscriptionIds = []
param dlzDomainNames = []

// Feature flags — IL5 has TIGHTER edge surface
//   - Front Door: NOT IL5-certified → false. Use AGW WAF only.
//   - AI Foundry: not IL5 yet → false.
//   - AI Search: limited IL5 region surface → false.
param deployAppsEnabled = true
param aiFoundryEnabled = false
// Azure AI Content Safety is NOT offered in the DoD regions (US DoD Central /
// US DoD East) per the Microsoft Learn region matrix. Leave off — the Console
// honest-gates the copilot moderation pipeline with a warning MessageBar
// (prompts pass unfiltered, never a silent claim of filtering).
param contentSafetyEnabled = false
param apimEnabled = true
param hubFirewallEnabled = true
param aiSearchEnabled = false
// Azure Analysis Services is NOT available in the DoD regions — pin OFF (main.bicep
// now defaults aasEnabled=true for Commercial day-one). The semantic-model surfaces
// fall back to Synapse-Serverless / Loom-native here per the documented boundary.
param aasEnabled = false
param adxEnabled = true
// RTI backends — Event Hubs + Stream Analytics ON by default (opt-out). Entra-
// only auth (the only IL5-allowed posture). Set the env var to 'false' to skip,
// or reuse an existing namespace/job via the EXISTING_* vars above.
param loomEventHubEnabled = bool(readEnvironmentVariable('LOOM_EVENTHUB_ENABLED', 'true'))
param loomStreamAnalyticsEnabled = bool(readEnvironmentVariable('LOOM_STREAM_ANALYTICS_ENABLED', 'true'))
// no-op here (containerPlatform=='aks' fails the setupOrchestratorActive gate); on
// AKS the orchestrator runs via the cluster GitOps path as the same Console UAMI.
param setupOrchestratorEnabled = bool(readEnvironmentVariable('LOOM_SETUP_ORCHESTRATOR_ENABLED', 'true'))
param setupTemplateUri = readEnvironmentVariable('LOOM_SETUP_TEMPLATE_URI', '')
// Gremlin (graph editor) + NoSQL vector. Gov suffix gremlin.cosmos.azure.us
// is selected automatically from boundary='IL5'.
param cosmosGraphVectorEnabled = true
param vpnGatewayEnabled = true
param appGatewayEnabled = true
param frontDoorEnabled = false

// Tags
param complianceTags = {
  Environment: 'IL5'
  CSA_Loom: 'true'
  FedRAMP_Level: 'High'
  DISA_IL: 'IL5'
  Data_Classification: 'CUI-SP'
  M365_Boundary: 'IL5'
}

// =====================================================================
// Data-engineering backends — ON by default (opt-out). Set any to false to
// skip that provision; the console editor then honest-gates (LOOM_* env blanked)
// instead of 502-ing. See docs/fiab/prp/deploy-readiness-100pct.md.
// =====================================================================
param loomSynapseEnabled = true
param loomDatabricksEnabled = true
param loomDataFactoryEnabled = true
param loomSelfHostedIrEnabled = true
