// CSA Loom — DoD IL5 parameters (Azure Government, IL5-accredited services only)
//
// Per the per-boundary dispatch matrix + v3 audit (2026-05). Differences vs
// GCC-High:
//
// - storageRequireCmk: true (IL5 mandates CMK)
// - keyVaultHsmIsolated: true (Premium HSM, isolated key pool)
// - frontDoorEnabled: false (Front Door not IL5-certified — use AGW only)
// - aiFoundryEnabled: false (Foundry Hub not certified IL5 yet — MAF + AOAI direct)
// - atlasOnAksEnabled: true (Atlas on AKS replaces Purview at IL5)
// - aiSearchEnabled: false (limited IL5 region surface)
//
// Storage CMK key URI: set via env `LOOM_STORAGE_CMK_KEY_URI` once provisioned
// in the IL5 Key Vault (out-of-band — wrapped by an HSM-isolated key).
// main.bicep will receive it through a future param; today storageRequireCmk
// triggers the CMK code path against a key resolved by the storage module.

using '../main.bicep'

// ---------- Bring-your-own existing services (reuse instead of provision-new) ----------
// Gov boundary: no Microsoft Fabric (fabricEnabled hard-false). Generate with:
//   bash scripts/csa-loom/byo-wizard.sh --boundary il5
// >>> BYO-WIZARD START (regenerated by scripts/csa-loom/byo-wizard.sh — edit env vars or re-run the wizard)
param existingAiSearchService    = readEnvironmentVariable('EXISTING_AI_SEARCH_SERVICE', '')
param existingAiSearchRg         = readEnvironmentVariable('EXISTING_AI_SEARCH_RG', '')
param existingAiSearchSub        = readEnvironmentVariable('EXISTING_AI_SEARCH_SUB', '')
param existingApimName           = readEnvironmentVariable('EXISTING_APIM', '')
param existingApimRg             = readEnvironmentVariable('EXISTING_APIM_RG', '')
param existingApimSub            = readEnvironmentVariable('EXISTING_APIM_SUB', '')
param existingAdxClusterName     = readEnvironmentVariable('EXISTING_KUSTO_CLUSTER', '')
param existingAdxClusterRg       = readEnvironmentVariable('EXISTING_KUSTO_RG', '')
param existingAdxClusterSub      = readEnvironmentVariable('EXISTING_KUSTO_SUB', '')
param existingFoundryAccountName = readEnvironmentVariable('EXISTING_AOAI', '')
param existingFoundryRg          = readEnvironmentVariable('EXISTING_AOAI_RG', '')
param existingFoundrySub         = readEnvironmentVariable('EXISTING_AOAI_SUB', '')
param existingPurviewAccount     = readEnvironmentVariable('EXISTING_PURVIEW', '')
param existingPurviewRg          = readEnvironmentVariable('EXISTING_PURVIEW_RG', '')
param existingPurviewSub         = readEnvironmentVariable('EXISTING_PURVIEW_SUB', '')
param existingSynapseWorkspace   = readEnvironmentVariable('EXISTING_SYNAPSE', '')
param existingSynapseRg          = readEnvironmentVariable('EXISTING_SYNAPSE_RG', '')
param existingSynapseSub         = readEnvironmentVariable('EXISTING_SYNAPSE_SUB', '')
param existingCosmosAccount      = readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT', '')
param existingCosmosRg           = readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT_RG', '')
param existingCosmosSub          = readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT_SUB', '')
param existingEventHubNamespace  = readEnvironmentVariable('EXISTING_EVENTHUB_NAMESPACE', '')
param existingEventHubRg         = readEnvironmentVariable('EXISTING_EVENTHUB_RG', '')
param existingEventHubSub        = readEnvironmentVariable('EXISTING_EVENTHUB_SUB', '')
param existingDatabricksWorkspace = readEnvironmentVariable('EXISTING_DATABRICKS', '')
param existingDatabricksRg       = readEnvironmentVariable('EXISTING_DATABRICKS_RG', '')
param existingDatabricksSub      = readEnvironmentVariable('EXISTING_DATABRICKS_SUB', '')
param existingDatabricksHostname = readEnvironmentVariable('EXISTING_DATABRICKS_HOSTNAME', '')
// Adopt-existing shared services (D6 Setup-Wizard discovery): LAW / Key Vault / gateway.
param existingLogAnalyticsWorkspace = readEnvironmentVariable('EXISTING_LAW', '')
param existingLogAnalyticsRg      = readEnvironmentVariable('EXISTING_LAW_RG', '')
param existingLogAnalyticsSub     = readEnvironmentVariable('EXISTING_LAW_SUB', '')
param existingKeyVaultName        = readEnvironmentVariable('EXISTING_KEYVAULT', '')
param existingKeyVaultRg          = readEnvironmentVariable('EXISTING_KEYVAULT_RG', '')
param existingKeyVaultSub         = readEnvironmentVariable('EXISTING_KEYVAULT_SUB', '')
param existingGatewayName         = readEnvironmentVariable('EXISTING_GATEWAY', '')
param existingGatewayRg           = readEnvironmentVariable('EXISTING_GATEWAY_RG', '')
param existingGatewaySub          = readEnvironmentVariable('EXISTING_GATEWAY_SUB', '')
param fabricEnabled              = false
// <<< BYO-WIZARD END

param environment = 'AzureUSGovernment'
param location = 'usgovvirginia'
param boundary = 'IL5'
param loomAzureCloud = 'AzureUSGovernment'   // Console AZURE_CLOUD discriminator (IL5 runs on AzureUSGovernment endpoints)
param deploymentMode = 'multi-sub'

// Compute (IL5 differences)
param containerPlatform = 'aks'
param functionsHostSku = 'EP1'
param apimSku = 'Premium'

// Catalog (IL5)
param catalogPrimary = 'atlas-aks'        // Atlas on AKS — Purview Data Map not IL5-accredited

// AI orchestration (IL5)
param agentOrchestrator = 'maf'           // Foundry Agent Service NOT IL5
param foundryPortalEnabled = false
// MAF orchestration tier (loom-copilot-maf) — the Gov AOAI-direct copilot
// backend for boundaries with no AI Foundry Hub (IL5). It deploys as an Azure
// Container App. Per the Microsoft Learn Azure Government services-by-audit-
// scope table (last updated Feb 2026), Azure Container Apps is authorized only
// at FedRAMP High / DoD IL2 — NOT at DoD IL4 or IL5. IL5 therefore runs on the
// AKS compute path (containerPlatform below), where the MAF Container App
// cannot deploy. This flag is set FALSE accordingly: the Console copilot-
// orchestrator uses Gov AOAI-direct, which is the real, working backend at IL5.
// Setting it true here would advertise a tier that can never activate on this
// compute platform (a silent no-op), so it is honestly false. The flag is still
// threaded through main.bicep (test_main_bicep_threads_copilot_maf_enabled) so
// the tier activates automatically once an AKS-workload deployment for the apps
// exists. See docs/fiab/runbooks/il5-gcch-fullstack-verification.md (gap #2/#3).
param copilotMafEnabled = false

// Capacity sizing
param capacitySku = 'F8'

// Databricks (IL5: same Gov constraints as IL4)
param databricksUnityCatalogEnabled = false
param databricksSqlWarehouseEnabled = false

// Security (IL5 hardening)
param defenderForAIEnabled = false        // Sentinel pipeline
param purviewEnabled = false              // Atlas on AKS instead
param atlasOnAksEnabled = true
param storageRequireCmk = true            // IL5 mandated
param keyVaultHsmIsolated = true          // IL5 mandated

// OpenAI (Gov endpoints + region constraints)
param openaiLocation = 'usgovvirginia'
param openaiEmbeddingsLocation = 'usgovarizona'
param openaiChatModel = 'gpt-4o'
param openaiEmbeddingsModel = 'text-embedding-3-large'

// Power BI
param powerBiSku = 'F64'

// Azure Maps — NOT available in IL5. azure-maps.bicep already gates on
// boundary == Commercial || GCC, so this is documentary; the geo-map / map
// editors render their honest-gate MessageBars here.
param azureMapsEnabled = false

// Network
param hubVnetCidr = '10.0.0.0/16'

// Identity (Gov tenant)
param adminEntraGroupId = '<replace-with-IL5-tenant-FiaB-Admins-group-guid>'

// Loom version + image tags
param loomVersion = readEnvironmentVariable('LOOM_VERSION', 'v3.0')
param appImageTags = {
  console: readEnvironmentVariable('LOOM_CONSOLE_TAG', 'v3.0')
  mcp: readEnvironmentVariable('LOOM_MCP_TAG', 'v0.7')
  orchestrator: readEnvironmentVariable('LOOM_ORCHESTRATOR_TAG', 'v0.7')
  activator: readEnvironmentVariable('LOOM_ACTIVATOR_TAG', 'v0.7')
  mirroring: readEnvironmentVariable('LOOM_MIRRORING_TAG', 'v0.7')
  directLake: readEnvironmentVariable('LOOM_DIRECTLAKE_TAG', 'v0.7')
}

// MSAL — IL5 tenant client id+secret via env (don't commit)
param loomMsalClientId = readEnvironmentVariable('LOOM_MSAL_CLIENT_ID', '')
param loomMsalClientSecret = readEnvironmentVariable('LOOM_MSAL_CLIENT_SECRET', '')

// Multi-sub
param dlzSubscriptionIds = []
param dlzDomainNames = []

// Feature flags — IL5 has TIGHTER edge surface
//   - Front Door: NOT IL5-certified → false. Use AGW WAF only.
//   - AI Foundry: not IL5 yet → false.
//   - AI Search: limited IL5 region surface → false.
param deployAppsEnabled = true
param aiFoundryEnabled = false
// Azure AI Content Safety is NOT offered in the DoD regions (US DoD Central /
// US DoD East) per the Microsoft Learn region matrix. Leave off — the Console
// honest-gates the copilot moderation pipeline with a warning MessageBar
// (prompts pass unfiltered, never a silent claim of filtering).
param contentSafetyEnabled = false
param apimEnabled = true
param aiSearchEnabled = false
param adxEnabled = true
// Gremlin (graph editor) + NoSQL vector. Gov suffix gremlin.cosmos.azure.us
// is selected automatically from boundary='IL5'.
param cosmosGraphVectorEnabled = true
param vpnGatewayEnabled = true
param appGatewayEnabled = true
param frontDoorEnabled = false

// Tags
param complianceTags = {
  Environment: 'IL5'
  CSA_Loom: 'true'
  FedRAMP_Level: 'High'
  DISA_IL: 'IL5'
  Data_Classification: 'CUI-SP'
  M365_Boundary: 'IL5'
}
