// CSA Loom — DoD IL5 parameters (Azure Government, IL5-accredited services only)
//
// Per the per-boundary dispatch matrix + v3 audit (2026-05). Differences vs
// GCC-High:
//
// - storageRequireCmk: true (IL5 mandates CMK)
// - keyVaultHsmIsolated: true (Premium HSM, isolated key pool)
// - frontDoorEnabled: false (Front Door not IL5-certified — use AGW only)
// - aiFoundryEnabled: false (Foundry Hub not certified IL5 yet — MAF + AOAI direct)
// - atlasOnAksEnabled: true (Atlas on AKS replaces Purview at IL5)
// - aiSearchEnabled: false (limited IL5 region surface)
//
// Storage CMK key URI: set via env `LOOM_STORAGE_CMK_KEY_URI` once provisioned
// in the IL5 Key Vault (out-of-band — wrapped by an HSM-isolated key).
// main.bicep will receive it through a future param; today storageRequireCmk
// triggers the CMK code path against a key resolved by the storage module.

using '../main.bicep'

// ---------- Bring-your-own existing services (reuse instead of provision-new) ----------
// Gov boundary: no Microsoft Fabric (fabricEnabled hard-false). Generate with:
//   bash scripts/csa-loom/byo-wizard.sh --boundary il5
// >>> BYO-WIZARD START (regenerated by scripts/csa-loom/byo-wizard.sh — edit env vars or re-run the wizard)
// ---------- ADOPT-OR-CREATE plan (replaces the per-service EXISTING_* params) ----------
// main.bicep no longer declares 36 `existing*` scalars; it declares ONE `adopt`
// object keyed by the service key in apps/fiab-console/lib/deploy/adoption-catalog.ts.
// That is what freed the ARM parameter budget (251 -> 216 of 256) so networking,
// storage, Log Analytics and ACR adoption become possible at all.
//
// TWO input paths, and the explicit plan always wins:
//
//   1. LOOM_ADOPT_JSON - the whole plan as one JSON document, emitted by
//      `planToArmParameters()` (apps/fiab-console/lib/deploy/plan-to-arm.ts).
//      This is the first-class path every deploy tier uses.
//   2. The legacy per-service EXISTING_* environment variables below, kept
//      working verbatim so byo-wizard.sh / scan-and-deploy.sh / a hand-exported
//      shell keep behaving exactly as before.
//
// `union(legacy, plan)` means a service present in BOTH resolves to the plan's
// decision. A service in NEITHER is absent from the object, and main.bicep's
// `adoptMode()` defaults an absent key to 'create' - so an empty environment
// still produces a complete greenfield deployment.
//
// NOTE: setting an EXISTING_* name now also SUPPRESSES the matching new resource
// (main.bicep's provision<Service> vars). Previously several services - Purview,
// Maps, Foundry, Synapse, Databricks, ADF - rebound the Console env to the
// existing resource while STILL deploying a duplicate beside it.
var legacyAdoptFromEnv = union(
  empty(readEnvironmentVariable('EXISTING_AI_SEARCH_SERVICE', '')) ? {} : { aisearch: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_AI_SEARCH_SERVICE', ''), rg: readEnvironmentVariable('EXISTING_AI_SEARCH_RG', ''), sub: readEnvironmentVariable('EXISTING_AI_SEARCH_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_APIM', '')) ? {} : { apim: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_APIM', ''), rg: readEnvironmentVariable('EXISTING_APIM_RG', ''), sub: readEnvironmentVariable('EXISTING_APIM_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_KUSTO_CLUSTER', '')) ? {} : { adx: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_KUSTO_CLUSTER', ''), rg: readEnvironmentVariable('EXISTING_KUSTO_RG', ''), sub: readEnvironmentVariable('EXISTING_KUSTO_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_AOAI', '')) ? {} : { foundry: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_AOAI', ''), rg: readEnvironmentVariable('EXISTING_AOAI_RG', ''), sub: readEnvironmentVariable('EXISTING_AOAI_SUB', '') }, extra: { chatDeployment: readEnvironmentVariable('EXISTING_AOAI_CHAT_DEPLOYMENT', ''), embedDeployment: readEnvironmentVariable('EXISTING_AOAI_EMBED_DEPLOYMENT', ''), miniDeployment: readEnvironmentVariable('EXISTING_AOAI_MINI_DEPLOYMENT', ''), strongDeployment: readEnvironmentVariable('EXISTING_AOAI_STRONG_DEPLOYMENT', '') } } },
  empty(readEnvironmentVariable('EXISTING_PURVIEW', '')) ? {} : { purview: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_PURVIEW', ''), rg: readEnvironmentVariable('EXISTING_PURVIEW_RG', ''), sub: readEnvironmentVariable('EXISTING_PURVIEW_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_SYNAPSE', '')) ? {} : { synapse: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_SYNAPSE', ''), rg: readEnvironmentVariable('EXISTING_SYNAPSE_RG', ''), sub: readEnvironmentVariable('EXISTING_SYNAPSE_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT', '')) ? {} : { cosmos: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT', ''), rg: readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT_RG', ''), sub: readEnvironmentVariable('EXISTING_COSMOS_ACCOUNT_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_EVENTHUB_NAMESPACE', '')) ? {} : { eventhubs: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_EVENTHUB_NAMESPACE', ''), rg: readEnvironmentVariable('EXISTING_EVENTHUB_RG', ''), sub: readEnvironmentVariable('EXISTING_EVENTHUB_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_ASA_JOB', '')) ? {} : { streamanalytics: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_ASA_JOB', ''), rg: readEnvironmentVariable('EXISTING_ASA_RG', ''), sub: readEnvironmentVariable('EXISTING_ASA_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_DATABRICKS', '')) ? {} : { databricks: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_DATABRICKS', ''), rg: readEnvironmentVariable('EXISTING_DATABRICKS_RG', ''), sub: readEnvironmentVariable('EXISTING_DATABRICKS_SUB', '') }, extra: { hostname: readEnvironmentVariable('EXISTING_DATABRICKS_HOSTNAME', '') } } },
  empty(readEnvironmentVariable('EXISTING_ADF', '')) ? {} : { adf: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_ADF', ''), rg: readEnvironmentVariable('EXISTING_ADF_RG', ''), sub: readEnvironmentVariable('EXISTING_ADF_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_AZURE_MAPS_ACCOUNT', '')) ? {} : { maps: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_AZURE_MAPS_ACCOUNT', ''), rg: readEnvironmentVariable('EXISTING_AZURE_MAPS_RG', ''), sub: readEnvironmentVariable('EXISTING_AZURE_MAPS_SUB', '') } } },
  empty(readEnvironmentVariable('EXISTING_AML_WORKSPACE', '')) ? {} : { aml: { mode: 'adopt', target: { name: readEnvironmentVariable('EXISTING_AML_WORKSPACE', ''), rg: readEnvironmentVariable('EXISTING_AML_RG', ''), sub: readEnvironmentVariable('EXISTING_AML_SUB', '') } } }
)
param adopt = union(legacyAdoptFromEnv, json(readEnvironmentVariable('LOOM_ADOPT_JSON', '{}')))
param fabricEnabled              = false
// <<< BYO-WIZARD END

param environment = 'AzureUSGovernment'
param location = 'usgovvirginia'
param boundary = 'IL5'
param loomAzureCloud = 'AzureUSGovernment'   // Console AZURE_CLOUD discriminator (IL5 runs on AzureUSGovernment endpoints)
param deploymentMode = 'multi-sub'
// audit-t157: tenant = first-run install (deploys the hub + DLZ). Add-landing-zone uses dlz-attach via the orchestrator, never this param file.
param topology = 'tenant'

// Compute (IL5 differences)
// containerApps: Microsoft.App (Azure Container Apps) is LIVE-verified GA in the
// USGov regions (US Gov Virginia / Arizona / Texas) this param targets (location
// below = usgovvirginia) — see docs/fiab/gov-parity-audit.md GOV-3. The prior
// 'aks' selection assumed ACA was unavailable in Gov; that assumption is
// superseded. IL5 workloads must confirm the ACA IL5 authorization scope for
// their accreditation; if AKS is required, flip this back to 'aks' and register
// the AKS EnableAPIServerVnetIntegrationPreview feature in the subscription.
param containerPlatform = 'containerApps' // ACA GA in USGov Virginia/Arizona/Texas (GOV-3)
param functionsHostSku = 'EP1'
param apimSku = 'Premium'

// Catalog (IL5)
param catalogPrimary = 'atlas-aks'        // Atlas on AKS — Purview Data Map not IL5-accredited

// AI orchestration (IL5)
param agentOrchestrator = 'maf'           // Foundry Agent Service NOT IL5
param foundryPortalEnabled = false
// MAF orchestration tier (loom-copilot-maf) — the Gov AOAI-direct copilot
// backend for boundaries with no AI Foundry Hub (IL5). It deploys as an Azure
// Container App. Now that this boundary runs on the Container Apps compute path
// (containerPlatform above — ACA is GA in the USGov regions, GOV-3), the MAF tier
// CAN activate here. It is kept FALSE as the conservative default: the Console
// copilot-orchestrator uses Gov AOAI-direct, which is the real, working backend
// at IL5, and enabling MAF requires the loom-copilot-maf image in ACR first.
// Flip to true (with the image pushed) to stand up the dedicated MAF tier. The
// flag is threaded through main.bicep (test_main_bicep_threads_copilot_maf_enabled);
// its activation gate additionally requires containerPlatform==containerApps +
// deployAppsEnabled. See docs/fiab/runbooks/il5-gcch-fullstack-verification.md (gap #2/#3).
param copilotMafEnabled = false

// Capacity sizing
param capacitySku = 'F8'

// Databricks (IL5: same Gov constraints as IL4)
param databricksUnityCatalogEnabled = false
param databricksSqlWarehouseEnabled = false

// Security (IL5 hardening)
param defenderForAIEnabled = false        // Sentinel pipeline
param purviewEnabled = false              // Atlas on AKS instead
param atlasOnAksEnabled = true
param storageRequireCmk = true            // IL5 mandated
param keyVaultHsmIsolated = true          // IL5 mandated
// CMK1 — Cosmos CMK-at-rest is likewise IL5-MANDATED, and rides the drConfig
// bag (256-param cap: never a new top-level param). It needs two estate-
// specific values that only exist once the IL5 Key Vault + UAMI are
// provisioned, so it cannot be hard-coded here — at deploy time pass:
//   drConfig={cosmosRequireCmk:true,
//             cosmosCmkKeyUri:'<VERSIONLESS https://<vault>.vault.usgovcloudapi.net/keys/<key>>',
//             cosmosCmkIdentityId:'<UAMI resource id w/ Key Vault Crypto Service Encryption User>'}
// (az deployment sub create … -p il5.bicepparam -p drConfig=@drconfig.json).
// Applies to the hub Console store + every DLZ state/graph/vector account; the
// svc-dr-restore-posture audit row then asserts it via live ARM
// (LOOM_COSMOS_REQUIRE_CMK=true).

// OpenAI (Gov endpoints + region constraints)
param openaiLocation = 'usgovvirginia'
param openaiEmbeddingsLocation = 'usgovarizona'
param openaiChatModel = 'gpt-4o'
// Deploy-readiness (opt-out): provision the dedicated AOAI account + gpt-4o chat
// + embedding deployments so Copilot / data-agents / AI-functions work on first
// login. Set false to skip (those surfaces then honest-gate). In Gov boundaries
// the model/version may be pinned via foundry-project.bicep params if a region
// lacks gpt-4o GlobalStandard.
param agentFoundryEnabled = true
param openaiEmbeddingsModel = 'text-embedding-3-large'

// Power BI
param powerBiSku = 'F64'

// Azure Maps — NOT available in IL5. azure-maps.bicep already gates on
// boundary == Commercial || GCC, so this is documentary; the geo-map / map
// editors render their honest-gate MessageBars here.
param azureMapsEnabled = false

// Network
param hubVnetCidr = '10.0.0.0/16'

// Identity (Gov tenant)
param adminEntraGroupId = readEnvironmentVariable('LOOM_ADMIN_ENTRA_GROUP_ID', '')

// Loom version + image tags
param loomVersion = readEnvironmentVariable('LOOM_VERSION', 'v3.0')
param appImageTags = {
  console: readEnvironmentVariable('LOOM_CONSOLE_TAG', 'v3.0')
  mcp: readEnvironmentVariable('LOOM_MCP_TAG', 'v0.7')
  orchestrator: readEnvironmentVariable('LOOM_ORCHESTRATOR_TAG', 'v0.7')
  activator: readEnvironmentVariable('LOOM_ACTIVATOR_TAG', 'v0.7')
  mirroring: readEnvironmentVariable('LOOM_MIRRORING_TAG', 'v0.7')
  directLake: readEnvironmentVariable('LOOM_DIRECTLAKE_TAG', 'v0.7')
  // ── THESE KEYS MUST BE PRESENT (cloud-parity blocker, measured 2026-08-06) ──
  // A .bicepparam object assignment REPLACES the template default, it does not
  // merge with it. admin-plane/main.bicep dereferences these five with a PLAIN
  // `.` (no `.?` safe-access):
  //   appImageTags.mcpBridge        — inside the `apps` array literal that is
  //                                   passed as a parameter to the
  //                                   `appDeployments` nested deployment, whose
  //                                   condition is
  //                                   and(containerPlatform=='containerApps',
  //                                       deployAppsEnabled).
  //                                   (An earlier revision called this array
  //                                   "UNCONDITIONAL … evaluated on EVERY deploy
  //                                   regardless of any module condition". That
  //                                   was wrong: it is unconditional only
  //                                   *within* appDeployments, which is itself
  //                                   gated. Corrected 2026-08-07.)
  //   appImageTags.maf              — copilot/maf.bicep call site
  //   appImageTags.setupOrchestrator— setup-orchestrator.bicep call site
  //   appImageTags.scriptRunner     — script-runner-app.bicep call site
  //   appImageTags.wrangler         — integration/wrangler.bicep call site
  // Omitting them fails template EVALUATION ("property 'mcpBridge' doesn't
  // exist") and aborts the whole nested deployment before a single resource is
  // touched.
  //
  // SEVERITY FOR *THIS* FILE (corrected 2026-08-07): **would abort on IL5's
  // first apps-enabled deploy; never empirically observed, because
  // .github/workflows/deploy-fiab-il5.yml has NEVER RUN (zero runs, measured
  // 2026-08-07).** All five derefs are gated on `deployAppsEnabled`
  // (appDeployments' condition; admin-plane L688/691/724/740). This file
  // declares `param deployAppsEnabled = true` below and deploy-fiab-il5.yml
  // passes NO override — so unlike commercial-full, whose every caller sets it
  // false, nothing here disables the app tier. GCC-High carries the keys and so
  // was never exposed. An earlier revision said "the IL5 boundary could not
  // deploy at all"; that overstated an untested lane as an observed failure, and
  // deploy-integrity R7 forbids asserting a cause the code did not establish.
  // params/gcc-high.bicepparam has documented this hazard since PR #2640;
  // this file never picked the keys up.
  // script-runner + wrangler are boundary-gated OFF here, so their tags are
  // placeholders that are never pulled — they still have to EXIST.
  mcpBridge: readEnvironmentVariable('LOOM_MCP_BRIDGE_TAG', 'v0.1')
  setupOrchestrator: readEnvironmentVariable('LOOM_SETUP_ORCHESTRATOR_TAG', 'v0.1')
  maf: readEnvironmentVariable('LOOM_MAF_TAG', 'v0.1')
  scriptRunner: readEnvironmentVariable('LOOM_SCRIPT_RUNNER_TAG', 'v0.1')
  wrangler: readEnvironmentVariable('LOOM_WRANGLER_TAG', 'v0.1')
  // loom-duckdb — the N2b/N3 DuckDB serving tier admin-plane/main.bicep now
  // deploys BY DEFAULT (duckdbTierActive). STATED EXPLICITLY rather than left to
  // the module's `?? 'v0.1'` fallback because this is the tag the IL5 TEMPLATE
  // pulls, and it has to match what the IL5 producer stamps:
  //   producer .github/workflows/gov-provision-dataplane-images.yml
  //            boundary=il5, image_tag default v0.1 -> az acr build --image loom-duckdb:v0.1
  //   template <acr>/loom-duckdb:v0.1
  // Round 2 had the producer stamp only the short SHA + `latest` while the
  // template asked for v0.1 — a tag nothing produced. Override BOTH or neither.
  // .github/workflows/deploy-fiab-il5.yml image-preflights this tag before it
  // deploys over a live estate.
  duckdb: readEnvironmentVariable('LOOM_DUCKDB_TAG', 'v0.1')
  // loom-migrate (M1 estate-assessment reader) + loom-risingwave (N7a stateful
  // streaming-SQL tier) are DEFAULT-ON in EVERY Container Apps boundary as of
  // 2026-07-28. IL5 sets containerPlatform='containerApps' (L76) and
  // deployAppsEnabled=true (below), so admin-plane/main.bicep DOES deploy both
  // here and DOES pull these tags. A .bicepparam assignment REPLACES the object
  // (it does not merge with the template default), so omitting these keys left
  // the tag pinned to the `?? 'v0.1'` fallback with no operator lever at all.
  //
  // Both images MUST be in the IL5 ACR before an apps-enabled deploy — same
  // precondition as loom-console. Build them SERVER-SIDE with
  // .github/workflows/build-fiab-images-acr-tasks.yml (boundary=IL5) or, for
  // just these two, gov-provision-streaming-migrate.yml (boundary=IL5,
  // mode=build-only). NOT build-fiab-images.yml — that workflow authenticates
  // with the Commercial SP and pushes client-side, so it cannot reach a
  // sovereign publicNetworkAccess=Disabled registry (it now hard-fails if
  // dispatched with a Gov boundary rather than silently no-op'ing).
  loomMigrate: readEnvironmentVariable('LOOM_MIGRATE_TAG', 'v0.1')
  risingwave: readEnvironmentVariable('LOOM_RISINGWAVE_TAG', 'v0.1')
  // loom-unity (#2681) — the Unity-Catalog-compatible OSS metastore.
  // admin-plane/main.bicep now deploys it DEFAULT-ON on every boundary (it was
  // an out-of-band standalone entrypoint before), so this image is a hard
  // prerequisite of the apps phase — a missing manifest fails the Container App
  // PUT with MANIFEST_UNKNOWN, not just the feature.
  unity: readEnvironmentVariable('LOOM_UNITY_TAG', 'v0.1')
  // loom-trino (N7e) — the DEFAULT-ON Federated SQL engine. Together with the
  // Iceberg REST Catalog (which runs the loom-unity image above) this IS the
  // external-engine federation product for a boundary with no Databricks Unity
  // Catalog, so the tag contract matters here more than in Commercial:
  //   producer .github/workflows/gov-provision-dataplane-images.yml
  //            image_tag input, default v0.1 -> az acr build --image loom-trino:v0.1
  //   template <acr>/loom-trino:v0.1  (admin-plane reads appImageTags.?trino ?? 'v0.1')
  // Stated explicitly so the tag is operator-settable per boundary instead of
  // being pinned by a fallback with no lever, exactly like duckdb/unity above.
  trino: readEnvironmentVariable('LOOM_TRINO_TAG', 'v0.1')
}

// MSAL — IL5 tenant client id+secret via env (don't commit)
param loomMsalClientId = readEnvironmentVariable('LOOM_MSAL_CLIENT_ID', '')
param loomMsalClientSecret = readEnvironmentVariable('LOOM_MSAL_CLIENT_SECRET', '')

// Multi-sub
param dlzSubscriptionIds = []
param dlzDomainNames = []

// Feature flags — IL5 has TIGHTER edge surface
//   - Front Door: NOT IL5-certified → false. Use AGW WAF only.
//   - AI Foundry: not IL5 yet → false.
//   - AI Search: limited IL5 region surface → false.
param deployAppsEnabled = true
param aiFoundryEnabled = false
// Azure AI Content Safety is NOT offered in the DoD regions (US DoD Central /
// US DoD East) per the Microsoft Learn region matrix. Leave off — the Console
// honest-gates the copilot moderation pipeline with a warning MessageBar
// (prompts pass unfiltered, never a silent claim of filtering).
param contentSafetyEnabled = false
param apimEnabled = true

// Postgres-backed day-one services (OSS Airflow metadata DB + the N8 DuckLake
// catalog store). Azure Database for PostgreSQL Flexible Server IS an Azure
// Government service — Microsoft Learn lists US Gov Virginia / Arizona / Texas
// as supported regions (https://learn.microsoft.com/azure/postgresql/overview#azure-regions),
// and the Gov comparison page records NO Flexible Server feature gaps beyond
// Cosmos DB for PostgreSQL and Single Server extras
// (https://learn.microsoft.com/azure/azure-government/compare-azure-government-global-azure#databases).
// So `false` is not a service gap; it is a DELIBERATE, reviewable IL5 posture
// stated here rather than inherited.
//
// ROUND-4: kept OFF in this PR. `postgresQuotaAvailable` gates TWO hosts, and
// turning it on would bring the OSS Airflow host into IL5 with (1) an anonymous
// `apache/airflow:2.10.5-python3.12` DOCKER HUB pull that nothing mirrors into
// the IL5 ACR (unpullable in a locked-egress boundary, unscanned on the way in),
// and (2) a metadata Postgres created with `publicNetworkAccess: 'Enabled'` and a
// `0.0.0.0` AllowAllAzureServices firewall rule (admin-plane passes
// `privateEndpointsEnabled: false`). Neither belongs in an IL5 boundary as a side
// effect of a DuckLake change. Both are handled by the follow-up that mirrors
// upstream images into each cloud's ACR and adds the private endpoint; flip this
// true there.
//
// Consequence: the N8 DuckLake catalog store is skipped in IL5 and its editor
// honest-gates with a Fix-it (the pre-existing state). The DuckDB serving tier
// has no Postgres dependency and still deploys by default.
param postgresQuotaAvailable = bool(readEnvironmentVariable('LOOM_POSTGRES_QUOTA_AVAILABLE', 'false'))
param hubFirewallEnabled = true
param aiSearchEnabled = false
// Azure Analysis Services is NOT available in the DoD regions — pin OFF (main.bicep
// now defaults aasEnabled=true for Commercial day-one). The semantic-model surfaces
// fall back to Synapse-Serverless / Loom-native here per the documented boundary.
param aasEnabled = false
param adxEnabled = true
// RTI backends — Event Hubs + Stream Analytics ON by default (opt-out). Entra-
// only auth (the only IL5-allowed posture). Set the env var to 'false' to skip,
// or reuse an existing namespace/job via the EXISTING_* vars above.
param loomEventHubEnabled = bool(readEnvironmentVariable('LOOM_EVENTHUB_ENABLED', 'true'))
param loomStreamAnalyticsEnabled = bool(readEnvironmentVariable('LOOM_STREAM_ANALYTICS_ENABLED', 'true'))
// no-op here (containerPlatform=='aks' fails the setupOrchestratorActive gate); on
// AKS the orchestrator runs via the cluster GitOps path as the same Console UAMI.
param setupOrchestratorEnabled = bool(readEnvironmentVariable('LOOM_SETUP_ORCHESTRATOR_ENABLED', 'true'))
param setupTemplateUri = readEnvironmentVariable('LOOM_SETUP_TEMPLATE_URI', '')
// Gremlin (graph editor) + NoSQL vector. Gov suffix gremlin.cosmos.azure.us
// is selected automatically from boundary='IL5'.
param cosmosGraphVectorEnabled = true
param vpnGatewayEnabled = true
param appGatewayEnabled = true
param frontDoorEnabled = false

// Tags
param complianceTags = {
  Environment: 'IL5'
  CSA_Loom: 'true'
  FedRAMP_Level: 'High'
  DISA_IL: 'IL5'
  Data_Classification: 'CUI-SP'
  M365_Boundary: 'IL5'
}

// =====================================================================
// Data-engineering backends — ON by default (opt-out). Set any to false to
// skip that provision; the console editor then honest-gates (LOOM_* env blanked)
// instead of 502-ing. See docs/fiab/prp/deploy-readiness-100pct.md.
// =====================================================================
param loomSynapseEnabled = true
param loomDatabricksEnabled = true
param loomDataFactoryEnabled = true
param loomSelfHostedIrEnabled = true
