/**
 * compileToSaql — unit tests.
 *
 * Verifies the Eventstream transform nodes compile to valid Stream Analytics
 * Query Language for the four guided shapes (filter, aggregate+window, join,
 * multi-transform WITH chain) plus pass-through and union.
 */
import { describe, it, expect } from 'vitest';
import {
  compileToSaql,
  windowClause,
  type SourceNode,
  type TransformNode,
  type SinkNode,
} from '../asa-query-compiler';

const src = (name: string): SourceNode => ({ kind: 'eventhub', name });
const sink = (name: string): SinkNode => ({ kind: 'kusto', name });

describe('compileToSaql', () => {
  it('emits pass-through when there are no transforms', () => {
    const q = compileToSaql([src('input-eh')], [], [sink('out-kusto')]);
    expect(q).toContain('SELECT *');
    expect(q).toContain('INTO [out-kusto]');
    expect(q).toContain('FROM [input-eh]');
    expect(q).toContain('Generated by CSA Loom');
  });

  it('compiles a filter transform to a WHERE clause with TIMESTAMP BY', () => {
    const t: TransformNode = {
      kind: 'filter',
      name: 'hot',
      expression: "temperature > 30 AND deviceId = 'sensor-A'",
      timestampBy: 'eventTime',
    };
    const q = compileToSaql([src('input-eh')], [t], [sink('out')]);
    expect(q).toContain('FROM [input-eh] TIMESTAMP BY eventTime');
    expect(q).toContain("WHERE temperature > 30 AND deviceId = 'sensor-A'");
    expect(q).toContain('INTO [out]');
  });

  it('compiles an aggregate with a tumbling window + HAVING', () => {
    const t: TransformNode = {
      kind: 'aggregate',
      name: 'avgTemp',
      timestampBy: 'eventTime',
      groupBy: ['deviceId'],
      aggregates: [
        { func: 'AVG', field: 'temperature', alias: 'avgTemp' },
        { func: 'COUNT', field: '*', alias: 'n' },
      ],
      windowType: 'Tumbling',
      windowSize: 30,
      windowUnit: 'second',
      havingExpression: 'AVG(temperature) > 30',
    };
    const q = compileToSaql([src('input-eh')], [t], [sink('out')]);
    expect(q).toContain('AVG(temperature) AS avgTemp');
    expect(q).toContain('COUNT(*) AS n');
    expect(q).toContain('System.Timestamp() AS windowEnd');
    expect(q).toContain('GROUP BY deviceId, TumblingWindow(second, 30)');
    expect(q).toContain('HAVING AVG(temperature) > 30');
  });

  it('compiles a hopping window with the hop size', () => {
    const t: TransformNode = {
      kind: 'window',
      name: 'hop',
      aggregates: [{ func: 'SUM', field: 'amount', alias: 'total' }],
      windowType: 'Hopping',
      windowSize: 60,
      windowUnit: 'second',
      hopSize: 10,
    };
    const q = compileToSaql([src('in')], [t], [sink('out')]);
    expect(q).toContain('HoppingWindow(second, 60, 10)');
    expect(q).toContain('SUM(amount) AS total');
  });

  it('compiles a join with DATEDIFF temporal bound', () => {
    const t: TransformNode = {
      kind: 'join',
      name: 'enrich',
      joinSource: 'ref-stream',
      joinType: 'LEFT OUTER',
      joinOn: 'L.deviceId = R.deviceId',
      joinDurationSeconds: 5,
      timestampBy: 'eventTime',
    };
    const q = compileToSaql([src('left-eh'), src('ref-stream')], [t], [sink('out')]);
    expect(q).toContain('FROM [left-eh] L TIMESTAMP BY eventTime');
    expect(q).toContain('LEFT OUTER JOIN [ref-stream] R');
    expect(q).toContain('ON L.deviceId = R.deviceId');
    expect(q).toContain('AND DATEDIFF(second, L, R) BETWEEN 0 AND 5');
    expect(q).toContain('SELECT L.*, R.*');
  });

  it('chains multiple transforms into a WITH … step CTE', () => {
    const filter: TransformNode = { kind: 'filter', name: 'f', expression: 'amount > 0' };
    const agg: TransformNode = {
      kind: 'aggregate',
      name: 'a',
      groupBy: ['region'],
      aggregates: [{ func: 'SUM', field: 'amount', alias: 'total' }],
      windowType: 'Tumbling',
      windowSize: 1,
      windowUnit: 'minute',
    };
    const q = compileToSaql([src('in')], [filter, agg], [sink('out')]);
    expect(q).toContain('WITH step1 AS (');
    expect(q).toContain('step2 AS (');
    expect(q).toContain('FROM step1');
    expect(q).toContain('INTO [out]');
    expect(q).toContain('FROM step2');
  });

  it('materializes a union through a WITH step with a single INTO', () => {
    const u: TransformNode = { kind: 'union', name: 'merge' };
    const q = compileToSaql([src('a'), src('b')], [u], [sink('out')]);
    expect(q).toContain('WITH step1 AS (');
    expect(q).toContain('FROM [a]');
    expect(q).toContain('UNION');
    expect(q).toContain('FROM [b]');
    expect(q).toMatch(/INTO \[out\][\s\S]*FROM step1/);
  });

  it('fans out to multiple sinks', () => {
    const t: TransformNode = { kind: 'filter', name: 'f', expression: 'x = 1' };
    const q = compileToSaql([src('in')], [t], [sink('out1'), sink('out2')]);
    expect(q).toContain('INTO [out1]');
    expect(q).toContain('INTO [out2]');
  });
});

describe('windowClause', () => {
  it('returns null when no window is configured', () => {
    expect(windowClause({ kind: 'aggregate', name: 'a' })).toBeNull();
  });
  it('renders a snapshot window', () => {
    expect(windowClause({ kind: 'window', name: 'w', windowType: 'Snapshot' })).toBe('SnapshotWindow()');
  });
});
