// Ambient declarations for non-code side-effect imports.
//
// Next ships `declare module '*.css' {}` in next/types/global.d.ts, but that is
// only reachable through `next-env.d.ts`, which is UNTRACKED and generated by
// `next build`. A fresh CI checkout type-checks before any build has run, so
// those declarations are absent and TypeScript 6 rejects
// `import '@/styles/globals.css'` with TS2882. (TypeScript 5 tolerated it,
// which is why this surfaced only with the 6.0.3 bump.)
//
// TRADEOFF, stated rather than hidden: a wildcard declaration means a stylesheet
// import type-checks even if the file is missing. That is the same latitude
// Next's own declaration grants, and the bundler still fails on a missing file.
declare module '*.css';
declare module '*.scss';
