"""GraphRAG index builder for CSA-in-a-Box.

Orchestrates the Microsoft GraphRAG indexing pipeline to build a knowledge
graph from documents stored in Azure Blob Storage or local directories.
"""

from __future__ import annotations

import json
import logging
import os
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


@dataclass
class IndexConfig:
    """Configuration for GraphRAG indexing pipeline."""

    # LLM settings
    llm_model: str = "gpt-5.4"
    llm_deployment_name: str = "gpt-5.4"
    llm_api_base: str = ""
    llm_api_version: str = "2025-04-01-preview"

    # Embedding settings
    embedding_model: str = "text-embedding-3-large"
    embedding_deployment_name: str = "text-embedding-3-large"

    # Input settings
    input_type: str = "file"  # "file" or "blob"
    input_dir: str = "./input"

    # Blob storage (if input_type == "blob")
    storage_account_name: str = ""
    storage_container_name: str = ""

    # Chunking
    chunk_size: int = 1200
    chunk_overlap: int = 100

    # Graph settings
    entity_extraction_max_gleanings: int = 1
    claim_extraction_enabled: bool = False
    community_report_max_length: int = 3000

    # Output
    output_dir: str = "./output"

    def to_settings_yaml(self) -> str:
        """Generate GraphRAG settings.yaml content."""
        api_base = self.llm_api_base or os.getenv("AZURE_OPENAI_ENDPOINT", "")

        settings = f"""# GraphRAG Settings — generated by CSA-in-a-Box
# See: https://microsoft.github.io/graphrag/config/yaml

llm:
  type: azure_openai_chat
  model: {self.llm_model}
  deployment_name: {self.llm_deployment_name}
  api_base: {api_base}
  api_version: {self.llm_api_version}
  auth_type: azure_identity

embeddings:
  llm:
    type: azure_openai_embedding
    model: {self.embedding_model}
    deployment_name: {self.embedding_deployment_name}
    api_base: {api_base}
    api_version: {self.llm_api_version}
    auth_type: azure_identity

input:
  type: {self.input_type}
  base_dir: {self.input_dir}
"""
        if self.input_type == "blob":
            settings += f"""  storage_account_name: {self.storage_account_name}
  container_name: {self.storage_container_name}
  auth_type: azure_identity
"""

        settings += f"""
chunks:
  size: {self.chunk_size}
  overlap: {self.chunk_overlap}

entity_extraction:
  max_gleanings: {self.entity_extraction_max_gleanings}

claim_extraction:
  enabled: {str(self.claim_extraction_enabled).lower()}

community_reports:
  max_length: {self.community_report_max_length}

storage:
  type: file
  base_dir: {self.output_dir}
"""
        return settings


class GraphRAGIndexBuilder:
    """Orchestrate GraphRAG indexing pipeline.

    Wraps the `graphrag` CLI and Python API to build knowledge graph
    indexes from document collections.

    Example:
        config = IndexConfig(
            llm_model="gpt-5.4",
            input_dir="./my-documents",
            output_dir="./graphrag-output",
        )
        builder = GraphRAGIndexBuilder(config)
        result = builder.build_index()
        print(f"Entities: {result['entity_count']}")
    """

    def __init__(self, config: IndexConfig) -> None:
        self.config = config

    def initialize_workspace(self, workspace_dir: str | Path) -> Path:
        """Initialize a GraphRAG workspace with settings.yaml.

        Creates the workspace directory structure and writes the
        configuration file.

        Args:
            workspace_dir: Directory for the GraphRAG workspace.

        Returns:
            Path to the workspace directory.
        """
        workspace = Path(workspace_dir)
        workspace.mkdir(parents=True, exist_ok=True)

        # Create input directory
        input_dir = workspace / "input"
        input_dir.mkdir(exist_ok=True)

        # Write settings.yaml
        settings_path = workspace / "settings.yaml"
        settings_content = self.config.to_settings_yaml()
        settings_path.write_text(settings_content, encoding="utf-8")

        logger.info("Initialized GraphRAG workspace at %s", workspace)
        return workspace

    def build_index(
        self,
        workspace_dir: str | Path | None = None,
        verbose: bool = False,
    ) -> dict[str, Any]:
        """Run the GraphRAG indexing pipeline.

        This executes the full pipeline:
        1. Document chunking
        2. Entity extraction (via LLM)
        3. Relationship extraction (via LLM)
        4. Community detection (Leiden algorithm)
        5. Community summarization (via LLM)
        6. Embedding generation

        Args:
            workspace_dir: GraphRAG workspace directory. If None,
                creates a temporary workspace.
            verbose: Enable verbose output.

        Returns:
            Dict with index statistics (entity_count, relationship_count, etc.).
        """
        if workspace_dir is None:
            workspace_dir = tempfile.mkdtemp(prefix="graphrag-")
            self.initialize_workspace(workspace_dir)

        workspace = Path(workspace_dir)

        # Run graphrag index command
        cmd = ["graphrag", "index", "--root", str(workspace)]
        if verbose:
            cmd.append("--verbose")

        logger.info("Starting GraphRAG indexing at %s", workspace)
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=3600,  # 1 hour timeout for large corpora
                cwd=str(workspace),
            )

            if result.returncode != 0:
                logger.error("GraphRAG indexing failed: %s", result.stderr)
                raise RuntimeError(
                    f"GraphRAG indexing failed (exit {result.returncode}): "
                    f"{result.stderr[:500]}"
                )

            logger.info("GraphRAG indexing completed successfully")

        except subprocess.TimeoutExpired:
            raise RuntimeError("GraphRAG indexing timed out after 1 hour")

        # Parse output statistics
        return self._parse_index_output(workspace)

    def build_index_api(
        self,
        workspace_dir: str | Path,
    ) -> dict[str, Any]:
        """Run GraphRAG indexing via Python API (alternative to CLI).

        Uses the graphrag Python package directly instead of subprocess.
        Preferred for programmatic use and better error handling.
        """
        try:
            from graphrag.index.run import run_pipeline
            from graphrag.config.create_graphrag_config import create_graphrag_config
        except ImportError:
            raise ImportError(
                "graphrag package required. Install: pip install graphrag"
            )

        workspace = Path(workspace_dir)
        settings_path = workspace / "settings.yaml"

        if not settings_path.exists():
            self.initialize_workspace(workspace)

        settings_yaml = settings_path.read_text(encoding="utf-8")
        config = create_graphrag_config(settings_yaml, str(workspace))

        import asyncio

        asyncio.run(run_pipeline(config))

        return self._parse_index_output(workspace)

    def _parse_index_output(self, workspace: Path) -> dict[str, Any]:
        """Parse GraphRAG index output files for statistics."""
        output_dir = workspace / "output"
        stats: dict[str, Any] = {
            "workspace": str(workspace),
            "entity_count": 0,
            "relationship_count": 0,
            "community_count": 0,
            "text_unit_count": 0,
            "output_files": [],
        }

        # Check for Parquet output files
        parquet_files = {
            "entities": "entities.parquet",
            "relationships": "relationships.parquet",
            "communities": "communities.parquet",
            "community_reports": "community_reports.parquet",
            "text_units": "text_units.parquet",
        }

        for name, filename in parquet_files.items():
            # Search in output directory tree
            matches = list(output_dir.rglob(filename)) if output_dir.exists() else []
            if matches:
                file_path = matches[0]
                stats["output_files"].append(str(file_path))
                try:
                    import pandas as pd

                    df = pd.read_parquet(file_path)
                    count = len(df)
                    stats[f"{name.rstrip('s')}_count"] = count
                    logger.info("%s: %d records", name, count)
                except Exception:
                    logger.warning("Could not read %s", file_path)

        return stats
