/**
 * Unit tests for the tutorial regeneration merge policy
 * (`apps/fiab-console/tools/tutorial-merge.mjs`).
 *
 * These exist because the generator's emitted banner promises that hand-written
 * content survives a re-gen, and for a long time it did not: `writeFileSync`
 * overwrote the whole file. The first fix read back the text after the end
 * marker — which silently did nothing for the 66 of 124 indexed tutorials that
 * carry no marker at all, i.e. the fully hand-authored ones with the MOST to
 * lose. The `authored` case below is the regression guard for exactly that hole.
 *
 * Every assertion here fails loudly on a regression — no try/catch, no
 * asserting on a caught value.
 */
import { describe, it, expect } from 'vitest';
import { END_MARKER, mergeTutorial } from '../tools/tutorial-merge.mjs';

const GENERATED = [
  '<!-- auto-generated by tools/uat-report.mjs -->',
  '# Tutorial: Widget editor',
  '',
  '## What this editor does',
  '',
  'Regenerated from the catalog learnContent.',
  '',
  END_MARKER,
].join('\n');

describe('mergeTutorial', () => {
  it('writes the generated doc when no file exists yet', () => {
    const r = mergeTutorial(GENERATED, null);
    expect(r.mode).toBe('new');
    expect(r.action).toBe('write');
    expect(r.content).toBe(GENERATED);
  });

  it('treats undefined (missing file) the same as null', () => {
    const r = mergeTutorial(GENERATED, undefined);
    expect(r.mode).toBe('new');
    expect(r.action).toBe('write');
  });

  it('re-appends the authored tail below the end marker', () => {
    const existing = [
      '<!-- auto-generated by tools/uat-report.mjs -->',
      '# Tutorial: Widget editor',
      '',
      'STALE generated prose that must NOT survive.',
      '',
      END_MARKER,
      '',
      '## Hand-written deep dive',
      '',
      'Authored paragraph the generator does not model.',
    ].join('\n');

    const r = mergeTutorial(GENERATED, existing);
    expect(r.mode).toBe('generated');
    expect(r.action).toBe('write');
    expect(r.content).toContain('## Hand-written deep dive');
    expect(r.content).toContain('Authored paragraph the generator does not model.');
    // The regenerated block replaces the old one.
    expect(r.content).not.toContain('STALE generated prose');
    expect(r.content).toContain('Regenerated from the catalog learnContent.');
  });

  it('emits just the generated block when the marker is last with nothing after it', () => {
    const existing = `${GENERATED}\n`;
    const r = mergeTutorial(GENERATED, existing);
    expect(r.mode).toBe('generated');
    expect(r.tail).toBe('');
    expect(r.content).toBe(GENERATED);
  });

  // ── The hole the first "data-loss fix" left open ────────────────────────
  it('SKIPS a fully hand-authored tutorial that has no end marker anywhere', () => {
    const authored = [
      '# Tutorial: Mapping data flow editor',
      '',
      '> A guide written entirely by hand — no generator banner, no end marker.',
      '',
      '## Debug the flow',
      '',
      'Sixty-two lines of authored depth live here.',
    ].join('\n');

    const r = mergeTutorial(GENERATED, authored);
    expect(r.mode).toBe('authored');
    expect(r.action).toBe('skip');
    // `content: null` is what stops the caller writing anything at all. If this
    // ever becomes a string, the generator will clobber the whole guide again.
    expect(r.content).toBeNull();
  });

  it('never returns generated-only content for a marker-less file (data-loss guard)', () => {
    const authored = '# Fully hand-written guide\n\nIrreplaceable prose.\n';
    const r = mergeTutorial(GENERATED, authored);
    // Simulate what the caller would put on disk. With the pre-fix behaviour
    // (tail = '' then writeFileSync(generated)) this expectation fails.
    const onDisk = r.action === 'skip' ? authored : r.content;
    expect(onDisk).toContain('Irreplaceable prose.');
  });

  it('does not truncate a tail that quotes the end marker', () => {
    // An authored section documenting this very regeneration contract mentions
    // the marker. `lastIndexOf` would cut the tail at the author's mention and
    // silently drop everything before it.
    const existing = [
      GENERATED,
      '',
      '## How regeneration works',
      '',
      `Everything below \`${END_MARKER}\` is preserved.`,
      '',
      'Closing paragraph after the quoted marker.',
    ].join('\n');

    const r = mergeTutorial(GENERATED, existing);
    expect(r.mode).toBe('generated');
    expect(r.content).toContain('## How regeneration works');
    expect(r.content).toContain('Closing paragraph after the quoted marker.');
  });

  it('is idempotent — merging its own output twice is stable', () => {
    const first = mergeTutorial(GENERATED, [
      GENERATED, '', '## Authored', '', 'Body.',
    ].join('\n'));
    const second = mergeTutorial(GENERATED, first.content);
    expect(second.content).toBe(first.content);
  });
});
