/**
 * GENERATED — do not edit by hand. TYPE-ONLY (no runtime import is emitted).
 * Source: apps/fiab-console/app/api/**\/route.ts   (1673 routes)
 * Regenerate: node scripts/ci/generate-client-route-map.mjs
 * Drift gate:  node scripts/ci/generate-client-route-map.mjs --check
 *
 * R15/R16 — the typed client-route map. `clientFetch` applies
 * `ValidateApiPath` to its `input`, so a string LITERAL naming a BFF route
 * that does not exist fails to COMPILE instead of 404ing in front of a user.
 * Paths built from variables are unconstrained here by design and are covered
 * by the R17 guard (scripts/ci/check-known-client-routes.mjs).
 */

/** Routes with no dynamic segment — a union of UNIT types (cheap to check). */
export type StaticApiRoute =
  | '/api/a2a'
  | '/api/a2a/agent-cards'
  | '/api/a2a/delegate'
  | '/api/access-governance/backfill'
  | '/api/access-governance/group-sync'
  | '/api/access-governance/report'
  | '/api/access-governance/reviews'
  | '/api/access-governance/reviews/sweep'
  | '/api/access-governance/revoke-all'
  | '/api/access-governance/sweep'
  | '/api/access-packages'
  | '/api/access-requests'
  | '/api/access-requests/bulk-decision'
  | '/api/access-requests/public'
  | '/api/activity'
  | '/api/adf/cdc'
  | '/api/adf/dataflows'
  | '/api/adf/datasets'
  | '/api/adf/factories/create'
  | '/api/adf/global-parameters'
  | '/api/adf/integration-runtimes'
  | '/api/adf/linked-services'
  | '/api/adf/linked-services/test'
  | '/api/adf/managed-private-endpoints'
  | '/api/adf/pipelines'
  | '/api/adf/resource-json'
  | '/api/adf/triggers'
  | '/api/admin/access-requests'
  | '/api/admin/agent-quality'
  | '/api/admin/agent-quality/eval-alert'
  | '/api/admin/audit-logs'
  | '/api/admin/autopilot'
  | '/api/admin/autopilot/apply'
  | '/api/admin/autopilot/run'
  | '/api/admin/azure-resources'
  | '/api/admin/batch-labeling'
  | '/api/admin/bootstrap-catalogs'
  | '/api/admin/capacity/chargeback'
  | '/api/admin/capacity/cost'
  | '/api/admin/capacity/guardrails'
  | '/api/admin/capacity/utilization'
  | '/api/admin/capacity/viz-config'
  | '/api/admin/chaos/dependency'
  | '/api/admin/chargeback'
  | '/api/admin/chargeback/attribution'
  | '/api/admin/chargeback/workspaces'
  | '/api/admin/classifications'
  | '/api/admin/coe-library'
  | '/api/admin/coe-library/render'
  | '/api/admin/copilot-config'
  | '/api/admin/copilot-quality'
  | '/api/admin/copilot-quality/budgets'
  | '/api/admin/copilot-quality/prompts'
  | '/api/admin/copilot-quality/run'
  | '/api/admin/copilot-quality/search'
  | '/api/admin/copilot-quality/tier'
  | '/api/admin/copilot-usage'
  | '/api/admin/copilot/memory'
  | '/api/admin/copilot/memory/audit'
  | '/api/admin/data-products-backend'
  | '/api/admin/data-quality-rules'
  | '/api/admin/deploy-plan'
  | '/api/admin/deploy-plan/cost-estimate'
  | '/api/admin/deploy-status'
  | '/api/admin/developer/tokens'
  | '/api/admin/diagnostics/bundle'
  | '/api/admin/domains'
  | '/api/admin/domains/assign-workspaces'
  | '/api/admin/domains/images'
  | '/api/admin/domains/mesh'
  | '/api/admin/domains/purview-status'
  | '/api/admin/domains/sync'
  | '/api/admin/dspm-ai'
  | '/api/admin/embed-codes'
  | '/api/admin/env-config'
  | '/api/admin/feedback-forwarding'
  | '/api/admin/finops/anomalies'
  | '/api/admin/finops/breakdown'
  | '/api/admin/finops/budgets'
  | '/api/admin/finops/focus'
  | '/api/admin/finops/forecast'
  | '/api/admin/gates'
  | '/api/admin/governance-catalog/reindex'
  | '/api/admin/health/exercise'
  | '/api/admin/lineage/reconcile'
  | '/api/admin/load-sample-data'
  | '/api/admin/mcp-servers'
  | '/api/admin/mcp-servers/bridge'
  | '/api/admin/mcp-servers/builtin'
  | '/api/admin/mcp-servers/deploy'
  | '/api/admin/mcp-servers/deployed/status'
  | '/api/admin/mcp-servers/deployed/teardown'
  | '/api/admin/mcp-servers/ms-remote'
  | '/api/admin/mcp-servers/ms-remote/config'
  | '/api/admin/mcp-servers/powerbi'
  | '/api/admin/mcp-servers/test-connection'
  | '/api/admin/model-fabric'
  | '/api/admin/model-fabric/run'
  | '/api/admin/network/topology'
  | '/api/admin/ops-copilot'
  | '/api/admin/ops-copilot/execute'
  | '/api/admin/org-visuals'
  | '/api/admin/org-visuals/dashboards'
  | '/api/admin/org-visuals/dashboards/render'
  | '/api/admin/overview'
  | '/api/admin/parity-autopilot'
  | '/api/admin/parity-autopilot/run'
  | '/api/admin/pdp/shadow-report'
  | '/api/admin/performance'
  | '/api/admin/performance/cache-stats'
  | '/api/admin/performance/copilot-slo'
  | '/api/admin/performance/prove-warm'
  | '/api/admin/performance/recommendations'
  | '/api/admin/performance/recommendations/apply'
  | '/api/admin/performance/retrieval-stats'
  | '/api/admin/performance/run'
  | '/api/admin/performance/tunables'
  | '/api/admin/permissions/capabilities'
  | '/api/admin/permissions/grants'
  | '/api/admin/permissions/principals'
  | '/api/admin/platform-settings'
  | '/api/admin/policy-code'
  | '/api/admin/policy-code/reconcile'
  | '/api/admin/protection-policies'
  | '/api/admin/readiness'
  | '/api/admin/readiness/export'
  | '/api/admin/refresh-summary'
  | '/api/admin/reindex-items'
  | '/api/admin/rum'
  | '/api/admin/runtime-flags'
  | '/api/admin/scaling/adx'
  | '/api/admin/scaling/ai-search'
  | '/api/admin/scaling/aks'
  | '/api/admin/scaling/apim'
  | '/api/admin/scaling/capacity'
  | '/api/admin/scaling/compute'
  | '/api/admin/scaling/compute/purview-managed-vnet'
  | '/api/admin/scaling/compute/register-purview-shir'
  | '/api/admin/scaling/container-apps'
  | '/api/admin/scaling/cosmos'
  | '/api/admin/scaling/databricks-cluster'
  | '/api/admin/scaling/databricks-warehouse'
  | '/api/admin/scaling/foundry-compute'
  | '/api/admin/scaling/synapse-dwu'
  | '/api/admin/scaling/utilization'
  | '/api/admin/secret-health'
  | '/api/admin/security/dlp/alerts'
  | '/api/admin/security/dlp/manage'
  | '/api/admin/security/dlp/policies'
  | '/api/admin/security/dlp/simulate'
  | '/api/admin/security/dlp/violations'
  | '/api/admin/security/mip/applicable-items'
  | '/api/admin/security/mip/evaluate'
  | '/api/admin/security/mip/labels'
  | '/api/admin/security/mip/policies'
  | '/api/admin/security/purview/collections'
  | '/api/admin/security/purview/dataquality'
  | '/api/admin/security/purview/discover'
  | '/api/admin/security/purview/domains'
  | '/api/admin/security/purview/glossary'
  | '/api/admin/security/purview/scans'
  | '/api/admin/security/purview/sources'
  | '/api/admin/self-audit'
  | '/api/admin/sensitivity-labels'
  | '/api/admin/slo'
  | '/api/admin/spark-telemetry/audit'
  | '/api/admin/spark/chaos'
  | '/api/admin/spark/health'
  | '/api/admin/spark/recover'
  | '/api/admin/synthetic-runs'
  | '/api/admin/tenant-settings'
  | '/api/admin/tenant-settings/groups'
  | '/api/admin/updates/apply'
  | '/api/admin/updates/status'
  | '/api/admin/usage'
  | '/api/admin/usage/embed'
  | '/api/admin/users'
  | '/api/admin/webhooks'
  | '/api/admin/workspaces'
  | '/api/adx/anomaly'
  | '/api/adx/continuous-exports'
  | '/api/adx/external-tables'
  | '/api/adx/functions'
  | '/api/adx/ingestion-mappings'
  | '/api/adx/materialized-views'
  | '/api/adx/overview'
  | '/api/adx/policies'
  | '/api/adx/policy-authoring'
  | '/api/adx/principals'
  | '/api/adx/rls'
  | '/api/adx/tables'
  | '/api/ai-functions'
  | '/api/ai-functions/table'
  | '/api/ai-search/aliases'
  | '/api/ai-search/datasources'
  | '/api/ai-search/debug-sessions'
  | '/api/ai-search/index-my-data/prepare'
  | '/api/ai-search/index-my-data/run'
  | '/api/ai-search/index-my-data/sources'
  | '/api/ai-search/indexers'
  | '/api/ai-search/indexes'
  | '/api/ai-search/knowledge-bases'
  | '/api/ai-search/knowledge-sources'
  | '/api/ai-search/service'
  | '/api/ai-search/service/metrics'
  | '/api/ai-search/skillsets'
  | '/api/ai-search/synonymmaps'
  | '/api/aml/compute-instances'
  | '/api/aml/compute-instances/mine'
  | '/api/aml/datastores'
  | '/api/aml/environments'
  | '/api/aml/experiments'
  | '/api/aml/runs'
  | '/api/analytics/visualize'
  | '/api/apim/apis'
  | '/api/apim/backends'
  | '/api/apim/developer-portal'
  | '/api/apim/gateways'
  | '/api/apim/import'
  | '/api/apim/instances'
  | '/api/apim/named-values'
  | '/api/apim/operations'
  | '/api/apim/products'
  | '/api/apim/service'
  | '/api/apim/subscriptions'
  | '/api/approval-policies'
  | '/api/apps-catalog'
  | '/api/apps/supercharge/seed'
  | '/api/ask'
  | '/api/assets'
  | '/api/assets/freshness'
  | '/api/assets/lineage'
  | '/api/assets/materialize'
  | '/api/assets/status'
  | '/api/attribute-groups'
  | '/api/auth/cli-session'
  | '/api/auth/me'
  | '/api/auth/refresh'
  | '/api/azure/connectables'
  | '/api/azure/function-apps'
  | '/api/azure/iothub/policies'
  | '/api/azure/resources'
  | '/api/business-events/channels'
  | '/api/business-events/publish'
  | '/api/business-events/topics'
  | '/api/business-events/types'
  | '/api/canvas/suggest-next'
  | '/api/capacity/admit'
  | '/api/catalog/browse'
  | '/api/catalog/domains'
  | '/api/catalog/find'
  | '/api/catalog/glossary'
  | '/api/catalog/iceberg/config'
  | '/api/catalog/iceberg/connect'
  | '/api/catalog/iceberg/namespaces'
  | '/api/catalog/iceberg/overview'
  | '/api/catalog/iceberg/table'
  | '/api/catalog/iceberg/tables'
  | '/api/catalog/interop/export'
  | '/api/catalog/interop/ingest'
  | '/api/catalog/lineage'
  | '/api/catalog/lineage/item'
  | '/api/catalog/metastores'
  | '/api/catalog/permissions'
  | '/api/catalog/register'
  | '/api/catalog/request-access'
  | '/api/catalog/search'
  | '/api/catalog/shortcut'
  | '/api/catalog/unity/capabilities'
  | '/api/catalog/unity/foreign-catalogs'
  | '/api/catalog/unity/governance'
  | '/api/catalog/unity/governed-tags'
  | '/api/cdc/connectors'
  | '/api/cdc/connectors/source-tables'
  | '/api/cloud'
  | '/api/config/ui'
  | '/api/connections'
  | '/api/connections/test'
  | '/api/copilot/code-interpret'
  | '/api/copilot/complete'
  | '/api/copilot/dax'
  | '/api/copilot/memory/flush'
  | '/api/copilot/notebook-assist'
  | '/api/copilot/orchestrate'
  | '/api/copilot/sessions'
  | '/api/copilot/skills'
  | '/api/copilot/skills/suggested'
  | '/api/copilot/status'
  | '/api/copilot/tools'
  | '/api/cosmos/account'
  | '/api/cosmos/account-management'
  | '/api/cosmos/container-settings'
  | '/api/cosmos/container-throughput'
  | '/api/cosmos/containers'
  | '/api/cosmos/databases'
  | '/api/cosmos/items'
  | '/api/cosmos/items/action'
  | '/api/cosmos/items/rerank'
  | '/api/cosmos/scripts'
  | '/api/cosmos/scripts/execute'
  | '/api/dab/create'
  | '/api/dab/deploy-source'
  | '/api/dab/sources'
  | '/api/data-agent/run-steps'
  | '/api/data-products'
  | '/api/data-products/import'
  | '/api/data-products/import/template'
  | '/api/data-products/my-access-requests'
  | '/api/data-products/search'
  | '/api/databricks/catalogs'
  | '/api/databricks/clusters'
  | '/api/databricks/jobs'
  | '/api/databricks/mlflow/experiments'
  | '/api/databricks/mlflow/models'
  | '/api/databricks/notebooks'
  | '/api/databricks/pipelines'
  | '/api/databricks/repos'
  | '/api/databricks/serving-endpoints'
  | '/api/databricks/unity-catalog/bindings'
  | '/api/databricks/unity-catalog/catalogs'
  | '/api/databricks/unity-catalog/clean-rooms'
  | '/api/databricks/unity-catalog/connections'
  | '/api/databricks/unity-catalog/data-classification'
  | '/api/databricks/unity-catalog/external-locations'
  | '/api/databricks/unity-catalog/functions'
  | '/api/databricks/unity-catalog/governed-tags'
  | '/api/databricks/unity-catalog/grants'
  | '/api/databricks/unity-catalog/lineage'
  | '/api/databricks/unity-catalog/marketplace'
  | '/api/databricks/unity-catalog/metric-views'
  | '/api/databricks/unity-catalog/models'
  | '/api/databricks/unity-catalog/online-tables'
  | '/api/databricks/unity-catalog/policies'
  | '/api/databricks/unity-catalog/principals'
  | '/api/databricks/unity-catalog/quality-monitors'
  | '/api/databricks/unity-catalog/schemas'
  | '/api/databricks/unity-catalog/storage-credentials'
  | '/api/databricks/unity-catalog/system-tables'
  | '/api/databricks/unity-catalog/tables'
  | '/api/databricks/unity-catalog/tags'
  | '/api/databricks/unity-catalog/temporary-credentials'
  | '/api/databricks/unity-catalog/volumes'
  | '/api/databricks/warehouses'
  | '/api/databricks/workspace'
  | '/api/debug/cookie'
  | '/api/demo/deploy'
  | '/api/deploy/discovery'
  | '/api/deployment-pipelines'
  | '/api/deployment-pipelines/arm'
  | '/api/deployment-pipelines/create'
  | '/api/deployment-pipelines/loom'
  | '/api/developer/tokens'
  | '/api/directlake/frame'
  | '/api/directlake/scan'
  | '/api/downloads'
  | '/api/dq/monitors'
  | '/api/dq/results'
  | '/api/dq/rules'
  | '/api/dq/run'
  | '/api/duckdb/capabilities'
  | '/api/duckdb/query'
  | '/api/ducklake/catalog'
  | '/api/embed/query'
  | '/api/embed/token'
  | '/api/estate/execute'
  | '/api/estate/plan'
  | '/api/eventhubs/authrules'
  | '/api/eventhubs/capture'
  | '/api/eventhubs/consumergroups'
  | '/api/eventhubs/data-explorer'
  | '/api/eventhubs/geodr'
  | '/api/eventhubs/geodr-actions'
  | '/api/eventhubs/hubs'
  | '/api/eventhubs/network'
  | '/api/eventhubs/private-endpoints'
  | '/api/eventhubs/schemagroups'
  | '/api/experience/warp/home'
  | '/api/experience/warp/transforms'
  | '/api/external-shares'
  | '/api/external-shares/received'
  | '/api/fabric/workspaces'
  | '/api/feedback'
  | '/api/flightsql/connect'
  | '/api/flightsql/session'
  | '/api/foundry/accounts'
  | '/api/foundry/activity'
  | '/api/foundry/agents'
  | '/api/foundry/agents/eval'
  | '/api/foundry/agents/eval/judge'
  | '/api/foundry/agents/rollup'
  | '/api/foundry/agents/run'
  | '/api/foundry/agents/spans'
  | '/api/foundry/agents/threads'
  | '/api/foundry/audio'
  | '/api/foundry/batch'
  | '/api/foundry/browser-tool/status'
  | '/api/foundry/chat'
  | '/api/foundry/computes'
  | '/api/foundry/connections'
  | '/api/foundry/data-sources'
  | '/api/foundry/datastores'
  | '/api/foundry/deployments'
  | '/api/foundry/evaluations'
  | '/api/foundry/evaluations/files'
  | '/api/foundry/fine-tuning'
  | '/api/foundry/fine-tuning/files'
  | '/api/foundry/images'
  | '/api/foundry/keys'
  | '/api/foundry/model-deployments'
  | '/api/foundry/models-catalog'
  | '/api/foundry/networking'
  | '/api/foundry/observability'
  | '/api/foundry/quota'
  | '/api/foundry/rbac'
  | '/api/foundry/workspace'
  | '/api/git-integration/commit'
  | '/api/git-integration/pull'
  | '/api/git-integration/resolve'
  | '/api/git-integration/status'
  | '/api/governance-domains'
  | '/api/governance/catalog'
  | '/api/governance/classification-types'
  | '/api/governance/classifications'
  | '/api/governance/classifications/system'
  | '/api/governance/contract-check'
  | '/api/governance/copilot/ask'
  | '/api/governance/data-contracts'
  | '/api/governance/dlp/library'
  | '/api/governance/dlp/meta'
  | '/api/governance/dlp/restrict'
  | '/api/governance/dlp/scan'
  | '/api/governance/dlp/schemas'
  | '/api/governance/dlp/violations'
  | '/api/governance/domains'
  | '/api/governance/dq-findings'
  | '/api/governance/govern/actions'
  | '/api/governance/govern/copilot'
  | '/api/governance/govern/embed'
  | '/api/governance/govern/owner'
  | '/api/governance/govern/posture'
  | '/api/governance/govern/refresh'
  | '/api/governance/govern/trigger-scan'
  | '/api/governance/identities/search'
  | '/api/governance/insights'
  | '/api/governance/irm'
  | '/api/governance/labels/library'
  | '/api/governance/lineage'
  | '/api/governance/pdp-mode'
  | '/api/governance/policies'
  | '/api/governance/policy-code/engine-rules'
  | '/api/governance/purview/status'
  | '/api/governance/scans'
  | '/api/governance/scans/register-existing'
  | '/api/governance/sensitivity'
  | '/api/governance/workspace-egress'
  | '/api/health'
  | '/api/health/deep'
  | '/api/help-copilot/chat'
  | '/api/help-copilot/reindex'
  | '/api/help-copilot/sessions'
  | '/api/insights/digests'
  | '/api/internal/assets/reconcile'
  | '/api/internal/copilot/eval-probe'
  | '/api/internal/copilot/memory/consolidate'
  | '/api/internal/copilot/search-probe'
  | '/api/internal/copilot/skills/learn'
  | '/api/internal/copilot/tools'
  | '/api/internal/cost-anomaly/run'
  | '/api/internal/scheduler/tick'
  | '/api/internal/spark/keep-warm'
  | '/api/internal/topology/register-domain'
  | '/api/iq/mcp'
  | '/api/items'
  | '/api/items/activation-sync'
  | '/api/items/activator'
  | '/api/items/adf-dataset'
  | '/api/items/adf-pipeline'
  | '/api/items/adf-trigger'
  | '/api/items/ai-builder-model'
  | '/api/items/ai-foundry-project'
  | '/api/items/ai-search-index'
  | '/api/items/aip-logic'
  | '/api/items/airflow-job'
  | '/api/items/apim-api'
  | '/api/items/apim-policy'
  | '/api/items/apim-product'
  | '/api/items/automl/jobs'
  | '/api/items/automl/options'
  | '/api/items/automl/submit'
  | '/api/items/azure-sql-database'
  | '/api/items/azure-sql-managed-instance'
  | '/api/items/azure-sql-server'
  | '/api/items/batch-pool'
  | '/api/items/batch-pool/jobs'
  | '/api/items/batch-pool/tasks'
  | '/api/items/by-type'
  | '/api/items/code-report/validate'
  | '/api/items/compute'
  | '/api/items/content-safety'
  | '/api/items/content-safety/blocklists'
  | '/api/items/content-safety/blocklists/items'
  | '/api/items/content-safety/rai-policies'
  | '/api/items/copilot-studio-action'
  | '/api/items/copilot-studio-agent'
  | '/api/items/copilot-studio-channel'
  | '/api/items/copilot-studio-knowledge'
  | '/api/items/copilot-studio-topic'
  | '/api/items/copilot-template-library'
  | '/api/items/copy-job'
  | '/api/items/cosmos-gremlin-graph'
  | '/api/items/cypher-graph'
  | '/api/items/dashboard'
  | '/api/items/data-agent'
  | '/api/items/data-pipeline'
  | '/api/items/data-pipeline/import'
  | '/api/items/data-pipeline/practice-seed'
  | '/api/items/data-product-instance'
  | '/api/items/data-product-template'
  | '/api/items/data-science/home'
  | '/api/items/databricks-cluster'
  | '/api/items/databricks-cluster/hygiene'
  | '/api/items/databricks-cluster/options'
  | '/api/items/databricks-job'
  | '/api/items/databricks-notebook/list'
  | '/api/items/dataflow'
  | '/api/items/dataflow/config'
  | '/api/items/dataflow/copilot'
  | '/api/items/dataflow/profile'
  | '/api/items/datamart/migrate'
  | '/api/items/dataset'
  | '/api/items/dataset/browse'
  | '/api/items/dataverse-table'
  | '/api/items/dbt-job'
  | '/api/items/environment'
  | '/api/items/evaluation'
  | '/api/items/event-grid-topic'
  | '/api/items/event-hubs-namespace'
  | '/api/items/event-schema-set'
  | '/api/items/eventstream/spark-binding'
  | '/api/items/geo-dataset'
  | '/api/items/geo-map'
  | '/api/items/geo-pipeline'
  | '/api/items/geo-query'
  | '/api/items/gql-graph'
  | '/api/items/graph-model'
  | '/api/items/health-check'
  | '/api/items/integration-runtime'
  | '/api/items/lakehouse'
  | '/api/items/lakehouse-shortcut'
  | '/api/items/linked-service'
  | '/api/items/loom-app-runtime/config'
  | '/api/items/loom-app-runtime/import'
  | '/api/items/mirrored-database'
  | '/api/items/mirrored-database/source-tables'
  | '/api/items/mirrored-database/verify'
  | '/api/items/mirrored-databricks'
  | '/api/items/mirrored-databricks/catalogs'
  | '/api/items/ml-experiment'
  | '/api/items/ml-experiment/submit'
  | '/api/items/ml-model'
  | '/api/items/mounted-adf'
  | '/api/items/notebook'
  | '/api/items/notebook/import'
  | '/api/items/ontology-sdk'
  | '/api/items/paginated-report'
  | '/api/items/paginated-report/capabilities'
  | '/api/items/postgres-flexible-server'
  | '/api/items/power-app'
  | '/api/items/power-automate-flow'
  | '/api/items/power-page'
  | '/api/items/prompt-flow'
  | '/api/items/rayfin-app/model-objects'
  | '/api/items/rayfin-app/models'
  | '/api/items/rayfin-app/preview'
  | '/api/items/recent'
  | '/api/items/release-environment'
  | '/api/items/report'
  | '/api/items/report/copilot'
  | '/api/items/scorecard'
  | '/api/items/semantic-model'
  | '/api/items/semantic-model/aas-databases'
  | '/api/items/semantic-model/build'
  | '/api/items/semantic-model/scaffold'
  | '/api/items/semantic-model/workspace-pane'
  | '/api/items/service-bus-namespace'
  | '/api/items/service-bus-namespace/data-explorer'
  | '/api/items/slate-app'
  | '/api/items/spark-environment'
  | '/api/items/spark-job-definition'
  | '/api/items/sql-database'
  | '/api/items/sql-databases'
  | '/api/items/sql-server-2025-vector-index'
  | '/api/items/stream-analytics-job'
  | '/api/items/synapse-pipeline/list'
  | '/api/items/synapse-spark-pool/list'
  | '/api/items/tracing'
  | '/api/items/transformation-project'
  | '/api/items/vector-store'
  | '/api/items/warehouse/migrate/import'
  | '/api/items/warehouse/migrate/scan'
  | '/api/items/workshop-app'
  | '/api/lakehouse/ai-clean-suggest'
  | '/api/lakehouse/containers'
  | '/api/lakehouse/download'
  | '/api/lakehouse/history'
  | '/api/lakehouse/interop'
  | '/api/lakehouse/load-to-table'
  | '/api/lakehouse/maintenance'
  | '/api/lakehouse/path'
  | '/api/lakehouse/paths'
  | '/api/lakehouse/permissions'
  | '/api/lakehouse/permissions/rls-test'
  | '/api/lakehouse/preview'
  | '/api/lakehouse/references'
  | '/api/lakehouse/references/paths'
  | '/api/lakehouse/schemas'
  | '/api/lakehouse/settings'
  | '/api/lakehouse/shortcuts'
  | '/api/lakehouse/shortcuts/browse'
  | '/api/lakehouse/shortcuts/credentials'
  | '/api/lakehouse/shortcuts/sharepoint'
  | '/api/lakehouse/shortcuts/test'
  | '/api/lakehouse/table-stats'
  | '/api/lakehouse/tables'
  | '/api/lakehouse/transform-preview'
  | '/api/lakehouse/upload'
  | '/api/landing-zones'
  | '/api/landing-zones/discover'
  | '/api/learn/notebook-import'
  | '/api/lineage/openlineage'
  | '/api/lineage/openlineage/export'
  | '/api/loom/capacities'
  | '/api/loom/compute-targets'
  | '/api/loom/compute-targets/databricks-options'
  | '/api/loom/shir'
  | '/api/loom/storage-paths'
  | '/api/loom/workspaces'
  | '/api/maps/static'
  | '/api/marketplace/catalog'
  | '/api/marketplace/gate'
  | '/api/marketplace/mini-app'
  | '/api/marketplace/products'
  | '/api/marketplace/sharing/catalogs'
  | '/api/marketplace/sharing/manifest'
  | '/api/marketplace/sharing/providers'
  | '/api/marketplace/sharing/publishable-tables'
  | '/api/marketplace/sharing/query'
  | '/api/marketplace/sharing/recipients'
  | '/api/marketplace/sharing/shares'
  | '/api/marketplace/subscriptions'
  | '/api/mdm/golden-records'
  | '/api/mdm/match'
  | '/api/mdm/match/approve'
  | '/api/mdm/merge'
  | '/api/mdm/models'
  | '/api/mdm/reference-data'
  | '/api/me'
  | '/api/mesh/a2a/delegate'
  | '/api/mesh/agents'
  | '/api/mesh/catalog'
  | '/api/mesh/run'
  | '/api/messaging/metrics'
  | '/api/metrics/query'
  | '/api/migrate/assess'
  | '/api/migrate/copy'
  | '/api/migrate/translate'
  | '/api/monitor/action-groups'
  | '/api/monitor/activities'
  | '/api/monitor/activity'
  | '/api/monitor/alerts'
  | '/api/monitor/cost'
  | '/api/monitor/defender'
  | '/api/monitor/defender/remediate'
  | '/api/monitor/diagnostics'
  | '/api/monitor/health'
  | '/api/monitor/inventory'
  | '/api/monitor/logic-app-callback'
  | '/api/monitor/logs'
  | '/api/monitor/metrics'
  | '/api/monitor/spark'
  | '/api/network/managed-private-endpoints'
  | '/api/network/pbi-gateway'
  | '/api/network/private-endpoints'
  | '/api/network/vnet-data-gateway'
  | '/api/network/vpn-profile'
  | '/api/notebook/execute'
  | '/api/notebook/wrangler'
  | '/api/notifications'
  | '/api/observability/incidents'
  | '/api/observability/monitors'
  | '/api/onelake/catalog'
  | '/api/onelake/governance'
  | '/api/onelake/lifecycle'
  | '/api/onelake/paths'
  | '/api/onelake/recycle'
  | '/api/onelake/resolve'
  | '/api/onelake/security'
  | '/api/onelake/storage'
  | '/api/onelake/tier'
  | '/api/ontology-functions'
  | '/api/openapi.json'
  | '/api/org-reports'
  | '/api/org-reports/render'
  | '/api/powerbi/access'
  | '/api/powerbi/datasources'
  | '/api/powerbi/endorsement'
  | '/api/powerbi/pipelines'
  | '/api/powerbi/workspaces'
  | '/api/powerplatform/apps'
  | '/api/powerplatform/connections'
  | '/api/powerplatform/connectors'
  | '/api/powerplatform/environments'
  | '/api/powerplatform/environments/operation'
  | '/api/powerplatform/flows'
  | '/api/powerplatform/solutions'
  | '/api/powerplatform/tables'
  | '/api/pub/swa-bundle'
  | '/api/real-time-hub/sources'
  | '/api/realtime-hub/connect-source'
  | '/api/realtime-hub/databases'
  | '/api/realtime-hub/endpoints'
  | '/api/realtime-hub/http-source'
  | '/api/realtime-hub/keyvault-certificates'
  | '/api/realtime-hub/options'
  | '/api/realtime-hub/preview'
  | '/api/realtime-hub/provision'
  | '/api/realtime-hub/streams'
  | '/api/rti-hub'
  | '/api/running-workloads'
  | '/api/runtime-flags'
  | '/api/s3-gateway/info'
  | '/api/scheduler'
  | '/api/scim/v2/Groups'
  | '/api/scim/v2/ResourceTypes'
  | '/api/scim/v2/ServiceProviderConfig'
  | '/api/scim/v2/Users'
  | '/api/search/items'
  | '/api/semantic-model/metric-view'
  | '/api/setup/config'
  | '/api/setup/deploy'
  | '/api/setup/deploy-preflight'
  | '/api/setup/deploy-status'
  | '/api/setup/discover-services'
  | '/api/setup/estate-scan'
  | '/api/setup/existing-aoai'
  | '/api/setup/existing-dlzs'
  | '/api/setup/existing-storage'
  | '/api/setup/identity'
  | '/api/setup/landing-zones'
  | '/api/setup/landing-zones/grant'
  | '/api/setup/quota-preflight'
  | '/api/setup/regions'
  | '/api/setup/scan'
  | '/api/setup/scan-cosmos'
  | '/api/setup/scan-purview'
  | '/api/setup/subscriptions'
  | '/api/setup/tenant-topology'
  | '/api/setup/wire-existing'
  | '/api/setup/workflow-run-status'
  | '/api/spark/session-pool'
  | '/api/sql/trino'
  | '/api/sqldb/columns'
  | '/api/sqldb/constraints'
  | '/api/sqldb/functions'
  | '/api/sqldb/indexes'
  | '/api/sqldb/preview'
  | '/api/sqldb/procedures'
  | '/api/sqldb/rename'
  | '/api/sqldb/schemas'
  | '/api/sqldb/script'
  | '/api/sqldb/table-types'
  | '/api/sqldb/tables'
  | '/api/sqldb/views'
  | '/api/storage/accounts'
  | '/api/streaming-sql/mv'
  | '/api/streaming-sql/query'
  | '/api/streaming-sql/status'
  | '/api/synapse/dataflows'
  | '/api/synapse/datasets'
  | '/api/synapse/environments'
  | '/api/synapse/integration-runtimes'
  | '/api/synapse/kqlscripts'
  | '/api/synapse/linkedservices'
  | '/api/synapse/linkedservices/test'
  | '/api/synapse/notebooks'
  | '/api/synapse/pipelines'
  | '/api/synapse/pools'
  | '/api/synapse/sparkjobdefinitions'
  | '/api/synapse/sqlscripts'
  | '/api/synapse/triggers'
  | '/api/tabs'
  | '/api/telemetry/rum'
  | '/api/tenant-theme'
  | '/api/thread/add-data-agent-source'
  | '/api/thread/analyze-in-notebook'
  | '/api/thread/analyze-in-powerbi'
  | '/api/thread/analyze-with-dax'
  | '/api/thread/bind-to-ontology'
  | '/api/thread/build-loom-report'
  | '/api/thread/build-powerbi-model'
  | '/api/thread/edges'
  | '/api/thread/kql-query-to-dashboard-tile'
  | '/api/thread/lakehouse-delta-tables'
  | '/api/thread/materialize-to-kql'
  | '/api/thread/mirror-to-lakehouse'
  | '/api/thread/mirror-to-notebook'
  | '/api/thread/model-tables'
  | '/api/thread/open-in-report-builder'
  | '/api/thread/promote-medallion'
  | '/api/thread/publish-as-api'
  | '/api/thread/warehouse-tables'
  | '/api/user-prefs'
  | '/api/v1/whoami'
  | '/api/version'
  | '/api/warehouse/explain'
  | '/api/warehouse/history'
  | '/api/warehouse/query'
  | '/api/workloads-catalog'
  | '/api/workspaces'
  | '/api/workspaces/bulk-delete';

/** Routes with a `[param]` / `[...catchAll]` segment, as template literals. */
export type DynamicApiRoute =
  | `/api/a2a/agent-cards/${string}/${string}`
  | `/api/access-governance/assignments/${string}/activate`
  | `/api/access-governance/reviews/${string}`
  | `/api/access-governance/reviews/${string}/decision`
  | `/api/access-governance/reviews/${string}/evidence`
  | `/api/access-packages/${string}`
  | `/api/access-packages/${string}/request`
  | `/api/access-requests/${string}/decision`
  | `/api/adf/dataflows/${string}`
  | `/api/adf/dataflows/${string}/debug`
  | `/api/adf/datasets/${string}`
  | `/api/adf/linked-services/${string}`
  | `/api/admin/access-requests/${string}`
  | `/api/admin/access-requests/${string}/create-user`
  | `/api/admin/access-requests/${string}/invite-guest`
  | `/api/admin/copilot-quality/${string}`
  | `/api/admin/copilot-quality/prompts/${string}`
  | `/api/admin/copilot/memory/${string}`
  | `/api/admin/developer/tokens/${string}`
  | `/api/admin/directory-users/${string}/lifecycle`
  | `/api/admin/domains/${string}/inventory`
  | `/api/admin/gates/${string}/options`
  | `/api/admin/gates/${string}/resolve`
  | `/api/admin/protection-policies/${string}`
  | `/api/admin/runtime-flags/${string}`
  | `/api/admin/security/mip/labels/${string}`
  | `/api/admin/security/mip/policies/${string}`
  | `/api/admin/webhooks/${string}`
  | `/api/admin/webhooks/${string}/test`
  | `/api/admin/workspaces/${string}`
  | `/api/admin/workspaces/${string}/cmk`
  | `/api/admin/workspaces/${string}/connections`
  | `/api/admin/workspaces/${string}/connections/${string}`
  | `/api/admin/workspaces/${string}/connections/adls-accounts`
  | `/api/admin/workspaces/${string}/connections/log-analytics-workspaces`
  | `/api/admin/workspaces/${string}/folders`
  | `/api/admin/workspaces/${string}/git`
  | `/api/admin/workspaces/${string}/git/branch-out`
  | `/api/admin/workspaces/${string}/git/meta`
  | `/api/admin/workspaces/${string}/git/status`
  | `/api/admin/workspaces/${string}/git/sync`
  | `/api/admin/workspaces/${string}/identity`
  | `/api/admin/workspaces/${string}/m365`
  | `/api/admin/workspaces/${string}/networking/inbound`
  | `/api/admin/workspaces/${string}/networking/ip-rules`
  | `/api/admin/workspaces/${string}/networking/outbound`
  | `/api/admin/workspaces/${string}/networking/trusted`
  | `/api/admin/workspaces/${string}/networking/trusted-resources`
  | `/api/admin/workspaces/${string}/spark/environment`
  | `/api/admin/workspaces/${string}/spark/jobs`
  | `/api/admin/workspaces/${string}/spark/pools`
  | `/api/admin/workspaces/${string}/spark/runtime`
  | `/api/admin/workspaces/${string}/storage-metrics`
  | `/api/admin/workspaces/${string}/task-flows`
  | `/api/admin/workspaces/${string}/task-flows/${string}`
  | `/api/agents/${string}/memory`
  | `/api/ai-search/indexes/${string}`
  | `/api/ai-search/indexes/${string}/analyze`
  | `/api/ai-search/indexes/${string}/search`
  | `/api/ai-search/knowledge-bases/${string}`
  | `/api/ai-search/knowledge-bases/${string}/retrieve`
  | `/api/aml/compute-instances/${string}/idle-shutdown`
  | `/api/aml/compute-instances/${string}/start`
  | `/api/aml/compute-instances/${string}/stop`
  | `/api/aml/runs/${string}`
  | `/api/aml/runs/${string}/artifact`
  | `/api/aml/runs/${string}/artifacts`
  | `/api/aml/runs/${string}/metrics`
  | `/api/aml/runs/${string}/traces`
  | `/api/apim/subscriptions/${string}`
  | `/api/apim/subscriptions/${string}/keys`
  | `/api/app-templates/${string}/instantiate`
  | `/api/approval-policies/${string}`
  | `/api/apps/${string}/install`
  | `/api/apps/install-jobs/${string}`
  | `/api/catalog/asset/${string}`
  | `/api/cdc/connectors/${string}`
  | `/api/cdc/connectors/${string}/monitor`
  | `/api/cdc/connectors/${string}/state`
  | `/api/connections/${string}`
  | `/api/connections/${string}/dependents`
  | `/api/connections/${string}/objects`
  | `/api/connections/${string}/preview`
  | `/api/connections/${string}/purview`
  | `/api/connections/${string}/test`
  | `/api/copilot/sessions/${string}`
  | `/api/copilot/sessions/${string}/trace`
  | `/api/copilot/skills/${string}`
  | `/api/copilot/skills/${string}/duplicate`
  | `/api/copilot/skills/${string}/state`
  | `/api/copilot/skills/suggested/${string}`
  | `/api/copilot/tools/${string}/invoke`
  | `/api/cosmos-items/${string}`
  | `/api/cosmos-items/${string}/${string}`
  | `/api/dab/${string}/apply-to-runtime`
  | `/api/dab/${string}/config`
  | `/api/dab/${string}/download`
  | `/api/dab/${string}/preview/graphql`
  | `/api/dab/${string}/preview/probe`
  | `/api/dab/${string}/preview/rest`
  | `/api/dab/${string}/preview/schema`
  | `/api/dab/${string}/publish`
  | `/api/dab/${string}/validate`
  | `/api/dab/sources/${string}/columns`
  | `/api/dab/sources/${string}/schema`
  | `/api/data-products/${string}`
  | `/api/data-products/${string}/access-policy`
  | `/api/data-products/${string}/access-requests`
  | `/api/data-products/${string}/analytics`
  | `/api/data-products/${string}/assets`
  | `/api/data-products/${string}/cdes`
  | `/api/data-products/${string}/certification`
  | `/api/data-products/${string}/certify`
  | `/api/data-products/${string}/contract-quality`
  | `/api/data-products/${string}/deprecate`
  | `/api/data-products/${string}/glossary-terms`
  | `/api/data-products/${string}/health-actions`
  | `/api/data-products/${string}/observability`
  | `/api/data-products/${string}/okrs`
  | `/api/data-products/${string}/policies`
  | `/api/data-products/${string}/ports`
  | `/api/data-products/${string}/preview`
  | `/api/data-products/${string}/principal-search`
  | `/api/data-products/${string}/sla-check`
  | `/api/data-products/${string}/status`
  | `/api/data-products/${string}/subscribers`
  | `/api/data-products/${string}/versions`
  | `/api/data-products/jobs/${string}`
  | `/api/delta-sharing/${string}`
  | `/api/demo/deploy/${string}`
  | `/api/deployment-pipelines/${string}/compare`
  | `/api/deployment-pipelines/${string}/deploy`
  | `/api/deployment-pipelines/${string}/operations`
  | `/api/deployment-pipelines/${string}/stages`
  | `/api/deployment-pipelines/${string}/stages/${string}/items`
  | `/api/deployment-pipelines/${string}/stages/${string}/workspace`
  | `/api/deployment-pipelines/arm/${string}/operations`
  | `/api/deployment-pipelines/git/${string}/commit`
  | `/api/deployment-pipelines/git/${string}/connection`
  | `/api/deployment-pipelines/git/${string}/initialize`
  | `/api/deployment-pipelines/git/${string}/status`
  | `/api/deployment-pipelines/git/${string}/update`
  | `/api/deployment-pipelines/loom/${string}`
  | `/api/deployment-pipelines/loom/${string}/approvals`
  | `/api/deployment-pipelines/loom/${string}/approvals/${string}`
  | `/api/deployment-pipelines/loom/${string}/compare`
  | `/api/deployment-pipelines/loom/${string}/deploy`
  | `/api/deployment-pipelines/loom/${string}/history`
  | `/api/deployment-pipelines/loom/${string}/stages/${string}/approvals`
  | `/api/deployment-pipelines/loom/${string}/stages/${string}/rules`
  | `/api/deployment-pipelines/loom/${string}/variables`
  | `/api/developer/tokens/${string}`
  | `/api/eventhubs/authrules/${string}/keys`
  | `/api/eventhubs/authrules/${string}/keys/regenerate`
  | `/api/external-shares/${string}`
  | `/api/external-shares/${string}/accept`
  | `/api/foundry/agents/${string}`
  | `/api/foundry/batch/${string}`
  | `/api/foundry/computes/${string}/start`
  | `/api/foundry/computes/${string}/status`
  | `/api/foundry/fine-tuning/${string}`
  | `/api/governance/label-propagation/${string}`
  | `/api/governance/workspace-egress/${string}`
  | `/api/insights/digests/${string}`
  | `/api/insights/digests/${string}/preview`
  | `/api/insights/digests/${string}/run`
  | `/api/internal/copilot/tools/${string}/invoke`
  | `/api/items/${string}/${string}`
  | `/api/items/${string}/${string}/access-mode`
  | `/api/items/${string}/${string}/ai-function`
  | `/api/items/${string}/${string}/alerts`
  | `/api/items/${string}/${string}/assist`
  | `/api/items/${string}/${string}/audit`
  | `/api/items/${string}/${string}/business-metadata`
  | `/api/items/${string}/${string}/canvas-comments`
  | `/api/items/${string}/${string}/canvas-comments/${string}`
  | `/api/items/${string}/${string}/canvas-presence`
  | `/api/items/${string}/${string}/canvas-suggest`
  | `/api/items/${string}/${string}/classifications`
  | `/api/items/${string}/${string}/collab/stream`
  | `/api/items/${string}/${string}/comments`
  | `/api/items/${string}/${string}/definition`
  | `/api/items/${string}/${string}/endorsement`
  | `/api/items/${string}/${string}/explain`
  | `/api/items/${string}/${string}/export-check`
  | `/api/items/${string}/${string}/impact`
  | `/api/items/${string}/${string}/lineage`
  | `/api/items/${string}/${string}/monitoring`
  | `/api/items/${string}/${string}/onelake-security/${string}/cls`
  | `/api/items/${string}/${string}/onelake-security/${string}/rls`
  | `/api/items/${string}/${string}/onelake-security/schema`
  | `/api/items/${string}/${string}/optimize`
  | `/api/items/${string}/${string}/pbi-source`
  | `/api/items/${string}/${string}/pbids`
  | `/api/items/${string}/${string}/permissions`
  | `/api/items/${string}/${string}/security`
  | `/api/items/${string}/${string}/security-roles`
  | `/api/items/${string}/${string}/security-roles/preview-as`
  | `/api/items/${string}/${string}/sensitivity`
  | `/api/items/${string}/${string}/sensitivity-label`
  | `/api/items/${string}/${string}/share`
  | `/api/items/${string}/${string}/shortcuts`
  | `/api/items/${string}/${string}/shortcuts/${string}`
  | `/api/items/${string}/${string}/shortcuts/${string}/test`
  | `/api/items/${string}/${string}/sql-security`
  | `/api/items/${string}/${string}/statistics`
  | `/api/items/${string}/${string}/versions`
  | `/api/items/${string}/${string}/versions/${string}`
  | `/api/items/${string}/${string}/versions/${string}/restore`
  | `/api/items/${string}/${string}/visual-query`
  | `/api/items/activation-sync/${string}`
  | `/api/items/activation-sync/${string}/bind-trigger`
  | `/api/items/activation-sync/${string}/run`
  | `/api/items/activation-sync/${string}/runs`
  | `/api/items/activation-sync/${string}/schema`
  | `/api/items/activator/${string}`
  | `/api/items/activator/${string}/adx-source`
  | `/api/items/activator/${string}/history`
  | `/api/items/activator/${string}/rules`
  | `/api/items/activator/${string}/start`
  | `/api/items/activator/${string}/stop`
  | `/api/items/adf-dataset/${string}`
  | `/api/items/adf-pipeline/${string}`
  | `/api/items/adf-pipeline/${string}/bind`
  | `/api/items/adf-pipeline/${string}/connections`
  | `/api/items/adf-pipeline/${string}/copilot`
  | `/api/items/adf-pipeline/${string}/debug`
  | `/api/items/adf-pipeline/${string}/run`
  | `/api/items/adf-pipeline/${string}/runs`
  | `/api/items/adf-pipeline/${string}/triggers`
  | `/api/items/adf-pipeline/${string}/validate`
  | `/api/items/adf-trigger/${string}`
  | `/api/items/adf-trigger/${string}/state`
  | `/api/items/agent-flow/${string}`
  | `/api/items/agent-flow/${string}/a2a`
  | `/api/items/agent-flow/${string}/mcp`
  | `/api/items/agent-flow/${string}/publish-mcp`
  | `/api/items/agent-flow/${string}/run`
  | `/api/items/agent-flow/${string}/runs`
  | `/api/items/ai-builder-model/${string}`
  | `/api/items/ai-builder-model/${string}/predict`
  | `/api/items/ai-builder-model/${string}/publish`
  | `/api/items/ai-builder-model/${string}/train`
  | `/api/items/ai-enrich/${string}/preview`
  | `/api/items/ai-enrichment/${string}`
  | `/api/items/ai-enrichment/${string}/preview`
  | `/api/items/ai-enrichment/${string}/run`
  | `/api/items/ai-enrichment/${string}/runs`
  | `/api/items/ai-enrichment/${string}/schema`
  | `/api/items/ai-foundry-project/${string}`
  | `/api/items/ai-red-team/${string}`
  | `/api/items/ai-red-team/${string}/run`
  | `/api/items/ai-search-index/${string}`
  | `/api/items/ai-search-index/${string}/analyze`
  | `/api/items/ai-search-index/${string}/bind`
  | `/api/items/ai-search-index/${string}/indexers`
  | `/api/items/ai-search-index/${string}/search`
  | `/api/items/ai-search-index/${string}/stats`
  | `/api/items/aip-logic/${string}`
  | `/api/items/aip-logic/${string}/bind-ontology`
  | `/api/items/aip-logic/${string}/deploy`
  | `/api/items/aip-logic/${string}/eval`
  | `/api/items/aip-logic/${string}/invoke`
  | `/api/items/aip-logic/${string}/publish`
  | `/api/items/aip-logic/${string}/run-agent`
  | `/api/items/aip-logic/${string}/versions`
  | `/api/items/airflow-job/${string}`
  | `/api/items/airflow-job/${string}/connection`
  | `/api/items/airflow-job/${string}/dag-runs`
  | `/api/items/airflow-job/${string}/dags`
  | `/api/items/airflow-job/${string}/task-logs`
  | `/api/items/analysis-board/${string}/run`
  | `/api/items/apim-api/${string}`
  | `/api/items/apim-api/${string}/operations`
  | `/api/items/apim-api/${string}/revisions`
  | `/api/items/apim-api/${string}/spec`
  | `/api/items/apim-api/${string}/test-call`
  | `/api/items/apim-policy/${string}`
  | `/api/items/apim-product/${string}`
  | `/api/items/apim-product/${string}/apis`
  | `/api/items/apim-product/${string}/subscriptions`
  | `/api/items/automl/${string}/assist`
  | `/api/items/automl/jobs/${string}`
  | `/api/items/azure-sql-database/${string}/aad-admin`
  | `/api/items/azure-sql-database/${string}/connect`
  | `/api/items/azure-sql-database/${string}/copilot`
  | `/api/items/azure-sql-database/${string}/create-db`
  | `/api/items/azure-sql-database/${string}/firewall`
  | `/api/items/azure-sql-database/${string}/get-data`
  | `/api/items/azure-sql-database/${string}/maintenance-configs`
  | `/api/items/azure-sql-database/${string}/mirroring`
  | `/api/items/azure-sql-database/${string}/performance`
  | `/api/items/azure-sql-database/${string}/principal-search`
  | `/api/items/azure-sql-database/${string}/queries`
  | `/api/items/azure-sql-database/${string}/query`
  | `/api/items/azure-sql-database/${string}/query/cancel`
  | `/api/items/azure-sql-database/${string}/replication`
  | `/api/items/azure-sql-database/${string}/restore`
  | `/api/items/azure-sql-database/${string}/scale`
  | `/api/items/azure-sql-database/${string}/search-management`
  | `/api/items/azure-sql-database/${string}/share`
  | `/api/items/azure-sql-database/${string}/sql2025-features`
  | `/api/items/azure-sql-server/${string}/databases`
  | `/api/items/code-report/${string}/content`
  | `/api/items/code-report/${string}/render`
  | `/api/items/compute/${string}`
  | `/api/items/compute/${string}/start`
  | `/api/items/compute/${string}/stop`
  | `/api/items/copilot-studio-action/${string}`
  | `/api/items/copilot-studio-agent/${string}`
  | `/api/items/copilot-studio-agent/${string}/directline-token`
  | `/api/items/copilot-studio-agent/${string}/publish`
  | `/api/items/copilot-studio-analytics/${string}`
  | `/api/items/copilot-studio-channel/${string}/publish`
  | `/api/items/copilot-studio-knowledge/${string}`
  | `/api/items/copilot-studio-topic/${string}`
  | `/api/items/copilot-template-library/${string}`
  | `/api/items/copy-job/${string}`
  | `/api/items/copy-job/${string}/run`
  | `/api/items/copy-job/${string}/runs`
  | `/api/items/copy-job/${string}/watermark`
  | `/api/items/cosmos-db/${string}/gremlin`
  | `/api/items/cosmos-db/${string}/keys`
  | `/api/items/cosmos-db/${string}/metrics`
  | `/api/items/cosmos-gremlin-graph/${string}/query`
  | `/api/items/cypher-graph/${string}/assist`
  | `/api/items/dashboard/${string}`
  | `/api/items/dashboard/${string}/embed-token`
  | `/api/items/dashboard/${string}/pin`
  | `/api/items/dashboard/${string}/tile-embed-token`
  | `/api/items/dashboard/${string}/tile-query`
  | `/api/items/data-agent/${string}`
  | `/api/items/data-agent/${string}/a2a`
  | `/api/items/data-agent/${string}/chat`
  | `/api/items/data-agent/${string}/conversations`
  | `/api/items/data-agent/${string}/copilot`
  | `/api/items/data-agent/${string}/deploy`
  | `/api/items/data-agent/${string}/evaluate`
  | `/api/items/data-agent/${string}/m365-copilot`
  | `/api/items/data-agent/${string}/mcp`
  | `/api/items/data-agent/${string}/publish`
  | `/api/items/data-agent/${string}/publish-mcp`
  | `/api/items/data-agent/${string}/source-schema`
  | `/api/items/data-contract/${string}`
  | `/api/items/data-contract/${string}/introspect`
  | `/api/items/data-contract/${string}/odcs`
  | `/api/items/data-contract/${string}/quality`
  | `/api/items/data-pipeline/${string}`
  | `/api/items/data-pipeline/${string}/approval-logicapp`
  | `/api/items/data-pipeline/${string}/connections`
  | `/api/items/data-pipeline/${string}/copilot`
  | `/api/items/data-pipeline/${string}/debug`
  | `/api/items/data-pipeline/${string}/evaluate`
  | `/api/items/data-pipeline/${string}/export`
  | `/api/items/data-pipeline/${string}/integration-runtimes`
  | `/api/items/data-pipeline/${string}/jobs`
  | `/api/items/data-pipeline/${string}/output`
  | `/api/items/data-pipeline/${string}/publish`
  | `/api/items/data-pipeline/${string}/run`
  | `/api/items/data-pipeline/${string}/triggers`
  | `/api/items/data-pipeline/${string}/validate`
  | `/api/items/data-product-instance/${string}`
  | `/api/items/data-product-instance/${string}/provision`
  | `/api/items/data-product-template/${string}`
  | `/api/items/data-product-template/${string}/instantiate`
  | `/api/items/data-product/${string}/publish-api`
  | `/api/items/data-product/${string}/register-purview`
  | `/api/items/data-quality/${string}`
  | `/api/items/data-quality/${string}/checks`
  | `/api/items/data-quality/${string}/diff`
  | `/api/items/data-quality/${string}/run`
  | `/api/items/databricks-cluster/${string}`
  | `/api/items/databricks-cluster/${string}/events`
  | `/api/items/databricks-cluster/${string}/libraries`
  | `/api/items/databricks-cluster/${string}/state`
  | `/api/items/databricks-job/${string}`
  | `/api/items/databricks-job/${string}/run`
  | `/api/items/databricks-job/${string}/run-output`
  | `/api/items/databricks-job/${string}/runs`
  | `/api/items/databricks-notebook/${string}`
  | `/api/items/databricks-notebook/${string}/command`
  | `/api/items/databricks-notebook/${string}/context`
  | `/api/items/databricks-notebook/${string}/ensure-cluster`
  | `/api/items/databricks-notebook/${string}/run`
  | `/api/items/databricks-notebook/${string}/runs`
  | `/api/items/databricks-notebook/${string}/schedule`
  | `/api/items/databricks-notebook/${string}/versions`
  | `/api/items/databricks-pipeline/${string}/events`
  | `/api/items/databricks-pipeline/${string}/pipelines`
  | `/api/items/databricks-pipeline/${string}/spec`
  | `/api/items/databricks-pipeline/${string}/start`
  | `/api/items/databricks-pipeline/${string}/stop`
  | `/api/items/databricks-pipeline/${string}/updates`
  | `/api/items/databricks-sql-warehouse/${string}/cancel`
  | `/api/items/databricks-sql-warehouse/${string}/clone`
  | `/api/items/databricks-sql-warehouse/${string}/connection`
  | `/api/items/databricks-sql-warehouse/${string}/create`
  | `/api/items/databricks-sql-warehouse/${string}/ctas`
  | `/api/items/databricks-sql-warehouse/${string}/delete`
  | `/api/items/databricks-sql-warehouse/${string}/edit`
  | `/api/items/databricks-sql-warehouse/${string}/iqy`
  | `/api/items/databricks-sql-warehouse/${string}/model`
  | `/api/items/databricks-sql-warehouse/${string}/query`
  | `/api/items/databricks-sql-warehouse/${string}/query-history`
  | `/api/items/databricks-sql-warehouse/${string}/query-profile`
  | `/api/items/databricks-sql-warehouse/${string}/schema`
  | `/api/items/databricks-sql-warehouse/${string}/script-out`
  | `/api/items/databricks-sql-warehouse/${string}/start`
  | `/api/items/databricks-sql-warehouse/${string}/state`
  | `/api/items/databricks-sql-warehouse/${string}/warehouses`
  | `/api/items/dataflow/${string}`
  | `/api/items/dataflow/${string}/refresh`
  | `/api/items/dataset/${string}`
  | `/api/items/dataset/${string}/lineage`
  | `/api/items/dataset/${string}/preview`
  | `/api/items/dataverse-table/${string}`
  | `/api/items/dataverse-table/${string}/business-rules`
  | `/api/items/dataverse-table/${string}/columns`
  | `/api/items/dataverse-table/${string}/keys`
  | `/api/items/dataverse-table/${string}/relationships`
  | `/api/items/dataverse-table/${string}/rows`
  | `/api/items/dataverse-table/${string}/views`
  | `/api/items/dbt-job/${string}`
  | `/api/items/dbt-job/${string}/generate`
  | `/api/items/dbt-job/${string}/run`
  | `/api/items/dbt-job/${string}/runs`
  | `/api/items/digital-twin/${string}`
  | `/api/items/digital-twin/${string}/event-route`
  | `/api/items/digital-twin/${string}/materialize`
  | `/api/items/digital-twin/${string}/query`
  | `/api/items/digital-twin/${string}/source-schema`
  | `/api/items/digital-twin/${string}/time-series`
  | `/api/items/environment/${string}`
  | `/api/items/evaluation/${string}`
  | `/api/items/event-schema-set/${string}`
  | `/api/items/event-schema-set/${string}/check-compat`
  | `/api/items/event-schema-set/${string}/versions`
  | `/api/items/eventhouse/${string}`
  | `/api/items/eventhouse/${string}/capacity`
  | `/api/items/eventhouse/${string}/continuous-export`
  | `/api/items/eventhouse/${string}/database`
  | `/api/items/eventhouse/${string}/ingest`
  | `/api/items/eventhouse/${string}/ingest/preview`
  | `/api/items/eventhouse/${string}/journal`
  | `/api/items/eventhouse/${string}/overview`
  | `/api/items/eventhouse/${string}/policies`
  | `/api/items/eventhouse/${string}/purge`
  | `/api/items/eventstream/${string}`
  | `/api/items/eventstream/${string}/activator`
  | `/api/items/eventstream/${string}/asa-sync`
  | `/api/items/eventstream/${string}/assist`
  | `/api/items/eventstream/${string}/business-events`
  | `/api/items/eventstream/${string}/definition`
  | `/api/items/eventstream/${string}/events`
  | `/api/items/eventstream/${string}/geo-reference`
  | `/api/items/eventstream/${string}/mirror-cdf`
  | `/api/items/eventstream/${string}/provision`
  | `/api/items/eventstream/${string}/publish`
  | `/api/items/eventstream/${string}/source`
  | `/api/items/eventstream/${string}/sql-operator`
  | `/api/items/feature-table/${string}`
  | `/api/items/feature-table/${string}/online`
  | `/api/items/feature-table/${string}/pit-join`
  | `/api/items/feature-table/${string}/serve`
  | `/api/items/fine-tuning-job/${string}`
  | `/api/items/fine-tuning-job/${string}/deploy`
  | `/api/items/fine-tuning-job/${string}/events`
  | `/api/items/fine-tuning-job/${string}/safety-eval`
  | `/api/items/geo-pipeline/${string}/run`
  | `/api/items/gql-graph/${string}/assist`
  | `/api/items/gql-graph/${string}/query`
  | `/api/items/graph-model/${string}`
  | `/api/items/graph-model/${string}/materialize`
  | `/api/items/graph-model/${string}/query`
  | `/api/items/graph-model/${string}/source-schema`
  | `/api/items/graphql-api/${string}`
  | `/api/items/graphql-api/${string}/publish`
  | `/api/items/graphql-api/${string}/query`
  | `/api/items/health-check/${string}`
  | `/api/items/health-check/${string}/action-group`
  | `/api/items/health-check/${string}/history`
  | `/api/items/health-check/${string}/rule`
  | `/api/items/health-check/${string}/rule/${string}`
  | `/api/items/health-check/${string}/rule/${string}/run`
  | `/api/items/health-check/${string}/rule/preview`
  | `/api/items/kql-dashboard/${string}`
  | `/api/items/kql-dashboard/${string}/activator`
  | `/api/items/kql-dashboard/${string}/generate-tile`
  | `/api/items/kql-dashboard/${string}/param-values`
  | `/api/items/kql-dashboard/${string}/run`
  | `/api/items/kql-database/${string}`
  | `/api/items/kql-database/${string}/assist`
  | `/api/items/kql-database/${string}/data-connections`
  | `/api/items/kql-database/${string}/follower`
  | `/api/items/kql-database/${string}/query`
  | `/api/items/kql-database/${string}/schema-graph`
  | `/api/items/kql-database/${string}/tables`
  | `/api/items/kql-queryset/${string}`
  | `/api/items/kql-queryset/${string}/assist`
  | `/api/items/kql-queryset/${string}/run`
  | `/api/items/lakebase-postgres/${string}`
  | `/api/items/lakebase-postgres/${string}/branches`
  | `/api/items/lakebase-postgres/${string}/pgvector`
  | `/api/items/lakebase-postgres/${string}/provision`
  | `/api/items/lakebase-postgres/${string}/query`
  | `/api/items/lakebase-postgres/${string}/replicas`
  | `/api/items/lakebase-postgres/${string}/snapshot`
  | `/api/items/lakehouse/${string}/abfss`
  | `/api/items/lakehouse/${string}/assist`
  | `/api/items/lakehouse/${string}/query`
  | `/api/items/logic-app/${string}`
  | `/api/items/logic-app/${string}/run`
  | `/api/items/logic-app/${string}/runs`
  | `/api/items/loom-app-runtime/${string}`
  | `/api/items/loom-app-runtime/${string}/assist`
  | `/api/items/loom-app-runtime/${string}/build`
  | `/api/items/loom-app-runtime/${string}/context`
  | `/api/items/loom-app-runtime/${string}/deploy`
  | `/api/items/loom-app-runtime/${string}/export`
  | `/api/items/loom-app-runtime/${string}/git-credential`
  | `/api/items/loom-app-runtime/${string}/lifecycle`
  | `/api/items/loom-app-runtime/${string}/logs`
  | `/api/items/loom-app-runtime/${string}/mcp`
  | `/api/items/loom-app-runtime/${string}/monitoring`
  | `/api/items/loom-app-runtime/${string}/publish-api`
  | `/api/items/loom-app-runtime/${string}/publish-mcp`
  | `/api/items/loom-app-runtime/${string}/reconcile`
  | `/api/items/loom-app-runtime/${string}/resources`
  | `/api/items/loom-app/${string}`
  | `/api/items/loom-app/${string}/candidates`
  | `/api/items/loom-app/${string}/publish`
  | `/api/items/loom-app/${string}/render`
  | `/api/items/map/${string}`
  | `/api/items/map/${string}/geocode`
  | `/api/items/map/${string}/map-token`
  | `/api/items/mapping-dataflow/${string}/debug/preview`
  | `/api/items/mapping-dataflow/${string}/debug/schema`
  | `/api/items/mapping-dataflow/${string}/debug/session`
  | `/api/items/mapping-dataflow/${string}/debug/stats`
  | `/api/items/materialized-lake-view/${string}/adf-pipeline`
  | `/api/items/materialized-lake-view/${string}/assist`
  | `/api/items/materialized-lake-view/${string}/lineage`
  | `/api/items/materialized-lake-view/${string}/preview`
  | `/api/items/materialized-lake-view/${string}/refresh`
  | `/api/items/materialized-lake-view/${string}/runs`
  | `/api/items/mirrored-database/${string}`
  | `/api/items/mirrored-database/${string}/assist`
  | `/api/items/mirrored-database/${string}/lifecycle`
  | `/api/items/mirrored-database/${string}/monitor`
  | `/api/items/mirrored-database/${string}/open-mirror`
  | `/api/items/mirrored-database/${string}/sources`
  | `/api/items/mirrored-database/${string}/sql-endpoint`
  | `/api/items/mirrored-database/${string}/state`
  | `/api/items/mirrored-database/${string}/tables`
  | `/api/items/mirrored-databricks/${string}`
  | `/api/items/mirrored-databricks/${string}/catalog`
  | `/api/items/mirrored-databricks/${string}/sql-endpoint`
  | `/api/items/ml-experiment/${string}`
  | `/api/items/ml-experiment/${string}/assist`
  | `/api/items/ml-experiment/${string}/register`
  | `/api/items/ml-experiment/${string}/runs`
  | `/api/items/ml-experiment/${string}/runs/${string}/metrics`
  | `/api/items/ml-model/${string}`
  | `/api/items/ml-model/${string}/bind`
  | `/api/items/ml-model/${string}/endpoint`
  | `/api/items/ml-model/${string}/predict`
  | `/api/items/ml-model/${string}/predict/history`
  | `/api/items/ml-model/${string}/predict/status`
  | `/api/items/ml-model/${string}/register`
  | `/api/items/ml-model/${string}/stage`
  | `/api/items/model-serving-endpoint/${string}`
  | `/api/items/model-serving-endpoint/${string}/invoke`
  | `/api/items/model-serving-endpoint/${string}/metrics`
  | `/api/items/model-serving-endpoint/${string}/traffic`
  | `/api/items/mounted-adf/${string}`
  | `/api/items/mounted-adf/${string}/run`
  | `/api/items/notebook/${string}`
  | `/api/items/notebook/${string}/deploy-app`
  | `/api/items/notebook/${string}/execute-spark`
  | `/api/items/notebook/${string}/jobs`
  | `/api/items/notebook/${string}/run`
  | `/api/items/notebook/${string}/runs/${string}`
  | `/api/items/notebook/${string}/runs/${string}/log`
  | `/api/items/notepad/${string}/run-block`
  | `/api/items/ontology-sdk/${string}`
  | `/api/items/ontology-sdk/${string}/bind-ontology`
  | `/api/items/ontology-sdk/${string}/generate`
  | `/api/items/ontology-sdk/${string}/publish`
  | `/api/items/ontology-sdk/${string}/query`
  | `/api/items/ontology/${string}`
  | `/api/items/ontology/${string}/activator`
  | `/api/items/ontology/${string}/approvals`
  | `/api/items/ontology/${string}/audit-export`
  | `/api/items/ontology/${string}/bind`
  | `/api/items/ontology/${string}/datasource`
  | `/api/items/ontology/${string}/explore`
  | `/api/items/ontology/${string}/justifications`
  | `/api/items/ontology/${string}/links`
  | `/api/items/ontology/${string}/objects`
  | `/api/items/ontology/${string}/objects/${string}/view`
  | `/api/items/ontology/${string}/resolve`
  | `/api/items/ontology/${string}/run-action`
  | `/api/items/ontology/${string}/sync`
  | `/api/items/operations-agent/${string}`
  | `/api/items/operations-agent/${string}/deploy`
  | `/api/items/operations-agent/${string}/rules`
  | `/api/items/operations-agent/${string}/run`
  | `/api/items/paginated-report/${string}`
  | `/api/items/paginated-report/${string}/definition`
  | `/api/items/paginated-report/${string}/export`
  | `/api/items/paginated-report/${string}/preview`
  | `/api/items/paginated-report/${string}/rdl`
  | `/api/items/paginated-report/${string}/render`
  | `/api/items/plan/${string}`
  | `/api/items/plan/${string}/approval`
  | `/api/items/plan/${string}/approval-callback`
  | `/api/items/plan/${string}/binding`
  | `/api/items/plan/${string}/copilot`
  | `/api/items/plan/${string}/model`
  | `/api/items/plan/${string}/writeback`
  | `/api/items/postgres-flexible-server/${string}/databases`
  | `/api/items/postgres-flexible-server/${string}/firewall`
  | `/api/items/postgres-flexible-server/${string}/query`
  | `/api/items/power-app/${string}`
  | `/api/items/power-app/${string}/publish`
  | `/api/items/power-app/${string}/state`
  | `/api/items/power-automate-flow/${string}`
  | `/api/items/power-automate-flow/${string}/definition`
  | `/api/items/power-automate-flow/${string}/run`
  | `/api/items/power-automate-flow/${string}/runs`
  | `/api/items/power-page/${string}`
  | `/api/items/prompt-flow/${string}`
  | `/api/items/prompt-flow/${string}/run`
  | `/api/items/rayfin-app/${string}`
  | `/api/items/rayfin-app/${string}/render`
  | `/api/items/release-environment/${string}`
  | `/api/items/release-environment/${string}/approve`
  | `/api/items/release-environment/${string}/arm`
  | `/api/items/release-environment/${string}/promote`
  | `/api/items/release-environment/${string}/swap`
  | `/api/items/report/${string}`
  | `/api/items/report/${string}/ai-visual`
  | `/api/items/report/${string}/connector-objects`
  | `/api/items/report/${string}/connector-preview`
  | `/api/items/report/${string}/data-source`
  | `/api/items/report/${string}/definition`
  | `/api/items/report/${string}/embed-token`
  | `/api/items/report/${string}/endorsement`
  | `/api/items/report/${string}/export`
  | `/api/items/report/${string}/fields`
  | `/api/items/report/${string}/map-token`
  | `/api/items/report/${string}/native-query`
  | `/api/items/report/${string}/pages`
  | `/api/items/report/${string}/paginated-embed-token`
  | `/api/items/report/${string}/powerbi-copilot`
  | `/api/items/report/${string}/profile`
  | `/api/items/report/${string}/publish`
  | `/api/items/report/${string}/query`
  | `/api/items/report/${string}/refresh`
  | `/api/items/report/${string}/script-visual`
  | `/api/items/report/${string}/sensitivity`
  | `/api/items/report/${string}/subscriptions`
  | `/api/items/report/${string}/subscriptions/${string}`
  | `/api/items/report/${string}/subscriptions/${string}/logs`
  | `/api/items/report/${string}/visual`
  | `/api/items/report/${string}/visual-data`
  | `/api/items/scorecard/${string}`
  | `/api/items/scorecard/${string}/config`
  | `/api/items/scorecard/${string}/goals`
  | `/api/items/scorecard/${string}/metric-value`
  | `/api/items/semantic-model/${string}`
  | `/api/items/semantic-model/${string}/content`
  | `/api/items/semantic-model/${string}/copilot-structure`
  | `/api/items/semantic-model/${string}/datasource`
  | `/api/items/semantic-model/${string}/dax-query`
  | `/api/items/semantic-model/${string}/describe-bulk`
  | `/api/items/semantic-model/${string}/direct-lake`
  | `/api/items/semantic-model/${string}/embed-token`
  | `/api/items/semantic-model/${string}/ingest`
  | `/api/items/semantic-model/${string}/measures`
  | `/api/items/semantic-model/${string}/model`
  | `/api/items/semantic-model/${string}/model-health`
  | `/api/items/semantic-model/${string}/prep-for-ai`
  | `/api/items/semantic-model/${string}/refresh`
  | `/api/items/semantic-model/${string}/refresh-policy`
  | `/api/items/semantic-model/${string}/refresh-schedule`
  | `/api/items/semantic-model/${string}/refreshes`
  | `/api/items/semantic-model/${string}/roles`
  | `/api/items/semantic-model/${string}/semantic-link`
  | `/api/items/semantic-model/${string}/synonyms`
  | `/api/items/semantic-model/${string}/take-over`
  | `/api/items/semantic-model/${string}/verified-queries`
  | `/api/items/slate-app/${string}`
  | `/api/items/slate-app/${string}/generate`
  | `/api/items/slate-app/${string}/publish`
  | `/api/items/slate-app/${string}/query/run`
  | `/api/items/spark-environment/${string}`
  | `/api/items/spark-job-definition/${string}`
  | `/api/items/spark-job-definition/${string}/files`
  | `/api/items/spark-job-definition/${string}/lineage-targets`
  | `/api/items/spark-job-definition/${string}/runs`
  | `/api/items/spark-job-definition/${string}/runs/${string}`
  | `/api/items/spark-job-definition/${string}/runs/${string}/cancel`
  | `/api/items/spark-job-definition/${string}/submit`
  | `/api/items/sql-analytics-endpoint/${string}/objects`
  | `/api/items/sql-analytics-endpoint/${string}/query`
  | `/api/items/sql-analytics-endpoint/${string}/schema`
  | `/api/items/sql-database/${string}`
  | `/api/items/stream-analytics-job/${string}`
  | `/api/items/stream-analytics-job/${string}/assist`
  | `/api/items/stream-analytics-job/${string}/inputs`
  | `/api/items/stream-analytics-job/${string}/metrics`
  | `/api/items/stream-analytics-job/${string}/outputs`
  | `/api/items/stream-analytics-job/${string}/query`
  | `/api/items/stream-analytics-job/${string}/state`
  | `/api/items/stream-analytics-job/${string}/test`
  | `/api/items/synapse-dedicated-sql-pool/${string}/cancel`
  | `/api/items/synapse-dedicated-sql-pool/${string}/clone`
  | `/api/items/synapse-dedicated-sql-pool/${string}/connection`
  | `/api/items/synapse-dedicated-sql-pool/${string}/model`
  | `/api/items/synapse-dedicated-sql-pool/${string}/query`
  | `/api/items/synapse-dedicated-sql-pool/${string}/query-history`
  | `/api/items/synapse-dedicated-sql-pool/${string}/resume`
  | `/api/items/synapse-dedicated-sql-pool/${string}/schema`
  | `/api/items/synapse-dedicated-sql-pool/${string}/script-out`
  | `/api/items/synapse-dedicated-sql-pool/${string}/state`
  | `/api/items/synapse-notebook/${string}`
  | `/api/items/synapse-pipeline/${string}`
  | `/api/items/synapse-pipeline/${string}/bind`
  | `/api/items/synapse-pipeline/${string}/connections`
  | `/api/items/synapse-pipeline/${string}/copilot`
  | `/api/items/synapse-pipeline/${string}/debug`
  | `/api/items/synapse-pipeline/${string}/run`
  | `/api/items/synapse-pipeline/${string}/runs`
  | `/api/items/synapse-pipeline/${string}/triggers`
  | `/api/items/synapse-serverless-sql-pool/${string}/cancel`
  | `/api/items/synapse-serverless-sql-pool/${string}/connection`
  | `/api/items/synapse-serverless-sql-pool/${string}/iqy`
  | `/api/items/synapse-serverless-sql-pool/${string}/objects`
  | `/api/items/synapse-serverless-sql-pool/${string}/query`
  | `/api/items/synapse-serverless-sql-pool/${string}/schema`
  | `/api/items/synapse-spark-pool/${string}`
  | `/api/items/synapse-spark-pool/${string}/auto-pause`
  | `/api/items/synapse-spark-pool/${string}/config`
  | `/api/items/synapse-spark-pool/${string}/runs`
  | `/api/items/synapse-spark-pool/${string}/scale`
  | `/api/items/synapse-spark-pool/${string}/state`
  | `/api/items/synapse-spark-pool/${string}/submit`
  | `/api/items/synthetic-data/${string}`
  | `/api/items/synthetic-data/${string}/catalog`
  | `/api/items/synthetic-data/${string}/generate`
  | `/api/items/synthetic-data/${string}/preview`
  | `/api/items/synthetic-data/${string}/sources`
  | `/api/items/tapestry/${string}/geo`
  | `/api/items/tapestry/${string}/link`
  | `/api/items/tapestry/${string}/timeline`
  | `/api/items/tracing/${string}`
  | `/api/items/transformation-project/${string}`
  | `/api/items/user-data-function/${string}`
  | `/api/items/user-data-function/${string}/invoke`
  | `/api/items/variable-library/${string}`
  | `/api/items/variable-library/${string}/resolve`
  | `/api/items/vector-store/${string}/index`
  | `/api/items/vector-store/${string}/search`
  | `/api/items/vector-store/${string}/sync`
  | `/api/items/warehouse/${string}/cancel`
  | `/api/items/warehouse/${string}/clone`
  | `/api/items/warehouse/${string}/copy-into`
  | `/api/items/warehouse/${string}/iqy`
  | `/api/items/warehouse/${string}/model`
  | `/api/items/warehouse/${string}/query`
  | `/api/items/warehouse/${string}/query-acceleration`
  | `/api/items/warehouse/${string}/restore-points`
  | `/api/items/warehouse/${string}/schema`
  | `/api/items/warehouse/${string}/script-out`
  | `/api/items/warehouse/${string}/snapshots`
  | `/api/items/warehouse/${string}/time-travel`
  | `/api/items/workshop-app/${string}`
  | `/api/items/workshop-app/${string}/bind-ontology`
  | `/api/items/workshop-app/${string}/eject`
  | `/api/items/workshop-app/${string}/publish`
  | `/api/items/workshop-app/${string}/run-action`
  | `/api/landing-zones/${string}/attach`
  | `/api/landing-zones/${string}/attach/preflight`
  | `/api/landing-zones/${string}/services`
  | `/api/landing-zones/${string}/services/${string}`
  | `/api/loom/compute-targets/${string}/${string}`
  | `/api/maps/tiles/${string}`
  | `/api/marketplace/products/${string}`
  | `/api/marketplace/products/${string}/certify`
  | `/api/marketplace/products/${string}/subscribe`
  | `/api/marketplace/sharing/providers/${string}`
  | `/api/marketplace/sharing/recipients/${string}`
  | `/api/marketplace/sharing/shares/${string}`
  | `/api/marketplace/subscriptions/${string}`
  | `/api/marketplace/subscriptions/${string}/keys`
  | `/api/marketplace/subscriptions/${string}/keys/regenerate`
  | `/api/mesh/a2a/${string}/card`
  | `/api/mesh/agents/${string}`
  | `/api/notebook/${string}/assist`
  | `/api/notebook/${string}/contents`
  | `/api/notebook/${string}/execute`
  | `/api/notebook/${string}/lsp`
  | `/api/notebook/${string}/schedule`
  | `/api/notebook/${string}/session`
  | `/api/notebook/${string}/wrangler-ai`
  | `/api/observability/incidents/${string}`
  | `/api/observability/incidents/${string}/transition`
  | `/api/observability/monitors/${string}/observe`
  | `/api/onelake/${string}`
  | `/api/powerbi/${string}`
  | `/api/scheduler/${string}`
  | `/api/scheduler/${string}/run`
  | `/api/scheduler/${string}/runs`
  | `/api/scim/v2/Groups/${string}`
  | `/api/scim/v2/Users/${string}`
  | `/api/spark-environment/${string}/attach`
  | `/api/spark-environment/${string}/libraries`
  | `/api/spark-environment/${string}/publish`
  | `/api/spark-environment/${string}/validate`
  | `/api/synapse/datasets/${string}`
  | `/api/synapse/kqlscripts/${string}`
  | `/api/synapse/kqlscripts/${string}/run`
  | `/api/synapse/linkedservices/${string}`
  | `/api/synapse/notebooks/${string}`
  | `/api/synapse/notebooks/${string}/run-cell`
  | `/api/synapse/sparkjobdefinitions/${string}`
  | `/api/synapse/sparkjobdefinitions/${string}/run`
  | `/api/transform/${string}/apply`
  | `/api/transform/${string}/diff`
  | `/api/transform/${string}/environments`
  | `/api/transform/${string}/history`
  | `/api/transform/${string}/plan`
  | `/api/transform/${string}/run`
  | `/api/workspaces/${string}`
  | `/api/workspaces/${string}/agent-config`
  | `/api/workspaces/${string}/clone`
  | `/api/workspaces/${string}/export`
  | `/api/workspaces/${string}/folders`
  | `/api/workspaces/${string}/image`
  | `/api/workspaces/${string}/import`
  | `/api/workspaces/${string}/items`
  | `/api/workspaces/${string}/items/${string}`
  | `/api/workspaces/${string}/permissions`
  | `/api/workspaces/${string}/powerbi-mapping`
  | `/api/workspaces/${string}/role-assignments`
  | `/api/workspaces/${string}/role-assignments/${string}`
  | `/api/workspaces/${string}/scm`
  | `/api/workspaces/${string}/task-flows`
  | `/api/workspaces/${string}/task-flows/${string}`
  | `/api/workspaces/${string}/task-flows/${string}/run`
  | `/api/workspaces/${string}/time-branches`
  | `/api/workspaces/${string}/time-branches/${string}`;

/** Every BFF route. Dynamic segments are `${string}`. */
export type ApiRoutePattern = StaticApiRoute | DynamicApiRoute;

/**
 * The compile-time error surface, kept as a NAMED alias for documentation and
 * for tests to reference. Note that `ValidateApiPath` inlines the same shape
 * rather than referencing this alias — see the note there.
 */
export type UnknownApiRoute<S extends string> = {
  __loomUnknownApiRoute: `No BFF route matches "${S}". Add the app/api/…/route.ts, or fix the path.`;
};

/** Strip `?query` / `#hash` at the type level so callers may pass either. */
type StripSuffix<S extends string> =
  S extends `${infer H}?${string}` ? StripSuffix<H>
  : S extends `${infer H}#${string}` ? H
  : S;

/**
 * R16 — the `clientFetch` path guard.
 *
 *   - a NON-LITERAL `string` passes through unconstrained (`string extends S`
 *     holds only for the wide type). Those are R17's remit, not the type
 *     system's — narrowing them would break every computed URL in the tree.
 *   - a literal that is not an /api path passes through (absolute URLs, blob:).
 *   - a CONCRETE literal /api path must match a static route, else a dynamic one.
 *   - a PARTIALLY-concrete path — the shape TS infers for
 *     `const u = \`/api/foo/report${qs}\`` — is neither `string` nor a member of
 *     the union, so it needs the OTHER assignability direction: it is accepted
 *     when at least one real route is assignable TO it (i.e. some route could
 *     be what it resolves to). Without this clause five legitimate call sites
 *     that append a query string to a variable failed to compile — the union
 *     carries `'/api/foo/report'`, and `\`/api/foo/report${string}\`` is wider
 *     than that member, not narrower. `[X] extends [never]` is bracketed to
 *     suppress distribution, so an empty Extract reads as "no route matches"
 *     rather than silently distributing to `never` and passing.
 *
 * The failure branch INLINES the error object rather than referencing the
 * `UnknownApiRoute` alias. TypeScript prints an alias by NAME and will not
 * expand it, so the alias form produced
 *   `… not assignable to 'URL | UnknownApiRoute<"/api/loom/workspacs">'`
 * — the path was there, but the remedy was not. Inlining makes tsc print the
 * structural type, so the message itself lands in the diagnostic.
 */
export type ValidateApiPath<S extends string> =
  string extends S ? S
  : S extends `/api/${string}`
    ? (StripSuffix<S> extends StaticApiRoute
        ? S
        : StripSuffix<S> extends DynamicApiRoute
          ? S
          : [Extract<ApiRoutePattern, StripSuffix<S>>] extends [never]
            ? { __loomUnknownApiRoute: `No BFF route matches "${S}" — add the app/api/…/route.ts, or fix the path` }
            : S)
    : S;
