'use client';

/**
 * RayfinAppEditor — author a Rayfin app backend (Microsoft Fabric "apps"
 * workload, Build 2026 preview) and generate the real @microsoft/rayfin-core
 * SDK model + the exact CLI command sequence to deploy it to a Fabric workspace.
 *
 * Rayfin is an open-source SDK + CLI: you define entities/services/auth in
 * TypeScript and `npx rayfin up` deploys an app backend (database, auth, Data
 * APIs via DAB, storage, hosting) to Fabric, with data landing in OneLake under
 * your tenant's identity + governance. The CLI runs on the developer's machine,
 * so Loom authors the spec + emits the model and commands (the no-vaporware
 * honest path — like the deploy planner generating bicep). The spec persists on
 * the Cosmos item so it round-trips.
 *
 * Refs (preview): https://learn.microsoft.com/fabric/apps/overview ·
 *   https://github.com/microsoft/rayfin · npm @microsoft/rayfin-cli
 */

import { useCallback, useEffect, useMemo, useState } from 'react';
import {
  makeStyles, tokens, Button, Input, Field, Switch, Subtitle2, Body1, Caption1,
  Badge, MessageBar, MessageBarBody, MessageBarTitle, Dropdown, Option, Divider,
  Spinner, Tooltip, useId, useToastController, Toast, ToastTitle, Toaster,
} from '@fluentui/react-components';
import {
  Add20Regular, Delete20Regular, Copy20Regular, Checkmark20Regular, Save20Regular,
  Rocket20Regular, Open20Regular,
} from '@fluentui/react-icons';
import { MonacoTextarea } from '@/lib/components/editor/monaco-textarea';

type FieldType = 'text' | 'boolean' | 'date' | 'number';
interface EntityField { name: string; type: FieldType; }
interface RayfinEntity { name: string; fields: EntityField[]; }
interface RayfinSpec {
  appName: string;
  workspaceName: string;
  services: { database: boolean; storage: boolean };
  auth: 'fabric';
  staticHosting: boolean;
  entities: RayfinEntity[];
}

const DEFAULT_SPEC: RayfinSpec = {
  appName: 'my-app',
  workspaceName: '',
  services: { database: true, storage: false },
  auth: 'fabric',
  staticHosting: true,
  entities: [{ name: 'Todo', fields: [{ name: 'title', type: 'text' }, { name: 'done', type: 'boolean' }, { name: 'dueDate', type: 'date' }] }],
};

const useStyles = makeStyles({
  root: { display: 'flex', flexDirection: 'column', gap: '12px', padding: '12px', minWidth: 0, maxWidth: '100%' },
  row: { display: 'flex', gap: '12px', flexWrap: 'wrap', alignItems: 'flex-end' },
  cols: { display: 'grid', gridTemplateColumns: 'minmax(0,1fr) minmax(0,1fr)', gap: '16px', minWidth: 0 },
  card: {
    padding: '16px', border: `1px solid ${tokens.colorNeutralStroke2}`,
    borderRadius: tokens.borderRadiusLarge, backgroundColor: tokens.colorNeutralBackground1,
    display: 'flex', flexDirection: 'column', gap: '10px', minWidth: 0,
  },
  entity: { border: `1px solid ${tokens.colorNeutralStroke2}`, borderRadius: '6px', padding: '10px', display: 'flex', flexDirection: 'column', gap: '6px' },
  fieldRow: { display: 'flex', gap: '8px', alignItems: 'center' },
  code: {
    fontFamily: 'Consolas, monospace', fontSize: '12px', whiteSpace: 'pre', overflowX: 'auto',
    background: tokens.colorNeutralBackground3, border: `1px solid ${tokens.colorNeutralStroke2}`,
    borderRadius: '6px', padding: '12px', margin: 0,
  },
  head: { display: 'flex', alignItems: 'center', gap: '8px' },
});

function CopyBtn({ text }: { text: string }) {
  const [done, setDone] = useState(false);
  return (
    <Button size="small" appearance="outline" icon={done ? <Checkmark20Regular /> : <Copy20Regular />}
      onClick={async () => { try { await navigator.clipboard.writeText(text); setDone(true); setTimeout(() => setDone(false), 1600); } catch { /* manual */ } }}>
      {done ? 'Copied' : 'Copy'}
    </Button>
  );
}

const DECO: Record<FieldType, string> = { text: 'text', boolean: 'boolean', date: 'date', number: 'number' };
const TS_TYPE: Record<FieldType, string> = { text: 'string', boolean: 'boolean', date: 'Date', number: 'number' };

function pascal(s: string): string {
  return (s || 'Entity').replace(/[^A-Za-z0-9]+/g, ' ').trim().split(' ').map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join('') || 'Entity';
}

function generateModel(spec: RayfinSpec): string {
  const used = Array.from(new Set(spec.entities.flatMap((e) => e.fields.map((f) => DECO[f.type])))).sort();
  const imports = ['entity', ...used].join(', ');
  const blocks = spec.entities.map((e) => {
    const cls = pascal(e.name);
    const props = e.fields.map((f) => `  @${DECO[f.type]}() ${f.name || 'field'}!: ${TS_TYPE[f.type]};`).join('\n');
    return `@entity()\nexport class ${cls} {\n${props || '  // add fields'}\n}`;
  }).join('\n\n');
  return `// rayfin/model.ts — generated by CSA Loom (verify against the current @microsoft/rayfin-core API)\nimport { ${imports} } from '@microsoft/rayfin-core';\n\n${blocks}\n`;
}

function generateCommands(spec: RayfinSpec): string {
  const services = [spec.services.database ? 'db' : '', spec.services.storage ? 'storage' : ''].filter(Boolean).join(',') || 'db';
  const ws = spec.workspaceName?.trim();
  const lines = [
    '# 1) Scaffold a Rayfin app (creates the project + Fabric workspace binding)',
    `npm create @microsoft/rayfin@latest ${spec.appName}${ws ? ` --workspace "${ws}"` : ''}`,
    `cd ${spec.appName}`,
    '',
    '# 2) (or, in an existing project) initialize Rayfin with the services above',
    `npx rayfin init ${spec.appName} --services ${services} --auth-methods ${spec.auth}${spec.staticHosting ? ' --static-hosting' : ''}`,
    '',
    '# 3) Paste the generated entities into rayfin/model.ts, then deploy to Fabric',
    'npx rayfin up',
  ];
  return lines.join('\n');
}

export function RayfinAppEditor({ id }: { item?: unknown; id: string }) {
  const s = useStyles();
  const toasterId = useId('rayfin-toaster');
  const { dispatchToast } = useToastController(toasterId);
  const [spec, setSpec] = useState<RayfinSpec>(DEFAULT_SPEC);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    let alive = true;
    (async () => {
      try {
        const r = await fetch(`/api/items/rayfin-app/${encodeURIComponent(id)}`);
        const j = await r.json().catch(() => ({}));
        const saved = (j?.state?.spec || j?.item?.state?.spec || j?.definition?.state?.spec) as RayfinSpec | undefined;
        if (alive && saved && Array.isArray(saved.entities)) setSpec({ ...DEFAULT_SPEC, ...saved });
      } catch { /* keep default */ }
      finally { if (alive) setLoading(false); }
    })();
    return () => { alive = false; };
  }, [id]);

  const model = useMemo(() => generateModel(spec), [spec]);
  const commands = useMemo(() => generateCommands(spec), [spec]);

  const save = useCallback(async () => {
    setSaving(true);
    try {
      const r = await fetch(`/api/items/rayfin-app/${encodeURIComponent(id)}`, {
        method: 'PUT', headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ state: { spec } }),
      });
      dispatchToast(<Toast><ToastTitle>{r.ok ? 'Saved' : 'Save failed'}</ToastTitle></Toast>, { intent: r.ok ? 'success' : 'error' });
    } catch (e: any) {
      dispatchToast(<Toast><ToastTitle>Save failed: {e?.message || String(e)}</ToastTitle></Toast>, { intent: 'error' });
    } finally { setSaving(false); }
  }, [id, spec, dispatchToast]);

  const patch = (p: Partial<RayfinSpec>) => setSpec((prev) => ({ ...prev, ...p }));
  const patchEntity = (i: number, e: Partial<RayfinEntity>) =>
    setSpec((prev) => ({ ...prev, entities: prev.entities.map((x, idx) => idx === i ? { ...x, ...e } : x) }));

  if (loading) return <div className={s.root}><Spinner label="Loading Rayfin app…" /></div>;

  return (
    <div className={s.root}>
      <Toaster toasterId={toasterId} />
      <div className={s.head}>
        <Rocket20Regular />
        <Subtitle2>Rayfin app</Subtitle2>
        <Badge appearance="outline" color="warning">Preview</Badge>
        <div style={{ marginLeft: 'auto', display: 'flex', gap: 8 }}>
          <Button appearance="outline" icon={<Open20Regular />} as="a" href="https://learn.microsoft.com/fabric/apps/overview" target="_blank">Docs</Button>
          <Button appearance="outline" icon={<Open20Regular />} as="a" href="https://github.com/microsoft/rayfin" target="_blank">Repo</Button>
          <Button appearance="primary" icon={<Save20Regular />} onClick={save} disabled={saving}>{saving ? 'Saving…' : 'Save'}</Button>
        </div>
      </div>

      <MessageBar intent="warning">
        <MessageBarBody>
          <MessageBarTitle>Rayfin is a preview SDK + CLI that runs on your dev machine.</MessageBarTitle>
          Define the backend below — Loom generates the real <code>@microsoft/rayfin-core</code> model and the exact
          CLI commands. Run them locally (<code>npx rayfin up</code>) to deploy the app backend to your Fabric
          workspace; data lands in OneLake under your tenant's identity + governance.
        </MessageBarBody>
      </MessageBar>

      <div className={s.cols}>
        {/* Left — spec */}
        <div className={s.card}>
          <Subtitle2>Backend definition</Subtitle2>
          <div className={s.row}>
            <Field label="App name"><Input value={spec.appName} onChange={(_, d) => patch({ appName: d.value.replace(/\s+/g, '-').toLowerCase() })} /></Field>
            <Field label="Fabric workspace (optional)"><Input value={spec.workspaceName} placeholder="workspace name" onChange={(_, d) => patch({ workspaceName: d.value })} /></Field>
          </div>
          <div className={s.row}>
            <Field label="Database"><Switch checked={spec.services.database} onChange={(_, d) => patch({ services: { ...spec.services, database: !!d.checked } })} /></Field>
            <Field label="Storage"><Switch checked={spec.services.storage} onChange={(_, d) => patch({ services: { ...spec.services, storage: !!d.checked } })} /></Field>
            <Field label="Static hosting"><Switch checked={spec.staticHosting} onChange={(_, d) => patch({ staticHosting: !!d.checked })} /></Field>
            <Field label="Auth"><Input readOnly value="Fabric (Entra SSO)" /></Field>
          </div>

          <Divider />
          <div className={s.head}>
            <Body1><strong>Entities</strong></Body1>
            <Button size="small" appearance="outline" icon={<Add20Regular />}
              onClick={() => patch({ entities: [...spec.entities, { name: `Entity${spec.entities.length + 1}`, fields: [{ name: 'name', type: 'text' }] }] })}>Add entity</Button>
          </div>
          {spec.entities.map((e, i) => (
            <div key={i} className={s.entity}>
              <div className={s.fieldRow}>
                <Input value={e.name} onChange={(_, d) => patchEntity(i, { name: d.value })} />
                <Button size="small" appearance="subtle" icon={<Add20Regular />}
                  onClick={() => patchEntity(i, { fields: [...e.fields, { name: 'field', type: 'text' }] })}>Field</Button>
                <Tooltip content="Remove entity" relationship="label">
                  <Button size="small" appearance="subtle" icon={<Delete20Regular />}
                    onClick={() => patch({ entities: spec.entities.filter((_, idx) => idx !== i) })} />
                </Tooltip>
              </div>
              {e.fields.map((f, fi) => (
                <div key={fi} className={s.fieldRow} style={{ paddingLeft: 16 }}>
                  <Input size="small" value={f.name} onChange={(_, d) => patchEntity(i, { fields: e.fields.map((x, xi) => xi === fi ? { ...x, name: d.value } : x) })} />
                  <Dropdown size="small" value={f.type} selectedOptions={[f.type]}
                    onOptionSelect={(_, d) => patchEntity(i, { fields: e.fields.map((x, xi) => xi === fi ? { ...x, type: (d.optionValue as FieldType) } : x) })}>
                    {(['text', 'boolean', 'date', 'number'] as FieldType[]).map((t) => <Option key={t} value={t}>{t}</Option>)}
                  </Dropdown>
                  <Button size="small" appearance="subtle" icon={<Delete20Regular />}
                    onClick={() => patchEntity(i, { fields: e.fields.filter((_, xi) => xi !== fi) })} />
                </div>
              ))}
            </div>
          ))}
        </div>

        {/* Right — generated artifacts */}
        <div className={s.card}>
          <div className={s.head}><Subtitle2>rayfin/model.ts</Subtitle2><div style={{ marginLeft: 'auto' }}><CopyBtn text={model} /></div></div>
          <MonacoTextarea value={model} onChange={() => { /* read-only */ }} language="typescript" height={240} readOnly lineNumbers={false} ariaLabel="Generated Rayfin model" />
          <Caption1>Decorator API per @microsoft/rayfin-core — verify against the current SDK version (preview).</Caption1>

          <Divider />
          <div className={s.head}><Subtitle2>Deploy commands</Subtitle2><div style={{ marginLeft: 'auto' }}><CopyBtn text={commands} /></div></div>
          <pre className={s.code}>{commands}</pre>
        </div>
      </div>
    </div>
  );
}
