/**
 * compileGraph — unit tests.
 *
 * Verifies the visual-query canvas graph compiles to valid SQL for the guided
 * shapes (source, filter, choose columns, keep top rows, group by + aggregate,
 * merge/join) in both dialects (T-SQL and Spark SQL), plus the multi-step
 * WITH chain and dead-branch pruning.
 */
import { describe, it, expect } from 'vitest';
import {
  compileGraph,
  type VqGraph,
  type VqNode,
} from '../visual-query-compiler';

const source = (id: string, schema: string, table: string): VqNode => ({
  id,
  kind: 'source',
  inputs: [],
  schema,
  table,
});

describe('compileGraph', () => {
  it('emits a placeholder for an empty graph', () => {
    const sql = compileGraph({ nodes: [] }, 'tsql');
    expect(sql).toContain('Add a table to the canvas');
  });

  it('compiles a single source to a bare SELECT * (no CTE)', () => {
    const g: VqGraph = { nodes: [source('s1', 'dbo', 'fact_sale')] };
    const sql = compileGraph(g, 'tsql');
    expect(sql).toContain('SELECT * FROM [dbo].[fact_sale]');
    expect(sql).not.toContain('WITH ');
    expect(sql).toContain('Generated by CSA Loom');
  });

  it('compiles source → filter to a WHERE clause', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'fact_sale'),
        { id: 'f1', kind: 'filter', inputs: ['s1'], whereExpression: '[amount] > 1000' },
      ],
    };
    const sql = compileGraph(g, 'tsql');
    expect(sql).toContain('WITH ');
    expect(sql).toContain('FROM [dbo].[fact_sale]');
    expect(sql).toContain('WHERE [amount] > 1000');
    expect(sql).toMatch(/SELECT \* FROM q2_f1\s*$/m);
  });

  it('compiles source → choose columns to an explicit column list', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'dimension_city'),
        { id: 'c1', kind: 'select-columns', inputs: ['s1'], columns: ['CityKey', 'CityName'] },
      ],
    };
    const sql = compileGraph(g, 'tsql');
    expect(sql).toContain('SELECT [CityKey], [CityName] FROM q1_s1');
  });

  it('compiles keep-top-rows to TOP (n) for T-SQL and LIMIT for Spark SQL', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'fact_sale'),
        { id: 't1', kind: 'keep-top-rows', inputs: ['s1'], topN: 50 },
      ],
    };
    expect(compileGraph(g, 'tsql')).toContain('SELECT TOP (50) * FROM q1_s1');
    expect(compileGraph(g, 'sparksql')).toContain('SELECT * FROM q1_s1 LIMIT 50');
  });

  it('compiles group-by with SUM aggregate', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'fact_sale'),
        {
          id: 'g1',
          kind: 'group-by',
          inputs: ['s1'],
          groupBy: ['CityName'],
          aggregates: [{ func: 'SUM', field: 'Amount', alias: 'total_amount' }],
        },
      ],
    };
    const sql = compileGraph(g, 'tsql');
    expect(sql).toContain('SELECT [CityName], SUM([Amount]) AS [total_amount] FROM q1_s1');
    expect(sql).toContain('GROUP BY [CityName]');
  });

  it('compiles COUNT_DISTINCT to COUNT(DISTINCT field) in both dialects', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'fact_sale'),
        {
          id: 'g1',
          kind: 'group-by',
          inputs: ['s1'],
          groupBy: ['CityName'],
          aggregates: [{ func: 'COUNT_DISTINCT', field: 'CustomerKey', alias: 'customers' }],
        },
      ],
    };
    expect(compileGraph(g, 'tsql')).toContain('COUNT(DISTINCT [CustomerKey]) AS [total]'.replace('total', 'customers'));
    expect(compileGraph(g, 'sparksql')).toContain('COUNT(DISTINCT `CustomerKey`) AS `customers`');
  });

  it('compiles a two-source INNER join on key columns', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'fact_sale'),
        source('s2', 'dbo', 'dimension_city'),
        {
          id: 'j1',
          kind: 'join',
          inputs: ['s1', 's2'],
          joinKind: 'INNER',
          leftKey: 'CityKey',
          rightKey: 'CityKey',
        },
      ],
    };
    const sql = compileGraph(g, 'tsql');
    expect(sql).toContain('SELECT L.*, R.*');
    expect(sql).toContain('FROM q1_s1 AS L');
    expect(sql).toContain('INNER JOIN q2_s2 AS R ON L.[CityKey] = R.[CityKey]');
  });

  it('LEFT ANTI join projects only the left side', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'fact_sale'),
        source('s2', 'dbo', 'dimension_city'),
        { id: 'j1', kind: 'join', inputs: ['s1', 's2'], joinKind: 'LEFT ANTI', leftKey: 'CityKey', rightKey: 'CityKey' },
      ],
    };
    const sql = compileGraph(g, 'tsql');
    expect(sql).toContain('SELECT L.*');
    expect(sql).toContain('LEFT ANTI JOIN q2_s2 AS R');
  });

  it('compiles a full chain source → filter → group-by → join', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'fact_sale'),
        { id: 'f1', kind: 'filter', inputs: ['s1'], whereExpression: '[CityKey] > 0' },
        {
          id: 'g1',
          kind: 'group-by',
          inputs: ['f1'],
          groupBy: ['CityKey'],
          aggregates: [{ func: 'SUM', field: 'Amount', alias: 'total' }],
        },
        source('s2', 'dbo', 'dimension_city'),
        { id: 'j1', kind: 'join', inputs: ['g1', 's2'], joinKind: 'INNER', leftKey: 'CityKey', rightKey: 'CityKey' },
      ],
      outputId: 'j1',
    };
    const sql = compileGraph(g, 'tsql');
    expect(sql).toContain('WITH ');
    expect(sql).toContain('WHERE [CityKey] > 0');
    expect(sql).toContain('GROUP BY [CityKey]');
    expect(sql).toContain('INNER JOIN');
    // Output CTE is the join step.
    expect(sql).toMatch(/SELECT \* FROM q5_j1\s*$/m);
  });

  it('uses backticks and bare table refs for Spark SQL', () => {
    const g: VqGraph = {
      nodes: [
        { id: 's1', kind: 'source', inputs: [], table: 'sales' },
        { id: 'c1', kind: 'select-columns', inputs: ['s1'], columns: ['city', 'amount'] },
      ],
    };
    const sql = compileGraph(g, 'sparksql');
    expect(sql).toContain('SELECT * FROM `sales`');
    expect(sql).toContain('SELECT `city`, `amount` FROM q1_s1');
  });

  it('compiles source → sort to an ORDER BY (multi-key, dialect-aware)', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'fact_sale'),
        {
          id: 'o1',
          kind: 'sort',
          inputs: ['s1'],
          sortKeys: [
            { field: 'sale_date', dir: 'DESC' },
            { field: 'amount', dir: 'ASC' },
          ],
        },
      ],
    };
    const tsql = compileGraph(g, 'tsql');
    expect(tsql).toContain('ORDER BY [sale_date] DESC, [amount] ASC');
    const spark = compileGraph(g, 'sparksql');
    expect(spark).toContain('ORDER BY `sale_date` DESC, `amount` ASC');
  });

  it('sort with no keys is a pass-through SELECT * (no dangling ORDER BY)', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'fact_sale'),
        { id: 'o1', kind: 'sort', inputs: ['s1'], sortKeys: [] },
      ],
    };
    const sql = compileGraph(g, 'tsql');
    expect(sql).not.toContain('ORDER BY');
    expect(sql).toMatch(/SELECT \* FROM q2_o1\s*$/m);
  });

  // ---- Wave-3 Warp transform-builder steps ----

  it('compiles a derive step to a computed column projection', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'fact_sale'),
        { id: 'd1', kind: 'derive', inputs: ['s1'], derived: [{ name: 'net', expression: '[price] * [qty]' }] },
      ],
    };
    const sql = compileGraph(g, 'tsql');
    expect(sql).toContain('SELECT *, [price] * [qty] AS [net] FROM q1_s1');
  });

  it('compiles a cast step to CAST(... AS type)', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'fact_sale'),
        { id: 'c1', kind: 'cast', inputs: ['s1'], casts: [{ field: 'amount', to: 'DECIMAL(18,2)' }] },
      ],
    };
    const sql = compileGraph(g, 'tsql');
    expect(sql).toContain('CAST([amount] AS DECIMAL(18,2)) AS [amount]');
  });

  it('compiles a rename step to AS projections', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'fact_sale'),
        { id: 'r1', kind: 'rename', inputs: ['s1'], renames: [{ from: 'amt', to: 'amount' }] },
      ],
    };
    const sql = compileGraph(g, 'tsql');
    expect(sql).toContain('SELECT [amt] AS [amount], * FROM q1_s1');
  });

  it('compiles a keyless dedup to SELECT DISTINCT', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'fact_sale'),
        { id: 'x1', kind: 'dedup', inputs: ['s1'], dedupKeys: [] },
      ],
    };
    expect(compileGraph(g, 'tsql')).toContain('SELECT DISTINCT * FROM q1_s1');
  });

  it('compiles a keyed dedup to a ROW_NUMBER window', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'fact_sale'),
        { id: 'x1', kind: 'dedup', inputs: ['s1'], dedupKeys: ['id'] },
      ],
    };
    const sql = compileGraph(g, 'tsql');
    expect(sql).toContain('ROW_NUMBER() OVER (PARTITION BY [id]');
    expect(sql).toContain('__rn = 1');
  });

  it('compiles a union of two sources', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'a'),
        source('s2', 'dbo', 'b'),
        { id: 'u1', kind: 'union', inputs: ['s1', 's2'], unionAll: true },
      ],
      outputId: 'u1',
    };
    const sql = compileGraph(g, 'tsql');
    expect(sql).toContain('UNION ALL');
    expect(sql).toContain('[a]');
    expect(sql).toContain('[b]');
  });

  it('wraps a sink node as CTAS (CREATE TABLE … AS) for Spark SQL', () => {
    const g: VqGraph = {
      nodes: [
        { id: 's1', kind: 'source', inputs: [], table: 'raw' },
        { id: 'f1', kind: 'filter', inputs: ['s1'], whereExpression: '`x` > 0' },
        { id: 'snk', kind: 'sink', inputs: ['f1'], sink: { mode: 'table', schema: 'silver', table: 'clean' } },
      ],
      outputId: 'snk',
    };
    const sql = compileGraph(g, 'sparksql');
    expect(sql).toContain('CREATE TABLE `silver`.`clean` AS');
    expect(sql).toContain('WITH ');
    expect(sql).not.toContain('snk AS ('); // sink is never a CTE
  });

  it('materializes a T-SQL sink table via SELECT … INTO (WITH stays in front)', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'fact_sale'),
        { id: 'f1', kind: 'filter', inputs: ['s1'], whereExpression: '[amt] > 0' },
        { id: 'snk', kind: 'sink', inputs: ['f1'], sink: { mode: 'table', schema: 'dbo', table: 'clean' } },
      ],
      outputId: 'snk',
    };
    const sql = compileGraph(g, 'tsql');
    expect(sql).toMatch(/^-- Generated[\s\S]*WITH /m);
    expect(sql).toContain('INTO [dbo].[clean]');
    expect(sql).not.toContain('CREATE TABLE'); // T-SQL uses SELECT … INTO, not CTAS
  });

  it('wraps a sink node as a CREATE VIEW when mode is view', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'fact_sale'),
        { id: 'snk', kind: 'sink', inputs: ['s1'], sink: { mode: 'view', table: 'v_sales' } },
      ],
      outputId: 'snk',
    };
    const sql = compileGraph(g, 'tsql');
    expect(sql).toContain('CREATE OR ALTER VIEW [v_sales] AS');
  });

  it('a sink with an empty table name falls back to a plain SELECT', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'fact_sale'),
        { id: 'snk', kind: 'sink', inputs: ['s1'], sink: { mode: 'table', table: '' } },
      ],
      outputId: 'snk',
    };
    const sql = compileGraph(g, 'tsql');
    expect(sql).not.toContain('CREATE TABLE');
    expect(sql).toContain('SELECT * FROM');
  });

  it('prunes dead branches not feeding the output', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'a'),
        source('s2', 'dbo', 'b'), // dangling — nothing consumes it, not the output
        { id: 'f1', kind: 'filter', inputs: ['s1'], whereExpression: '1 = 1' },
      ],
      outputId: 'f1',
    };
    const sql = compileGraph(g, 'tsql');
    expect(sql).toContain('[a]');
    expect(sql).not.toContain('[b]');
  });
});
