/**
 * compileGraph — unit tests.
 *
 * Verifies the visual-query canvas graph compiles to valid SQL for the guided
 * shapes (source, filter, choose columns, keep top rows, group by + aggregate,
 * merge/join) in both dialects (T-SQL and Spark SQL), plus the multi-step
 * WITH chain and dead-branch pruning.
 */
import { describe, it, expect } from 'vitest';
import {
  compileGraph,
  type VqGraph,
  type VqNode,
} from '../visual-query-compiler';

const source = (id: string, schema: string, table: string): VqNode => ({
  id,
  kind: 'source',
  inputs: [],
  schema,
  table,
});

describe('compileGraph', () => {
  it('emits a placeholder for an empty graph', () => {
    const sql = compileGraph({ nodes: [] }, 'tsql');
    expect(sql).toContain('Add a table to the canvas');
  });

  it('compiles a single source to a bare SELECT * (no CTE)', () => {
    const g: VqGraph = { nodes: [source('s1', 'dbo', 'fact_sale')] };
    const sql = compileGraph(g, 'tsql');
    expect(sql).toContain('SELECT * FROM [dbo].[fact_sale]');
    expect(sql).not.toContain('WITH ');
    expect(sql).toContain('Generated by CSA Loom');
  });

  it('compiles source → filter to a WHERE clause', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'fact_sale'),
        { id: 'f1', kind: 'filter', inputs: ['s1'], whereExpression: '[amount] > 1000' },
      ],
    };
    const sql = compileGraph(g, 'tsql');
    expect(sql).toContain('WITH ');
    expect(sql).toContain('FROM [dbo].[fact_sale]');
    expect(sql).toContain('WHERE [amount] > 1000');
    expect(sql).toMatch(/SELECT \* FROM q2_f1\s*$/m);
  });

  it('compiles source → choose columns to an explicit column list', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'dimension_city'),
        { id: 'c1', kind: 'select-columns', inputs: ['s1'], columns: ['CityKey', 'CityName'] },
      ],
    };
    const sql = compileGraph(g, 'tsql');
    expect(sql).toContain('SELECT [CityKey], [CityName] FROM q1_s1');
  });

  it('compiles keep-top-rows to TOP (n) for T-SQL and LIMIT for Spark SQL', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'fact_sale'),
        { id: 't1', kind: 'keep-top-rows', inputs: ['s1'], topN: 50 },
      ],
    };
    expect(compileGraph(g, 'tsql')).toContain('SELECT TOP (50) * FROM q1_s1');
    expect(compileGraph(g, 'sparksql')).toContain('SELECT * FROM q1_s1 LIMIT 50');
  });

  it('compiles group-by with SUM aggregate', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'fact_sale'),
        {
          id: 'g1',
          kind: 'group-by',
          inputs: ['s1'],
          groupBy: ['CityName'],
          aggregates: [{ func: 'SUM', field: 'Amount', alias: 'total_amount' }],
        },
      ],
    };
    const sql = compileGraph(g, 'tsql');
    expect(sql).toContain('SELECT [CityName], SUM([Amount]) AS [total_amount] FROM q1_s1');
    expect(sql).toContain('GROUP BY [CityName]');
  });

  it('compiles COUNT_DISTINCT to COUNT(DISTINCT field) in both dialects', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'fact_sale'),
        {
          id: 'g1',
          kind: 'group-by',
          inputs: ['s1'],
          groupBy: ['CityName'],
          aggregates: [{ func: 'COUNT_DISTINCT', field: 'CustomerKey', alias: 'customers' }],
        },
      ],
    };
    expect(compileGraph(g, 'tsql')).toContain('COUNT(DISTINCT [CustomerKey]) AS [total]'.replace('total', 'customers'));
    expect(compileGraph(g, 'sparksql')).toContain('COUNT(DISTINCT `CustomerKey`) AS `customers`');
  });

  it('compiles a two-source INNER join on key columns', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'fact_sale'),
        source('s2', 'dbo', 'dimension_city'),
        {
          id: 'j1',
          kind: 'join',
          inputs: ['s1', 's2'],
          joinKind: 'INNER',
          leftKey: 'CityKey',
          rightKey: 'CityKey',
        },
      ],
    };
    const sql = compileGraph(g, 'tsql');
    expect(sql).toContain('SELECT L.*, R.*');
    expect(sql).toContain('FROM q1_s1 AS L');
    expect(sql).toContain('INNER JOIN q2_s2 AS R ON L.[CityKey] = R.[CityKey]');
  });

  it('LEFT ANTI join projects only the left side', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'fact_sale'),
        source('s2', 'dbo', 'dimension_city'),
        { id: 'j1', kind: 'join', inputs: ['s1', 's2'], joinKind: 'LEFT ANTI', leftKey: 'CityKey', rightKey: 'CityKey' },
      ],
    };
    const sql = compileGraph(g, 'tsql');
    expect(sql).toContain('SELECT L.*');
    expect(sql).toContain('LEFT ANTI JOIN q2_s2 AS R');
  });

  it('compiles a full chain source → filter → group-by → join', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'fact_sale'),
        { id: 'f1', kind: 'filter', inputs: ['s1'], whereExpression: '[CityKey] > 0' },
        {
          id: 'g1',
          kind: 'group-by',
          inputs: ['f1'],
          groupBy: ['CityKey'],
          aggregates: [{ func: 'SUM', field: 'Amount', alias: 'total' }],
        },
        source('s2', 'dbo', 'dimension_city'),
        { id: 'j1', kind: 'join', inputs: ['g1', 's2'], joinKind: 'INNER', leftKey: 'CityKey', rightKey: 'CityKey' },
      ],
      outputId: 'j1',
    };
    const sql = compileGraph(g, 'tsql');
    expect(sql).toContain('WITH ');
    expect(sql).toContain('WHERE [CityKey] > 0');
    expect(sql).toContain('GROUP BY [CityKey]');
    expect(sql).toContain('INNER JOIN');
    // Output CTE is the join step.
    expect(sql).toMatch(/SELECT \* FROM q5_j1\s*$/m);
  });

  it('uses backticks and bare table refs for Spark SQL', () => {
    const g: VqGraph = {
      nodes: [
        { id: 's1', kind: 'source', inputs: [], table: 'sales' },
        { id: 'c1', kind: 'select-columns', inputs: ['s1'], columns: ['city', 'amount'] },
      ],
    };
    const sql = compileGraph(g, 'sparksql');
    expect(sql).toContain('SELECT * FROM `sales`');
    expect(sql).toContain('SELECT `city`, `amount` FROM q1_s1');
  });

  it('prunes dead branches not feeding the output', () => {
    const g: VqGraph = {
      nodes: [
        source('s1', 'dbo', 'a'),
        source('s2', 'dbo', 'b'), // dangling — nothing consumes it, not the output
        { id: 'f1', kind: 'filter', inputs: ['s1'], whereExpression: '1 = 1' },
      ],
      outputId: 'f1',
    };
    const sql = compileGraph(g, 'tsql');
    expect(sql).toContain('[a]');
    expect(sql).not.toContain('[b]');
  });
});
