"""csa_platform.streaming.silver — silver materialized view builder (CSA-0137).

The :class:`MaterializedViewBuilder` produces dbt-flavoured SQL scaffolds
for a :class:`SilverMaterializedView`.  It does NOT execute dbt — that is
owned by the dbt orchestration layer (``make dbt-run`` / Airflow DAGs).
Instead it provides the integration surface:

* :meth:`build_dbt_model_yaml`  — dbt schema.yml fragment for the view.
* :meth:`build_incremental_sql` — incremental model scaffolding with
  watermark + dedup semantics pre-wired.

Keeping these as pure functions makes them trivial to unit-test against
golden outputs.
"""

from __future__ import annotations

from textwrap import dedent

from csa_platform.streaming.models import SilverMaterializedView


class MaterializedViewBuilder:
    """Builds dbt-compatible artefacts for a :class:`SilverMaterializedView`."""

    def __init__(self, view: SilverMaterializedView) -> None:
        self.view = view

    # ----- dbt YAML schema -------------------------------------------------

    def build_dbt_model_yaml(self) -> str:
        """Return a dbt ``schema.yml`` fragment describing the silver model."""
        dedup_cols = list(self.view.deduplication_keys) or [self.view.watermark_field]
        tests_block = ""
        if self.view.deduplication_keys:
            tests_block = (
                "    tests:\n"
                "      - dbt_utils.unique_combination_of_columns:\n"
                "          combination_of_columns:\n"
                + "".join(f"            - {k}\n" for k in self.view.deduplication_keys)
            )

        return dedent(
            f"""\
            version: 2

            models:
              - name: {self.view.name}
                description: >
                  Silver materialized view backed by dbt model {self.view.dbt_model_ref}.
                  Generated by csa_platform.streaming.silver.MaterializedViewBuilder.
                config:
                  materialized: incremental
                  unique_key: {dedup_cols!r}
                  incremental_strategy: merge
                columns:
                  - name: {self.view.watermark_field}
                    description: Event-time watermark column used for incremental merges.
            {tests_block}""",
        )

    # ----- Incremental SQL scaffold ---------------------------------------

    def build_incremental_sql(self, *, bronze_source: str) -> str:
        """Return a dbt-style incremental SQL scaffold.

        The caller fills in the actual business logic in the dbt model
        referenced by ``self.view.dbt_model_ref`` — this scaffold only
        wires up watermark + dedup boilerplate that is otherwise easy to
        get wrong.
        """
        dedup_cols = list(self.view.deduplication_keys) or [self.view.watermark_field]
        dedup_expr = ", ".join(dedup_cols)
        return dedent(
            f"""\
            {{{{ config(
                materialized='incremental',
                unique_key={dedup_cols!r},
                incremental_strategy='merge'
            ) }}}}

            with source_data as (
                select *
                from {{{{ source('streaming', '{bronze_source}') }}}}
                {{% if is_incremental() %}}
                where {self.view.watermark_field} > (
                    select coalesce(max({self.view.watermark_field}), '1970-01-01')
                    from {{{{ this }}}}
                )
                {{% endif %}}
            ),

            deduplicated as (
                select *,
                    row_number() over (
                        partition by {dedup_expr}
                        order by {self.view.watermark_field} desc
                    ) as _csa_row
                from source_data
            )

            select * exclude (_csa_row)
            from deduplicated
            where _csa_row = 1
            """,
        )
