#!/usr/bin/env node
/**
 * BR-TERRAFORM — regenerate the Terraform resource reference from the SAME
 * OpenAPI document the API serves, so the module attributes never drift from
 * the real API contract.
 *
 * It imports `buildOpenApiSpec()` (apps/fiab-console/lib/openapi/spec.ts) via
 * Node's built-in TypeScript type-stripping (Node >= 22.6), writes a JSON
 * snapshot of the spec, and emits GENERATED-SCHEMAS.md — an attribute table per
 * Terraform resource derived from the create/update request schemas.
 *
 * Run:  node --experimental-strip-types tools/terraform/generate-schemas.mjs
 * (On Node >= 22.18 the flag is a no-op — type-stripping is on by default.)
 */

import { fileURLToPath } from 'node:url';
import path from 'node:path';
import fs from 'node:fs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..', '..');
const SPEC_TS = path.join(REPO_ROOT, 'apps', 'fiab-console', 'lib', 'openapi', 'spec.ts');
const SNAPSHOT = path.join(__dirname, 'openapi.snapshot.json');
const OUT_MD = path.join(__dirname, 'GENERATED-SCHEMAS.md');

// Which OpenAPI request schema backs each Terraform module resource.
const RESOURCES = [
  { module: 'loom-workspace', title: 'Loom workspace', createSchema: 'CreateWorkspace', createPath: 'POST /api/workspaces' },
  { module: 'loom-item', title: 'Loom item', createSchema: 'CreateItem', createPath: 'POST /api/workspaces/{workspaceId}/items' },
];

async function loadSpec() {
  // Prefer importing the live TS source (single source of truth).
  try {
    const mod = await import(`file://${SPEC_TS.split(path.sep).join('/')}`);
    return mod.buildOpenApiSpec('');
  } catch (e) {
    // Fallback: the committed snapshot (for environments without type-stripping).
    if (fs.existsSync(SNAPSHOT)) {
      return JSON.parse(fs.readFileSync(SNAPSHOT, 'utf8'));
    }
    throw e;
  }
}

function attrRows(schema) {
  if (!schema || !schema.properties) return [];
  const required = new Set(schema.required ?? []);
  return Object.entries(schema.properties).map(([name, def]) => ({
    name,
    type: def.type ?? (def.$ref ? def.$ref.split('/').pop() : 'object'),
    required: required.has(name),
    description: def.description ?? '',
  }));
}

async function main() {
  const spec = await loadSpec();
  fs.writeFileSync(SNAPSHOT, JSON.stringify(spec, null, 2) + '\n');

  const schemas = spec.components.schemas;
  const lines = [];
  lines.push('<!-- GENERATED by tools/terraform/generate-schemas.mjs — do not edit by hand. -->');
  lines.push('');
  lines.push('# Loom Terraform — generated resource schemas');
  lines.push('');
  lines.push(`Derived from the OpenAPI document \`CSA Loom API\` v${spec.info.version}.`);
  lines.push('Run `node tools/terraform/generate-schemas.mjs` to regenerate after the API changes.');
  lines.push('');

  for (const r of RESOURCES) {
    lines.push(`## \`${r.module}\` — ${r.title}`);
    lines.push('');
    lines.push(`Create: \`${r.createPath}\` (request schema \`${r.createSchema}\`).`);
    lines.push('');
    lines.push('| Attribute | Type | Required | Description |');
    lines.push('|-----------|------|----------|-------------|');
    for (const a of attrRows(schemas[r.createSchema])) {
      lines.push(`| \`${a.name}\` | ${a.type} | ${a.required ? 'yes' : 'no'} | ${a.description} |`);
    }
    lines.push('');
  }

  fs.writeFileSync(OUT_MD, lines.join('\n') + '\n');
  console.log(`[terraform] wrote ${path.relative(REPO_ROOT, SNAPSHOT)} + ${path.relative(REPO_ROOT, OUT_MD)}`);
}

main().catch((e) => {
  console.error('[terraform] generation failed:', e);
  process.exit(1);
});
