/**
 * Loom item-type taxonomy — the SAME set the Console exposes as per-type routes
 * under `apps/fiab-console/app/api/items/<type>/` and that the `loom` CLI
 * validates against. The SDK exposes it so callers can validate `itemType`
 * before a create round-trips.
 *
 * Every type is Azure-native by default (no Microsoft Fabric tenant required).
 * Keep in sync with `apps/loom-cli/src/item-types.ts` when new types land.
 */
export const ITEM_TYPES: readonly string[] = [
  'activator',
  'adf-dataset',
  'adf-pipeline',
  'adf-trigger',
  'ai-builder-model',
  'ai-foundry-project',
  'ai-search-index',
  'aip-logic',
  'airflow-job',
  'apim-api',
  'apim-policy',
  'apim-product',
  'automl',
  'azure-sql-database',
  'azure-sql-managed-instance',
  'azure-sql-server',
  'content-safety',
  'copilot-studio-action',
  'copilot-studio-agent',
  'copilot-studio-analytics',
  'copilot-studio-channel',
  'copilot-studio-knowledge',
  'copilot-studio-topic',
  'copilot-template-library',
  'copy-job',
  'cosmos-db',
  'cosmos-gremlin-graph',
  'cypher-graph',
  'dashboard',
  'data-agent',
  'data-pipeline',
  'data-product',
  'data-product-instance',
  'data-product-template',
  'dataflow',
  'datamart',
  'dataset',
  'dataverse-table',
  'dbt-job',
  'environment',
  'evaluation',
  'event-schema-set',
  'eventhouse',
  'eventstream',
  'geo-dataset',
  'geo-map',
  'geo-pipeline',
  'geo-query',
  'gql-graph',
  'graph-model',
  'graphql-api',
  'health-check',
  'kql-dashboard',
  'kql-database',
  'kql-queryset',
  'lakehouse',
  'logic-app',
  'map',
  'materialized-lake-view',
  'mirrored-database',
  'mirrored-databricks',
  'ml-experiment',
  'ml-model',
  'mounted-adf',
  'notebook',
  'ontology',
  'ontology-sdk',
  'operations-agent',
  'paginated-report',
  'plan',
  'postgres-flexible-server',
  'power-app',
  'power-automate-flow',
  'power-page',
  'prompt-flow',
  'rayfin-app',
  'release-environment',
  'report',
  'scorecard',
  'semantic-model',
  'slate-app',
  'spark-environment',
  'spark-job-definition',
  'sql-database',
  'sql-databases',
  'sql-server-2025-vector-index',
  'stream-analytics-job',
  'synapse-dedicated-sql-pool',
  'synapse-notebook',
  'synapse-pipeline',
  'synapse-serverless-sql-pool',
  'synapse-spark-pool',
  'tracing',
  'user-data-function',
  'variable-library',
  'vector-store',
  'warehouse',
  'workshop-app',
];

const ITEM_TYPE_SET = new Set(ITEM_TYPES);

export function isKnownItemType(t: string): boolean {
  return ITEM_TYPE_SET.has(t);
}
