/**
 * Render a planner subscription into a .bicepparam the real deploy consumes
 * (`az deployment sub create -f platform/fiab/bicep/main.bicep -p <this>`).
 *
 * The plan's per-domain service sets are unioned into the bicep feature flags
 * (a service deployed in ANY domain turns its flag on for that subscription's
 * deployment), and the domain ids become `dlzDomainNames`. Per-resource config
 * (SKU/tier/runtime) is written as the matching top-level main.bicep params, so
 * the visual plan stays in sync with what bicep actually deploys (no drift = no
 * vaporware). main.bicep forwards each param to its deploy-planner module, so
 * the exported file applies the chosen SKU/tier — not just the module default.
 */
import {
  flagsForServices, SERVICE_CATALOG, serviceByKey, resolveConfigValue, type ConfigField,
} from './service-catalog';
import type { PlanSubscription, ConfigValue } from './types';

/**
 * Default `armRegionName` per boundary. Exported so the cost-estimate route
 * resolves the same region the bicepparam export would deploy into.
 */
export const BOUNDARY_DEFAULT_REGION: Record<string, string> = {
  'Commercial': 'eastus2',
  'GCC': 'usgovvirginia',
  'GCC-High': 'usgovvirginia',
  'IL5': 'usgovarizona',
};

/** Render one config value as a bicepparam literal (quoted string or bare int). */
function formatBicepValue(field: ConfigField, value: ConfigValue): string {
  const asInt = field.emit === 'int' || (field.emit === undefined && field.type === 'number');
  if (asInt) return String(Math.round(Number(value)));
  return `'${String(value).replace(/'/g, "\\'")}'`;
}

export function planToBicepparam(sub: PlanSubscription): string {
  const boundary = sub.boundary || 'Commercial';
  const region = sub.region || BOUNDARY_DEFAULT_REGION[boundary] || 'eastus2';
  const domainNames = sub.domains.map((d) => d.domainId).filter(Boolean);

  // Union every selected service across the subscription's domains → flags.
  const allServices = new Set<string>();
  for (const d of sub.domains) for (const k of d.services) allServices.add(k);
  const onFlags = flagsForServices([...allServices]);

  // Emit every toggleable flag explicitly (true when selected, false otherwise)
  // so the generated file is unambiguous and matches the committed param shape.
  const toggleable = SERVICE_CATALOG
    .map((s) => s.bicepFlag)
    .filter((f): f is string => !!f);
  const uniqueFlags = [...new Set(toggleable)].sort();

  const lines: string[] = [];
  lines.push(`// Generated by the CSA Loom Deployment planner — ${sub.name}`);
  lines.push(`// Apply: az deployment sub create -f platform/fiab/bicep/main.bicep -p <this-file>`);
  lines.push(`using '../main.bicep'`);
  lines.push('');
  lines.push(`param boundary = '${boundary}'`);
  lines.push(`param location = '${region}'`);
  // deploymentMode is a REQUIRED, no-default param on main.bicep
  // (@allowed(['single-sub','multi-sub'])). Emit it so the exported file is
  // actually deployable. Use the explicit choice when set, else derive it from
  // the domain count — single-sub supports at most one DLZ, so any plan with >1
  // domain must be multi-sub.
  const mode = sub.deploymentMode || (domainNames.length > 1 ? 'multi-sub' : 'single-sub');
  lines.push(`param deploymentMode = '${mode}'`);
  lines.push(`param dlzDomainNames = [${domainNames.map((n) => `'${n}'`).join(', ')}]`);
  if (mode === 'multi-sub') {
    // dlzSubscriptionIds holds the real Azure sub GUIDs (parallel to
    // dlzDomainNames) — they are NOT known to the planner, so the operator
    // fills them in before deploying. Emit a TODO rather than a fake value.
    lines.push(`// TODO: supply one Azure subscription id per domain (parallel to dlzDomainNames):`);
    lines.push(`// param dlzSubscriptionIds = [${domainNames.map(() => `'<sub-guid>'`).join(', ')}]`);
  }
  lines.push('');
  for (const flag of uniqueFlags) {
    lines.push(`param ${flag} = ${onFlags[flag] ? 'true' : 'false'}`);
  }

  // Per-resource config — only for SELECTED toggleable services that expose a
  // config schema. Core / plan-only services emit nothing (no fake knobs).
  const configLines: string[] = [];
  for (const key of [...allServices].sort()) {
    const def = serviceByKey(key);
    if (!def?.bicepFlag || !def.config?.length) continue;
    const stored = sub.serviceConfigs?.[key];
    for (const field of def.config) {
      const value = resolveConfigValue(field, stored);
      configLines.push(`param ${field.bicepParam} = ${formatBicepValue(field, value)}`);
    }
  }
  if (configLines.length) {
    lines.push('');
    lines.push('// Per-resource configuration (SKU / tier / runtime)');
    lines.push(...configLines);
  }

  return lines.join('\n') + '\n';
}
