/**
 * Render a planner subscription into a .bicepparam the real deploy consumes
 * (`az deployment sub create -f platform/fiab/bicep/main.bicep -p <this>`).
 *
 * The plan's per-domain service sets are unioned into the bicep feature flags
 * (a service deployed in ANY domain turns its flag on for that subscription's
 * deployment), and the domain ids become `dlzDomainNames`. This is the same
 * shape as params/commercial.bicepparam / gcc-high.bicepparam, so the visual
 * plan stays in sync with what bicep actually deploys (no drift = no vaporware).
 */
import { flagsForServices, SERVICE_CATALOG } from './service-catalog';
import type { PlanSubscription } from './types';

const BOUNDARY_DEFAULT_REGION: Record<string, string> = {
  'Commercial': 'eastus2',
  'GCC': 'usgovvirginia',
  'GCC-High': 'usgovvirginia',
  'IL5': 'usgovarizona',
};

export function planToBicepparam(sub: PlanSubscription): string {
  const boundary = sub.boundary || 'Commercial';
  const region = sub.region || BOUNDARY_DEFAULT_REGION[boundary] || 'eastus2';
  const domainNames = sub.domains.map((d) => d.domainId).filter(Boolean);

  // Union every selected service across the subscription's domains → flags.
  const allServices = new Set<string>();
  for (const d of sub.domains) for (const k of d.services) allServices.add(k);
  const onFlags = flagsForServices([...allServices]);

  // Emit every toggleable flag explicitly (true when selected, false otherwise)
  // so the generated file is unambiguous and matches the committed param shape.
  const toggleable = SERVICE_CATALOG
    .map((s) => s.bicepFlag)
    .filter((f): f is string => !!f);
  const uniqueFlags = [...new Set(toggleable)].sort();

  const lines: string[] = [];
  lines.push(`// Generated by the CSA Loom Deployment planner — ${sub.name}`);
  lines.push(`// Apply: az deployment sub create -f platform/fiab/bicep/main.bicep -p <this-file>`);
  lines.push(`using '../main.bicep'`);
  lines.push('');
  lines.push(`param boundary = '${boundary}'`);
  lines.push(`param location = '${region}'`);
  lines.push(`param dlzDomainNames = [${domainNames.map((n) => `'${n}'`).join(', ')}]`);
  lines.push('');
  for (const flag of uniqueFlags) {
    lines.push(`param ${flag} = ${onFlags[flag] ? 'true' : 'false'}`);
  }
  return lines.join('\n') + '\n';
}
