/**
 * GET /api/items/report/[id]/native-query  — REPORT-BUILDER PARITY · WAVE 4
 *
 * Power Query "View Native Query" for the report Transform host (the "Transform
 * Data" surface that reuses the proven Dataflow Gen2 `PowerQueryHost`). Returns
 * the REAL T-SQL the Loom-native (Synapse) renderer would send for THIS query —
 * the source's base SELECT with the Power Query applied steps FOLDED onto it
 * (DirectQuery query-folding), optionally compiled through the wells→SQL designer
 * for a supplied visual. NOT a stub: the SQL is generated by the same
 * `foldAppliedStepsToSql` + `buildSqlFromVisual` the /fields and /query routes
 * compile, never hand-typed (no-vaporware.md / no-freeform-config.md), and runs
 * 100% Azure-native over Synapse — no api.fabric / api.powerbi / onelake host on
 * any path (no-fabric-dependency.md).
 *
 * ── How it works (the same source resolution /query + /profile use) ───────────
 *   1. Owner-load the report item (a `loom:` content id OR a plain Cosmos id),
 *      tenant-scoped, exactly like /query / /fields / /profile.
 *   2. `resolveReportModel` → the Azure-native backend. The native query is the
 *      folded T-SQL over the Loom-native SQL path (semantic-model / direct-query
 *      → Synapse warehouse dedicated pool or lakehouse serverless), the
 *      report-designer-v2 DEFAULT and the path the Wave-4 Transform host folds
 *      onto. `unbound` → honest 412. `aas` (DAX/XMLA) and `connection` (Get-Data)
 *      sources don't expose a foldable Synapse SQL relation here → honest 412
 *      gate naming the limitation (never a wrong/mock query).
 *   3. Resolve the source's BASE SELECT — the direct-query's validated SELECT, or
 *      `SELECT * FROM [schema].[table]` for the model table the visual references
 *      (else the first bindable model table) — then, when a Wave-4 Power Query
 *      transform is layered on (`state.dataSource.appliedSteps`), WRAP the FROM by
 *      folding the applied steps to nested derived SELECTs via
 *      `m-script.foldAppliedStepsToSql`. A non-foldable step (parse JSON/XML,
 *      transpose, examples-heuristics …) returns an HONEST 409
 *      (`code:'not-foldable'`) naming the step + the Import remediation, instead
 *      of a silently-wrong native query.
 *   4. With a `?visual=<base64 DaxVisual>` supplied, compile the folded derived
 *      FROM through `buildSqlFromVisual` (the SAME wells→SQL compiler /query runs)
 *      and return that visual's `SELECT … GROUP BY`; otherwise return the folded
 *      base SELECT. Identifiers are resolver-whitelisted + bracket-quoted.
 *
 * Response contract:
 *   200 → { ok:true, dialect:SqlDialect, sql:string, foldable:true }  (REAL SQL)
 *   409 → { ok:false, code:'not-foldable', error, unfoldableStep }    (honest fold gate)
 *   412 → { ok:false, code:'unbound'|'gate', error, missing? }        (honest source gate)
 *   4xx/5xx → { ok:false, error, status? }
 */

import { NextRequest, NextResponse } from 'next/server';
import { getSession } from '@/lib/auth/session';
import { loadModelItem } from '@/lib/azure/model-binding';
import { AasError, type DaxVisual } from '@/lib/azure/aas-client';
import {
  resolveReportModel,
  type FieldTable,
  type ReportSqlSource,
  type ResolvedReportModel,
} from '@/lib/azure/report-model-resolver';
import {
  fromLegacyState,
  hasTransform,
  reportTransformMode,
} from '@/lib/editors/report/report-data-source';
import { foldAppliedStepsToSql, parseSharedQueries } from '@/lib/components/pipeline/dataflow/m-script';
import {
  buildSqlFromVisual,
  type SqlDialect,
  type SqlSource,
  type SqlSourceColumn,
} from '@/lib/azure/wells-to-sql';
import {
  isLoomContentId,
  cosmosIdFromLoomId,
  loadContentBackedItem,
} from '../../../_lib/pbi-content-fallback';
import type { WorkspaceItem } from '@/lib/types/workspace';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/** The Loom-native report path folds + compiles over the Synapse SQL family. */
const DIALECT: SqlDialect = 'synapse';

/** Strip a trailing `;` so a base SELECT splices cleanly as a derived relation. */
function stripSemicolons(sql: string): string {
  return sql.trim().replace(/;+\s*$/, '');
}

/** Map a resolved Fields table's columns onto the compiler's column whitelist. */
function whitelist(table: FieldTable | undefined): SqlSourceColumn[] {
  return (table?.columns || []).map((c) => ({
    table: table?.name,
    name: c.name,
    dataType: c.dataType,
  }));
}

/** Collect the model-table names a visual's wells reference (for table choice). */
function referencedTables(visual: DaxVisual): string[] {
  const out = new Set<string>();
  const wells = visual.wells || {};
  for (const arr of [wells.category, wells.values, wells.legend]) {
    for (const w of arr || []) if (w?.table) out.add(w.table);
  }
  return [...out];
}

/**
 * Decode the optional `?visual=<base64 DaxVisual>` param. Returns the parsed
 * visual, or `null` when the param is malformed (caller → 400). A valid visual
 * must at least carry a string `type` (the designer always sends one).
 */
function decodeVisual(b64: string): DaxVisual | null {
  try {
    const json = Buffer.from(b64, 'base64').toString('utf8');
    const obj = JSON.parse(json) as unknown;
    if (obj && typeof obj === 'object' && typeof (obj as { type?: unknown }).type === 'string') {
      return obj as DaxVisual;
    }
    return null;
  } catch {
    return null;
  }
}

/**
 * The base SELECT + the chosen Fields table a loom-native report compiles its
 * native query over. A derived source uses its own validated SELECT (the single
 * synthetic table); a table-map / source-groups model uses `SELECT * FROM
 * [schema].[table]` for the table the visual references (when supplied), else the
 * first model table with bindable columns. Mirrors the /profile route's
 * `baseRelation` selection (minus the Synapse target — native-query only
 * COMPILES SQL, it never executes).
 */
function chooseBase(
  tables: FieldTable[],
  sqlSource: ReportSqlSource,
  refs: string[],
): { baseSelect: string; chosen?: FieldTable } | null {
  if (sqlSource.mode === 'derived') {
    const chosen = tables.find((t) => t.name === sqlSource.tableName) || tables[0];
    return { baseSelect: stripSemicolons(sqlSource.sql), chosen };
  }
  // table-map | source-groups → both carry the model-table → base-relation map.
  const tableMap = sqlSource.tableMap;
  const keys = Object.keys(tableMap || {});
  if (!keys.length) return null;

  let chosenName = refs.find((r) => tableMap[r]) || '';
  if (!chosenName) {
    const withCols = tables.find((t) => tableMap[t.name] && t.columns.length > 0);
    chosenName = withCols?.name || keys[0];
  }
  const rel = tableMap[chosenName];
  if (!rel) return null;
  return { baseSelect: `SELECT * FROM ${rel.relation}`, chosen: tables.find((t) => t.name === chosenName) };
}

/** Load the report item (loom: content id OR plain Cosmos id), owner-checked. */
async function loadReport(id: string, oid: string): Promise<WorkspaceItem | null> {
  if (isLoomContentId(id)) {
    return loadContentBackedItem(cosmosIdFromLoomId(id), 'report', oid);
  }
  return loadModelItem(id, 'report', oid);
}

/** A typed JSON error response. */
function err(status: number, payload: Record<string, unknown>): NextResponse {
  return NextResponse.json({ ok: false, ...payload }, { status });
}

/**
 * Pick the query the Transform host is acting on from the persisted M section.
 * The host can author MULTIPLE `shared` queries and reports the ACTIVE one (via
 * `onActiveQueryChange` / the `onViewNativeQuery(queryName)` argument); honoring
 * that name folds THAT query for multi-query parity instead of an implicit
 * `queries[0]`. Falls back to the first query when no name is supplied
 * (single-query reports — the common case) or the supplied name isn't present
 * (stale client state), preserving the original single-query behavior. Returns
 * undefined only when the section parsed to no queries (→ the honest parse gate).
 */
function pickActiveQuery(
  queries: Array<{ name: string; body: string }>,
  queryName: string | undefined,
): { name: string; body: string } | undefined {
  if (queryName) {
    const want = queryName.trim().toLowerCase();
    const match = queries.find((qq) => qq.name.toLowerCase() === want);
    if (match) return match;
  }
  return queries[0];
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ id: string }> }) {
  const session = getSession();
  if (!session) return err(401, { error: 'unauthenticated' });

  // Optional visual (base64 DaxVisual). A supplied-but-malformed param is a
  // client error (400); absent ⇒ return the folded base SELECT (source as-is).
  let visual: DaxVisual | undefined;
  const visualParam = req.nextUrl.searchParams.get('visual');
  if (visualParam) {
    const decoded = decodeVisual(visualParam);
    if (!decoded) {
      return err(400, {
        error:
          'The `visual` query parameter is not a valid base64-encoded visual descriptor ' +
          '(expected base64 JSON with a string `type`).',
      });
    }
    visual = decoded;
  }

  // Optional active-query name. The Transform host can author MULTIPLE `shared`
  // queries; it passes the query the user is viewing (the `onViewNativeQuery`
  // argument) so the fold targets THAT query, not always the first. Absent ⇒ the
  // first query (single-query reports — back-compat).
  const queryName = req.nextUrl.searchParams.get('queryName') || undefined;

  const id = (await ctx.params).id;
  const item = await loadReport(id, session.claims.oid);
  if (!item) return err(404, { error: 'report item not found' });

  // Resolve the report's data source → Azure-native backend (same as /query).
  let resolved: ResolvedReportModel;
  try {
    resolved = await resolveReportModel(item, session.claims.oid);
  } catch (e: any) {
    const status = e instanceof AasError ? e.status : 502;
    return err(status, { error: e?.message || String(e), status });
  }

  // Honest gate — name the exact remediation, never a silent/empty native query.
  if (resolved.backend === 'unbound') {
    return err(412, { code: 'unbound', error: resolved.gate.error, missing: resolved.gate.missing });
  }

  // The native query is the folded T-SQL over the Loom-native Synapse path. AAS
  // (DAX/XMLA) and Get-Data connection sources don't expose a foldable Synapse
  // SQL relation here — honest gate naming the limitation (no wrong query, no
  // Fabric / Power BI).
  if (resolved.backend === 'aas') {
    return err(412, {
      code: 'gate',
      error:
        'View Native Query renders the folded T-SQL of the Loom-native (Synapse) source. This ' +
        'report is bound to Azure Analysis Services (XMLA), which executes DAX over the tabular ' +
        'model rather than SQL — switch the data source to a Loom semantic model or a ' +
        'warehouse/lakehouse query to view the native query here. No Fabric / Power BI required.',
    });
  }
  if (resolved.backend === 'connection') {
    return err(412, {
      code: 'gate',
      error:
        `View Native Query renders the folded T-SQL of the Loom-native (Synapse) source ` +
        `(semantic-model / direct-query). This report uses a Get Data "${resolved.connType}" ` +
        `connection — preview it from the Navigator, or bind a Loom semantic model / ` +
        `warehouse-lakehouse query to view the native query here. Azure-native; no Fabric / Power BI.`,
      missing: resolved.connType,
    });
  }

  // ── loom-native: resolve the base SELECT for the chosen relation ────────────
  const refs = visual ? referencedTables(visual) : [];
  const base = chooseBase(resolved.tables, resolved.sqlSource, refs);
  if (!base) {
    return err(412, {
      code: 'gate',
      error:
        'The report’s data source has no bindable relation for a native query. Re-pick a data ' +
        'source in the designer.',
    });
  }

  // ── Wave-4 transform fold: wrap the FROM in the folded applied steps ─────────
  // The transform M (`appliedSteps`) is read from persisted state via the CLIENT
  // data-source parser (it carries the optional Wave-4 mixin; the resolver's
  // `readReportDataSource` intentionally drops it). DirectQuery folds the steps to
  // SQL here; a non-foldable step is an honest 409 (Import materializes it via the
  // report /refresh Spark/wrangling run — out of this read-only compile path).
  let foldedFrom = base.baseSelect;
  const ds = fromLegacyState((item.state || {}) as Record<string, unknown>);
  if (hasTransform(ds) && ds?.appliedSteps) {
    const queries = parseSharedQueries(ds.appliedSteps);
    const active = pickActiveQuery(queries, queryName);
    if (!active) {
      return err(412, {
        code: 'gate',
        error:
          'The report’s Power Query transform could not be parsed. Re-open Transform data and ' +
          're-apply the steps.',
      });
    }
    const folded = foldAppliedStepsToSql(base.baseSelect, active.body, DIALECT);
    if (!folded.ok) {
      const importMode = reportTransformMode(ds) === 'import';
      return err(409, {
        code: 'not-foldable',
        unfoldableStep: folded.unfoldableStep,
        error:
          `Step '${folded.unfoldableStep}' can't fold to a native query — switch this query to Import.` +
          (importMode
            ? ' This query is already set to Import — run Refresh to materialize it via the dataflow run, then it reads the materialized Delta.'
            : ' Set this query to Import in Transform data and run Refresh to materialize it (Synapse-Spark → Delta), or remove/replace the non-foldable step.'),
      });
    }
    foldedFrom = folded.sql;
  }

  // ── Compile the visual (if supplied) over the folded FROM, else the base ─────
  // With a visual, `buildSqlFromVisual` runs the SAME wells→SQL compiler /query
  // uses — REAL `SELECT … GROUP BY` over `(<foldedFrom>) AS [src]`. A visual with
  // no bindable fields falls back to the folded base SELECT (the source's own
  // native query) rather than erroring, so View-Native-Query always shows real SQL.
  if (visual) {
    const columns = whitelist(base.chosen);
    if (columns.length) {
      const sqlSource: SqlSource = {
        from: { kind: 'derived', sql: foldedFrom },
        columns,
        measures: [],
        dialect: DIALECT,
      };
      const compiled = buildSqlFromVisual(visual, undefined, sqlSource);
      if (compiled) {
        return NextResponse.json({ ok: true, dialect: DIALECT, sql: compiled.sql, foldable: true });
      }
    }
  }

  return NextResponse.json({ ok: true, dialect: DIALECT, sql: foldedFrom, foldable: true });
}
