// styles.ts — makeStyles block for the report-designer.
// No JSX; no 'use client' needed (makeStyles is build-time).

import { makeStyles, tokens } from '@fluentui/react-components';

export const useStyles = makeStyles({
  pane: { display: 'flex', flexDirection: 'column', gap: tokens.spacingVerticalS, padding: tokens.spacingVerticalM, minHeight: 0 },
  pageRow: {
    display: 'flex', alignItems: 'center', gap: tokens.spacingHorizontalXS,
    padding: tokens.spacingVerticalXS, borderRadius: tokens.borderRadiusMedium, cursor: 'pointer',
  },
  pageRowActive: { backgroundColor: tokens.colorNeutralBackground1Selected, fontWeight: tokens.fontWeightSemibold },
  pageRowName: { flex: 1, minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  canvasWrap: { display: 'flex', flexDirection: 'column', gap: tokens.spacingVerticalM, padding: tokens.spacingVerticalL, minHeight: 0 },
  canvasGrid: { display: 'grid', gridTemplateColumns: 'repeat(12, minmax(0, 1fr))', gap: tokens.spacingHorizontalM },
  vcard: {
    display: 'flex', flexDirection: 'column', gap: tokens.spacingVerticalXS,
    position: 'relative',
    padding: tokens.spacingVerticalM,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    borderRadius: tokens.borderRadiusLarge,
    backgroundColor: tokens.colorNeutralBackground1,
    boxShadow: tokens.shadow4,
    transitionProperty: 'box-shadow, border-color', transitionDuration: tokens.durationFaster,
    minHeight: '180px',
    ':hover': { boxShadow: tokens.shadow16 },
  },
  vcardSel: { border: `1px solid ${tokens.colorBrandStroke1}`, boxShadow: tokens.shadow16 },
  vcardDragHandle: {
    display: 'inline-flex', alignItems: 'center', cursor: 'grab',
    color: tokens.colorNeutralForeground3, borderRadius: tokens.borderRadiusSmall,
    ':hover': { color: tokens.colorBrandForeground1, backgroundColor: tokens.colorNeutralBackground1Hover },
  },
  vcardDragging: { opacity: 0.55 },
  vcardDropBefore: { boxShadow: `inset 3px 0 0 0 ${tokens.colorBrandStroke1}, ${tokens.shadow16}` },
  vcardDropAfter: { boxShadow: `inset -3px 0 0 0 ${tokens.colorBrandStroke1}, ${tokens.shadow16}` },
  vcardHead: { display: 'flex', alignItems: 'center', gap: tokens.spacingHorizontalXS },
  vcardTitle: { flex: 1, minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  vcardBody: { flex: 1, minWidth: 0, overflow: 'auto' },
  toolbar: { display: 'flex', alignItems: 'center', gap: tokens.spacingHorizontalS, flexWrap: 'wrap' },
  spacer: { flex: 1 },
  gallery: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(36px, 1fr))',
    gap: tokens.spacingHorizontalXXS,
  },
  galleryCat: { display: 'flex', flexDirection: 'column', gap: tokens.spacingVerticalXXS },
  galleryCatHead: {
    display: 'flex', alignItems: 'center', gap: tokens.spacingHorizontalXS,
    minWidth: 0, marginTop: tokens.spacingVerticalXXS,
  },
  galleryCatDot: {
    width: '6px', height: '6px', borderRadius: tokens.borderRadiusCircular, flexShrink: 0,
  },
  galleryCatLabel: {
    color: tokens.colorNeutralForeground3, fontWeight: tokens.fontWeightSemibold,
    minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
  },
  galleryBtn: {
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    padding: tokens.spacingVerticalXXS, minWidth: 0,
    border: `1px solid ${tokens.colorTransparentStroke}`,
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorTransparentBackground,
    color: tokens.colorNeutralForeground1, cursor: 'pointer',
    transitionProperty: 'background-color, border-color, box-shadow',
    transitionDuration: tokens.durationFaster,
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground1Hover,
      border: `1px solid ${tokens.colorBrandStroke1}`, boxShadow: tokens.shadow4,
    },
    ':focus-visible': { outline: `2px solid ${tokens.colorStrokeFocus2}`, outlineOffset: '1px' },
  },
  galleryIcon: {
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    width: '28px', height: '28px', flexShrink: 0,
    borderRadius: tokens.borderRadiusMedium,
    color: tokens.colorNeutralForeground1,
    fontSize: '20px',
  },
  galleryBtnActive: {
    border: `1px solid ${tokens.colorBrandStroke1}`,
    backgroundColor: tokens.colorBrandBackground2,
    boxShadow: `0 0 0 1px ${tokens.colorBrandStroke1}`,
  },
  galleryIconActive: {
    backgroundColor: tokens.colorBrandBackground,
    color: tokens.colorNeutralForegroundOnBrand,
  },
  well: {
    border: `1px dashed ${tokens.colorNeutralStroke2}`, borderRadius: tokens.borderRadiusMedium,
    padding: tokens.spacingVerticalXS, minHeight: '44px', display: 'flex', flexDirection: 'column',
    gap: tokens.spacingVerticalXXS, backgroundColor: tokens.colorNeutralBackground2,
  },
  wellOver: { border: `1px dashed ${tokens.colorBrandStroke1}`, backgroundColor: tokens.colorBrandBackground2 },
  wellHead: { display: 'flex', alignItems: 'center', gap: tokens.spacingHorizontalXS },
  token: {
    display: 'flex', alignItems: 'center', gap: tokens.spacingHorizontalXS,
    padding: `${tokens.spacingVerticalXXS} ${tokens.spacingHorizontalXS}`,
    borderRadius: tokens.borderRadiusMedium, backgroundColor: tokens.colorNeutralBackground1,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    borderLeft: `3px solid ${tokens.colorBrandStroke1}`,
    transitionProperty: 'box-shadow, border-color',
    transitionDuration: tokens.durationFaster,
    ':hover': { boxShadow: tokens.shadow4, border: `1px solid ${tokens.colorBrandStroke2}`, borderLeft: `3px solid ${tokens.colorBrandStroke1}` },
    '& .well-token-remove': { opacity: 0, transitionProperty: 'opacity', transitionDuration: tokens.durationFaster },
    '&:hover .well-token-remove': { opacity: 1 },
    '&:focus-within .well-token-remove': { opacity: 1 },
  },
  tokenName: { flex: 1, minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  tokenGrip: {
    display: 'inline-flex', alignItems: 'center', flexShrink: 0, cursor: 'grab',
    color: tokens.colorNeutralForeground4,
    ':hover': { color: tokens.colorBrandForeground1 },
  },
  tokenType: { display: 'inline-flex', alignItems: 'center', flexShrink: 0, color: tokens.colorNeutralForeground3 },
  tokenTypeMeasure: { color: tokens.colorBrandForeground1 },
  chip: {
    display: 'inline-flex', alignItems: 'center', gap: tokens.spacingHorizontalXXS, cursor: 'grab',
    padding: `${tokens.spacingVerticalXXS} ${tokens.spacingHorizontalXS}`,
    borderRadius: tokens.borderRadiusMedium, border: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: tokens.colorNeutralBackground1,
  },
  section: { display: 'flex', flexDirection: 'column', gap: tokens.spacingVerticalXS },
  kpi: { fontSize: tokens.fontSizeHero800, fontWeight: tokens.fontWeightSemibold, lineHeight: tokens.lineHeightHero800 },
  muted: { color: tokens.colorNeutralForeground3 },
  approxNote: {
    display: 'flex', alignItems: 'center', gap: tokens.spacingHorizontalXXS,
    marginTop: tokens.spacingVerticalXS, color: tokens.colorNeutralForeground3,
  },
  cardList: { display: 'flex', flexDirection: 'column', gap: tokens.spacingVerticalXS },
  cardRow: {
    display: 'flex', flexWrap: 'wrap', gap: tokens.spacingHorizontalM,
    padding: tokens.spacingVerticalS,
    border: `1px solid ${tokens.colorNeutralStroke2}`, borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorNeutralBackground2,
  },
  cardField: { display: 'flex', flexDirection: 'column', gap: tokens.spacingVerticalXXS, minWidth: 0 },
  refLineRow: { display: 'flex', flexWrap: 'wrap', gap: tokens.spacingHorizontalXS, marginTop: tokens.spacingVerticalXS },
  refLineChip: {
    display: 'inline-flex', alignItems: 'center', gap: tokens.spacingHorizontalXXS,
    padding: `${tokens.spacingVerticalXXS} ${tokens.spacingHorizontalXS}`,
    borderRadius: tokens.borderRadiusMedium, border: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: tokens.colorNeutralBackground2,
  },
  refLineDot: { width: '10px', height: '10px', borderRadius: tokens.borderRadiusCircular, flexShrink: 0 },
  pageSwatchRow: { display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: tokens.spacingHorizontalXXS },
  pageSwatchDot: {
    width: '20px', height: '20px', padding: 0, cursor: 'pointer',
    borderRadius: tokens.borderRadiusCircular, border: `1px solid ${tokens.colorNeutralStroke1}`,
  },
  pageSwatchActive: { border: `2px solid ${tokens.colorNeutralForeground1}`, boxShadow: tokens.shadow4 },
  filterScope: {
    display: 'flex', flexDirection: 'column', gap: tokens.spacingVerticalXS,
    padding: tokens.spacingVerticalS,
    border: `1px solid ${tokens.colorNeutralStroke2}`, borderRadius: tokens.borderRadiusLarge,
    backgroundColor: tokens.colorNeutralBackground1, boxShadow: tokens.shadow2,
  },
  filterRow: {
    display: 'flex', flexDirection: 'column', gap: tokens.spacingVerticalXXS,
    padding: tokens.spacingVerticalXS,
    border: `1px solid ${tokens.colorNeutralStroke2}`, borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorNeutralBackground2,
  },
  filterValues: { display: 'flex', gap: tokens.spacingHorizontalXS, alignItems: 'center', flexWrap: 'wrap' },
  resizeHandle: {
    position: 'absolute', right: '2px', bottom: '2px', width: '14px', height: '14px',
    cursor: 'nwse-resize', borderRight: `2px solid ${tokens.colorNeutralStroke1}`,
    borderBottom: `2px solid ${tokens.colorNeutralStroke1}`, borderBottomRightRadius: tokens.borderRadiusSmall,
    opacity: 0.5,
    ':hover': {
      opacity: 1,
      borderRight: `2px solid ${tokens.colorBrandStroke1}`,
      borderBottom: `2px solid ${tokens.colorBrandStroke1}`,
    },
  },
  vcardMulti: { border: `1px solid ${tokens.colorBrandStroke2}`, boxShadow: tokens.shadow8, outline: `2px solid ${tokens.colorBrandStroke2}`, outlineOffset: '-1px' },
  vcardHidden: { opacity: 0.4 },
  vcardLocked: { border: `1px dashed ${tokens.colorNeutralStroke1}` },
  arrangeBar: {
    display: 'flex', alignItems: 'center', gap: tokens.spacingHorizontalXXS, flexWrap: 'wrap',
    padding: tokens.spacingVerticalXXS, borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorNeutralBackground2, border: `1px solid ${tokens.colorNeutralStroke2}`,
  },
  backBar: {
    display: 'flex', alignItems: 'center', gap: tokens.spacingHorizontalS,
    padding: tokens.spacingVerticalS, borderRadius: tokens.borderRadiusLarge,
    backgroundColor: tokens.colorNeutralBackground2, border: `1px solid ${tokens.colorBrandStroke2}`,
    boxShadow: tokens.shadow2,
  },
  playRow: { display: 'flex', alignItems: 'center', gap: tokens.spacingHorizontalS, marginTop: tokens.spacingVerticalXS },
  playSlider: { flex: 1, minWidth: 0 },
  listRow: {
    display: 'flex', alignItems: 'center', gap: tokens.spacingHorizontalXS,
    padding: tokens.spacingVerticalXS, borderRadius: tokens.borderRadiusMedium,
    border: `1px solid ${tokens.colorNeutralStroke2}`, backgroundColor: tokens.colorNeutralBackground1,
  },
  listRowActive: { border: `1px solid ${tokens.colorBrandStroke1}`, backgroundColor: tokens.colorBrandBackground2 },
  listRowName: { flex: 1, minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  paneSectionHead: {
    display: 'flex', alignItems: 'center', gap: tokens.spacingHorizontalXS,
    width: '100%', minWidth: 0,
    padding: `${tokens.spacingVerticalXXS} 0`,
    border: 'none', backgroundColor: tokens.colorTransparentBackground,
    cursor: 'pointer', color: tokens.colorNeutralForeground1,
    ':hover': { color: tokens.colorBrandForeground1 },
    ':focus-visible': { outline: `2px solid ${tokens.colorStrokeFocus2}`, outlineOffset: '1px', borderRadius: tokens.borderRadiusSmall },
  },
  paneSectionChevron: { display: 'inline-flex', color: tokens.colorNeutralForeground3, flexShrink: 0 },
  paneSectionIcon: { display: 'inline-flex', color: tokens.colorBrandForeground1, flexShrink: 0 },
  paneSectionLabel: {
    flex: 1, minWidth: 0, textAlign: 'left', fontWeight: tokens.fontWeightSemibold,
    overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
  },
  paneSectionBody: { display: 'flex', flexDirection: 'column', gap: tokens.spacingVerticalXS },
  pageTabStrip: {
    display: 'flex', alignItems: 'stretch', gap: tokens.spacingHorizontalXXS,
    overflowX: 'auto', flexShrink: 0,
    paddingTop: tokens.spacingVerticalXXS,
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
  },
  pageTab: {
    display: 'inline-flex', alignItems: 'center', gap: tokens.spacingHorizontalXXS,
    padding: `${tokens.spacingVerticalXXS} ${tokens.spacingHorizontalM}`,
    maxWidth: '180px', whiteSpace: 'nowrap', cursor: 'pointer',
    border: `1px solid ${tokens.colorTransparentStroke}`,
    borderBottom: `2px solid ${tokens.colorTransparentStroke}`,
    borderTopLeftRadius: tokens.borderRadiusMedium, borderTopRightRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorTransparentBackground,
    color: tokens.colorNeutralForeground2,
    transitionProperty: 'background-color, border-color, color',
    transitionDuration: tokens.durationFaster,
    ':hover': { backgroundColor: tokens.colorNeutralBackground1Hover, color: tokens.colorNeutralForeground1 },
    ':focus-visible': { outline: `2px solid ${tokens.colorStrokeFocus2}`, outlineOffset: '-2px' },
  },
  pageTabActive: {
    backgroundColor: tokens.colorNeutralBackground1Selected,
    borderBottom: `2px solid ${tokens.colorBrandStroke1}`,
    color: tokens.colorNeutralForeground1,
    fontWeight: tokens.fontWeightSemibold,
  },
  pageTabName: { minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis' },
  guidedEmpty: {
    display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
    gap: tokens.spacingVerticalXL, flex: 1, minHeight: '320px', textAlign: 'center',
    padding: tokens.spacingVerticalXXL,
    border: `1px dashed ${tokens.colorNeutralStroke2}`, borderRadius: tokens.borderRadiusLarge,
    backgroundColor: tokens.colorNeutralBackground1,
  },
  guidedSteps: {
    display: 'flex', alignItems: 'stretch', gap: tokens.spacingHorizontalM,
    flexWrap: 'wrap', justifyContent: 'center',
  },
  guidedStep: {
    display: 'flex', flexDirection: 'column', alignItems: 'center', gap: tokens.spacingVerticalS,
    width: '200px', padding: tokens.spacingVerticalL,
    border: `1px solid ${tokens.colorNeutralStroke2}`, borderRadius: tokens.borderRadiusLarge,
    backgroundColor: tokens.colorNeutralBackground2,
    // Native <button>: without an explicit color, text inherits UA ButtonText (black-on-dark).
    color: tokens.colorNeutralForeground1,
    boxShadow: tokens.shadow2,
    transitionProperty: 'box-shadow, border-color', transitionDuration: tokens.durationFaster,
    ':hover': { boxShadow: tokens.shadow8, border: `1px solid ${tokens.colorBrandStroke2}` },
  },
  guidedStepIcon: {
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    width: '48px', height: '48px', flexShrink: 0,
    borderRadius: tokens.borderRadiusCircular,
    backgroundImage: `linear-gradient(135deg, ${tokens.colorBrandBackground2}, ${tokens.colorBrandBackground})`,
    color: tokens.colorNeutralForegroundOnBrand,
    fontSize: tokens.fontSizeBase500,
  },
  guidedStepNum: {
    display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
    width: '20px', height: '20px', flexShrink: 0,
    borderRadius: tokens.borderRadiusCircular,
    backgroundColor: tokens.colorBrandBackground,
    color: tokens.colorNeutralForegroundOnBrand,
    fontSize: tokens.fontSizeBase100, fontWeight: tokens.fontWeightSemibold,
  },
  guidedStepHead: { display: 'flex', alignItems: 'center', gap: tokens.spacingHorizontalXS },
  guidedArrow: { display: 'flex', alignItems: 'center', color: tokens.colorNeutralForeground3 },
  guidedBody: { color: tokens.colorNeutralForeground3, maxWidth: '520px' },
});

export type Styles = ReturnType<typeof useStyles>;
