#!/usr/bin/env bash
# =============================================================================
# CSA-0032 — Regenerate all dependency lock files.
#
# Reads pyproject.toml directly and emits fully-resolved, hash-pinned
# `*.lock` files via `pip-compile --extra=<name>` (pip-tools >=7 treats
# pyproject.toml as a first-class input, so no intermediate `.in` files
# are needed — the [project.optional-dependencies] tables are the single
# source of truth).
#
# The resulting locks are the source of truth for:
#   • Docker image builds (portal/kubernetes/docker/{backend,frontend}/Dockerfile)
#   • CI dependency installs
#   • SBOM generation (.github/workflows/sbom.yml)
#   • Trivy filesystem CVE scans (.github/workflows/trivy.yml)
#
# Usage:
#   scripts/update-locks.sh                  # regenerate every lock
#   scripts/update-locks.sh portal dev       # regenerate only those extras
#   PYTHON=python3.11 scripts/update-locks.sh
#
# Requirements:
#   • Python >= 3.10 (matches pyproject.toml `requires-python`)
#   • pip-tools >= 7.0 (`python -m pip install --upgrade 'pip-tools>=7'`)
# =============================================================================
set -euo pipefail

# Resolve repo root so the script works from any CWD.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
REQ_DIR="${REPO_ROOT}/requirements"

PYTHON="${PYTHON:-python3}"
if ! command -v "${PYTHON}" >/dev/null 2>&1; then
    # Fall back to `python` on Windows / when python3 is not symlinked.
    PYTHON="python"
fi

# Ensure pip-tools is available in the active interpreter.  We invoke it via
# `python -m piptools compile ...` rather than the `pip-compile` entrypoint
# to survive `$PATH` shenanigans in CI runners and on Windows shells.
if ! "${PYTHON}" -c "import piptools" >/dev/null 2>&1; then
    echo "ERROR: pip-tools is not installed for ${PYTHON}." >&2
    echo "Install it with:  ${PYTHON} -m pip install --upgrade 'pip-tools>=7'" >&2
    exit 1
fi

# Locks to regenerate (default: all extras declared in pyproject.toml, plus
# a `base` pseudo-extra for the bare package).  CLI args override.
DEFAULT_EXTRAS=(
    base
    dev
    governance
    functions
    platform
    portal
    bff
    postgres
    copilot
    streaming
)

if [[ $# -gt 0 ]]; then
    EXTRAS=("$@")
else
    EXTRAS=("${DEFAULT_EXTRAS[@]}")
fi

# Shared pip-compile flags.  Kept as an array so the expansion is safe.
#
#   --generate-hashes       — emit sha256 hashes for every resolved artifact
#                             (hash-checking mode; failed hash = install error).
#   --resolver=backtracking — pip's backtracking resolver (pip-tools default
#                             since 7.0 but passed explicitly for clarity).
#   --strip-extras          — drop the `[extra]` suffix from wheel URLs so
#                             the lock remains stable across pip-tools versions.
#   --quiet                 — suppress the pip-tools banner; errors still print.
#   --allow-unsafe          — include pip/setuptools/pkg_resources themselves
#                             (needed for `pip install -r lock` to succeed in
#                             hash-checking mode on modern pip).
#   --no-emit-index-url     — do not embed private index URLs in the lock
#                             (keeps the file reproducible across networks).
PIP_COMPILE_FLAGS=(
    --generate-hashes
    --resolver=backtracking
    --strip-extras
    --allow-unsafe
    --no-emit-index-url
    --quiet
)

cd "${REPO_ROOT}"
mkdir -p requirements

# Use repo-relative paths for --output-file so the autogenerated header
# line that pip-compile embeds in each lock is identical across machines
# (otherwise Windows absolute paths like E:/... would leak in and churn
# diffs for every contributor).
for extra in "${EXTRAS[@]}"; do
    LOCK_FILE_REL="requirements/${extra}.lock"

    if [[ "${extra}" == "base" ]]; then
        # Bare package — no extra, just whatever sits in [project].dependencies.
        echo "→ Regenerating ${LOCK_FILE_REL}  (base — no extra)"
        "${PYTHON}" -m piptools compile \
            "${PIP_COMPILE_FLAGS[@]}" \
            --output-file "${LOCK_FILE_REL}" \
            pyproject.toml
    else
        echo "→ Regenerating ${LOCK_FILE_REL}  (extra: ${extra})"
        "${PYTHON}" -m piptools compile \
            "${PIP_COMPILE_FLAGS[@]}" \
            --extra "${extra}" \
            --output-file "${LOCK_FILE_REL}" \
            pyproject.toml
    fi
done

echo ""
echo "Done. Review the diff and commit the lock files:"
echo "   git add requirements/ && git status"
