/**
 * POST /api/items/report/[id]/query
 *
 * Runs a compiled DAX query (from the Loom Visual Designer) against a semantic
 * model and returns the rows the visual renders. The DAX is generated by
 * `dax-visual-compiler.ts` from the visual's field wells + filters — never
 * hand-typed — so this route is the execution half of the no-freeform-config
 * visual pipeline.
 *
 * Query engine: Power BI `executeQueries` REST (the JSON variant — no Arrow, no
 * Premium/Fabric capacity requirement). It works against ANY Power BI dataset
 * regardless of its loomSemanticBackend (loom-native / powerbi / analysis-
 * services), because the dataset id is the only required reference. This is the
 * same engine the Semantic Model editor uses to validate measures.
 *
 * Power BI is opt-in (no-fabric-dependency.md): the Visual Designer surface only
 * renders when the Console UAMI is registered in a Power BI workspace. When it
 * is not, the caller never reaches this route; the editor shows an honest
 * MessageBar. There is no Fabric host on the default path here — `api.powerbi*`
 * is reached only through the opt-in Power BI workspace selection.
 *
 * Body: { workspaceId: string; datasetId: string; dax: string }
 *   - id (path) = the Loom report item id (auth/context); the query targets
 *     `datasetId` via executeQueries.
 *
 * 200 OK → { ok: true, rows: Array<Record<string, unknown>>, dax }
 * 4xx/5xx → { ok: false, error, status }
 *
 * Limits: the executeQueries JSON endpoint caps at 100,000 rows / 1,000,000
 * values per request (Microsoft Learn). Visual queries are aggregated
 * SUMMARIZECOLUMNS so they return far fewer; raw table visuals are TOPN-capped
 * by the compiler.
 */

import { NextRequest, NextResponse } from 'next/server';
import { getSession } from '@/lib/auth/session';
import { executeDatasetQueries, PowerBiError } from '@/lib/azure/powerbi-client';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

interface QueryRequest {
  workspaceId?: string;
  datasetId?: string;
  dax?: string;
}

export async function POST(req: NextRequest, _ctx: { params: Promise<{ id: string }> }) {
  const session = getSession();
  if (!session) return NextResponse.json({ ok: false, error: 'unauthenticated' }, { status: 401 });

  const body = (await req.json().catch(() => ({}))) as QueryRequest;
  const workspaceId = body.workspaceId?.trim();
  const datasetId = body.datasetId?.trim();
  const dax = body.dax?.trim();
  if (!workspaceId || !datasetId || !dax) {
    return NextResponse.json(
      { ok: false, error: 'workspaceId, datasetId, and dax are required' },
      { status: 400 },
    );
  }
  // Guard against accidentally shipping the compiler's placeholder comment as a
  // real query (it would 400 from Power BI with an opaque parse error).
  const hasEvaluate = /\bEVALUATE\b/i.test(dax);
  if (!hasEvaluate) {
    return NextResponse.json(
      { ok: false, error: 'The visual has no fields yet — add a category/value field to generate a runnable query.' },
      { status: 400 },
    );
  }

  try {
    const result = await executeDatasetQueries(workspaceId, datasetId, dax);
    const table = result?.results?.[0]?.tables?.[0];
    return NextResponse.json({ ok: true, rows: table?.rows || [], dax });
  } catch (e: any) {
    const status = e instanceof PowerBiError ? e.status : 502;
    return NextResponse.json({ ok: false, error: e?.message || String(e), status }, { status });
  }
}
