'use client';

/**
 * Loom Setup Wizard — PRP-04
 *
 * Conversational deployment of additional Data Landing Zones after
 * the Admin Plane is installed.
 *
 * State machine:
 *   intro → boundary → mode → subscription → domain → capacity → review → deploying → done
 *
 * The `subscription` step lists the operator's real Azure subscriptions via
 * GET /api/setup/subscriptions (ARM `GET /subscriptions`) and threads the
 * chosen subscriptionId into the deploy POST + the generated bicep preview.
 * Without it the deploy had nowhere to land and failed opaquely.
 *
 * Tier dispatch:
 *   Commercial/GCC → Foundry Agent Service backend
 *   GCC-High/IL5  → MAF + AOAI direct backend
 *
 * Both tiers share THIS UI; only the /api/setup endpoint that routes
 * the conversational turns differs.
 */

import { useState, useMemo, useEffect, useCallback } from 'react';
import {
  Title2,
  Body1,
  makeStyles,
  tokens,
  Button,
  Input,
  Dropdown,
  Option,
  ProgressBar,
  MessageBar,
  MessageBarBody,
  Spinner,
} from '@fluentui/react-components';
import { Send24Regular, ArrowClockwise24Regular } from '@fluentui/react-icons';

type Boundary = 'Commercial' | 'GCC' | 'GCC-High' | 'IL5';
type Mode = 'single-sub' | 'multi-sub';

interface AzureSubscription {
  subscriptionId: string;
  displayName: string;
  state: string;
  tenantId?: string;
}

interface WizardState {
  step:
    | 'intro'
    | 'boundary'
    | 'mode'
    | 'subscription'
    | 'domain'
    | 'capacity'
    | 'review'
    | 'deploying'
    | 'done';
  boundary?: Boundary;
  mode?: Mode;
  subscriptionId?: string;
  subscriptionName?: string;
  location?: string;
  domainName?: string;
  capacitySku?: string;
  deployProgress?: number;
  deployStage?: string;
  deployError?: string;
  deploymentId?: string;
}

const REGIONS_COMMERCIAL = ['eastus2', 'eastus', 'westus2', 'westus3', 'centralus', 'westeurope', 'northeurope'];
const REGIONS_GOV = ['usgovvirginia', 'usgovtexas', 'usgovarizona'];

const useStyles = makeStyles({
  root: { display: 'flex', flexDirection: 'column', gap: '16px', maxWidth: '900px' },
  card: {
    backgroundColor: tokens.colorNeutralBackground1,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    borderRadius: '4px',
    padding: '24px',
  },
  preview: {
    backgroundColor: tokens.colorNeutralBackground3,
    borderLeft: `3px solid ${tokens.colorBrandStroke1}`,
    fontFamily: 'Cascadia Code, Consolas, monospace',
    fontSize: '12px',
    padding: '12px',
    margin: '12px 0',
    whiteSpace: 'pre-wrap',
  },
  buttons: { display: 'flex', gap: '8px', marginTop: '16px' },
});

function renderBicepParam(s: WizardState): string {
  const isGov = s.boundary === 'GCC-High' || s.boundary === 'IL5';
  return [
    `// Generated by Loom Setup Wizard`,
    `// Subscription: ${s.subscriptionName ?? '?'} (${s.subscriptionId ?? '?'})`,
    `// Region:       ${s.location ?? (isGov ? 'usgovvirginia' : 'eastus2')}`,
    `// Boundary:     ${s.boundary ?? '?'}`,
    `// Mode:         ${s.mode ?? '?'}`,
    `// Domain:       ${s.domainName ?? '?'}`,
    `// Capacity:     ${s.capacitySku ?? '?'}`,
    ``,
    `using '../main.bicep'`,
    ``,
    `param environment       = '${isGov ? 'AzureUSGovernment' : 'AzureCloud'}'`,
    `param boundary          = '${s.boundary ?? ''}'`,
    `param deploymentMode    = '${s.mode ?? ''}'`,
    `param containerPlatform = '${isGov ? 'aks' : 'containerApps'}'`,
    `param capacitySku       = '${s.capacitySku ?? ''}'`,
    `param dlzDomainNames    = ['${s.domainName ?? ''}']`,
    `// ... boundary-defaulted parameters omitted for brevity`,
    ``,
    `// Deploy target (passed to: az deployment sub create):`,
    `//   --subscription ${s.subscriptionId ?? '<select a subscription>'}`,
    `//   -l ${s.location ?? (isGov ? 'usgovvirginia' : 'eastus2')}`,
  ].join('\n');
}

export function SetupWizardPane() {
  const styles = useStyles();
  const [state, setState] = useState<WizardState>({ step: 'intro' });
  const [subs, setSubs] = useState<AzureSubscription[]>([]);
  const [subsLoading, setSubsLoading] = useState(false);
  const [subsError, setSubsError] = useState<string | undefined>();

  const bicepPreview = useMemo(() => renderBicepParam(state), [state]);

  const isGov = state.boundary === 'GCC-High' || state.boundary === 'IL5';
  const regions = isGov ? REGIONS_GOV : REGIONS_COMMERCIAL;

  const loadSubscriptions = useCallback(async () => {
    setSubsLoading(true);
    setSubsError(undefined);
    try {
      const res = await fetch('/api/setup/subscriptions');
      const ct = res.headers.get('content-type') || '';
      if (!ct.includes('application/json')) {
        const t = await res.text().catch(() => '');
        setSubsError(`Subscriptions service returned non-JSON (HTTP ${res.status}). ${t.slice(0, 160)}`);
        setSubs([]);
        return;
      }
      const j = await res.json();
      if (!res.ok || !j.ok) {
        setSubsError(j.error || j.hint || `Could not list subscriptions (HTTP ${res.status}).`);
        setSubs([]);
        return;
      }
      setSubs(j.subscriptions || []);
      if ((j.subscriptions || []).length === 0) {
        setSubsError('No subscriptions are visible to the Console identity. Grant it Reader on the target subscription.');
      }
    } catch (e) {
      setSubsError(e instanceof Error ? e.message : String(e));
      setSubs([]);
    } finally {
      setSubsLoading(false);
    }
  }, []);

  // Load subscriptions when the operator first reaches the subscription step.
  useEffect(() => {
    if (state.step === 'subscription' && subs.length === 0 && !subsLoading && !subsError) {
      void loadSubscriptions();
    }
  }, [state.step, subs.length, subsLoading, subsError, loadSubscriptions]);

  async function deploy() {
    // The backend validates the captured config (subscription, boundary,
    // mode, domain, capacity) and returns 400 if anything is missing, or
    // 503 with a copy-paste `az deployment sub create` (pre-filled with the
    // selected subscription + region) when the Setup Orchestrator isn't
    // deployed. We surface either honestly — no fake progress animation.
    setState((s) => ({ ...s, step: 'deploying', deployProgress: 0, deployStage: 'Submitting', deployError: undefined }));
    try {
      const res = await fetch('/api/setup/deploy', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(state),
      });
      const ct = res.headers.get('content-type') || '';
      if (!ct.includes('application/json')) {
        const t = await res.text().catch(() => '');
        setState((s) => ({ ...s, deployError: `Deploy service returned non-JSON (HTTP ${res.status}). ${t.slice(0, 200)}` }));
        return;
      }
      const j = await res.json().catch(() => ({}));
      if (!res.ok) {
        const msg = j.remediation?.message || j.error || `HTTP ${res.status}`;
        const commands = j.remediation?.commands ? '\n\n' + j.remediation.commands.join('\n') : '';
        setState((s) => ({ ...s, deployError: msg + commands }));
        return;
      }
      setState((s) => ({ ...s, deploymentId: j.deploymentId, deployStage: 'Submitted', deployProgress: 1, step: 'done' }));
    } catch (e) {
      setState((s) => ({ ...s, deployError: e instanceof Error ? e.message : String(e) }));
    }
  }

  return (
    <div className={styles.root}>
      <Title2>Setup Wizard</Title2>

      <div className={styles.card}>
        {state.step === 'intro' && (
          <>
            <Body1>
              I'll help you deploy a new Data Landing Zone. We'll choose the boundary, mode, domain
              name, and capacity together — then I'll execute the Bicep deployment under JIT
              Contributor elevation via the Azure MCP server.
            </Body1>
            <div className={styles.buttons}>
              <Button appearance="primary" onClick={() => setState({ ...state, step: 'boundary' })}>
                Get started
              </Button>
            </div>
          </>
        )}

        {state.step === 'boundary' && (
          <>
            <Body1 weight="semibold">Which Azure boundary?</Body1>
            <Dropdown
              placeholder="Select boundary"
              value={state.boundary}
              selectedOptions={state.boundary ? [state.boundary] : []}
              onOptionSelect={(_, d) => setState({ ...state, boundary: d.optionValue as Boundary })}
            >
              <Option value="Commercial">Commercial (Azure Public)</Option>
              <Option value="GCC">GCC (M365 GCC identity over Azure Public)</Option>
              <Option value="GCC-High">GCC-High / IL4 (Azure Government)</Option>
              <Option value="IL5">DoD IL5 (Azure Government)</Option>
            </Dropdown>
            <div className={styles.buttons}>
              <Button
                appearance="primary"
                disabled={!state.boundary}
                onClick={() => setState({ ...state, step: 'mode' })}
              >
                Next
              </Button>
            </div>
          </>
        )}

        {state.step === 'mode' && (
          <>
            <Body1 weight="semibold">Single-sub or multi-sub?</Body1>
            <Body1>
              Single-sub puts the DLZ in the same subscription as the Admin Plane. Multi-sub puts
              each DLZ in its own subscription (recommended for federal multi-tenant scenarios).
            </Body1>
            <Dropdown
              placeholder="Select mode"
              value={state.mode}
              selectedOptions={state.mode ? [state.mode] : []}
              onOptionSelect={(_, d) => setState({ ...state, mode: d.optionValue as Mode })}
            >
              <Option value="single-sub">Single-sub</Option>
              <Option value="multi-sub">Multi-sub</Option>
            </Dropdown>
            <div className={styles.buttons}>
              <Button onClick={() => setState({ ...state, step: 'boundary' })}>Back</Button>
              <Button
                appearance="primary"
                disabled={!state.mode}
                onClick={() => setState({ ...state, step: 'subscription' })}
              >
                Next
              </Button>
            </div>
          </>
        )}

        {state.step === 'subscription' && (
          <>
            <Body1 weight="semibold">Target subscription</Body1>
            <Body1>
              Choose the Azure subscription the new Data Landing Zone will be deployed into. This is
              the subscription threaded into <code>az deployment sub create --subscription …</code>.
              Only subscriptions your identity can see are listed.
            </Body1>

            {subsLoading && (
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', margin: '12px 0' }}>
                <Spinner size="tiny" /> <Body1>Listing subscriptions from Azure Resource Manager…</Body1>
              </div>
            )}

            {subsError && !subsLoading && (
              <MessageBar intent="warning">
                <MessageBarBody style={{ whiteSpace: 'pre-wrap' }}>{subsError}</MessageBarBody>
              </MessageBar>
            )}

            {!subsLoading && subs.length > 0 && (
              <Dropdown
                placeholder="Select subscription"
                value={state.subscriptionName}
                selectedOptions={state.subscriptionId ? [state.subscriptionId] : []}
                onOptionSelect={(_, d) => {
                  const chosen = subs.find((x) => x.subscriptionId === d.optionValue);
                  setState({
                    ...state,
                    subscriptionId: d.optionValue,
                    subscriptionName: chosen?.displayName,
                  });
                }}
              >
                {subs.map((sub) => (
                  <Option key={sub.subscriptionId} value={sub.subscriptionId} text={sub.displayName}>
                    {sub.displayName} — {sub.subscriptionId} ({sub.state})
                  </Option>
                ))}
              </Dropdown>
            )}

            <div style={{ marginTop: '12px' }}>
              <Body1 weight="semibold">Region</Body1>
              <Dropdown
                placeholder="Select region"
                value={state.location}
                selectedOptions={state.location ? [state.location] : []}
                onOptionSelect={(_, d) => setState({ ...state, location: d.optionValue as string })}
              >
                {regions.map((r) => (
                  <Option key={r} value={r}>
                    {r}
                  </Option>
                ))}
              </Dropdown>
            </div>

            <div className={styles.buttons}>
              <Button onClick={() => setState({ ...state, step: 'mode' })}>Back</Button>
              <Button
                icon={<ArrowClockwise24Regular />}
                onClick={() => {
                  setSubs([]);
                  setSubsError(undefined);
                  void loadSubscriptions();
                }}
                disabled={subsLoading}
              >
                Refresh
              </Button>
              <Button
                appearance="primary"
                disabled={!state.subscriptionId || !state.location}
                onClick={() => setState({ ...state, step: 'domain' })}
              >
                Next
              </Button>
            </div>
          </>
        )}

        {state.step === 'domain' && (
          <>
            <Body1 weight="semibold">DLZ domain name</Body1>
            <Body1>Used in resource names (e.g., "finance" → rg-csa-loom-dlz-finance-eastus2).</Body1>
            <Input
              value={state.domainName ?? ''}
              onChange={(_, d) => setState({ ...state, domainName: d.value.toLowerCase().replace(/[^a-z0-9-]/g, '') })}
              placeholder="finance, procurement, mission-ops..."
            />
            <div className={styles.buttons}>
              <Button onClick={() => setState({ ...state, step: 'subscription' })}>Back</Button>
              <Button
                appearance="primary"
                disabled={!state.domainName}
                onClick={() => setState({ ...state, step: 'capacity' })}
              >
                Next
              </Button>
            </div>
          </>
        )}

        {state.step === 'capacity' && (
          <>
            <Body1 weight="semibold">Capacity sizing</Body1>
            <Body1>
              Loom uses Fabric F-SKU labels as a familiar <i>sizing equivalence</i> so existing Fabric
              sizing guides apply, but the underlying compute is provisioned on Azure-native services
              you already pay for: Databricks cluster nodes + ADX SKU + Synapse Spark pool size.
              Pick the equivalence that matches your expected workload.
            </Body1>
            <Dropdown
              value={state.capacitySku}
              selectedOptions={state.capacitySku ? [state.capacitySku] : []}
              onOptionSelect={(_, d) => setState({ ...state, capacitySku: d.optionValue as string })}
            >
              <Option value="F2">F2 (smallest — dev)</Option>
              <Option value="F4">F4</Option>
              <Option value="F8">F8 (recommended for prod start)</Option>
              <Option value="F32">F32</Option>
              <Option value="F64">F64</Option>
              <Option value="F128">F128</Option>
              <Option value="F512">F512 (largest)</Option>
            </Dropdown>
            <div className={styles.buttons}>
              <Button onClick={() => setState({ ...state, step: 'domain' })}>Back</Button>
              <Button
                appearance="primary"
                disabled={!state.capacitySku}
                onClick={() => setState({ ...state, step: 'review' })}
              >
                Next
              </Button>
            </div>
          </>
        )}

        {state.step === 'review' && (
          <>
            <Body1 weight="semibold">Review</Body1>
            <Body1>Here's the generated Bicep parameter file:</Body1>
            <div className={styles.preview}>{bicepPreview}</div>
            <Body1>
              Deploy will request JIT Contributor elevation on the target subscription via PIM-for-
              Groups and execute via the self-hosted Azure MCP server.
            </Body1>
            <div className={styles.buttons}>
              <Button onClick={() => setState({ ...state, step: 'capacity' })}>Back</Button>
              <Button appearance="primary" icon={<Send24Regular />} onClick={deploy}>
                Deploy
              </Button>
            </div>
          </>
        )}

        {state.step === 'deploying' && (
          <>
            <Body1 weight="semibold">{state.deployError ? 'Deployment failed' : 'Deploying…'}</Body1>
            {!state.deployError && <ProgressBar value={state.deployProgress ?? 0} />}
            <Body1>{state.deployStage}</Body1>
            {state.deployError && (
              <>
                <MessageBar intent={/az deployment sub create/.test(state.deployError) ? 'warning' : 'error'}>
                  <MessageBarBody style={{ whiteSpace: 'pre-wrap' }}>{state.deployError}</MessageBarBody>
                </MessageBar>
                <div className={styles.buttons}>
                  <Button onClick={() => setState((s) => ({ ...s, step: 'review', deployError: undefined }))}>
                    Back to review
                  </Button>
                  <Button appearance="primary" onClick={deploy}>
                    Retry deploy
                  </Button>
                </div>
              </>
            )}
          </>
        )}

        {state.step === 'done' && (
          <>
            <MessageBar intent="success">
              <MessageBarBody>
                Data Landing Zone "{state.domainName}" deployed successfully. Deployment ID:{' '}
                <code>{state.deploymentId}</code>
              </MessageBarBody>
            </MessageBar>
            <Body1>
              Next steps:
              <ul>
                <li>Configure mirroring from your source systems (Mirroring pane)</li>
                <li>Define Activator rules over the ADX database (Activator pane)</li>
                <li>Build a semantic model on the gold layer (Semantic Model pane)</li>
                <li>Create a Data Agent grounded on this lakehouse (Data Agent pane)</li>
              </ul>
            </Body1>
            <div className={styles.buttons}>
              <Button
                appearance="primary"
                onClick={() => setState({ step: 'intro' })}
              >
                Deploy another
              </Button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
