"""#3717 — the credential-safe opener in the Semantic Link notebook module.

``apps/fiab-console/lib/notebook/loom-semantic-link.py`` is the only one of the
six sites that carries TWO credentials on every request:

    req.add_header("cookie", "loom_session={t}".format(t=_TOKEN))
    req.add_header("authorization", "Bearer {t}".format(t=_TOKEN))

`urllib.request.HTTPRedirectHandler.redirect_request` rebuilds the Request
copying EVERY header except content-length/content-type, so BOTH travelled to
whatever host a `Location:` named — and the caller SUCCEEDED, so nothing raised
and nothing was logged. `LOOM_CONSOLE_BASE_URL` is environment-supplied inside a
notebook session the user can edit, which is what makes it reachable.

WHY THIS FILE IS TESTED FROM `tests/` RATHER THAN vitest. The module is Python
that is EMBEDDED VERBATIM into a TypeScript preamble string
(`lib/notebook/loom-semantic-link-preamble.ts`, generated by
`scripts/embed-semantic-link.mjs`), so the console's own suite cannot execute it.
It has to be loaded and run as Python, which is here.
"""

from __future__ import annotations

import http.server
import importlib.util
import io
import sys
import threading
import urllib.error
import urllib.request
from http.client import HTTPMessage
from pathlib import Path
from types import ModuleType

import pytest

_MODULE_PATH = (
    Path(__file__).resolve().parents[2]
    / "apps"
    / "fiab-console"
    / "lib"
    / "notebook"
    / "loom-semantic-link.py"
)


def _load_semantic_link() -> ModuleType:
    """Load the notebook module, defeating its re-entry guard.

    The file's whole body sits under
    `if not getattr(sys, "_loom_semantic_link_v1", False):` and sets that
    attribute True on the way out — deliberate, so re-running the preamble in a
    live notebook is a no-op. A second load in the same interpreter would
    therefore produce an EMPTY module and every assertion below would fail with
    AttributeError rather than a real verdict, so the sentinel is cleared first.
    """
    sys._loom_semantic_link_v1 = False  # type: ignore[attr-defined]
    spec = importlib.util.spec_from_file_location("loom_semantic_link_under_test", _MODULE_PATH)
    assert spec is not None
    assert spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = mod
    spec.loader.exec_module(mod)
    return mod


_mod = _load_semantic_link()


def test_the_module_actually_loaded_its_body() -> None:
    # THE POPULATION FLOOR. If the re-entry guard ever wins, every other spec in
    # this file collapses into AttributeError-shaped noise or, worse, gets
    # skipped — a suite measuring nothing while reporting green. This asserts the
    # subject exists before anything is asserted about it.
    assert hasattr(_mod, "_OPENER")
    assert hasattr(_mod, "_SameOriginRedirectHandler")
    assert hasattr(_mod, "_request")


class TestTheOpenerHasNoNonHttpTransport:
    def test_ftp_file_and_data_routes_are_absent(self) -> None:
        routes = set(_mod._OPENER.handle_open)
        assert "ftp" not in routes
        assert "file" not in routes
        assert "data" not in routes

    def test_the_routes_the_notebook_needs_are_present(self) -> None:
        routes = set(_mod._OPENER.handle_open)
        assert "http" in routes
        assert "https" in routes

    def test_an_ftp_proxy_env_var_cannot_re_register_the_ftp_route(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # A Livy / AML session is very often behind a proxy, which is exactly
        # where the unscoped `ProxyHandler()` fails OPEN.
        monkeypatch.setenv("ftp_proxy", "http://127.0.0.1:9")
        assert "ftp" not in set(_mod._http_only_opener().handle_open)


class TestTheRedirectGuardCoversBOTHCredentials:
    def test_a_cross_host_redirect_is_refused(self) -> None:
        handler = _mod._SameOriginRedirectHandler()
        req = urllib.request.Request("https://csa-loom.example.com/api/items/semantic-model/m1/semantic-link")
        req.add_header("cookie", "loom_session=SESSION_SECRET")
        req.add_header("authorization", "Bearer SESSION_SECRET")
        with pytest.raises(urllib.error.HTTPError) as excinfo:
            handler.redirect_request(req, io.BytesIO(b""), 302, "Found", HTTPMessage(), "https://attacker.invalid/loot")
        # R7 — the message names what would actually have been handed over.
        assert "refusing cross-origin redirect" in str(excinfo.value)
        assert "loom_session cookie" in str(excinfo.value)

    def test_a_scheme_downgrade_and_a_port_change_are_refused(self) -> None:
        handler = _mod._SameOriginRedirectHandler()
        base = urllib.request.Request("https://csa-loom.example.com/api/items/semantic-model/m1/semantic-link")
        for target in (
            "http://csa-loom.example.com/api/items/semantic-model/m1/semantic-link",
            "https://csa-loom.example.com:8443/api/items/semantic-model/m1/semantic-link",
        ):
            with pytest.raises(urllib.error.HTTPError, match="refusing cross-origin redirect"):
                handler.redirect_request(base, io.BytesIO(b""), 302, "Found", HTTPMessage(), target)

    def test_a_same_origin_redirect_is_still_followed(self) -> None:
        handler = _mod._SameOriginRedirectHandler()
        req = urllib.request.Request("https://csa-loom.example.com/api/items/semantic-model/m1/semantic-link")
        redirected = handler.redirect_request(
            req, io.BytesIO(b""), 302, "Found", HTTPMessage(),
            "https://csa-loom.example.com/api/items/semantic-model/m1/semantic-link/",
        )
        assert redirected is not None

    def test_the_stdlib_handler_would_have_leaked_both_credentials(self) -> None:
        # THE COUNTERFACTUAL, and the reason this site is the worst of the six:
        # the cookie travels too, and a `loom_session` cookie is a whole session,
        # not one API call's worth of authority.
        req = urllib.request.Request("https://csa-loom.example.com/api/items/semantic-model/m1/semantic-link")
        req.add_header("cookie", "loom_session=SESSION_SECRET")
        req.add_header("authorization", "Bearer SESSION_SECRET")
        # A real HTTPMessage, not `{}`. The stdlib signature wants one, and mypy
        # is right to reject a bare dict here — but the stronger reason is that
        # an empty dict is not what urllib hands this method in production, so
        # the counterfactual would have been exercising a shape the real code
        # path never sees.
        leaked = urllib.request.HTTPRedirectHandler().redirect_request(
            req, io.BytesIO(b""), 302, "Found", HTTPMessage(), "https://attacker.invalid/loot"
        )
        assert leaked is not None
        assert leaked.get_header("Cookie") == "loom_session=SESSION_SECRET"
        assert leaked.get_header("Authorization") == "Bearer SESSION_SECRET"


class TestEndToEndOverRealSockets:
    def test_neither_credential_reaches_the_redirect_target(self, monkeypatch: pytest.MonkeyPatch) -> None:
        received: list[tuple[str | None, str | None]] = []

        class Attacker(http.server.BaseHTTPRequestHandler):
            def do_GET(self) -> None:
                received.append((self.headers.get("Authorization"), self.headers.get("Cookie")))
                self.send_response(200)
                self.end_headers()
                self.wfile.write(b'{"ok": true}')

            def log_message(self, *_args: object) -> None:
                pass

        attacker = http.server.HTTPServer(("127.0.0.1", 0), Attacker)
        attacker_port = attacker.server_address[1]

        class Origin(http.server.BaseHTTPRequestHandler):
            def do_GET(self) -> None:
                self.send_response(302)
                self.send_header("Location", f"http://127.0.0.1:{attacker_port}/loot")
                self.end_headers()

            def log_message(self, *_args: object) -> None:
                pass

        origin = http.server.HTTPServer(("127.0.0.1", 0), Origin)
        for srv in (attacker, origin):
            threading.Thread(target=srv.serve_forever, daemon=True).start()
        # THE OUTCOME IS CAPTURED, NOT ASSERTED INLINE. With `pytest.raises(…)`
        # around the call, a regression that re-followed the redirect fails on
        # "DID NOT RAISE" and the attacker-log assertion never runs — red for the
        # weaker reason, with the real evidence unread.
        outcome: object = None
        try:
            monkeypatch.setattr(_mod, "_BASE", f"http://127.0.0.1:{origin.server_address[1]}")
            monkeypatch.setattr(_mod, "_TOKEN", "SESSION_SECRET")
            try:
                outcome = _mod._request("GET", "m1")
            except _mod.LoomSemanticLinkError as exc:
                outcome = exc
        finally:
            for srv in (attacker, origin):
                srv.shutdown()
                srv.server_close()

        assert received == [], f"a Loom session reached the attacker: {received!r}"
        assert isinstance(outcome, _mod.LoomSemanticLinkError), f"the redirect was followed: {outcome!r}"
        assert "refusing cross-origin redirect" in str(outcome)

    def test_a_same_origin_redirect_still_returns_the_payload(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # THE CONTROL. Without it "nothing reached the attacker" is equally true
        # of a notebook helper that can no longer follow any redirect, which
        # would be a broken Semantic Link reported as a fixed one.
        class Server(http.server.BaseHTTPRequestHandler):
            def do_GET(self) -> None:
                if not self.path.endswith("/"):
                    self.send_response(302)
                    self.send_header("Location", f"{self.path}/")
                    self.end_headers()
                    return
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.end_headers()
                self.wfile.write(b'{"ok": true, "tables": [{"name": "Sales"}]}')

            def log_message(self, *_args: object) -> None:
                pass

        srv = http.server.HTTPServer(("127.0.0.1", 0), Server)
        threading.Thread(target=srv.serve_forever, daemon=True).start()
        try:
            monkeypatch.setattr(_mod, "_BASE", f"http://127.0.0.1:{srv.server_address[1]}")
            monkeypatch.setattr(_mod, "_TOKEN", "SESSION_SECRET")
            payload = _mod._request("GET", "m1")
        finally:
            srv.shutdown()
            srv.server_close()
        assert payload["tables"] == [{"name": "Sales"}]


class TestTheSchemeGuardAtTheCallSite:
    def test_a_non_http_console_base_url_is_refused(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setattr(_mod, "_BASE", "file:///etc")
        monkeypatch.setattr(_mod, "_TOKEN", "SESSION_SECRET")
        with pytest.raises(_mod.LoomSemanticLinkError, match="refusing non-http"):
            _mod._request("GET", "m1")

    def test_an_unset_base_url_still_gives_the_original_honest_gate(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # The new scheme check must not have displaced the pre-existing
        # "LOOM_CONSOLE_BASE_URL is not set" guidance, which is the message a
        # user in an unwired notebook actually needs.
        monkeypatch.setattr(_mod, "_BASE", "")
        with pytest.raises(_mod.LoomSemanticLinkError, match="LOOM_CONSOLE_BASE_URL is not set"):
            _mod._request("GET", "m1")
